In [1]:
import numpy as np
import pickle
import os

seed = 2023

In [2]:
from nlpsig_networks.scripts.swmhau_network_functions import (
    swmhau_network_hyperparameter_search,
)

In [3]:
output_dir = "therapist_talk_type_output"
if not os.path.isdir(output_dir):
    os.makedirs(output_dir)

## AnnoMI

In [4]:
%run ../load_anno_mi.py

In [5]:
anno_mi.head()

mi_quality  transcript_id                         topic  utterance_id  \
0       high              0  reducing alcohol consumption             0   
1       high              0  reducing alcohol consumption             1   
2       high              0  reducing alcohol consumption             2   
3       high              0  reducing alcohol consumption             3   
4       high              0  reducing alcohol consumption             4   

  interlocutor timestamp                                     utterance_text  \
0    therapist  00:00:13  Thanks for filling it out. We give this form t...   
1       client  00:00:24                                              Sure.   
2    therapist  00:00:25  So, let's see. It looks that you put-- You dri...   
3       client  00:00:34                                            Mm-hmm.   
4    therapist  00:00:34  -and you usually have three to four drinks whe...   

   annotator_id therapist_input_exists therapist_input_subtype  \
0             3                  False                     NaN   
1             3                    NaN                     NaN   
2             3                   True             information   
3             3                    NaN                     NaN   
4             3                   True             information   

  reflection_exists reflection_subtype question_exists question_subtype  \
0             False                NaN            True             open   
1               NaN                NaN             NaN              NaN   
2             False                NaN           False              NaN   
3               NaN                NaN             NaN              NaN   
4             False                NaN           False              NaN   

  main_therapist_behaviour client_talk_type            datetime  
0                 question              NaN 2023-08-21 00:00:13  
1                      NaN          neutral 2023-08-21 00:00:24  
2          therapist_input              NaN 2023-08-21 00:00:25  
3                      NaN          neutral 2023-08-21 00:00:34  
4          therapist_input              NaN 2023-08-21 00:00:34

In [6]:
with open("../anno_mi_sbert.pkl", "rb") as f:
    sbert_embeddings = pickle.load(f)

sbert_embeddings.shape

(9699, 384)

# swmhau Network

In [7]:
features = ["timeline_index"]
standardise_method = [None]
num_features = len(features)
include_features_in_path = True

In [8]:
num_epochs = 100
embedding_dim = 384
dimensions = [15]
# define swmhau parameters: (output_channels, sig_depth, num_heads)
swmhau_parameters = [(12, 3, 10), (8, 4, 6), (8, 4, 12)]
num_layers = [1]
ffn_hidden_dim_sizes = [[256, 256], [512, 512]]
dropout_rates = [0.5, 0.1]
learning_rates = [1e-3, 1e-4, 5e-4]
seeds = [1, 12, 123]
loss = "focal"
gamma = 2
validation_metric = "f1"
patience = 5

## UMAP

In [9]:
size = 20
(
    swmhau_network_umap_kfold_20,
    best_swmhau_network_umap_kfold_20,
    _,
    __,
) = swmhau_network_hyperparameter_search(
    num_epochs=num_epochs,
    df=anno_mi,
    id_column="transcript_id",
    label_column="main_therapist_behaviour",
    embeddings=sbert_embeddings,
    y_data=y_data_therapist,
    embedding_dim=embedding_dim,
    output_dim=output_dim_therapist,
    history_lengths=[size],
    dim_reduce_methods=["umap"],
    dimensions=dimensions,
    log_signature=True,
    swmhau_parameters=swmhau_parameters,
    num_layers=num_layers,
    ffn_hidden_dim_sizes=ffn_hidden_dim_sizes,
    dropout_rates=dropout_rates,
    learning_rates=learning_rates,
    seeds=seeds,
    loss=loss,
    gamma=gamma,
    features=features,
    standardise_method=standardise_method,
    include_features_in_path=include_features_in_path,
    path_indices=therapist_index,
    k_fold=True,
    patience=patience,
    validation_metric=validation_metric,
    results_output=f"{output_dir}/swmhau_network_umap_focal_{gamma}_{size}_kfold.csv",
    verbose=False,
)

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]


##################################################
dimension: 15 | method: umap
[INFO] Concatenating the embeddings to the dataframe...
[INFO] - columns beginning with 'e' denote the full embddings.
[INFO] - columns beginning with 'd' denote the dimension reduced embeddings.
[INFO] Adding time feature columns into dataframe in `.df`.
[INFO] Adding 'time_encoding' feature...
[INFO] Adding 'time_diff' feature...
[INFO] Adding 'timeline_index' feature...
[INFO] Padding ids and storing in `.df_padded` and `.array_padded` attributes.


  0%|          | 0/9699 [00:00<?, ?it/s]

[INFO] The path was created for each item in the dataframe, by looking at its history, so to include embeddings in the FFN input, we concatenate the embeddings for each sentence / text.


  0%|          | 0/3 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/2 [00:00<?, ?it/s]

  0%|          | 0/2 [00:00<?, ?it/s]

  0%|          | 0/3 [00:00<?, ?it/s]

  0%|          | 0/3 [00:00<?, ?it/s]

  0%|          | 0/2 [00:00<?, ?it/s]

  0%|          | 0/3 [00:00<?, ?it/s]

  0%|          | 0/3 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/2 [00:00<?, ?it/s]

  0%|          | 0/2 [00:00<?, ?it/s]

  0%|          | 0/3 [00:00<?, ?it/s]

  0%|          | 0/3 [00:00<?, ?it/s]

  0%|          | 0/2 [00:00<?, ?it/s]

  0%|          | 0/3 [00:00<?, ?it/s]

  0%|          | 0/3 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/2 [00:00<?, ?it/s]

  0%|          | 0/2 [00:00<?, ?it/s]

  0%|          | 0/3 [00:00<?, ?it/s]

  0%|          | 0/3 [00:00<?, ?it/s]

  0%|          | 0/2 [00:00<?, ?it/s]

  0%|          | 0/3 [00:00<?, ?it/s]

  0%|          | 0/3 [00:00<?, ?it/s]

[INFO] Concatenating the embeddings to the dataframe...
[INFO] - columns beginning with 'e' denote the full embddings.
[INFO] - columns beginning with 'd' denote the dimension reduced embeddings.
[INFO] Adding time feature columns into dataframe in `.df`.
[INFO] Adding 'time_encoding' feature...
[INFO] Adding 'time_diff' feature...
[INFO] Adding 'timeline_index' feature...
[INFO] Padding ids and storing in `.df_padded` and `.array_padded` attributes.


  0%|          | 0/9699 [00:00<?, ?it/s]

[INFO] The path was created for each item in the dataframe, by looking at its history, so to include embeddings in the FFN input, we concatenate the embeddings for each sentence / text.
saving results dataframe to CSV for this hyperparameter search in therapist_talk_type_output/swmhau_network_umap_focal_2_20_kfold.csv
saving the best model results dataframe to CSV for this hyperparameter search in therapist_talk_type_output/swmhau_network_umap_focal_2_20_kfold_best_model.csv


In [10]:
swmhau_network_umap_kfold_20.groupby(
    [
        "dimensions",
        "output_channels",
        "sig_depth",
        "num_heads",
        "num_layers",
        "ffn_hidden_dim",
        "learning_rate",
    ]
).mean()

/tmp/ipykernel_54341/767646728.py:1: FutureWarning: The default value of numeric_only in DataFrameGroupBy.mean is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  swmhau_network_umap_kfold_20.groupby(["dimensions",


accuracy  \
dimensions output_channels sig_depth num_heads num_layers ffn_hidden_dim learning_rate             
15         8               4         6         1          (256, 256)     0.0001         0.565240   
                                                                         0.0005         0.736037   
                                                                         0.0010         0.732214   
                                                          (512, 512)     0.0001         0.573843   
                                                                         0.0005         0.727605   
                                                                         0.0010         0.725352   
                                     12        1          (256, 256)     0.0001         0.561450   
                                                                         0.0005         0.731326   
                                                                         0.0010         0.729756   
                                                          (512, 512)     0.0001         0.570736   
                                                                         0.0005         0.728151   
                                                                         0.0010         0.726820   
           12              3         10        1          (256, 256)     0.0001         0.571214   
                                                                         0.0005         0.708692   
                                                                         0.0010         0.728390   
                                                          (512, 512)     0.0001         0.575959   
                                                                         0.0005         0.705005   
                                                                         0.0010         0.722825   

                                                                                              f1  \
dimensions output_channels sig_depth num_heads num_layers ffn_hidden_dim learning_rate             
15         8               4         6         1          (256, 256)     0.0001         0.513817   
                                                                         0.0005         0.702147   
                                                                         0.0010         0.698647   
                                                          (512, 512)     0.0001         0.526182   
                                                                         0.0005         0.694506   
                                                                         0.0010         0.691037   
                                     12        1          (256, 256)     0.0001         0.509693   
                                                                         0.0005         0.698870   
                                                                         0.0010         0.697434   
                                                          (512, 512)     0.0001         0.523074   
                                                                         0.0005         0.695032   
                                                                         0.0010         0.693010   
           12              3         10        1          (256, 256)     0.0001         0.525884   
                                                                         0.0005         0.673610   
                                                                         0.0010         0.694965   
                                                          (512, 512)     0.0001         0.530615   
                                                                         0.0005         0.668114   
                                                                         0.0010         0.691755   

                                                                                      

In [11]:
best_swmhau_network_umap_kfold_20

loss  accuracy        f1  \
0  None  0.737403  0.705430   
0  None  0.736174  0.701990   
0  None  0.739246  0.704795   

                                           f1_scores  precision  \
0  [0.7460982108869432, 0.5281173594132028, 0.678...   0.711521   
0  [0.7535919540229885, 0.5218120805369129, 0.668...   0.706816   
0  [0.7590066456803077, 0.5279352226720648, 0.667...   0.706244   

                                    precision_scores    recall  \
0  [0.7821229050279329, 0.5409015025041736, 0.622...  0.703583   
0  [0.7439716312056738, 0.5514184397163121, 0.637...  0.699202   
0  [0.7306397306397306, 0.5370675453047776, 0.674...  0.704212   

                                       recall_scores valid_loss  \
0  [0.7132459970887919, 0.5159235668789809, 0.745...       None   
0  [0.7634643377001455, 0.49522292993630573, 0.70...       None   
0  [0.789665211062591, 0.5191082802547771, 0.6605...       None   

   valid_accuracy  ...  learning_rate seed  loss_function gamma  k_fold  \
0        0.736230  ...         0.0005    1          focal     2    True   
0        0.737161  ...         0.0005   12          focal     2    True   
0        0.740884  ...         0.0005  123          focal     2    True   

  n_splits  augmentation_type  hidden_dim_aug    comb_method batch_size  
0        5             Conv1d            None  concatenation         64  
0        5             Conv1d            None  concatenation         64  
0        5             Conv1d            None  concatenation         64  

[3 rows x 42 columns]

In [12]:
best_swmhau_network_umap_kfold_20["f1"].mean()

0.7040717525292837

In [13]:
best_swmhau_network_umap_kfold_20["precision"].mean()

0.7081935309049031

In [14]:
best_swmhau_network_umap_kfold_20["recall"].mean()

0.7023322823197091

In [15]:
np.stack(best_swmhau_network_umap_kfold_20["f1_scores"]).mean(axis=0)

array([0.75289894, 0.52595489, 0.67122888, 0.86620431])

In [16]:
np.stack(best_swmhau_network_umap_kfold_20["precision_scores"]).mean(axis=0)

array([0.75224476, 0.54312916, 0.64486382, 0.89253639])

In [17]:
np.stack(best_swmhau_network_umap_kfold_20["recall_scores"]).mean(axis=0)

array([0.75545852, 0.51008493, 0.70233513, 0.84145056])

## Random Projections

In [18]:
size = 20
(
    swmhau_network_grp_kfold_20,
    best_swmhau_network_grp_kfold_20,
    _,
    __,
) = swmhau_network_hyperparameter_search(
    num_epochs=num_epochs,
    df=anno_mi,
    id_column="transcript_id",
    label_column="main_therapist_behaviour",
    embeddings=sbert_embeddings,
    y_data=y_data_therapist,
    embedding_dim=embedding_dim,
    output_dim=output_dim_therapist,
    history_lengths=[size],
    dim_reduce_methods=["gaussian_random_projection"],
    dimensions=dimensions,
    log_signature=True,
    swmhau_parameters=swmhau_parameters,
    num_layers=num_layers,
    ffn_hidden_dim_sizes=ffn_hidden_dim_sizes,
    dropout_rates=dropout_rates,
    learning_rates=learning_rates,
    seeds=seeds,
    loss=loss,
    gamma=gamma,
    features=features,
    standardise_method=standardise_method,
    path_indices=therapist_index,
    k_fold=True,
    patience=patience,
    validation_metric=validation_metric,
    results_output=f"{output_dir}/swmhau_network_grp_focal_{gamma}_{size}_kfold.csv",
    verbose=False,
)

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]


##################################################
dimension: 15 | method: gaussian_random_projection
[INFO] Concatenating the embeddings to the dataframe...
[INFO] - columns beginning with 'e' denote the full embddings.
[INFO] - columns beginning with 'd' denote the dimension reduced embeddings.
[INFO] Adding time feature columns into dataframe in `.df`.
[INFO] Adding 'time_encoding' feature...
[INFO] Adding 'time_diff' feature...
[INFO] Adding 'timeline_index' feature...
[INFO] Padding ids and storing in `.df_padded` and `.array_padded` attributes.


  0%|          | 0/9699 [00:00<?, ?it/s]

[INFO] The path was created for each item in the dataframe, by looking at its history, so to include embeddings in the FFN input, we concatenate the embeddings for each sentence / text.


  0%|          | 0/3 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/2 [00:00<?, ?it/s]

  0%|          | 0/2 [00:00<?, ?it/s]

  0%|          | 0/3 [00:00<?, ?it/s]

  0%|          | 0/3 [00:00<?, ?it/s]

  0%|          | 0/2 [00:00<?, ?it/s]

  0%|          | 0/3 [00:00<?, ?it/s]

  0%|          | 0/3 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/2 [00:00<?, ?it/s]

  0%|          | 0/2 [00:00<?, ?it/s]

  0%|          | 0/3 [00:00<?, ?it/s]

  0%|          | 0/3 [00:00<?, ?it/s]

  0%|          | 0/2 [00:00<?, ?it/s]

  0%|          | 0/3 [00:00<?, ?it/s]

  0%|          | 0/3 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/2 [00:00<?, ?it/s]

  0%|          | 0/2 [00:00<?, ?it/s]

  0%|          | 0/3 [00:00<?, ?it/s]

  0%|          | 0/3 [00:00<?, ?it/s]

  0%|          | 0/2 [00:00<?, ?it/s]

  0%|          | 0/3 [00:00<?, ?it/s]

  0%|          | 0/3 [00:00<?, ?it/s]

[INFO] Concatenating the embeddings to the dataframe...
[INFO] - columns beginning with 'e' denote the full embddings.
[INFO] - columns beginning with 'd' denote the dimension reduced embeddings.
[INFO] Adding time feature columns into dataframe in `.df`.
[INFO] Adding 'time_encoding' feature...
[INFO] Adding 'time_diff' feature...
[INFO] Adding 'timeline_index' feature...
[INFO] Padding ids and storing in `.df_padded` and `.array_padded` attributes.


  0%|          | 0/9699 [00:00<?, ?it/s]

[INFO] The path was created for each item in the dataframe, by looking at its history, so to include embeddings in the FFN input, we concatenate the embeddings for each sentence / text.
saving results dataframe to CSV for this hyperparameter search in therapist_talk_type_output/swmhau_network_grp_focal_2_20_kfold.csv
saving the best model results dataframe to CSV for this hyperparameter search in therapist_talk_type_output/swmhau_network_grp_focal_2_20_kfold_best_model.csv


In [19]:
swmhau_network_grp_kfold_20.groupby(
    [
        "dimensions",
        "output_channels",
        "sig_depth",
        "num_heads",
        "num_layers",
        "ffn_hidden_dim",
        "dropout_rate",
        "learning_rate",
    ]
).mean()

/tmp/ipykernel_54341/1948036447.py:1: FutureWarning: The default value of numeric_only in DataFrameGroupBy.mean is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  swmhau_network_grp_kfold_20.groupby(["dimensions",


accuracy  \
dimensions output_channels sig_depth num_heads num_layers ffn_hidden_dim dropout_rate learning_rate             
15         8               4         6         1          (256, 256)     0.1          0.0001         0.402499   
                                                                                      0.0005         0.618326   
                                                                                      0.0010         0.718353   
                                                                         0.5          0.0001         0.415404   
                                                                                      0.0005         0.648914   
                                                                                      0.0010         0.715963   
                                                          (512, 512)     0.1          0.0001         0.423255   
                                                                                      0.0005         0.642018   
                                                                                      0.0010         0.717329   
                                                                         0.5          0.0001         0.411785   
                                                                                      0.0005         0.635873   
                                                                                      0.0010         0.714461   
                                     12        1          (256, 256)     0.1          0.0001         0.403113   
                                                                                      0.0005         0.613478   
                                                                                      0.0010         0.723133   
                                                                         0.5          0.0001         0.420661   
                                                                                      0.0005         0.640584   
                                                                                      0.0010         0.721494   
                                                          (512, 512)     0.1          0.0001         0.422914   
                                                                                      0.0005         0.633484   
                                                                                      0.0010         0.725317   
                                                                         0.5          0.0001         0.410692   
                                                                                      0.0005         0.638263   
                                                                                      0.0010         0.718353   
           12              3         10        1          (256, 256)     0.1          0.0001         0.495698   
                                                                                      0.0005         0.564113   
                                                                                      0.0010         0.652260   
                                                                         0.5          0.0001         0.493309   
                                                                                      0.0005         0.563908   
                                                                                      0.0010         0.646729   
                                                          (512, 512)     0.1          0.0001         0.509969   
                                                                                      0.0005         0.576062   
                                                                                      0.0010         0.671446   
                                                                         0.5          0.0001         0.495972   
                                 

In [20]:
best_swmhau_network_grp_kfold_20

loss  accuracy        f1  \
0  None  0.718353  0.689700   
0  None  0.709545  0.678953   
0  None  0.724088  0.691761   

                                           f1_scores  precision  \
0  [0.7304672897196262, 0.5233506300963677, 0.646...   0.689632   
0  [0.7385068039720484, 0.49791376912378305, 0.62...   0.677774   
0  [0.7343283582089551, 0.5084745762711865, 0.661...   0.697059   

                                    precision_scores    recall  \
0  [0.7509607993850884, 0.4895977808599168, 0.621...  0.692572   
0  [0.7464684014869889, 0.4419753086419753, 0.630...  0.684938   
0  [0.7534456355283308, 0.5155482815057283, 0.610...  0.690211   

                                       recall_scores valid_loss  \
0  [0.7110625909752547, 0.5621019108280255, 0.673...       None   
0  [0.7307132459970888, 0.5700636942675159, 0.613...       None   
0  [0.7161572052401747, 0.5015923566878981, 0.722...       None   

   valid_accuracy  ...  learning_rate seed  loss_function gamma  k_fold  \
0        0.721955  ...          0.001    1          focal     2    True   
0        0.717766  ...          0.001   12          focal     2    True   
0        0.732661  ...          0.001  123          focal     2    True   

  n_splits  augmentation_type  hidden_dim_aug    comb_method batch_size  
0        5             Conv1d            None  concatenation         64  
0        5             Conv1d            None  concatenation         64  
0        5             Conv1d            None  concatenation         64  

[3 rows x 42 columns]

In [21]:
best_swmhau_network_grp_kfold_20["f1"].mean()

0.6868047155741359

In [22]:
best_swmhau_network_grp_kfold_20["precision"].mean()

0.6881549643809765

In [23]:
best_swmhau_network_grp_kfold_20["recall"].mean()

0.689240383625818

In [24]:
np.stack(best_swmhau_network_grp_kfold_20["f1_scores"]).mean(axis=0)

array([0.73443415, 0.50991299, 0.64329698, 0.85957474])

In [25]:
np.stack(best_swmhau_network_grp_kfold_20["precision_scores"]).mean(axis=0)

array([0.75029161, 0.48237379, 0.62073661, 0.89921784])

In [26]:
np.stack(best_swmhau_network_grp_kfold_20["recall_scores"]).mean(axis=0)

array([0.71931101, 0.54458599, 0.66974596, 0.82331857])