In [1]:
import numpy as np
import pickle
import os

seed = 2023

In [2]:
from nlpsig_networks.scripts.ffn_baseline_functions import (
    ffn_hyperparameter_search,
)

In [3]:
output_dir = "therapist_talk_type_output"
if not os.path.isdir(output_dir):
    os.makedirs(output_dir)

## AnnoMI

In [4]:
%run ../load_anno_mi.py

In [5]:
anno_mi.head()

mi_quality  transcript_id                         topic  utterance_id  \
0       high              0  reducing alcohol consumption             0   
1       high              0  reducing alcohol consumption             1   
2       high              0  reducing alcohol consumption             2   
3       high              0  reducing alcohol consumption             3   
4       high              0  reducing alcohol consumption             4   

  interlocutor timestamp                                     utterance_text  \
0    therapist  00:00:13  Thanks for filling it out. We give this form t...   
1       client  00:00:24                                              Sure.   
2    therapist  00:00:25  So, let's see. It looks that you put-- You dri...   
3       client  00:00:34                                            Mm-hmm.   
4    therapist  00:00:34  -and you usually have three to four drinks whe...   

   annotator_id therapist_input_exists therapist_input_subtype  \
0             3                  False                     NaN   
1             3                    NaN                     NaN   
2             3                   True             information   
3             3                    NaN                     NaN   
4             3                   True             information   

  reflection_exists reflection_subtype question_exists question_subtype  \
0             False                NaN            True             open   
1               NaN                NaN             NaN              NaN   
2             False                NaN           False              NaN   
3               NaN                NaN             NaN              NaN   
4             False                NaN           False              NaN   

  main_therapist_behaviour client_talk_type            datetime  
0                 question              NaN 2023-08-19 00:00:13  
1                      NaN          neutral 2023-08-19 00:00:24  
2          therapist_input              NaN 2023-08-19 00:00:25  
3                      NaN          neutral 2023-08-19 00:00:34  
4          therapist_input              NaN 2023-08-19 00:00:34

In [6]:
with open("../anno_mi_sbert.pkl", "rb") as f:
    sbert_embeddings = pickle.load(f)
    
sbert_embeddings.shape

(9699, 384)

In [7]:
output_dim_therapist

4

In [8]:
label_to_id_therapist

{'question': 0, 'therapist_input': 1, 'reflection': 2, 'other': 3}

In [9]:
id_to_label_therapist

{0: 'question', 1: 'therapist_input', 2: 'reflection', 3: 'other'}

# Baseline: FFN baseline

Using the embeddings for the sentences directly in a FFN to predict the therapist talk type.

In [10]:
num_epochs = 100
hidden_dim_sizes = [[64,64],[128,128],[256,256]]
dropout_rates = [0.5, 0.1]
learning_rates = [1e-3, 1e-4, 5e-4]
seeds = [1, 12, 123]
loss = "focal"
gamma = 2
validation_metric = "f1"
patience = 5

We use the `ffn_hyperparameter_search` function which loops through the different hidden dimensions, dropout rates and learning rates to find the best model for the validation set. We evaluate the model on several seeds and average the performance over the seeds.

In [11]:
ffn_current, best_ffn_current, _, __ = ffn_hyperparameter_search(
    num_epochs=num_epochs,
    x_data=sbert_embeddings[therapist_index],
    y_data=y_data_therapist,
    hidden_dim_sizes=hidden_dim_sizes,
    output_dim=output_dim_therapist,
    dropout_rates=dropout_rates,
    learning_rates=learning_rates,
    seeds=seeds,
    loss=loss,
    gamma=gamma,
    k_fold=False,
    patience=patience,
    split_ids=therapist_transcript_id,
    validation_metric=validation_metric,
    results_output=f"{output_dir}/ffn_current_focal_{gamma}.csv",
    verbose=False
)

  0%|          | 0/3 [00:00<?, ?it/s]

  0%|          | 0/2 [00:00<?, ?it/s]

  0%|          | 0/3 [00:00<?, ?it/s]

  0%|          | 0/3 [00:00<?, ?it/s]

  0%|          | 0/2 [00:00<?, ?it/s]

  0%|          | 0/3 [00:00<?, ?it/s]

  0%|          | 0/3 [00:00<?, ?it/s]

  0%|          | 0/2 [00:00<?, ?it/s]

  0%|          | 0/3 [00:00<?, ?it/s]

  0%|          | 0/3 [00:00<?, ?it/s]

saving results dataframe to CSV for this hyperparameter search in therapist_talk_type_output/ffn_current_focal_2.csv
saving the best model results dataframe to CSV for this hyperparameter search in therapist_talk_type_output/ffn_current_focal_2_best_model.csv


In [12]:
ffn_current

loss  accuracy        f1  \
0  0.688400  0.775556  0.738975   
0  0.698119  0.764444  0.725872   
0  0.695803  0.764444  0.729739   
0  0.737284  0.772222  0.737210   
0  0.705236  0.764444  0.724082   
0  0.725045  0.766667  0.726373   
0  0.732368  0.772222  0.735728   
0  0.685390  0.767778  0.731942   
0  0.656865  0.771111  0.733758   
0  0.734442  0.771111  0.734854   
0  0.658676  0.761111  0.728152   
0  0.710308  0.762222  0.727039   
0  0.680285  0.773333  0.741574   
0  0.702354  0.765556  0.727577   
0  0.678220  0.764444  0.726172   
0  0.689191  0.770000  0.734850   
0  0.686889  0.766667  0.728952   
0  0.743731  0.760000  0.720126   
0  0.669882  0.757778  0.723126   
0  0.707350  0.764444  0.729888   
0  0.708885  0.765556  0.722208   
0  0.757341  0.767778  0.731562   
0  0.709618  0.764444  0.728221   
0  0.737151  0.766667  0.728860   
0  0.721884  0.768889  0.734856   
0  0.734172  0.763333  0.729328   
0  0.727643  0.767778  0.737613   
0  0.710951  0.767778  0.732877   
0  0.695080  0.760000  0.722125   
0  0.668978  0.773333  0.737762   
0  0.706657  0.768889  0.736378   
0  0.710932  0.766667  0.731169   
0  0.645986  0.770000  0.740521   
0  0.729884  0.764444  0.729548   
0  0.711897  0.762222  0.727674   
0  0.716814  0.771111  0.739942   
0  0.693359  0.777778  0.739260   
0  0.682007  0.772222  0.740575   
0  0.660814  0.768889  0.736052   
0  0.786738  0.762222  0.715794   
0  0.657338  0.770000  0.738265   
0  0.679351  0.772222  0.734912   
0  0.730269  0.770000  0.733466   
0  0.702233  0.768889  0.737927   
0  0.785093  0.773333  0.738609   
0  0.695278  0.770000  0.734477   
0  0.705279  0.755556  0.715103   
0  0.651912  0.766667  0.732006   
0  0.723556  0.774444  0.738025   
0  0.735966  0.767778  0.734577   
0  0.654705  0.766667  0.729615   
0  0.707218  0.775556  0.740303   
0  0.685166  0.766667  0.730861   
0  0.672289  0.767778  0.732699   

                                           f1_scores  precision  \
0  [0.815742397137746, 0.5784313725490198, 0.6997...   0.749626   
0  [0.8066298342541437, 0.5520833333333333, 0.687...   0.747548   
0  [0.7977736549165121, 0.5688073394495413, 0.690...   0.733279   
0  [0.8051948051948052, 0.5771144278606964, 0.694...   0.752662   
0  [0.8115942028985507, 0.5454545454545454, 0.678...   0.738973   
0  [0.8094373865698729, 0.5492227979274612, 0.685...   0.745613   
0  [0.8075471698113207, 0.5685279187817258, 0.695...   0.754755   
0  [0.8051001821493625, 0.5757575757575758, 0.682...   0.748368   
0  [0.8138686131386861, 0.5670103092783505, 0.692...   0.753762   
0  [0.8044280442804429, 0.5714285714285715, 0.694...   0.753782   
0  [0.7937743190661478, 0.5700000000000001, 0.689...   0.748905   
0  [0.8028419182948491, 0.5627705627705628, 0.675...   0.727782   
0  [0.8007448789571696, 0.5990338164251208, 0.698...   0.752208   
0  [0.8081180811808119, 0.5583756345177665, 0.679...   0.744836   
0  [0.8051470588235293, 0.5555555555555556, 0.675...   0.742826   
0  [0.8104089219330854, 0.5741626794258373, 0.694...   0.743106   
0  [0.8051948051948052, 0.5583756345177665, 0.695...   0.745407   
0  [0.8052434456928839, 0.5353535353535355, 0.674...   0.737536   
0  [0.7923809523809523, 0.5544554455445544, 0.689...   0.740630   
0  [0.7962616822429905, 0.5700000000000001, 0.688...   0.746854   
0  [0.8007054673721341, 0.5376344086021505, 0.681...   0.748109   
0  [0.8051470588235293, 0.5700000000000001, 0.686...   0.746361   
0  [0.7992700729927008, 0.5671641791044776, 0.682...   0.742136   
0  [0.7992495309568479, 0.5621621621621622, 0.684...   0.760718   
0  [0.8051470588235293, 0.5812807881773399, 0.690...   0.747984   
0  [0.7999999999999998, 0.5728155339805826, 0.683...   0.741433   
0  [0.7970479704797048, 0.6055045871559633, 0.683...   0.741734   
0  [0.8014705882352942, 0.5741626794258373, 0.691...   0.741274   
0  [0.7931034482758621, 0.5454545454545454, 0.691...   0.739868   
0  [0.8117001828153564, 0.5686274509803921, 0.709...   0.750410   
0  [

In [13]:
ffn_current.groupby(["hidden_dim", "dropout_rate", "learning_rate"]).mean()

/tmp/ipykernel_1915905/3305696319.py:1: FutureWarning: The default value of numeric_only in DataFrameGroupBy.mean is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  ffn_current.groupby(["hidden_dim", "dropout_rate", "learning_rate"]).mean()


loss  accuracy        f1  \
hidden_dim dropout_rate learning_rate                                 
(64, 64)   0.1          0.0001         0.686953  0.767778  0.731774   
                        0.0005         0.706603  0.765556  0.727976   
                        0.0010         0.701142  0.764815  0.730015   
           0.5          0.0001         0.722522  0.767778  0.729222   
                        0.0005         0.691541  0.770370  0.733810   
                        0.0010         0.694107  0.768148  0.731529   
(128, 128) 0.1          0.0001         0.687858  0.768519  0.736023   
                        0.0005         0.719532  0.765926  0.732388   
                        0.0010         0.691670  0.767037  0.730921   
           0.5          0.0001         0.734703  0.766296  0.729548   
                        0.0005         0.727900  0.766667  0.733933   
                        0.0010         0.695372  0.762593  0.725074   
(256, 256) 0.1          0.0001         0.704743  0.769630  0.734072   
                        0.0005         0.688224  0.770000  0.734621   
                        0.0010         0.684156  0.764074  0.727195   
           0.5          0.0001         0.707809  0.768148  0.729657   
                        0.0005         0.739199  0.770741  0.736667   
                        0.0010         0.678727  0.772963  0.738629   

                                       precision    recall  valid_loss  \
hidden_dim dropout_rate learning_rate                                    
(64, 64)   0.1          0.0001          0.746623  0.727195    0.755143   
                        0.0005          0.742016  0.724126    0.762475   
                        0.0010          0.743490  0.727845    0.765919   
           0.5          0.0001          0.745749  0.724245    0.766622   
                        0.0005          0.752295  0.728453    0.764874   
                        0.0010          0.743484  0.727816    0.760064   
(128, 128) 0.1          0.0001          0.750983  0.731518    0.749309   
                        0.0005          0.744541  0.729708    0.746130   
                        0.0010          0.743851  0.727956    0.748847   
           0.5          0.0001          0.749738  0.723915    0.766852   
                        0.0005          0.743717  0.731011    0.762495   
                        0.0010          0.745197  0.720595    0.765983   
(256, 256) 0.1          0.0001          0.746249  0.731011    0.751852   
                        0.0005          0.748143  0.731234    0.749426   
                        0.0010          0.736640  0.726032    0.757434   
           0.5          0.0001          0.747202  0.725700    0.776052   
                        0.0005          0.748962  0.733451    0.744417   
                        0.0010          0.750344  0.735826    0.748047   

                                       valid_accuracy  valid_f1  \
hidden_dim dropout_rate learning_rate                             
(64, 64)   0.1          0.0001               0.725241  0.694131   
                        0.0005               0.724856  0.692080   
                        0.0010               0.717919  0.688437   
           0.5          0.0001               0.729094  0.697413   
                        0.0005               0.726397  0.694321   
                        0.0010               0.723699  0.689815   
(128, 128) 0.1          0.0001               0.727553  0.697880   
                        0.0005               0.723699  0.692557   
                        0.0010               0.724856  0.693135   
           0.5          0.0001               0.728709  0.699479   
                        0.0005               0.726012  0.696401   
                        0.0010               0.723314  0.691885   
(256, 256) 0.1          0.0001               0.726782  0.697181   
                        0.0005               0.722929  0.693676   
                        0.0010               0.722158  0.690667   
  

In [14]:
best_ffn_current

loss  accuracy        f1  \
0  0.757341  0.767778  0.731562   
0  0.709618  0.764444  0.728221   
0  0.737151  0.766667  0.728860   

                                           f1_scores  precision  \
0  [0.8051470588235293, 0.5700000000000001, 0.686...   0.746361   
0  [0.7992700729927008, 0.5671641791044776, 0.682...   0.742136   
0  [0.7992495309568479, 0.5621621621621622, 0.684...   0.760718   

                                    precision_scores    recall  \
0  [0.8021978021978022, 0.6627906976744186, 0.622...  0.726750   
0  [0.7906137184115524, 0.6551724137931034, 0.622...  0.723541   
0  [0.8129770992366412, 0.7323943661971831, 0.595...  0.721454   

                                       recall_scores  valid_loss  \
0  [0.8081180811808119, 0.5, 0.7655502392344498, ...    0.758058   
0  [0.8081180811808119, 0.5, 0.7559808612440191, ...    0.751756   
0  [0.7859778597785978, 0.45614035087719296, 0.80...    0.790741   

   valid_accuracy  ...                                valid_recall_scores  \
0        0.731792  ...  [0.7559322033898305, 0.5294117647058824, 0.695...   
0        0.728324  ...  [0.752542372881356, 0.5392156862745098, 0.6826...   
0        0.726012  ...  [0.7186440677966102, 0.5098039215686274, 0.730...   

   hidden_dim  dropout_rate learning_rate  seed loss_function gamma  k_fold  \
0  (128, 128)           0.5        0.0001     1         focal     2   False   
0  (128, 128)           0.5        0.0001    12         focal     2   False   
0  (128, 128)           0.5        0.0001   123         focal     2   False   

   n_splits  batch_size  
0      None          64  
0      None          64  
0      None          64  

[3 rows x 25 columns]

In [15]:
best_ffn_current["f1"].mean()

0.7295480092797342

In [16]:
best_ffn_current["precision"].mean()

0.7497380871340166

In [17]:
best_ffn_current["recall"].mean()

0.7239150998790221

In [18]:
np.stack(best_ffn_current["f1_scores"]).mean(axis=0)

array([0.80122222, 0.56644211, 0.68450613, 0.86602157])

In [19]:
np.stack(best_ffn_current["precision_scores"]).mean(axis=0)

array([0.80192954, 0.68345249, 0.61345334, 0.90011698])

In [20]:
np.stack(best_ffn_current["recall_scores"]).mean(axis=0)

array([0.80073801, 0.48538012, 0.77511962, 0.83442266])

## KFold

We can repeat this but use K-Fold evaluation instead - by default, we have $K=5$ folds.

In [21]:
ffn_current_kfold, best_ffn_current_kfold, _, __ = ffn_hyperparameter_search(
    num_epochs=num_epochs,
    x_data=sbert_embeddings[therapist_index],
    y_data=y_data_therapist,
    hidden_dim_sizes=hidden_dim_sizes,
    output_dim=output_dim_therapist,
    dropout_rates=dropout_rates,
    learning_rates=learning_rates,
    seeds=seeds,
    loss=loss,
    gamma=gamma,
    k_fold=True,
    patience=patience,
    split_ids=therapist_transcript_id,
    validation_metric=validation_metric,
    results_output=f"{output_dir}/ffn_current_focal_{gamma}_kfold.csv",
    verbose=False
)

  0%|          | 0/3 [00:00<?, ?it/s]

  0%|          | 0/2 [00:00<?, ?it/s]

  0%|          | 0/3 [00:00<?, ?it/s]

  0%|          | 0/3 [00:00<?, ?it/s]

  0%|          | 0/2 [00:00<?, ?it/s]

  0%|          | 0/3 [00:00<?, ?it/s]

  0%|          | 0/3 [00:00<?, ?it/s]

  0%|          | 0/2 [00:00<?, ?it/s]

  0%|          | 0/3 [00:00<?, ?it/s]

  0%|          | 0/3 [00:00<?, ?it/s]

saving results dataframe to CSV for this hyperparameter search in therapist_talk_type_output/ffn_current_focal_2_kfold.csv
saving the best model results dataframe to CSV for this hyperparameter search in therapist_talk_type_output/ffn_current_focal_2_kfold_best_model.csv


In [22]:
ffn_current_kfold

loss  accuracy        f1  \
0  None  0.734725  0.701630   
0  None  0.736812  0.702193   
0  None  0.733207  0.700080   
0  None  0.736433  0.699780   
0  None  0.736433  0.697915   
0  None  0.735863  0.693420   
0  None  0.735294  0.701780   
0  None  0.734915  0.700256   
0  None  0.738899  0.704191   
0  None  0.732638  0.699670   
0  None  0.736622  0.703308   
0  None  0.733017  0.700861   
0  None  0.733966  0.700241   
0  None  0.732827  0.696705   
0  None  0.734915  0.700475   
0  None  0.738710  0.705008   
0  None  0.729981  0.695497   
0  None  0.731309  0.698489   
0  None  0.733586  0.701820   
0  None  0.732827  0.700480   
0  None  0.731879  0.699143   
0  None  0.740038  0.706514   
0  None  0.734915  0.701465   
0  None  0.738710  0.704654   
0  None  0.735104  0.703548   
0  None  0.732448  0.698834   
0  None  0.730740  0.697475   
0  None  0.731499  0.697051   
0  None  0.730930  0.699214   
0  None  0.726565  0.694470   
0  None  0.736622  0.703243   
0  None  0.732068  0.698439   
0  None  0.733397  0.700901   
0  None  0.732638  0.701386   
0  None  0.733966  0.700790   
0  None  0.732068  0.700492   
0  None  0.731879  0.699955   
0  None  0.736243  0.703160   
0  None  0.731120  0.699016   
0  None  0.734345  0.700826   
0  None  0.738140  0.704464   
0  None  0.733966  0.699673   
0  None  0.732068  0.699367   
0  None  0.735484  0.701811   
0  None  0.731689  0.699606   
0  None  0.727324  0.694708   
0  None  0.725427  0.695503   
0  None  0.727894  0.695294   
0  None  0.735104  0.702081   
0  None  0.733586  0.701874   
0  None  0.731879  0.698168   
0  None  0.734156  0.702087   
0  None  0.733586  0.700196   
0  None  0.729602  0.697712   

                                           f1_scores  precision  \
0  [0.7579222476314931, 0.5231884057971014, 0.662...   0.701194   
0  [0.767816091954023, 0.5121056493030082, 0.6645...   0.702707   
0  [0.7615635179153094, 0.5177304964539007, 0.658...   0.699226   
0  [0.7629678266579121, 0.5085271317829457, 0.660...   0.703100   
0  [0.7658743080429827, 0.49842271293375395, 0.66...   0.702077   
0  [0.7710371819960861, 0.4789915966386555, 0.660...   0.703673   
0  [0.7599738391105297, 0.5217391304347826, 0.661...   0.701258   
0  [0.7641478573765129, 0.5119760479041916, 0.663...   0.701895   
0  [0.7674190382728164, 0.5173176123802505, 0.669...   0.704327   
0  [0.7585067723818963, 0.5185724690458849, 0.662...   0.699748   
0  [0.7653910149750416, 0.5212922173274597, 0.666...   0.703546   
0  [0.7582345191040842, 0.5223021582733813, 0.663...   0.700606   
0  [0.7591045773471434, 0.5164594001463059, 0.665...   0.700220   
0  [0.7666666666666667, 0.5014970059880239, 0.659...   0.697872   
0  [0.7638795986622072, 0.513089005235602, 0.6666...   0.701862   
0  [0.7628797886393659, 0.5243445692883896, 0.671...   0.706085   
0  [0.7611741160773849, 0.5036179450072359, 0.658...   0.695510   
0  [0.7645687645687645, 0.5140449438202247, 0.658...   0.697206   
0  [0.7585983127839064, 0.5278174037089872, 0.659...   0.701222   
0  [0.7572099262240107, 0.5193687230989957, 0.666...   0.700116   
0  [0.7624671916010498, 0.5187279151943462, 0.656...   0.697944   
0  [0.7695338148391332, 0.5280478683620045, 0.666...   0.707462   
0  [0.7630708140304433, 0.5210954848260547, 0.663...   0.701970   
0  [0.7665896335424232, 0.5216095380029806, 0.670...   0.705361   
0  [0.763897972531066, 0.5332380271622589, 0.6566...   0.702521   
0  [0.7613333333333333, 0.5151953690303909, 0.656...   0.698462   
0  [0.76221928665786, 0.5131761442441055, 0.65313...   0.695775   
0  [0.7597509013438217, 0.5072886297376094, 0.666...   0.697028   
0  [0.7591863517060368, 0.5194071983062809, 0.657...   0.698866   
0  [0.7578806170355465, 0.5148788927335639, 0.645...   0.692881   
0  [0.7678452301534355, 0.5207877461706782, 0.665...   0.703036   
0  [0.7641572285143239, 0.5134155184916607, 0.658...   0.698190   
0  [0.7636974789915966, 0.5195729537366548, 0.663...   0.699943   
0  [0.7583417593528

In [23]:
ffn_current_kfold.groupby(["hidden_dim", "dropout_rate", "learning_rate"]).mean()

/tmp/ipykernel_1915905/3418571787.py:1: FutureWarning: The default value of numeric_only in DataFrameGroupBy.mean is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  ffn_current_kfold.groupby(["hidden_dim", "dropout_rate", "learning_rate"]).mean()


accuracy        f1  precision  \
hidden_dim dropout_rate learning_rate                                  
(64, 64)   0.1          0.0001         0.733903  0.699140   0.699985   
                        0.0005         0.733333  0.699665   0.699600   
                        0.0010         0.734092  0.701280   0.701300   
           0.5          0.0001         0.736243  0.697038   0.702950   
                        0.0005         0.736369  0.702076   0.702494   
                        0.0010         0.734915  0.701301   0.701042   
(128, 128) 0.1          0.0001         0.734029  0.700861   0.700390   
                        0.0005         0.732891  0.700889   0.700504   
                        0.0010         0.729665  0.696912   0.696258   
           0.5          0.0001         0.737887  0.704211   0.704931   
                        0.0005         0.732764  0.699953   0.698919   
                        0.0010         0.732764  0.700481   0.699761   
(256, 256) 0.1          0.0001         0.733523  0.700707   0.700130   
                        0.0005         0.732448  0.699998   0.699110   
                        0.0010         0.726882  0.695168   0.694039   
           0.5          0.0001         0.735484  0.701655   0.701602   
                        0.0005         0.733080  0.700261   0.700615   
                        0.0010         0.733080  0.700711   0.699996   

                                         recall  valid_accuracy  valid_f1  \
hidden_dim dropout_rate learning_rate                                       
(64, 64)   0.1          0.0001         0.699055        0.755274  0.725999   
                        0.0005         0.700784        0.754905  0.725671   
                        0.0010         0.702279        0.752004  0.723014   
           0.5          0.0001         0.694045        0.757173  0.724455   
                        0.0005         0.702580        0.756751  0.726481   
                        0.0010         0.702748        0.755169  0.725324   
(128, 128) 0.1          0.0001         0.702181        0.754430  0.725589   
                        0.0005         0.702972        0.753587  0.725764   
                        0.0010         0.699192        0.752373  0.722855   
           0.5          0.0001         0.704156        0.757437  0.727819   
                        0.0005         0.702245        0.756171  0.727361   
                        0.0010         0.702631        0.754747  0.726410   
(256, 256) 0.1          0.0001         0.702461        0.753586  0.725083   
                        0.0005         0.702967        0.750686  0.721666   
                        0.0010         0.699766        0.748101  0.719459   
           0.5          0.0001         0.702574        0.754852  0.725522   
                        0.0005         0.701771        0.756540  0.727958   
                        0.0010         0.703403        0.753903  0.724099   

                                       valid_precision  valid_recall  \
hidden_dim dropout_rate learning_rate                                  
(64, 64)   0.1          0.0001                0.724266      0.729179   
                        0.0005                0.723740      0.729527   
                        0.0010                0.721072      0.726920   
           0.5          0.0001                0.726269      0.723763   
                        0.0005                0.725006      0.729241   
                        0.0010                0.723544      0.728929   
(128, 128) 0.1          0.0001                0.723368      0.729714   
                        0.0005                0.723841      0.730474   
                        0.0010                0.720934      0.727293   
           0.5          0.0001                0.726095      0.730599   
                        0.0005                0.725003      0.732207   
                        0.0010                0.724277      0.730888   
(256, 256) 0.1          0.0001                0.7

In [24]:
best_ffn_current_kfold

loss  accuracy        f1  \
0  None  0.732068  0.699367   
0  None  0.735484  0.701811   
0  None  0.731689  0.699606   

                                           f1_scores  precision  \
0  [0.7584589614740368, 0.5145700071073205, 0.661...   0.698970   
0  [0.7597840755735493, 0.5161290322580646, 0.670...   0.704227   
0  [0.7595959595959595, 0.5131034482758621, 0.662...   0.698649   

                                    precision_scores    recall  \
0  [0.760752688172043, 0.49118046132971505, 0.644...  0.701272   
0  [0.7675528289025222, 0.5188536953242836, 0.635...  0.701075   
0  [0.7657841140529531, 0.47692307692307695, 0.65...  0.702967   

                                       recall_scores valid_loss  \
0  [0.7561790247160989, 0.5402985074626866, 0.679...       None   
0  [0.7521710086840347, 0.5134328358208955, 0.709...       None   
0  [0.7535070140280561, 0.5552238805970149, 0.674...       None   

   valid_accuracy  ...                                valid_recall_scores  \
0        0.755538  ...  [0.7607709750566893, 0.6163366336633663, 0.706...   
0        0.759177  ...  [0.7590702947845805, 0.5841584158415841, 0.732...   
0        0.754905  ...  [0.7647392290249433, 0.6126237623762376, 0.704...   

   hidden_dim  dropout_rate learning_rate  seed loss_function gamma  k_fold  \
0  (256, 256)           0.5        0.0005     1         focal     2    True   
0  (256, 256)           0.5        0.0005    12         focal     2    True   
0  (256, 256)           0.5        0.0005   123         focal     2    True   

   n_splits  batch_size  
0         5          64  
0         5          64  
0         5          64  

[3 rows x 25 columns]

In [25]:
best_ffn_current_kfold["f1"].mean()

0.7002612172691872

In [26]:
best_ffn_current_kfold["precision"].mean()

0.7006151039699103

In [27]:
best_ffn_current_kfold["recall"].mean()

0.7017711936951435

In [28]:
np.stack(best_ffn_current_kfold["f1_scores"]).mean(axis=0)

array([0.75927967, 0.51460083, 0.6646804 , 0.86248397])

In [29]:
np.stack(best_ffn_current_kfold["precision_scores"]).mean(axis=0)

array([0.76469654, 0.49565241, 0.64347717, 0.89863429])

In [30]:
np.stack(best_ffn_current_kfold["recall_scores"]).mean(axis=0)

array([0.75395235, 0.53631841, 0.68767908, 0.82913493])