In [1]:
import numpy as np
import pickle
import os

seed = 2023

In [2]:
import torch

# set device
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [4]:
import transformers

# set to only report critical errors to avoid excessing logging
transformers.utils.logging.set_verbosity(50)

In [5]:
from nlpsig_networks.scripts.fine_tune_bert_classification import (
    fine_tune_transformer_average_seed,
)

In [6]:
output_dir = "therapist_talk_type_output"
if not os.path.isdir(output_dir):
    os.makedirs(output_dir)

## AnnoMI

In [7]:
%run ../load_anno_mi.py

In [8]:
anno_mi.head()

mi_quality  transcript_id                         topic  utterance_id  \
0       high              0  reducing alcohol consumption             0   
1       high              0  reducing alcohol consumption             1   
2       high              0  reducing alcohol consumption             2   
3       high              0  reducing alcohol consumption             3   
4       high              0  reducing alcohol consumption             4   

  interlocutor timestamp                                     utterance_text  \
0    therapist  00:00:13  Thanks for filling it out. We give this form t...   
1       client  00:00:24                                              Sure.   
2    therapist  00:00:25  So, let's see. It looks that you put-- You dri...   
3       client  00:00:34                                            Mm-hmm.   
4    therapist  00:00:34  -and you usually have three to four drinks whe...   

   annotator_id therapist_input_exists therapist_input_subtype  \
0             3                  False                     NaN   
1             3                    NaN                     NaN   
2             3                   True             information   
3             3                    NaN                     NaN   
4             3                   True             information   

  reflection_exists reflection_subtype question_exists question_subtype  \
0             False                NaN            True             open   
1               NaN                NaN             NaN              NaN   
2             False                NaN           False              NaN   
3               NaN                NaN             NaN              NaN   
4             False                NaN           False              NaN   

  main_therapist_behaviour client_talk_type            datetime  
0                 question              NaN 2023-08-19 00:00:13  
1                      NaN          neutral 2023-08-19 00:00:24  
2          therapist_input              NaN 2023-08-19 00:00:25  
3                      NaN          neutral 2023-08-19 00:00:34  
4          therapist_input              NaN 2023-08-19 00:00:34

In [9]:
with open("../anno_mi_sbert.pkl", "rb") as f:
    sbert_embeddings = pickle.load(f)

sbert_embeddings.shape

(9699, 384)

# Baseline: Fine-tune BERT for classification

In [10]:
num_epochs = 10
seeds = [1, 12, 123]
loss = "focal"
gamma = 2
validation_metric = "f1"

In [11]:
bert_classifier = fine_tune_transformer_average_seed(
    num_epochs=num_epochs,
    pretrained_model_name="bert-base-uncased",
    df=anno_mi,
    feature_name="utterance_text",
    label_column="main_therapist_behaviour",
    seeds=seeds,
    loss=loss,
    gamma=gamma,
    path_indices=therapist_index,
    k_fold=True,
    validation_metric=validation_metric,
    results_output=f"{output_dir}/bert_classifier.csv",
    device=device,
    verbose=False,
)

Map:   0%|          | 0/4882 [00:00<?, ? examples/s]

Map:   0%|          | 0/4882 [00:00<?, ? examples/s]

/bask/projects/v/vjgo8416-rough-paths/envs/nlpsig-networks/lib/python3.8/site-packages/transformers/optimization.py:411: FutureWarning: This implementation of AdamW is deprecated and will be removed in a future version. Use the PyTorch implementation torch.optim.AdamW instead, or set `no_deprecation_warning=True` to disable this warning
  warnings.warn(


  0%|          | 0/977 [00:00<?, ?it/s]

Map:   0%|          | 0/4882 [00:00<?, ? examples/s]

Map:   0%|          | 0/4882 [00:00<?, ? examples/s]

/bask/projects/v/vjgo8416-rough-paths/envs/nlpsig-networks/lib/python3.8/site-packages/transformers/optimization.py:411: FutureWarning: This implementation of AdamW is deprecated and will be removed in a future version. Use the PyTorch implementation torch.optim.AdamW instead, or set `no_deprecation_warning=True` to disable this warning
  warnings.warn(


  0%|          | 0/977 [00:00<?, ?it/s]

Map:   0%|          | 0/4882 [00:00<?, ? examples/s]

Map:   0%|          | 0/4882 [00:00<?, ? examples/s]

/bask/projects/v/vjgo8416-rough-paths/envs/nlpsig-networks/lib/python3.8/site-packages/transformers/optimization.py:411: FutureWarning: This implementation of AdamW is deprecated and will be removed in a future version. Use the PyTorch implementation torch.optim.AdamW instead, or set `no_deprecation_warning=True` to disable this warning
  warnings.warn(


  0%|          | 0/976 [00:00<?, ?it/s]

Map:   0%|          | 0/4882 [00:00<?, ? examples/s]

Map:   0%|          | 0/4882 [00:00<?, ? examples/s]

/bask/projects/v/vjgo8416-rough-paths/envs/nlpsig-networks/lib/python3.8/site-packages/transformers/optimization.py:411: FutureWarning: This implementation of AdamW is deprecated and will be removed in a future version. Use the PyTorch implementation torch.optim.AdamW instead, or set `no_deprecation_warning=True` to disable this warning
  warnings.warn(


  0%|          | 0/976 [00:00<?, ?it/s]

Map:   0%|          | 0/4882 [00:00<?, ? examples/s]

Map:   0%|          | 0/4882 [00:00<?, ? examples/s]

/bask/projects/v/vjgo8416-rough-paths/envs/nlpsig-networks/lib/python3.8/site-packages/transformers/optimization.py:411: FutureWarning: This implementation of AdamW is deprecated and will be removed in a future version. Use the PyTorch implementation torch.optim.AdamW instead, or set `no_deprecation_warning=True` to disable this warning
  warnings.warn(


  0%|          | 0/976 [00:00<?, ?it/s]

Map:   0%|          | 0/4882 [00:00<?, ? examples/s]

Map:   0%|          | 0/4882 [00:00<?, ? examples/s]

/bask/projects/v/vjgo8416-rough-paths/envs/nlpsig-networks/lib/python3.8/site-packages/transformers/optimization.py:411: FutureWarning: This implementation of AdamW is deprecated and will be removed in a future version. Use the PyTorch implementation torch.optim.AdamW instead, or set `no_deprecation_warning=True` to disable this warning
  warnings.warn(


  0%|          | 0/977 [00:00<?, ?it/s]

Map:   0%|          | 0/4882 [00:00<?, ? examples/s]

Map:   0%|          | 0/4882 [00:00<?, ? examples/s]

/bask/projects/v/vjgo8416-rough-paths/envs/nlpsig-networks/lib/python3.8/site-packages/transformers/optimization.py:411: FutureWarning: This implementation of AdamW is deprecated and will be removed in a future version. Use the PyTorch implementation torch.optim.AdamW instead, or set `no_deprecation_warning=True` to disable this warning
  warnings.warn(


  0%|          | 0/977 [00:00<?, ?it/s]

Map:   0%|          | 0/4882 [00:00<?, ? examples/s]

Map:   0%|          | 0/4882 [00:00<?, ? examples/s]

/bask/projects/v/vjgo8416-rough-paths/envs/nlpsig-networks/lib/python3.8/site-packages/transformers/optimization.py:411: FutureWarning: This implementation of AdamW is deprecated and will be removed in a future version. Use the PyTorch implementation torch.optim.AdamW instead, or set `no_deprecation_warning=True` to disable this warning
  warnings.warn(


  0%|          | 0/976 [00:00<?, ?it/s]

Map:   0%|          | 0/4882 [00:00<?, ? examples/s]

Map:   0%|          | 0/4882 [00:00<?, ? examples/s]

/bask/projects/v/vjgo8416-rough-paths/envs/nlpsig-networks/lib/python3.8/site-packages/transformers/optimization.py:411: FutureWarning: This implementation of AdamW is deprecated and will be removed in a future version. Use the PyTorch implementation torch.optim.AdamW instead, or set `no_deprecation_warning=True` to disable this warning
  warnings.warn(


  0%|          | 0/976 [00:00<?, ?it/s]

Map:   0%|          | 0/4882 [00:00<?, ? examples/s]

Map:   0%|          | 0/4882 [00:00<?, ? examples/s]

/bask/projects/v/vjgo8416-rough-paths/envs/nlpsig-networks/lib/python3.8/site-packages/transformers/optimization.py:411: FutureWarning: This implementation of AdamW is deprecated and will be removed in a future version. Use the PyTorch implementation torch.optim.AdamW instead, or set `no_deprecation_warning=True` to disable this warning
  warnings.warn(


  0%|          | 0/976 [00:00<?, ?it/s]

Map:   0%|          | 0/4882 [00:00<?, ? examples/s]

Map:   0%|          | 0/4882 [00:00<?, ? examples/s]

/bask/projects/v/vjgo8416-rough-paths/envs/nlpsig-networks/lib/python3.8/site-packages/transformers/optimization.py:411: FutureWarning: This implementation of AdamW is deprecated and will be removed in a future version. Use the PyTorch implementation torch.optim.AdamW instead, or set `no_deprecation_warning=True` to disable this warning
  warnings.warn(


  0%|          | 0/977 [00:00<?, ?it/s]

Map:   0%|          | 0/4882 [00:00<?, ? examples/s]

Map:   0%|          | 0/4882 [00:00<?, ? examples/s]

/bask/projects/v/vjgo8416-rough-paths/envs/nlpsig-networks/lib/python3.8/site-packages/transformers/optimization.py:411: FutureWarning: This implementation of AdamW is deprecated and will be removed in a future version. Use the PyTorch implementation torch.optim.AdamW instead, or set `no_deprecation_warning=True` to disable this warning
  warnings.warn(


  0%|          | 0/977 [00:00<?, ?it/s]

Map:   0%|          | 0/4882 [00:00<?, ? examples/s]

Map:   0%|          | 0/4882 [00:00<?, ? examples/s]

/bask/projects/v/vjgo8416-rough-paths/envs/nlpsig-networks/lib/python3.8/site-packages/transformers/optimization.py:411: FutureWarning: This implementation of AdamW is deprecated and will be removed in a future version. Use the PyTorch implementation torch.optim.AdamW instead, or set `no_deprecation_warning=True` to disable this warning
  warnings.warn(


  0%|          | 0/976 [00:00<?, ?it/s]

Map:   0%|          | 0/4882 [00:00<?, ? examples/s]

Map:   0%|          | 0/4882 [00:00<?, ? examples/s]

/bask/projects/v/vjgo8416-rough-paths/envs/nlpsig-networks/lib/python3.8/site-packages/transformers/optimization.py:411: FutureWarning: This implementation of AdamW is deprecated and will be removed in a future version. Use the PyTorch implementation torch.optim.AdamW instead, or set `no_deprecation_warning=True` to disable this warning
  warnings.warn(


  0%|          | 0/976 [00:00<?, ?it/s]

Map:   0%|          | 0/4882 [00:00<?, ? examples/s]

Map:   0%|          | 0/4882 [00:00<?, ? examples/s]

/bask/projects/v/vjgo8416-rough-paths/envs/nlpsig-networks/lib/python3.8/site-packages/transformers/optimization.py:411: FutureWarning: This implementation of AdamW is deprecated and will be removed in a future version. Use the PyTorch implementation torch.optim.AdamW instead, or set `no_deprecation_warning=True` to disable this warning
  warnings.warn(


  0%|          | 0/976 [00:00<?, ?it/s]

saving the results dataframe to CSV in therapist_talk_type_output/bert_classifier.csv


In [12]:
bert_classifier["f1"].mean()

0.7662553535255058

In [13]:
bert_classifier["precision"].mean()

0.7647903751315419

In [14]:
bert_classifier["recall"].mean()

0.770116666013689

In [15]:
np.stack(bert_classifier["f1_scores"]).mean(axis=0)

array([0.84674532, 0.60189101, 0.73780547, 0.87857961])

In [16]:
np.stack(bert_classifier["precision_scores"]).mean(axis=0)

array([0.81775941, 0.5757255 , 0.75650451, 0.90917208])

In [17]:
np.stack(bert_classifier["recall_scores"]).mean(axis=0)

array([0.87797186, 0.63163482, 0.72055427, 0.85030571])

## Using Cross-Entropy loss

In [18]:
loss = "cross_entropy"
gamma = None

In [19]:
bert_classifier_ce = fine_tune_transformer_average_seed(
    num_epochs=num_epochs,
    pretrained_model_name="bert-base-uncased",
    df=anno_mi,
    feature_name="utterance_text",
    label_column="main_therapist_behaviour",
    seeds=seeds,
    loss=loss,
    gamma=gamma,
    path_indices=therapist_index,
    k_fold=True,
    validation_metric=validation_metric,
    results_output=f"{output_dir}/bert_classifier_ce.csv",
    device=device,
    verbose=False,
)

Map:   0%|          | 0/4882 [00:00<?, ? examples/s]

Map:   0%|          | 0/4882 [00:00<?, ? examples/s]

/bask/projects/v/vjgo8416-rough-paths/envs/nlpsig-networks/lib/python3.8/site-packages/transformers/optimization.py:411: FutureWarning: This implementation of AdamW is deprecated and will be removed in a future version. Use the PyTorch implementation torch.optim.AdamW instead, or set `no_deprecation_warning=True` to disable this warning
  warnings.warn(


  0%|          | 0/977 [00:00<?, ?it/s]

Map:   0%|          | 0/4882 [00:00<?, ? examples/s]

Map:   0%|          | 0/4882 [00:00<?, ? examples/s]

/bask/projects/v/vjgo8416-rough-paths/envs/nlpsig-networks/lib/python3.8/site-packages/transformers/optimization.py:411: FutureWarning: This implementation of AdamW is deprecated and will be removed in a future version. Use the PyTorch implementation torch.optim.AdamW instead, or set `no_deprecation_warning=True` to disable this warning
  warnings.warn(


  0%|          | 0/977 [00:00<?, ?it/s]

Map:   0%|          | 0/4882 [00:00<?, ? examples/s]

Map:   0%|          | 0/4882 [00:00<?, ? examples/s]

/bask/projects/v/vjgo8416-rough-paths/envs/nlpsig-networks/lib/python3.8/site-packages/transformers/optimization.py:411: FutureWarning: This implementation of AdamW is deprecated and will be removed in a future version. Use the PyTorch implementation torch.optim.AdamW instead, or set `no_deprecation_warning=True` to disable this warning
  warnings.warn(


  0%|          | 0/976 [00:00<?, ?it/s]

Map:   0%|          | 0/4882 [00:00<?, ? examples/s]

Map:   0%|          | 0/4882 [00:00<?, ? examples/s]

/bask/projects/v/vjgo8416-rough-paths/envs/nlpsig-networks/lib/python3.8/site-packages/transformers/optimization.py:411: FutureWarning: This implementation of AdamW is deprecated and will be removed in a future version. Use the PyTorch implementation torch.optim.AdamW instead, or set `no_deprecation_warning=True` to disable this warning
  warnings.warn(


  0%|          | 0/976 [00:00<?, ?it/s]

Map:   0%|          | 0/4882 [00:00<?, ? examples/s]

Map:   0%|          | 0/4882 [00:00<?, ? examples/s]

/bask/projects/v/vjgo8416-rough-paths/envs/nlpsig-networks/lib/python3.8/site-packages/transformers/optimization.py:411: FutureWarning: This implementation of AdamW is deprecated and will be removed in a future version. Use the PyTorch implementation torch.optim.AdamW instead, or set `no_deprecation_warning=True` to disable this warning
  warnings.warn(


  0%|          | 0/976 [00:00<?, ?it/s]

Map:   0%|          | 0/4882 [00:00<?, ? examples/s]

Map:   0%|          | 0/4882 [00:00<?, ? examples/s]

/bask/projects/v/vjgo8416-rough-paths/envs/nlpsig-networks/lib/python3.8/site-packages/transformers/optimization.py:411: FutureWarning: This implementation of AdamW is deprecated and will be removed in a future version. Use the PyTorch implementation torch.optim.AdamW instead, or set `no_deprecation_warning=True` to disable this warning
  warnings.warn(


  0%|          | 0/977 [00:00<?, ?it/s]

Map:   0%|          | 0/4882 [00:00<?, ? examples/s]

Map:   0%|          | 0/4882 [00:00<?, ? examples/s]

/bask/projects/v/vjgo8416-rough-paths/envs/nlpsig-networks/lib/python3.8/site-packages/transformers/optimization.py:411: FutureWarning: This implementation of AdamW is deprecated and will be removed in a future version. Use the PyTorch implementation torch.optim.AdamW instead, or set `no_deprecation_warning=True` to disable this warning
  warnings.warn(


  0%|          | 0/977 [00:00<?, ?it/s]

Map:   0%|          | 0/4882 [00:00<?, ? examples/s]

Map:   0%|          | 0/4882 [00:00<?, ? examples/s]

/bask/projects/v/vjgo8416-rough-paths/envs/nlpsig-networks/lib/python3.8/site-packages/transformers/optimization.py:411: FutureWarning: This implementation of AdamW is deprecated and will be removed in a future version. Use the PyTorch implementation torch.optim.AdamW instead, or set `no_deprecation_warning=True` to disable this warning
  warnings.warn(


  0%|          | 0/976 [00:00<?, ?it/s]

Map:   0%|          | 0/4882 [00:00<?, ? examples/s]

Map:   0%|          | 0/4882 [00:00<?, ? examples/s]

/bask/projects/v/vjgo8416-rough-paths/envs/nlpsig-networks/lib/python3.8/site-packages/transformers/optimization.py:411: FutureWarning: This implementation of AdamW is deprecated and will be removed in a future version. Use the PyTorch implementation torch.optim.AdamW instead, or set `no_deprecation_warning=True` to disable this warning
  warnings.warn(


  0%|          | 0/976 [00:00<?, ?it/s]

Map:   0%|          | 0/4882 [00:00<?, ? examples/s]

Map:   0%|          | 0/4882 [00:00<?, ? examples/s]

/bask/projects/v/vjgo8416-rough-paths/envs/nlpsig-networks/lib/python3.8/site-packages/transformers/optimization.py:411: FutureWarning: This implementation of AdamW is deprecated and will be removed in a future version. Use the PyTorch implementation torch.optim.AdamW instead, or set `no_deprecation_warning=True` to disable this warning
  warnings.warn(


  0%|          | 0/976 [00:00<?, ?it/s]

Map:   0%|          | 0/4882 [00:00<?, ? examples/s]

Map:   0%|          | 0/4882 [00:00<?, ? examples/s]

/bask/projects/v/vjgo8416-rough-paths/envs/nlpsig-networks/lib/python3.8/site-packages/transformers/optimization.py:411: FutureWarning: This implementation of AdamW is deprecated and will be removed in a future version. Use the PyTorch implementation torch.optim.AdamW instead, or set `no_deprecation_warning=True` to disable this warning
  warnings.warn(


  0%|          | 0/977 [00:00<?, ?it/s]

Map:   0%|          | 0/4882 [00:00<?, ? examples/s]

Map:   0%|          | 0/4882 [00:00<?, ? examples/s]

/bask/projects/v/vjgo8416-rough-paths/envs/nlpsig-networks/lib/python3.8/site-packages/transformers/optimization.py:411: FutureWarning: This implementation of AdamW is deprecated and will be removed in a future version. Use the PyTorch implementation torch.optim.AdamW instead, or set `no_deprecation_warning=True` to disable this warning
  warnings.warn(


  0%|          | 0/977 [00:00<?, ?it/s]

Map:   0%|          | 0/4882 [00:00<?, ? examples/s]

Map:   0%|          | 0/4882 [00:00<?, ? examples/s]

/bask/projects/v/vjgo8416-rough-paths/envs/nlpsig-networks/lib/python3.8/site-packages/transformers/optimization.py:411: FutureWarning: This implementation of AdamW is deprecated and will be removed in a future version. Use the PyTorch implementation torch.optim.AdamW instead, or set `no_deprecation_warning=True` to disable this warning
  warnings.warn(


  0%|          | 0/976 [00:00<?, ?it/s]

Map:   0%|          | 0/4882 [00:00<?, ? examples/s]

Map:   0%|          | 0/4882 [00:00<?, ? examples/s]

/bask/projects/v/vjgo8416-rough-paths/envs/nlpsig-networks/lib/python3.8/site-packages/transformers/optimization.py:411: FutureWarning: This implementation of AdamW is deprecated and will be removed in a future version. Use the PyTorch implementation torch.optim.AdamW instead, or set `no_deprecation_warning=True` to disable this warning
  warnings.warn(


  0%|          | 0/976 [00:00<?, ?it/s]

Map:   0%|          | 0/4882 [00:00<?, ? examples/s]

Map:   0%|          | 0/4882 [00:00<?, ? examples/s]

/bask/projects/v/vjgo8416-rough-paths/envs/nlpsig-networks/lib/python3.8/site-packages/transformers/optimization.py:411: FutureWarning: This implementation of AdamW is deprecated and will be removed in a future version. Use the PyTorch implementation torch.optim.AdamW instead, or set `no_deprecation_warning=True` to disable this warning
  warnings.warn(


  0%|          | 0/976 [00:00<?, ?it/s]

saving the results dataframe to CSV in therapist_talk_type_output/bert_classifier_ce.csv


In [20]:
bert_classifier_ce

accuracy        f1                                          f1_scores  \
0  0.806432  0.777498  [0.852482269503546, 0.6143896523848019, 0.7585...   
0  0.802335  0.766754  [0.8471337579617835, 0.5731497418244407, 0.760...   
0  0.799672  0.764325  [0.8514851485148515, 0.5827702702702703, 0.744...   

   precision                                   precision_scores    recall  \
0   0.779359  [0.8312586445366529, 0.6239737274220033, 0.735...  0.777315   
0   0.773974  [0.8243801652892562, 0.6235955056179775, 0.722...  0.763614   
0   0.769375  [0.8019292604501608, 0.6205035971223022, 0.761...  0.762299   

                                       recall_scores  seed           loss  \
0  [0.8748180494905385, 0.6050955414012739, 0.783...     1  cross_entropy   
0  [0.87117903930131, 0.5302547770700637, 0.80292...    12  cross_entropy   
0  [0.9075691411935953, 0.5493630573248408, 0.728...   123  cross_entropy   

  gamma  k_fold  
0  None    True  
0  None    True  
0  None    True

In [21]:
bert_classifier_ce["f1"].mean()

0.7695258089451796

In [22]:
bert_classifier_ce["precision"].mean()

0.7742359595241934

In [23]:
bert_classifier_ce["recall"].mean()

0.7677424570460639

In [24]:
np.stack(bert_classifier_ce["f1_scores"]).mean(axis=0)

array([0.85036706, 0.59010322, 0.75454642, 0.88308653])

In [25]:
np.stack(bert_classifier_ce["precision_scores"]).mean(axis=0)

array([0.81918936, 0.62269094, 0.73966398, 0.91539956])

In [26]:
np.stack(bert_classifier_ce["recall_scores"]).mean(axis=0)

array([0.88452208, 0.56157113, 0.77161919, 0.85325743])