In [1]:
import pickle
import numpy as np
import pandas as pd
import re

seed = 2023

In [3]:
import os
os.chdir("../../")

In [2]:
from nlpsig_networks.scripts.lstm_baseline_functions import (
    lstm_hyperparameter_search,
    obtain_path
)

In [4]:
%run notebooks/Rumours/load_rumours.py

In [5]:
df_rumours.head()

id label            datetime  \
0  5.249902e+17     0 2014-10-22 18:26:23   
1  5.249906e+17     0 2014-10-22 18:27:58   
2  5.249908e+17     1 2014-10-22 18:28:46   
3  5.249927e+17     1 2014-10-22 18:36:29   
4  5.250038e+17     1 2014-10-22 19:20:41   

                                                text timeline_id  
0  Police have clarified that there were two shoo...           0  
1  @CTVNews you guys "confirmed" there were 3 sho...           0  
2      @CTVNews get it right. http://t.co/GHYxMuzPG9           0  
3  RT @CTVNews Police have clarified that there w...           0  
4  @CTVNews @ctvsaskatoon so what happened at Rid...           0

In [6]:
sbert_embeddings = torch.rand((5568, 384))

In [7]:
import nlpsig
test = nlpsig.PrepareData(original_df=df_rumours, 
                          id_column="timeline_id",
                          label_column="label",
                          embeddings=sbert_embeddings)

[INFO] Concatenating the embeddings to the dataframe...
[INFO] - columns beginning with 'e' denote the full embddings.
[INFO] Adding time feature columns into dataframe in `.df`.
[INFO] Adding 'time_encoding' and feature...
[INFO] Adding 'time_diff' and feature...
[INFO] Adding 'timeline_index' feature...


In [8]:
path = test.pad(pad_by="history",
                embeddings="full",
                include_current_embedding=True,
                k=20,
                method="k_last")

[INFO] Padding ids and storing in `.df_padded` and `.array_padded` attributes.


  0%|          | 0/5568 [00:00<?, ?it/s]

In [9]:
df_rumours[df_rumours["timeline_id"]=='0']

id label            datetime  \
0     5.249902e+17     0 2014-10-22 18:26:23   
1     5.249906e+17     0 2014-10-22 18:27:58   
2     5.249908e+17     1 2014-10-22 18:28:46   
3     5.249927e+17     1 2014-10-22 18:36:29   
4     5.250038e+17     1 2014-10-22 19:20:41   
4238  5.803718e+17     0 2015-03-24 14:13:25   
4239  5.803726e+17     0 2015-03-24 14:16:23   
4240  5.803751e+17     0 2015-03-24 14:26:20   
4519  5.527889e+17     0 2015-01-07 11:28:49   
4520  5.527891e+17     0 2015-01-07 11:29:22   
4521  5.527891e+17     0 2015-01-07 11:29:37   
4522  5.527897e+17     0 2015-01-07 11:31:54   
4523  5.527901e+17     0 2015-01-07 11:33:15   
4524  5.527904e+17     0 2015-01-07 11:34:33   
4525  5.527904e+17     0 2015-01-07 11:34:47   
4526  5.527920e+17     0 2015-01-07 11:40:59   
4527  5.527929e+17     0 2015-01-07 11:44:37   
4528  5.527932e+17     0 2015-01-07 11:45:36   
4529  5.527938e+17     0 2015-01-07 11:48:16   
4530  5.527942e+17     0 2015-01-07 11:49:47   
4531  5.527943e+17     0 2015-01-07 11:50:08   
4532  5.527946e+17     0 2015-01-07 11:51:16   
4533  5.527949e+17     0 2015-01-07 11:52:24   
4534  5.527955e+17     0 2015-01-07 11:54:51   
4535  5.527957e+17     0 2015-01-07 11:55:29   
4536  5.527959e+17     0 2015-01-07 11:56:15   
4537  5.527960e+17     0 2015-01-07 11:56:44   
4538  5.527964e+17     0 2015-01-07 11:58:32   
4539  5.527967e+17     0 2015-01-07 11:59:36   
4540  5.527971e+17     0 2015-01-07 12:01:13   
4541  5.527978e+17     0 2015-01-07 12:04:05   
4542  5.527988e+17     0 2015-01-07 12:08:02   
4543  5.528012e+17     0 2015-01-07 12:17:22   
4544  5.528022e+17     0 2015-01-07 12:21:21   
4545  5.528029e+17     0 2015-01-07 12:24:05   
4546  5.528456e+17     0 2015-01-07 15:13:58   

                                                   text timeline_id  
0     Police have clarified that there were two shoo...           0  
1     @CTVNews you guys "confirmed" there were 3 sho...           0  
2         @CTVNews get it right. http://t.co/GHYxMuzPG9           0  
3     RT @CTVNews Police have clarified that there w...           0  
4     @CTVNews @ctvsaskatoon so what happened at Rid...           0  
4238  #4U9525 took eight minutes to descend from 38,...           0  
4239  @thatjohn @AirlineReporter at what point durin...           0  
4240  @thatjohn @AirlineReporter Just over 4500 fpm ...           0  
4519  Appalled by the attack on Charlie Hebdo in Par...           0  
4520  @tnewtondunn You guys should put one of their ...           0  
4521  @tnewtondunn Important moment. Other papers co...           0  
4522  @mjhsinclair @tnewtondunn Sadly, since none of...           0  
4523  @tnewtondunn solidarity is key - we can't be m...           0  
4524                @tnewtondunn @theuneasyreaper rip x           0  
4525    @tnewtondunn @theuneasyreaper poor people :((((           0  
4526  @tnewtondunn @mehdirhasan  attacking religion ...           0  
4527  @tnewtondunn @toadmeister \nWhen will EU wake up?           0  
4528                      @tnewtondunn #i'llridewithyou           0  
4529  @tnewtondunn Freedom of speech is something to...           0  
4530  @mjhsinclair @Olenkafrenkiel @tnewtondunn No.....           0  
4531  @m33ryg @tnewtondunn @mehdirhasan Of course it...           0  
4532  @Mumbobee @tnewtondunn @mehdirhasan  if free s...           0  
4533  @m33ryg @tnewtondunn @mehdirhasan You think pe...           0  
4534  @UnbiasedF @tnewtondunn @mehdirhasan of course...           0  
4535  @m33ryg @Mumbobee @tnewtondunn @mehdirhasan Yo...           0  
4536  @m33ryg @tnewtondunn @mehdirhasan "Facts about...           0  
4537  @katherine1924 @Mumbobee @tnewtondunn @mehdirh...           0  
4538  @m33ryg @tnewtondunn @mehdirhasan Can you supp...           0  
4539  @m33ryg @Mumbobee @tnewtondunn @mehdirhasan Th...           0  
4540  @katherine1924 @Mumbobee @tnewtondunn @mehdirh...           0  
4541  @UnbiasedF If you go into such facts it will b...           0  

In [10]:
test.df[test.df["timeline_id"]=='0']

id label            datetime  \
0   5.249902e+17     0 2014-10-22 18:26:23   
1   5.249906e+17     0 2014-10-22 18:27:58   
2   5.249908e+17     1 2014-10-22 18:28:46   
3   5.249927e+17     1 2014-10-22 18:36:29   
4   5.250038e+17     1 2014-10-22 19:20:41   
5   5.527889e+17     0 2015-01-07 11:28:49   
6   5.527891e+17     0 2015-01-07 11:29:22   
7   5.527891e+17     0 2015-01-07 11:29:37   
8   5.527897e+17     0 2015-01-07 11:31:54   
9   5.527901e+17     0 2015-01-07 11:33:15   
10  5.527904e+17     0 2015-01-07 11:34:33   
11  5.527904e+17     0 2015-01-07 11:34:47   
12  5.527920e+17     0 2015-01-07 11:40:59   
13  5.527929e+17     0 2015-01-07 11:44:37   
14  5.527932e+17     0 2015-01-07 11:45:36   
15  5.527938e+17     0 2015-01-07 11:48:16   
16  5.527942e+17     0 2015-01-07 11:49:47   
17  5.527943e+17     0 2015-01-07 11:50:08   
18  5.527946e+17     0 2015-01-07 11:51:16   
19  5.527949e+17     0 2015-01-07 11:52:24   
20  5.527955e+17     0 2015-01-07 11:54:51   
21  5.527957e+17     0 2015-01-07 11:55:29   
22  5.527959e+17     0 2015-01-07 11:56:15   
23  5.527960e+17     0 2015-01-07 11:56:44   
24  5.527964e+17     0 2015-01-07 11:58:32   
25  5.527967e+17     0 2015-01-07 11:59:36   
26  5.527971e+17     0 2015-01-07 12:01:13   
27  5.527978e+17     0 2015-01-07 12:04:05   
28  5.527988e+17     0 2015-01-07 12:08:02   
29  5.528012e+17     0 2015-01-07 12:17:22   
30  5.528022e+17     0 2015-01-07 12:21:21   
31  5.528029e+17     0 2015-01-07 12:24:05   
32  5.528456e+17     0 2015-01-07 15:13:58   
33  5.803718e+17     0 2015-03-24 14:13:25   
34  5.803726e+17     0 2015-03-24 14:16:23   
35  5.803751e+17     0 2015-03-24 14:26:20   

                                                 text timeline_id        e1  \
0   Police have clarified that there were two shoo...           0  0.760631   
1   @CTVNews you guys "confirmed" there were 3 sho...           0  0.087256   
2       @CTVNews get it right. http://t.co/GHYxMuzPG9           0  0.646033   
3   RT @CTVNews Police have clarified that there w...           0  0.506428   
4   @CTVNews @ctvsaskatoon so what happened at Rid...           0  0.900769   
5   Appalled by the attack on Charlie Hebdo in Par...           0  0.714292   
6   @tnewtondunn You guys should put one of their ...           0  0.430656   
7   @tnewtondunn Important moment. Other papers co...           0  0.499742   
8   @mjhsinclair @tnewtondunn Sadly, since none of...           0  0.077021   
9   @tnewtondunn solidarity is key - we can't be m...           0  0.241009   
10                @tnewtondunn @theuneasyreaper rip x           0  0.562280   
11    @tnewtondunn @theuneasyreaper poor people :((((           0  0.914830   
12  @tnewtondunn @mehdirhasan  attacking religion ...           0  0.637434   
13  @tnewtondunn @toadmeister \nWhen will EU wake up?           0  0.113659   
14                      @tnewtondunn #i'llridewithyou           0  0.102973   
15  @tnewtondunn Freedom of speech is something to...           0  0.367583   
16  @mjhsinclair @Olenkafrenkiel @tnewtondunn No.....           0  0.100173   
17  @m33ryg @tnewtondunn @mehdirhasan Of course it...           0  0.437179   
18  @Mumbobee @tnewtondunn @mehdirhasan  if free s...           0  0.832122   
19  @m33ryg @tnewtondunn @mehdirhasan You think pe...           0  0.887987   
20  @UnbiasedF @tnewtondunn @mehdirhasan of course...           0  0.656500   
21  @m33ryg @Mumbobee @tnewtondunn @mehdirhasan Yo...           0  0.195808   
22  @m33ryg @tnewtondunn @mehdirhasan "Facts about...           0  0.947593   
23  @katherine1924 @Mumbobee @tnewtondunn @mehdirh...           0  0.496822   
24  @m33ryg @tnewtondunn @mehdirhasan Can you supp...           0  0.484736   
25  @m33ryg @Mumbobee @tnewtondunn @mehdirhasan Th...           0  0.244681   
26  @katherine1924 @Mumbobee @tnewtondunn @mehdirh...           0  0.769417   
27  @UnbiasedF If you go into such facts it will b...           0  0.127574   
28  @Cavelloman1 @mj

In [15]:
path = path[:,:,:-2].astype("float")

In [16]:
path.shape

(5568, 20, 384)

In [21]:
path[36]

array([[0.09438896, 0.40236121, 0.0424611 , ..., 0.75273949, 0.33756298,
        0.37205309],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       ...,
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ]])

In [22]:
path[5,:,:6]

array([[0.76063091, 0.12631279, 0.26886719, 0.49926507, 0.94463491,
        0.63244152],
       [0.08725637, 0.46627671, 0.82576293, 0.41641968, 0.97817028,
        0.13840127],
       [0.64603299, 0.82171351, 0.1348384 , 0.05898112, 0.61936516,
        0.15020376],
       [0.50642848, 0.23047441, 0.006522  , 0.94399917, 0.31512761,
        0.20460558],
       [0.90076858, 0.30738407, 0.29393059, 0.67265528, 0.21803653,
        0.95985603],
       [0.71429211, 0.5487048 , 0.39909637, 0.46831083, 0.92386812,
        0.70548308],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        ],
       [0.        , 0

## Using obtain_path

In [18]:
x_data = obtain_path(
    df=df_rumours, 
    id_column="timeline_id",
    label_column="label",
    embeddings=sbert_embeddings,
    k=20
)

x_data.shape

[INFO] Concatenating the embeddings to the dataframe...
[INFO] - columns beginning with 'e' denote the full embddings.
[INFO] Adding time feature columns into dataframe in `.df`.
[INFO] Adding 'time_encoding' and feature...
[INFO] Adding 'time_diff' and feature...
[INFO] Adding 'timeline_index' feature...
[INFO] Padding ids and storing in `.df_padded` and `.array_padded` attributes.


  0%|          | 0/5568 [00:00<?, ?it/s]

(5568, 20, 384)

In [23]:
x_data[36]

array([[0.09438896, 0.40236121, 0.0424611 , ..., 0.75273949, 0.33756298,
        0.37205309],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       ...,
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ]])

In [19]:
x_data[5,:,:6]

array([[0.76063091, 0.12631279, 0.26886719, 0.49926507, 0.94463491,
        0.63244152],
       [0.08725637, 0.46627671, 0.82576293, 0.41641968, 0.97817028,
        0.13840127],
       [0.64603299, 0.82171351, 0.1348384 , 0.05898112, 0.61936516,
        0.15020376],
       [0.50642848, 0.23047441, 0.006522  , 0.94399917, 0.31512761,
        0.20460558],
       [0.90076858, 0.30738407, 0.29393059, 0.67265528, 0.21803653,
        0.95985603],
       [0.71429211, 0.5487048 , 0.39909637, 0.46831083, 0.92386812,
        0.70548308],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        ],
       [0.        , 0