In [1]:
import pickle
import numpy as np
import pandas as pd
import os
from tqdm.notebook import tqdm
import re

seed = 2023

In [2]:
import torch

# set device
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
device

device(type='cuda')

In [3]:
from nlpsig_networks.scripts.swnu_network_functions import (
    swnu_network_hyperparameter_search,
    obtain_SWNUNetwork_input,
)

In [4]:
output_dir = "rumours_output"
if not os.path.isdir(output_dir):
    os.makedirs(output_dir)

## Rumours

In [5]:
%run load_sbert-embeddings.py

In [6]:
df_rumours.head()

id label            datetime  \
0  5.249902e+17     0 2014-10-22 18:26:23   
1  5.249906e+17     0 2014-10-22 18:27:58   
2  5.249908e+17     1 2014-10-22 18:28:46   
3  5.249927e+17     1 2014-10-22 18:36:29   
4  5.250038e+17     1 2014-10-22 19:20:41   

                                                text timeline_id    set  
0  Police have clarified that there were two shoo...           0  train  
1  @CTVNews you guys "confirmed" there were 3 sho...           0  train  
2      @CTVNews get it right. http://t.co/GHYxMuzPG9           0  train  
3  RT @CTVNews Police have clarified that there w...           0  train  
4  @CTVNews @ctvsaskatoon so what happened at Rid...           0  train

## SWNU Network

In [7]:
features = ["time_encoding", "timeline_index"]
standardise_method = ["z_score", None]
include_features_in_path = True
include_features_in_input = True

In [8]:
num_epochs = 100
dimensions = [15]
swnu_hidden_dim_sizes_and_sig_depths = [([12], 3), ([10], 3)]
ffn_hidden_dim_sizes = [[32,32], [128,128], [512,512]]
dropout_rates = [0.1]
learning_rates = [5e-4, 3e-4, 1e-4]
seeds = [1, 12, 123]
loss = "focal"
gamma = 2
validation_metric = "f1"
patience = 3

In [9]:
kwargs = {
    "num_epochs": num_epochs,
    "df": df_rumours,
    "id_column": "timeline_id",
    "label_column": "label",
    "embeddings": sbert_embeddings,
    "y_data": y_data,
    "output_dim": output_dim,
    "dimensions": dimensions,
    "log_signature": True,
    "pooling": "signature",
    "swnu_hidden_dim_sizes_and_sig_depths": swnu_hidden_dim_sizes_and_sig_depths,
    "ffn_hidden_dim_sizes": ffn_hidden_dim_sizes,
    "dropout_rates": dropout_rates,
    "learning_rates": learning_rates,
    "BiLSTM": True,
    "seeds": seeds,
    "loss": loss,
    "gamma": gamma,
    "device": device,
    "features": features,
    "standardise_method": standardise_method,
    "include_features_in_path": include_features_in_path,
    "include_features_in_input": include_features_in_input,
    "split_ids": split_ids,
    "k_fold": True,
    "patience": patience,
    "validation_metric": validation_metric,
    "verbose": False,
}

# w=5

In [10]:
size = 5

## umap

In [11]:
(
    swnu_network_umap_kfold_5,
    best_swnu_network_umap_kfold_5,
    _,
    __,
) = swnu_network_hyperparameter_search(
    history_lengths=[size],
    dim_reduce_methods=["umap"],
    results_output=f"{output_dir}/swnu_network_umap_focal_{gamma}_{size}_kfold.csv",
    **kwargs,
)

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]


##################################################
dimension: 15 | method: umap
[INFO] Concatenating the embeddings to the dataframe...
[INFO] - columns beginning with 'e' denote the full embddings.
[INFO] - columns beginning with 'd' denote the dimension reduced embeddings.
[INFO] Adding time feature columns into dataframe in `.df`.
[INFO] Adding 'time_encoding' feature...
[INFO] Adding 'time_diff' feature...
[INFO] Adding 'timeline_index' feature...
[INFO] Padding ids and storing in `.df_padded` and `.array_padded` attributes.


  0%|          | 0/5568 [00:00<?, ?it/s]

[INFO] The path was created for each item in the dataframe, by looking at its history, so to include embeddings in the FFN input, we concatenate the embeddings for each sentence / text.


  0%|          | 0/2 [00:00<?, ?it/s]

  0%|          | 0/3 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/3 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/3 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/3 [00:00<?, ?it/s]

  0%|          | 0/3 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/3 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/3 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/3 [00:00<?, ?it/s]

[INFO] Concatenating the embeddings to the dataframe...
[INFO] - columns beginning with 'e' denote the full embddings.
[INFO] - columns beginning with 'd' denote the dimension reduced embeddings.
[INFO] Adding time feature columns into dataframe in `.df`.
[INFO] Adding 'time_encoding' feature...
[INFO] Adding 'time_diff' feature...
[INFO] Adding 'timeline_index' feature...
[INFO] Padding ids and storing in `.df_padded` and `.array_padded` attributes.


  0%|          | 0/5568 [00:00<?, ?it/s]

[INFO] The path was created for each item in the dataframe, by looking at its history, so to include embeddings in the FFN input, we concatenate the embeddings for each sentence / text.
saving results dataframe to CSV for this hyperparameter search in rumours_output/swnu_network_umap_focal_2_5_kfold.csv
saving the best model results dataframe to CSV for this hyperparameter search in rumours_output/swnu_network_umap_focal_2_5_kfold_best_model.csv


In [12]:
swnu_network_umap_kfold_5.groupby(
    ["dimensions", "swnu_hidden_dim", "ffn_hidden_dim", "dropout_rate", "learning_rate"]
).mean()

/tmp/ipykernel_2296062/1104105075.py:1: FutureWarning: The default value of numeric_only in DataFrameGroupBy.mean is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  swnu_network_umap_kfold_5.groupby(


accuracy  \
dimensions swnu_hidden_dim ffn_hidden_dim dropout_rate learning_rate             
15         (10,)           (32, 32)       0.1          0.0001         0.695993   
                                                       0.0003         0.693569   
                                                       0.0005         0.688785   
                           (128, 128)     0.1          0.0001         0.689779   
                                                       0.0003         0.685741   
                                                       0.0005         0.690401   
                           (512, 512)     0.1          0.0001         0.695806   
                                                       0.0003         0.695868   
                                                       0.0005         0.695868   
           (12,)           (32, 32)       0.1          0.0001         0.695371   
                                                       0.0003         0.689593   
                                                       0.0005         0.690339   
                           (128, 128)     0.1          0.0001         0.695558   
                                                       0.0003         0.686673   
                                                       0.0005         0.695620   
                           (512, 512)     0.1          0.0001         0.689904   
                                                       0.0003         0.693507   
                                                       0.0005         0.686362   

                                                                            f1  \
dimensions swnu_hidden_dim ffn_hidden_dim dropout_rate learning_rate             
15         (10,)           (32, 32)       0.1          0.0001         0.665693   
                                                       0.0003         0.664857   
                                                       0.0005         0.664661   
                           (128, 128)     0.1          0.0001         0.664521   
                                                       0.0003         0.665745   
                                                       0.0005         0.665239   
                           (512, 512)     0.1          0.0001         0.669261   
                                                       0.0003         0.670727   
                                                       0.0005         0.670215   
           (12,)           (32, 32)       0.1          0.0001         0.665128   
                                                       0.0003         0.662335   
                                                       0.0005         0.662134   
                           (128, 128)     0.1          0.0001         0.668163   
                                                       0.0003         0.665071   
                                                       0.0005         0.665048   
                           (512, 512)     0.1          0.0001         0.665188   
                                                       0.0003         0.665786   
                                                       0.0005         0.664142   

                                                                      precision  \
dimensions swnu_hidden_dim ffn_hidden_dim dropout_rate learning_rate              
15         (10,)           (32, 32)       0.1          0.0001          0.666005   
                                                       0.0003          0.664295   
                                                       0.0005          0.662588   
                           (128, 128)     0.1          0.0001          0.662508   
                                                       0.0003          0.663270   
                                                       0.0005          0.663548   
                           (512, 512)     0.1          0.0001          0.667747   
                                         

In [13]:
best_swnu_network_umap_kfold_5

loss  accuracy        f1                                 f1_scores  \
0  None  0.694129  0.667738  [0.7613785080703795, 0.5740981053724371]   
0  None  0.694129  0.664676  [0.7640546369518333, 0.5652980132450331]   
0  None  0.692265  0.664944  [0.7606205596636219, 0.5692668927732847]   

   precision                          precision_scores    recall  \
0   0.666108  [0.7724992623192682, 0.5597165991902834]  0.669906   
0   0.664270  [0.7663686184020767, 0.5621707060063225]  0.665107   
0   0.663602  [0.7694338515693752, 0.5577709611451943]  0.666627   

                              recall_scores valid_loss  valid_accuracy  ...  \
0  [0.7505733944954128, 0.5892381459776239]       None        0.730961  ...   
0  [0.7617545871559633, 0.5684603090037293]       None        0.737431  ...   
0   [0.752006880733945, 0.5812466702184337]       None        0.738509  ...   

   seed BiLSTM  loss_function gamma  k_fold n_splits  augmentation_type  \
0     1   True          focal     2    True        5             Conv1d   
0    12   True          focal     2    True        5             Conv1d   
0   123   True          focal     2    True        5             Conv1d   

   hidden_dim_aug    comb_method batch_size  
0            None  concatenation         64  
0            None  concatenation         64  
0            None  concatenation         64  

[3 rows x 44 columns]

In [14]:
best_swnu_network_umap_kfold_5["f1"].mean()

0.6657861193460982

In [15]:
best_swnu_network_umap_kfold_5["precision"].mean()

0.6646599997720867

In [16]:
best_swnu_network_umap_kfold_5["recall"].mean()

0.6672133312641847

In [17]:
np.stack(best_swnu_network_umap_kfold_5["f1_scores"]).mean(axis=0)

array([0.7620179 , 0.56955434])

In [18]:
np.stack(best_swnu_network_umap_kfold_5["precision_scores"]).mean(axis=0)

array([0.76943391, 0.55988609])

In [19]:
np.stack(best_swnu_network_umap_kfold_5["recall_scores"]).mean(axis=0)

array([0.75477829, 0.57964838])

# w=11

In [20]:
size = 11

## umap

In [21]:
(
    swnu_network_umap_kfold_11,
    best_swnu_network_umap_kfold_11,
    _,
    __,
) = swnu_network_hyperparameter_search(
    history_lengths=[size],
    dim_reduce_methods=["umap"],
    results_output=f"{output_dir}/swnu_network_umap_focal_{gamma}_{size}_kfold.csv",
    **kwargs,
)

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]


##################################################
dimension: 15 | method: umap
[INFO] Concatenating the embeddings to the dataframe...
[INFO] - columns beginning with 'e' denote the full embddings.
[INFO] - columns beginning with 'd' denote the dimension reduced embeddings.
[INFO] Adding time feature columns into dataframe in `.df`.
[INFO] Adding 'time_encoding' feature...
[INFO] Adding 'time_diff' feature...
[INFO] Adding 'timeline_index' feature...
[INFO] Padding ids and storing in `.df_padded` and `.array_padded` attributes.


  0%|          | 0/5568 [00:00<?, ?it/s]

[INFO] The path was created for each item in the dataframe, by looking at its history, so to include embeddings in the FFN input, we concatenate the embeddings for each sentence / text.


  0%|          | 0/2 [00:00<?, ?it/s]

  0%|          | 0/3 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/3 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/3 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/3 [00:00<?, ?it/s]

  0%|          | 0/3 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/3 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/3 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/3 [00:00<?, ?it/s]

[INFO] Concatenating the embeddings to the dataframe...
[INFO] - columns beginning with 'e' denote the full embddings.
[INFO] - columns beginning with 'd' denote the dimension reduced embeddings.
[INFO] Adding time feature columns into dataframe in `.df`.
[INFO] Adding 'time_encoding' feature...
[INFO] Adding 'time_diff' feature...
[INFO] Adding 'timeline_index' feature...
[INFO] Padding ids and storing in `.df_padded` and `.array_padded` attributes.


  0%|          | 0/5568 [00:00<?, ?it/s]

[INFO] The path was created for each item in the dataframe, by looking at its history, so to include embeddings in the FFN input, we concatenate the embeddings for each sentence / text.
saving results dataframe to CSV for this hyperparameter search in rumours_output/swnu_network_umap_focal_2_11_kfold.csv
saving the best model results dataframe to CSV for this hyperparameter search in rumours_output/swnu_network_umap_focal_2_11_kfold_best_model.csv


In [22]:
swnu_network_umap_kfold_11.groupby(
    ["dimensions", "swnu_hidden_dim", "ffn_hidden_dim", "dropout_rate", "learning_rate"]
).mean()

/tmp/ipykernel_2296062/2463364505.py:1: FutureWarning: The default value of numeric_only in DataFrameGroupBy.mean is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  swnu_network_umap_kfold_11.groupby(


accuracy  \
dimensions swnu_hidden_dim ffn_hidden_dim dropout_rate learning_rate             
15         (10,)           (32, 32)       0.1          0.0001         0.694626   
                                                       0.0003         0.690836   
                                                       0.0005         0.690090   
                           (128, 128)     0.1          0.0001         0.695247   
                                                       0.0003         0.692016   
                                                       0.0005         0.691208   
                           (512, 512)     0.1          0.0001         0.693942   
                                                       0.0003         0.700093   
                                                       0.0005         0.688413   
           (12,)           (32, 32)       0.1          0.0001         0.699845   
                                                       0.0003         0.694564   
                                                       0.0005         0.696303   
                           (128, 128)     0.1          0.0001         0.696987   
                                                       0.0003         0.698105   
                                                       0.0005         0.698291   
                           (512, 512)     0.1          0.0001         0.697297   
                                                       0.0003         0.701212   
                                                       0.0005         0.690463   

                                                                            f1  \
dimensions swnu_hidden_dim ffn_hidden_dim dropout_rate learning_rate             
15         (10,)           (32, 32)       0.1          0.0001         0.671392   
                                                       0.0003         0.670285   
                                                       0.0005         0.667941   
                           (128, 128)     0.1          0.0001         0.672524   
                                                       0.0003         0.671189   
                                                       0.0005         0.669131   
                           (512, 512)     0.1          0.0001         0.673833   
                                                       0.0003         0.677384   
                                                       0.0005         0.668002   
           (12,)           (32, 32)       0.1          0.0001         0.675856   
                                                       0.0003         0.671188   
                                                       0.0005         0.675129   
                           (128, 128)     0.1          0.0001         0.676062   
                                                       0.0003         0.676449   
                                                       0.0005         0.675017   
                           (512, 512)     0.1          0.0001         0.676418   
                                                       0.0003         0.675468   
                                                       0.0005         0.670286   

                                                                      precision  \
dimensions swnu_hidden_dim ffn_hidden_dim dropout_rate learning_rate              
15         (10,)           (32, 32)       0.1          0.0001          0.669043   
                                                       0.0003          0.667651   
                                                       0.0005          0.665372   
                           (128, 128)     0.1          0.0001          0.670132   
                                                       0.0003          0.668682   
                                                       0.0005          0.667737   
                           (512, 512)     0.1          0.0001          0.671177   
                                         

In [23]:
best_swnu_network_umap_kfold_11

loss  accuracy        f1                                 f1_scores  \
0  None  0.689469  0.665035  [0.7555033754035808, 0.5745658835546477]   
0  None  0.691706  0.669005  [0.7556868537666174, 0.5823232323232324]   
0  None  0.702516  0.679525    [0.76536312849162, 0.5936863543788188]   

   precision                          precision_scores    recall  \
0   0.662822  [0.7739025856885148, 0.5517410495340853]  0.668660   
0   0.666466  [0.7794028031687995, 0.5535285645703313]  0.673825   
0   0.676979   [0.7854556427278213, 0.568503169185763]  0.683738   

                              recall_scores valid_loss  valid_accuracy  ...  \
0  [0.7379587155963303, 0.5993606819392648]       None        0.749966  ...   
0  [0.7333715596330275, 0.6142781033564199]       None        0.761019  ...   
0  [0.7462729357798165, 0.6212040490143846]       None        0.748214  ...   

   seed BiLSTM  loss_function gamma  k_fold n_splits  augmentation_type  \
0     1   True          focal     2    True        5             Conv1d   
0    12   True          focal     2    True        5             Conv1d   
0   123   True          focal     2    True        5             Conv1d   

   hidden_dim_aug    comb_method batch_size  
0            None  concatenation         64  
0            None  concatenation         64  
0            None  concatenation         64  

[3 rows x 44 columns]

In [24]:
best_swnu_network_umap_kfold_11["f1"].mean()

0.6711881379864195

In [25]:
best_swnu_network_umap_kfold_11["precision"].mean()

0.6687556358125525

In [26]:
best_swnu_network_umap_kfold_11["recall"].mean()

0.6754076742198739

In [27]:
np.stack(best_swnu_network_umap_kfold_11["f1_scores"]).mean(axis=0)

array([0.75885112, 0.58352516])

In [28]:
np.stack(best_swnu_network_umap_kfold_11["precision_scores"]).mean(axis=0)

array([0.77958701, 0.55792426])

In [29]:
np.stack(best_swnu_network_umap_kfold_11["recall_scores"]).mean(axis=0)

array([0.73920107, 0.61161428])

# w=20

In [30]:
size = 20

## umap

In [31]:
(
    swnu_network_umap_kfold_20,
    best_swnu_network_umap_kfold_20,
    _,
    __,
) = swnu_network_hyperparameter_search(
    history_lengths=[size],
    dim_reduce_methods=["umap"],
    results_output=f"{output_dir}/swnu_network_umap_focal_{gamma}_{size}_kfold.csv",
    **kwargs,
)

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]


##################################################
dimension: 15 | method: umap
[INFO] Concatenating the embeddings to the dataframe...
[INFO] - columns beginning with 'e' denote the full embddings.
[INFO] - columns beginning with 'd' denote the dimension reduced embeddings.
[INFO] Adding time feature columns into dataframe in `.df`.
[INFO] Adding 'time_encoding' feature...
[INFO] Adding 'time_diff' feature...
[INFO] Adding 'timeline_index' feature...
[INFO] Padding ids and storing in `.df_padded` and `.array_padded` attributes.


  0%|          | 0/5568 [00:00<?, ?it/s]

[INFO] The path was created for each item in the dataframe, by looking at its history, so to include embeddings in the FFN input, we concatenate the embeddings for each sentence / text.


  0%|          | 0/2 [00:00<?, ?it/s]

  0%|          | 0/3 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/3 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/3 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/3 [00:00<?, ?it/s]

  0%|          | 0/3 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/3 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/3 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/3 [00:00<?, ?it/s]

[INFO] Concatenating the embeddings to the dataframe...
[INFO] - columns beginning with 'e' denote the full embddings.
[INFO] - columns beginning with 'd' denote the dimension reduced embeddings.
[INFO] Adding time feature columns into dataframe in `.df`.
[INFO] Adding 'time_encoding' feature...
[INFO] Adding 'time_diff' feature...
[INFO] Adding 'timeline_index' feature...
[INFO] Padding ids and storing in `.df_padded` and `.array_padded` attributes.


  0%|          | 0/5568 [00:00<?, ?it/s]

[INFO] The path was created for each item in the dataframe, by looking at its history, so to include embeddings in the FFN input, we concatenate the embeddings for each sentence / text.
saving results dataframe to CSV for this hyperparameter search in rumours_output/swnu_network_umap_focal_2_20_kfold.csv
saving the best model results dataframe to CSV for this hyperparameter search in rumours_output/swnu_network_umap_focal_2_20_kfold_best_model.csv


In [32]:
swnu_network_umap_kfold_20.groupby(
    ["dimensions", "swnu_hidden_dim", "ffn_hidden_dim", "dropout_rate", "learning_rate"]
).mean()

/tmp/ipykernel_2296062/29893126.py:1: FutureWarning: The default value of numeric_only in DataFrameGroupBy.mean is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  swnu_network_umap_kfold_20.groupby(


accuracy  \
dimensions swnu_hidden_dim ffn_hidden_dim dropout_rate learning_rate             
15         (10,)           (32, 32)       0.1          0.0001         0.685430   
                                                       0.0003         0.693756   
                                                       0.0005         0.689966   
                           (128, 128)     0.1          0.0001         0.693321   
                                                       0.0003         0.694688   
                                                       0.0005         0.693383   
                           (512, 512)     0.1          0.0001         0.689966   
                                                       0.0003         0.688661   
                                                       0.0005         0.689717   
           (12,)           (32, 32)       0.1          0.0001         0.683380   
                                                       0.0003         0.683628   
                                                       0.0005         0.682759   
                           (128, 128)     0.1          0.0001         0.689655   
                                                       0.0003         0.694377   
                                                       0.0005         0.688661   
                           (512, 512)     0.1          0.0001         0.690090   
                                                       0.0003         0.690401   
                                                       0.0005         0.692016   

                                                                            f1  \
dimensions swnu_hidden_dim ffn_hidden_dim dropout_rate learning_rate             
15         (10,)           (32, 32)       0.1          0.0001         0.669056   
                                                       0.0003         0.675167   
                                                       0.0005         0.671905   
                           (128, 128)     0.1          0.0001         0.675734   
                                                       0.0003         0.677597   
                                                       0.0005         0.676329   
                           (512, 512)     0.1          0.0001         0.673155   
                                                       0.0003         0.670589   
                                                       0.0005         0.671713   
           (12,)           (32, 32)       0.1          0.0001         0.665099   
                                                       0.0003         0.661770   
                                                       0.0005         0.664498   
                           (128, 128)     0.1          0.0001         0.672412   
                                                       0.0003         0.678492   
                                                       0.0005         0.669339   
                           (512, 512)     0.1          0.0001         0.673955   
                                                       0.0003         0.672435   
                                                       0.0005         0.673556   

                                                                      precision  \
dimensions swnu_hidden_dim ffn_hidden_dim dropout_rate learning_rate              
15         (10,)           (32, 32)       0.1          0.0001          0.667229   
                                                       0.0003          0.672952   
                                                       0.0005          0.669647   
                           (128, 128)     0.1          0.0001          0.673590   
                                                       0.0003          0.675277   
                                                       0.0005          0.673936   
                           (512, 512)     0.1          0.0001          0.671090   
                                         

In [33]:
best_swnu_network_umap_kfold_20

loss  accuracy        f1                                 f1_scores  \
0  None  0.676608  0.656369  [0.7397630118494075, 0.5729756337681516]   
0  None  0.688164  0.665587  [0.7524781772451546, 0.5786955426844623]   
0  None  0.686114  0.663353  [0.7508875739644971, 0.5758186397984887]   

   precision                          precision_scores    recall  \
0   0.654098  [0.7757156338471217, 0.5324794144556267]  0.663567   
0   0.663074  [0.7774380923265056, 0.5487106017191977]  0.670609   
0   0.660889  [0.7756723716381418, 0.5461060678451983]  0.668294   

                              recall_scores valid_loss  valid_accuracy  ...  \
0  [0.7069954128440367, 0.6201385189131593]       None        0.815204  ...   
0  [0.7290711009174312, 0.6121470431539691]       None        0.834075  ...   
0   [0.7276376146788991, 0.608950452850293]       None        0.798356  ...   

   seed BiLSTM  loss_function gamma  k_fold n_splits  augmentation_type  \
0     1   True          focal     2    True        5             Conv1d   
0    12   True          focal     2    True        5             Conv1d   
0   123   True          focal     2    True        5             Conv1d   

   hidden_dim_aug    comb_method batch_size  
0            None  concatenation         64  
0            None  concatenation         64  
0            None  concatenation         64  

[3 rows x 44 columns]

In [34]:
best_swnu_network_umap_kfold_20["f1"].mean()

0.6617697632183602

In [35]:
best_swnu_network_umap_kfold_20["precision"].mean()

0.6593536969719653

In [36]:
best_swnu_network_umap_kfold_20["recall"].mean()

0.6674900238929647

In [37]:
np.stack(best_swnu_network_umap_kfold_20["f1_scores"]).mean(axis=0)

array([0.74770959, 0.57582994])

In [38]:
np.stack(best_swnu_network_umap_kfold_20["precision_scores"]).mean(axis=0)

array([0.77627537, 0.54243203])

In [39]:
np.stack(best_swnu_network_umap_kfold_20["recall_scores"]).mean(axis=0)

array([0.72123471, 0.61374534])

# w=35

In [40]:
size = 35

## umap

In [ ]:
(
    swnu_network_umap_kfold_35,
    best_swnu_network_umap_kfold_35,
    _,
    __,
) = swnu_network_hyperparameter_search(
    history_lengths=[size],
    dim_reduce_methods=["umap"],
    results_output=f"{output_dir}/swnu_network_umap_focal_{gamma}_{size}_kfold.csv",
    **kwargs,
)

In [ ]:
swnu_network_umap_kfold_35.groupby(
    ["dimensions", "swnu_hidden_dim", "ffn_hidden_dim", "dropout_rate", "learning_rate"]
).mean()

In [ ]:
best_swnu_network_umap_kfold_35

In [ ]:
best_swnu_network_umap_kfold_35["f1"].mean()

In [ ]:
best_swnu_network_umap_kfold_35["precision"].mean()

In [ ]:
best_swnu_network_umap_kfold_35["recall"].mean()

In [ ]:
np.stack(best_swnu_network_umap_kfold_35["f1_scores"]).mean(axis=0)

In [ ]:
np.stack(best_swnu_network_umap_kfold_35["precision_scores"]).mean(axis=0)

In [ ]:
np.stack(best_swnu_network_umap_kfold_35["recall_scores"]).mean(axis=0)

# w=80

In [ ]:
size = 80

## umap

In [ ]:
(
    swnu_network_umap_kfold_80,
    best_swnu_network_umap_kfold_80,
    _,
    __,
) = swnu_network_hyperparameter_search(
    history_lengths=[size],
    dim_reduce_methods=["umap"],
    results_output=f"{output_dir}/swnu_network_umap_focal_{gamma}_{size}_kfold.csv",
    **kwargs,
)

In [ ]:
swnu_network_umap_kfold_80.groupby(
    ["dimensions", "swnu_hidden_dim", "ffn_hidden_dim", "dropout_rate", "learning_rate"]
).mean()

In [ ]:
best_swnu_network_umap_kfold_80

In [ ]:
best_swnu_network_umap_kfold_80["f1"].mean()

In [ ]:
best_swnu_network_umap_kfold_80["precision"].mean()

In [ ]:
best_swnu_network_umap_kfold_80["recall"].mean()

In [ ]:
np.stack(best_swnu_network_umap_kfold_80["f1_scores"]).mean(axis=0)

In [ ]:
np.stack(best_swnu_network_umap_kfold_80["precision_scores"]).mean(axis=0)

In [ ]:
np.stack(best_swnu_network_umap_kfold_80["recall_scores"]).mean(axis=0)