In [1]:
import pickle
import numpy as np
import pandas as pd
import re
import os

seed = 2023

In [2]:
import torch

# set device
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
device

device(type='cuda')

In [3]:
from nlpsig_networks.scripts.ffn_baseline_functions import (
    ffn_hyperparameter_search,
)

In [4]:
output_dir = "rumours_output"
if not os.path.isdir(output_dir):
    os.makedirs(output_dir)

## Rumours

In [5]:
%run load_sbert-embeddings.py

In [6]:
df_rumours.head()

id label            datetime  \
0  5.249902e+17     0 2014-10-22 18:26:23   
1  5.249906e+17     0 2014-10-22 18:27:58   
2  5.249908e+17     1 2014-10-22 18:28:46   
3  5.249927e+17     1 2014-10-22 18:36:29   
4  5.250038e+17     1 2014-10-22 19:20:41   

                                                text timeline_id    set  
0  Police have clarified that there were two shoo...           0  train  
1  @CTVNews you guys "confirmed" there were 3 sho...           0  train  
2      @CTVNews get it right. http://t.co/GHYxMuzPG9           0  train  
3  RT @CTVNews Police have clarified that there w...           0  train  
4  @CTVNews @ctvsaskatoon so what happened at Rid...           0  train

In [7]:
sbert_embeddings.shape

(5568, 384)

## Baseline: FFN

In [10]:
num_epochs = 100
hidden_dim_sizes = [[64, 64], [128, 128], [256, 256]]
dropout_rates = [0.5, 0.1]
learning_rates = [1e-3, 1e-4, 5e-4]
seeds = [1, 12, 123]
loss = "focal"
gamma = 2
validation_metric = "f1"
patience = 5
split_ids = torch.tensor(df_rumours['timeline_id'].astype(int))

In [11]:
ffn_current, best_ffn_current, _, __ = ffn_hyperparameter_search(
    num_epochs=num_epochs,
    x_data=sbert_embeddings,
    y_data=y_data,
    hidden_dim_sizes=hidden_dim_sizes,
    output_dim=output_dim,
    dropout_rates=dropout_rates,
    learning_rates=learning_rates,
    seeds=seeds,
    loss=loss,
    gamma=gamma,
    device=device,
    split_ids=split_ids,
    k_fold=True,
    patience=patience,
    validation_metric=validation_metric,
    results_output=f"{output_dir}/ffn_current_focal_{gamma}.csv",
    verbose=False,
)

  0%|          | 0/3 [00:00<?, ?it/s]

  0%|          | 0/2 [00:00<?, ?it/s]

  0%|          | 0/3 [00:00<?, ?it/s]

  0%|          | 0/3 [00:00<?, ?it/s]

  0%|          | 0/2 [00:00<?, ?it/s]

  0%|          | 0/3 [00:00<?, ?it/s]

  0%|          | 0/3 [00:00<?, ?it/s]

  0%|          | 0/2 [00:00<?, ?it/s]

  0%|          | 0/3 [00:00<?, ?it/s]

  0%|          | 0/3 [00:00<?, ?it/s]

saving results dataframe to CSV for this hyperparameter search in rumours_output/ffn_current_focal_2.csv
saving the best model results dataframe to CSV for this hyperparameter search in rumours_output/ffn_current_focal_2_best_model.csv


In [12]:
ffn_current

loss  accuracy        f1                                  f1_scores  \
0  None  0.612861  0.571105    [0.7049296775110101, 0.437279869953942]   
0  None  0.610997  0.562636  [0.7080710588893552, 0.41720189891091874]   
0  None  0.611743  0.574358   [0.7005032350826743, 0.4482119205298013]   
0  None  0.616775  0.580331   [0.7040023034840196, 0.4566596194503171]   
0  None  0.616216  0.582337   [0.7012911649499491, 0.4633828511858223]   
0  None  0.619385  0.586687  [0.7029386092522548, 0.47043568464730295]   
0  None  0.610065  0.568617  [0.7023335230506546, 0.43490005402485143]   
0  None  0.620503  0.579300  [0.7109596819988644, 0.44763971785132933]   
0  None  0.619758  0.578582  [0.7103095711445613, 0.44685466377440347]   
0  None  0.619758  0.579875   [0.7093188942718723, 0.4504310344827586]   
0  None  0.613420  0.575318   [0.7025243832472748, 0.4481106971793507]   
0  None  0.616589  0.579772    [0.704156479217604, 0.4553878739740535]   
0  None  0.618080  0.580179    [0.706320768238498, 0.4540367705835332]   
0  None  0.619012  0.586658   [0.7023011942907079, 0.4710144927536232]   
0  None  0.619758  0.586525   [0.7037467325007261, 0.4693028095733611]   
0  None  0.610252  0.582552   [0.6900844819919965, 0.4750188300276174]   
0  None  0.619199  0.578126   [0.709759909077994, 0.44649146572744514]   
0  None  0.611929  0.584220  [0.6915555555555556, 0.47688442211055276]   
0  None  0.603355  0.578573   [0.6807680768076807, 0.4763779527559055]   
0  None  0.603914  0.570714    [0.690097710368966, 0.4513297185644203]   
0  None  0.611370  0.577743   [0.6969036197121675, 0.4585821864450792]   
0  None  0.621808  0.585291   [0.7083513008480667, 0.4622316459051153]   
0  None  0.618080  0.583004   [0.7039445166883399, 0.4620635337358887]   
0  None  0.620690  0.587301  [0.7046872732549703, 0.46991404011461324]   
0  None  0.610252  0.572929   [0.6991799741044453, 0.4466790156125959]   
0  None  0.612675  0.576348  [0.7004036908881199, 0.45229309435951504]   
0  None  0.616216  0.577503  [0.7053941908713693, 0.44961240310077516]   
0  None  0.611370  0.578605   [0.6961084390030607, 0.4611010597053502]   
0  None  0.619758  0.581350   [0.7081545064377682, 0.4545454545454545]   
0  None  0.619571  0.574621   [0.7128991419327613, 0.4363435515051091]   
0  None  0.614725  0.576803   [0.7034858700329938, 0.4501197126895451]   
0  None  0.620317  0.584658   [0.7063572149344096, 0.4629580806749275]   
0  None  0.620503  0.581017   [0.7096406160867084, 0.4523937600860678]   
0  None  0.620690  0.582944   [0.7084109471270956, 0.4574780058651026]   
0  None  0.615657  0.579409   [0.7028818443804035, 0.4559366754617415]   
0  None  0.623672  0.584882  [0.7117773019271949, 0.45798657718120805]   
0  None  0.622554  0.584377   [0.7103418681161493, 0.4584113399304627]   
0  None  0.611743  0.575278   [0.6997261063860459, 0.4508304771948326]   
0  None  0.619385  0.576959   [0.7109286523216308, 0.4429896344789962]   
0  None  0.616775  0.582897   [0.7017696547722657, 0.4640250260688217]   
0  None  0.616403  0.582104  [0.7018255578093305, 0.46238244514106586]   
0  None  0.619012  0.581768   [0.7065747918461097, 0.4569606801275239]   
0  None  0.612488  0.577889   [0.6987393131430227, 0.4570383912248629]   
0  None  0.616216  0.576338  [0.7063186421337898, 0.44635654745899433]   
0  None  0.609320  0.570918   [0.6992826398852224, 0.4425531914893617]   
0  None  0.617707  0.576909   [0.7082918503769022, 0.4455258177885915]   
0  None  0.636719  0.584119   [0.7320225491544068, 0.4362163725773792]   
0  None  0.615843  0.579563   [0.7030687220861547, 0.4560570071258907]   
0  None  0.613980  0.579317    [0.7000724112961623, 0.458562091503268]   
0  None  0.616216  0.580172  [0.7031858151938879, 0.45715792248879517]   
0  None  0.616962  0.576192   [0.7076397780623132, 0.4447446636044312]   
0  None  0.623672  0.581888  [0.7140631638578105, 0.44971381847914965]   
0  None  0.613048  0.579228  [0.6985187336625036, 0.45993756503642036]   
0  None

In [13]:
best_ffn_current

loss  accuracy        f1                                  f1_scores  \
0  None  0.616775  0.582897   [0.7017696547722657, 0.4640250260688217]   
0  None  0.616403  0.582104  [0.7018255578093305, 0.46238244514106586]   
0  None  0.619012  0.581768   [0.7065747918461097, 0.4569606801275239]   

   precision                          precision_scores    recall  \
0   0.582265  [0.7102172636523781, 0.4543134252169474]  0.583841   
0   0.581523  [0.7094317516110135, 0.4536135315222963]  0.582939   
0   0.581670  [0.7075905692926969, 0.4557498675145734]  0.581870   

                              recall_scores valid_loss  valid_accuracy  ...  \
0   [0.6935206422018348, 0.474160895045285]       None        0.646987  ...   
0  [0.6943807339449541, 0.4714970697922216]       None        0.650088  ...   
0  [0.7055619266055045, 0.4581779435269046]       None        0.649683  ...   

                        valid_recall_scores  hidden_dim  dropout_rate  \
0   [0.7092136789370508, 0.545968882602546]  (256, 256)           0.5   
0  [0.7111740361576998, 0.5509193776520509]  (256, 256)           0.5   
0  [0.7225005445436724, 0.5314710042432814]  (256, 256)           0.5   

  learning_rate  seed loss_function gamma  k_fold  n_splits  batch_size  
0        0.0001     1         focal     2    True         5          64  
0        0.0001    12         focal     2    True         5          64  
0        0.0001   123         focal     2    True         5          64  

[3 rows x 25 columns]

In [14]:
best_ffn_current["f1"].mean()

0.5822563592941862

In [15]:
best_ffn_current["precision"].mean()

0.5818194014683176

In [16]:
best_ffn_current["recall"].mean()

0.5828832018527841

In [17]:
np.stack(best_ffn_current["f1_scores"]).mean(axis=0)

array([0.70339   , 0.46112272])

In [18]:
np.stack(best_ffn_current["precision_scores"]).mean(axis=0)

array([0.70907986, 0.45455894])

In [19]:
np.stack(best_ffn_current["recall_scores"]).mean(axis=0)

array([0.6978211, 0.4679453])