In [1]:
import numpy as np
import pickle
import os

seed = 2023

In [2]:
import torch

# set device
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
device

device(type='cuda')

In [3]:
from nlpsig_networks.scripts.seqsignet_attention_functions import (
    seqsignet_attention_hyperparameter_search,
)

In [4]:
output_dir = "rumours_output"
if not os.path.isdir(output_dir):
    os.makedirs(output_dir)

## Rumours

In [5]:
%run load_sbert-embeddings.py

In [6]:
df_rumours.head()

id label            datetime  \
0  5.249902e+17     0 2014-10-22 18:26:23   
1  5.249906e+17     0 2014-10-22 18:27:58   
2  5.249908e+17     1 2014-10-22 18:28:46   
3  5.249927e+17     1 2014-10-22 18:36:29   
4  5.250038e+17     1 2014-10-22 19:20:41   

                                                text timeline_id    set  
0  Police have clarified that there were two shoo...           0  train  
1  @CTVNews you guys "confirmed" there were 3 sho...           0  train  
2      @CTVNews get it right. http://t.co/GHYxMuzPG9           0  train  
3  RT @CTVNews Police have clarified that there w...           0  train  
4  @CTVNews @ctvsaskatoon so what happened at Rid...           0  train

# SeqSigNet with Attention Network

In [7]:
features = ["time_encoding", "timeline_index"]
standardise_method = ["z_score", None]
include_features_in_path = True
include_features_in_input = False

In [8]:
split_ids = torch.tensor(df_rumours['timeline_id'].astype(int))

In [9]:
num_epochs = 100
dimensions = [15]  # [50, 15]
# define swmhau parameters: (output_channels, sig_depth, num_heads)
swmhau_parameters = [(12, 3, 10), (8, 4, 6)]#, (8, 4, 12)]
num_layers = [1]
lstm_hidden_dim_sizes = [384]
ffn_hidden_dim_sizes = [[256,256],[512,512]]
dropout_rates = [0.1, 0.2]
learning_rates = [1e-3, 1e-4, 5e-4]
seeds = [1, 12, 123]
loss = "focal"
gamma = 2
validation_metric = "f1"
patience = 5

In [ ]:
kwargs = {
    "num_epochs": num_epochs,
    "df": df_rumours,
    "id_column": "timeline_id",
    "label_column": "label",
    "embeddings": sbert_embeddings,
    "y_data": y_data,
    "output_dim": output_dim,
    "dimensions": dimensions,
    "log_signature": True,
    "swmhau_parameters": swmhau_parameters,
    "num_layers": num_layers,
    "lstm_hidden_dim_sizes": lstm_hidden_dim_sizes,
    "ffn_hidden_dim_sizes": ffn_hidden_dim_sizes,
    "dropout_rates": dropout_rates,
    "learning_rates": learning_rates,
    "seeds": seeds,
    "loss": loss,
    "gamma": gamma,
    "device": device,
    "features": features,
    "standardise_method": standardise_method,
    "include_features_in_path": include_features_in_path,
    "include_features_in_input": include_features_in_input,
    "split_ids": split_ids,
    "k_fold": True,
    "patience": patience,
    "validation_metric": validation_metric,
    "verbose": False,
}

# history_length=11

In [10]:
shift = 3
window_size = 5
n = 3

## UMAP

In [11]:
(
    seqsignet_attention_umap_11,
    best_seqsignet_attention_umap_11,
    _,
    __,
) = seqsignet_attention_hyperparameter_search(
    shift=shift,
    window_size=window_size,
    n=n,
    dim_reduce_methods=["umap"],
    results_output=f"{output_dir}/seqsignet_attention_umap_focal_{gamma}_{shift}_{window_size}_{n}_kfold.csv",
    **kwargs,
)

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]


##################################################
dimension: 15 | method: umap
given shift 3, window size 5 and n 3: history length = 11
[INFO] Concatenating the embeddings to the dataframe...
[INFO] - columns beginning with 'e' denote the full embddings.
[INFO] - columns beginning with 'd' denote the dimension reduced embeddings.
[INFO] Adding time feature columns into dataframe in `.df`.
[INFO] Adding 'time_encoding' feature...
[INFO] Adding 'time_diff' feature...
[INFO] Adding 'timeline_index' feature...
[INFO] Padding ids and storing in `.df_padded` and `.array_padded` attributes.


  0%|          | 0/5568 [00:00<?, ?it/s]

[INFO] The path was created for each item in the dataframe, by looking at its history, so to include embeddings in the FFN input, we concatenate the embeddings for each sentence / text.


  0%|          | 0/2 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/2 [00:00<?, ?it/s]

  0%|          | 0/2 [00:00<?, ?it/s]

  0%|          | 0/3 [00:00<?, ?it/s]

  0%|          | 0/3 [00:00<?, ?it/s]

  0%|          | 0/2 [00:00<?, ?it/s]

  0%|          | 0/3 [00:00<?, ?it/s]

  0%|          | 0/3 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/2 [00:00<?, ?it/s]

  0%|          | 0/2 [00:00<?, ?it/s]

  0%|          | 0/3 [00:00<?, ?it/s]

  0%|          | 0/3 [00:00<?, ?it/s]

  0%|          | 0/2 [00:00<?, ?it/s]

  0%|          | 0/3 [00:00<?, ?it/s]

  0%|          | 0/3 [00:00<?, ?it/s]

given shift 3, window size 5 and n 3: history length = 11
[INFO] Concatenating the embeddings to the dataframe...
[INFO] - columns beginning with 'e' denote the full embddings.
[INFO] - columns beginning with 'd' denote the dimension reduced embeddings.
[INFO] Adding time feature columns into dataframe in `.df`.
[INFO] Adding 'time_encoding' feature...
[INFO] Adding 'time_diff' feature...
[INFO] Adding 'timeline_index' feature...
[INFO] Padding ids and storing in `.df_padded` and `.array_padded` attributes.


  0%|          | 0/5568 [00:00<?, ?it/s]

[INFO] The path was created for each item in the dataframe, by looking at its history, so to include embeddings in the FFN input, we concatenate the embeddings for each sentence / text.
saving results dataframe to CSV for this hyperparameter search in rumours_output/seqsignet_attention_umap_focal_2_3_5_3_kfold.csv
saving the best model results dataframe to CSV for this hyperparameter search in rumours_output/seqsignet_attention_umap_focal_2_3_5_3_kfold_best_model.csv


In [12]:
seqsignet_attention_umap_11.groupby(
    [
        "dimensions",
        "output_channels",
        "sig_depth",
        "num_heads",
        "num_layers",
        "ffn_hidden_dim",
        "learning_rate",
    ]
).mean()

/tmp/ipykernel_3911517/3651854706.py:1: FutureWarning: The default value of numeric_only in DataFrameGroupBy.mean is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  seqsignet_attention_umap_11.groupby(


accuracy  \
dimensions output_channels sig_depth num_heads num_layers ffn_hidden_dim learning_rate             
15         8               4         6         1          (256, 256)     0.0001         0.686518   
                                                                         0.0005         0.687729   
                                                                         0.0010         0.695371   
                                                          (512, 512)     0.0001         0.683970   
                                                                         0.0005         0.689376   
                                                                         0.0010         0.690711   
           12              3         10        1          (256, 256)     0.0001         0.676887   
                                                                         0.0005         0.687512   
                                                                         0.0010         0.694035   
                                                          (512, 512)     0.0001         0.680708   
                                                                         0.0005         0.687760   
                                                                         0.0010         0.689997   

                                                                                              f1  \
dimensions output_channels sig_depth num_heads num_layers ffn_hidden_dim learning_rate             
15         8               4         6         1          (256, 256)     0.0001         0.658252   
                                                                         0.0005         0.660093   
                                                                         0.0010         0.665844   
                                                          (512, 512)     0.0001         0.659242   
                                                                         0.0005         0.663043   
                                                                         0.0010         0.663290   
           12              3         10        1          (256, 256)     0.0001         0.654689   
                                                                         0.0005         0.661659   
                                                                         0.0010         0.663084   
                                                          (512, 512)     0.0001         0.653718   
                                                                         0.0005         0.659781   
                                                                         0.0010         0.661701   

                                                                                        precision  \
dimensions output_channels sig_depth num_heads num_layers ffn_hidden_dim learning_rate              
15         8               4         6         1          (256, 256)     0.0001          0.657149   
                                                                         0.0005          0.658900   
                                                                         0.0010          0.665707   
                                                          (512, 512)     0.0001          0.657705   
                                                                         0.0005          0.661366   
                                                                         0.0010          0.662487   
           12              3         10        1          (256, 256)     0.0001          0.653231   
                                                                         0.0005          0.660002   
                                                                         0.0010          0.663570   
                                                          (512, 512)     0.0001          0.652502   
                                                                         0

In [13]:
best_seqsignet_attention_umap_11

loss  accuracy        f1                                 f1_scores  \
0  None  0.681267  0.658929  [0.7462154942119322, 0.5716432865731463]   
0  None  0.690774  0.663940  [0.7589013224821974, 0.5689789555728761]   
0  None  0.681081  0.654037  [0.7507647487254188, 0.5573091849935318]   

   precision                          precision_scores    recall  \
0   0.656509  [0.7735384615384615, 0.5394799054373522]  0.664321   
0   0.662400  [0.7695254936634247, 0.5552738336713996]  0.665972   
0   0.652427  [0.7631033461652355, 0.5417505030181087]  0.656303   

                              recall_scores valid_loss  valid_accuracy  ...  \
0   [0.720756880733945, 0.6078849227490677]       None        0.747405  ...   
0  [0.7485665137614679, 0.5833777304208844]       None        0.753606  ...   
0  [0.7388188073394495, 0.5737879595098562]       None        0.744305  ...   

   learning_rate seed  loss_function gamma  k_fold n_splits  \
0         0.0001    1          focal     2    True        5   
0         0.0001   12          focal     2    True        5   
0         0.0001  123          focal     2    True        5   

   augmentation_type  hidden_dim_aug    comb_method  batch_size  
0             Conv1d            None  concatenation          64  
0             Conv1d            None  concatenation          64  
0             Conv1d            None  concatenation          64  

[3 rows x 47 columns]

In [14]:
best_seqsignet_attention_umap_11[
    [
        "dimensions",
        "output_channels",
        "sig_depth",
        "num_heads",
        "num_layers",
        "ffn_hidden_dim",
        "dropout_rate",
        "learning_rate",
    ]
]

dimensions  output_channels  sig_depth  num_heads  num_layers  \
0          15               12          3         10           1   
0          15               12          3         10           1   
0          15               12          3         10           1   

  ffn_hidden_dim  dropout_rate  learning_rate  
0     (512, 512)           0.1         0.0001  
0     (512, 512)           0.1         0.0001  
0     (512, 512)           0.1         0.0001

In [15]:
best_seqsignet_attention_umap_11["f1"].mean()

0.6589688320931838

In [16]:
best_seqsignet_attention_umap_11["precision"].mean()

0.6571119239156636

In [17]:
best_seqsignet_attention_umap_11["recall"].mean()

0.6621988024191118

In [18]:
np.stack(best_seqsignet_attention_umap_11["f1_scores"]).mean(axis=0)

array([0.75196052, 0.56597714])

In [19]:
np.stack(best_seqsignet_attention_umap_11["precision_scores"]).mean(axis=0)

array([0.76872243, 0.54550141])

In [20]:
np.stack(best_seqsignet_attention_umap_11["recall_scores"]).mean(axis=0)

array([0.7360474, 0.5883502])

## Random Projections

In [21]:
(
    seqsignet_attention_grp_11,
    best_seqsignet_attention_grp_11,
    _,
    __,
) = seqsignet_attention_hyperparameter_search(
    shift=shift,
    window_size=window_size,
    n=n,
    dim_reduce_methods=["gaussian_random_projection"],
    results_output=f"{output_dir}/seqsignet_attention_grp_focal_{gamma}_{shift}_{window_size}_{n}_kfold.csv",
    **kwargs,
)

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]


##################################################
dimension: 15 | method: gaussian_random_projection
given shift 3, window size 5 and n 3: history length = 11
[INFO] Concatenating the embeddings to the dataframe...
[INFO] - columns beginning with 'e' denote the full embddings.
[INFO] - columns beginning with 'd' denote the dimension reduced embeddings.
[INFO] Adding time feature columns into dataframe in `.df`.
[INFO] Adding 'time_encoding' feature...
[INFO] Adding 'time_diff' feature...
[INFO] Adding 'timeline_index' feature...
[INFO] Padding ids and storing in `.df_padded` and `.array_padded` attributes.


  0%|          | 0/5568 [00:00<?, ?it/s]

[INFO] The path was created for each item in the dataframe, by looking at its history, so to include embeddings in the FFN input, we concatenate the embeddings for each sentence / text.


  0%|          | 0/2 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/2 [00:00<?, ?it/s]

  0%|          | 0/2 [00:00<?, ?it/s]

  0%|          | 0/3 [00:00<?, ?it/s]

  0%|          | 0/3 [00:00<?, ?it/s]

  0%|          | 0/2 [00:00<?, ?it/s]

  0%|          | 0/3 [00:00<?, ?it/s]

  0%|          | 0/3 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/2 [00:00<?, ?it/s]

  0%|          | 0/2 [00:00<?, ?it/s]

  0%|          | 0/3 [00:00<?, ?it/s]

  0%|          | 0/3 [00:00<?, ?it/s]

  0%|          | 0/2 [00:00<?, ?it/s]

  0%|          | 0/3 [00:00<?, ?it/s]

  0%|          | 0/3 [00:00<?, ?it/s]

given shift 3, window size 5 and n 3: history length = 11
[INFO] Concatenating the embeddings to the dataframe...
[INFO] - columns beginning with 'e' denote the full embddings.
[INFO] - columns beginning with 'd' denote the dimension reduced embeddings.
[INFO] Adding time feature columns into dataframe in `.df`.
[INFO] Adding 'time_encoding' feature...
[INFO] Adding 'time_diff' feature...
[INFO] Adding 'timeline_index' feature...
[INFO] Padding ids and storing in `.df_padded` and `.array_padded` attributes.


  0%|          | 0/5568 [00:00<?, ?it/s]

[INFO] The path was created for each item in the dataframe, by looking at its history, so to include embeddings in the FFN input, we concatenate the embeddings for each sentence / text.
saving results dataframe to CSV for this hyperparameter search in rumours_output/seqsignet_attention_grp_focal_2_3_5_3_kfold.csv
saving the best model results dataframe to CSV for this hyperparameter search in rumours_output/seqsignet_attention_grp_focal_2_3_5_3_kfold_best_model.csv


In [22]:
seqsignet_attention_grp_11.groupby(
    [
        "dimensions",
        "output_channels",
        "sig_depth",
        "num_heads",
        "num_layers",
        "ffn_hidden_dim",
        "dropout_rate",
        "learning_rate",
    ]
).mean()

/tmp/ipykernel_3911517/2306022424.py:1: FutureWarning: The default value of numeric_only in DataFrameGroupBy.mean is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  seqsignet_attention_grp_11.groupby(


accuracy  \
dimensions output_channels sig_depth num_heads num_layers ffn_hidden_dim dropout_rate learning_rate             
15         8               4         6         1          (256, 256)     0.1          0.0001         0.675241   
                                                                                      0.0005         0.678969   
                                                                                      0.0010         0.689282   
                                                                         0.2          0.0001         0.676732   
                                                                                      0.0005         0.688599   
                                                                                      0.0010         0.692948   
                                                          (512, 512)     0.1          0.0001         0.676794   
                                                                                      0.0005         0.687232   
                                                                                      0.0010         0.697049   
                                                                         0.2          0.0001         0.680087   
                                                                                      0.0005         0.680833   
                                                                                      0.0010         0.686859   
           12              3         10        1          (256, 256)     0.1          0.0001         0.670332   
                                                                                      0.0005         0.693135   
                                                                                      0.0010         0.683691   
                                                                         0.2          0.0001         0.671513   
                                                                                      0.0005         0.681889   
                                                                                      0.0010         0.684063   
                                                          (512, 512)     0.1          0.0001         0.680770   
                                                                                      0.0005         0.685555   
                                                                                      0.0010         0.686486   
                                                                         0.2          0.0001         0.682013   
                                                                                      0.0005         0.684498   
                                                                                      0.0010         0.678037   

                                                                                                           f1  \
dimensions output_channels sig_depth num_heads num_layers ffn_hidden_dim dropout_rate learning_rate             
15         8               4         6         1          (256, 256)     0.1          0.0001         0.654311   
                                                                                      0.0005         0.658640   
                                                                                      0.0010         0.666969   
                                                                         0.2          0.0001         0.655811   
                                                                                      0.0005         0.663528   
                                                                                      0.0010         0.670933   
                                                          (512, 512)     0.1          0.0001         0.656375   
                                                                                      0.0005         0.663757   
                                

In [23]:
best_seqsignet_attention_grp_11

loss  accuracy        f1                                 f1_scores  \
0  None  0.678472  0.658936  [0.7405624906000904, 0.5773094829698603]   
0  None  0.683131  0.663463  [0.7448213749624737, 0.5821042281219273]   
0  None  0.691892  0.671196   [0.753687974966473, 0.5887036576262753]   

   precision                          precision_scores    recall  \
0   0.656675  [0.7788674470104398, 0.5344827586206896]  0.666723   
0   0.661028   [0.781663516068053, 0.5403925148334094]  0.671045   
0   0.668480  [0.7846726652187404, 0.5522875816993464]  0.677659   

                              recall_scores valid_loss  valid_accuracy  ...  \
0   [0.705848623853211, 0.6275972296217368]       None        0.765737  ...   
0    [0.711295871559633, 0.630793819925413]       None        0.770319  ...   
0  [0.7250573394495413, 0.6302610548748002]       None        0.761963  ...   

   learning_rate seed  loss_function gamma  k_fold n_splits  \
0         0.0001    1          focal     2    True        5   
0         0.0001   12          focal     2    True        5   
0         0.0001  123          focal     2    True        5   

   augmentation_type  hidden_dim_aug    comb_method  batch_size  
0             Conv1d            None  concatenation          64  
0             Conv1d            None  concatenation          64  
0             Conv1d            None  concatenation          64  

[3 rows x 47 columns]

In [24]:
best_seqsignet_attention_grp_11.columns

Index(['loss', 'accuracy', 'f1', 'f1_scores', 'precision', 'precision_scores',
       'recall', 'recall_scores', 'valid_loss', 'valid_accuracy', 'valid_f1',
       'valid_f1_scores', 'valid_precision', 'valid_precision_scores',
       'valid_recall', 'valid_recall_scores', 'k', 'shift', 'window_size', 'n',
       'dimensions', 'sig_depth', 'method', 'input_channels',
       'output_channels', 'features', 'standardise_method',
       'include_features_in_path', 'include_features_in_input',
       'embedding_dim', 'num_features', 'log_signature', 'num_heads',
       'num_layers', 'lstm_hidden_dim', 'ffn_hidden_dim', 'dropout_rate',
       'learning_rate', 'seed', 'loss_function', 'gamma', 'k_fold', 'n_splits',
       'augmentation_type', 'hidden_dim_aug', 'comb_method', 'batch_size'],
      dtype='object')

In [25]:
best_seqsignet_attention_grp_11[
    [
        "dimensions",
        "output_channels",
        "sig_depth",
        "num_heads",
        "num_layers",
        "ffn_hidden_dim",
        "dropout_rate",
        "learning_rate",
    ]
]

dimensions  output_channels  sig_depth  num_heads  num_layers  \
0          15               12          3         10           1   
0          15               12          3         10           1   
0          15               12          3         10           1   

  ffn_hidden_dim  dropout_rate  learning_rate  
0     (512, 512)           0.1         0.0001  
0     (512, 512)           0.1         0.0001  
0     (512, 512)           0.1         0.0001

In [26]:
best_seqsignet_attention_grp_11["f1"].mean()

0.6645315348745165

In [27]:
best_seqsignet_attention_grp_11["precision"].mean()

0.662061080575113

In [28]:
best_seqsignet_attention_grp_11["recall"].mean()

0.6718089898807226

In [29]:
np.stack(best_seqsignet_attention_grp_11["f1_scores"]).mean(axis=0)

array([0.74635728, 0.58270579])

In [30]:
np.stack(best_seqsignet_attention_grp_11["precision_scores"]).mean(axis=0)

array([0.78173454, 0.54238762])

In [31]:
np.stack(best_seqsignet_attention_grp_11["recall_scores"]).mean(axis=0)

array([0.71406728, 0.6295507 ])

# history_length=20

In [32]:
shift = 3
window_size = 5
n = 6

## UMAP

In [33]:
(
    seqsignet_attention_umap_20,
    best_seqsignet_attention_umap_20,
    _,
    __,
) = seqsignet_attention_hyperparameter_search(
    shift=shift,
    window_size=window_size,
    n=n,
    dim_reduce_methods=["umap"],
    results_output=f"{output_dir}/seqsignet_attention_umap_focal_{gamma}_{shift}_{window_size}_{n}_kfold.csv",
    **kwargs,
)

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]


##################################################
dimension: 15 | method: umap
given shift 3, window size 5 and n 6: history length = 20
[INFO] Concatenating the embeddings to the dataframe...
[INFO] - columns beginning with 'e' denote the full embddings.
[INFO] - columns beginning with 'd' denote the dimension reduced embeddings.
[INFO] Adding time feature columns into dataframe in `.df`.
[INFO] Adding 'time_encoding' feature...
[INFO] Adding 'time_diff' feature...
[INFO] Adding 'timeline_index' feature...
[INFO] Padding ids and storing in `.df_padded` and `.array_padded` attributes.


  0%|          | 0/5568 [00:00<?, ?it/s]

[INFO] The path was created for each item in the dataframe, by looking at its history, so to include embeddings in the FFN input, we concatenate the embeddings for each sentence / text.


  0%|          | 0/2 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/2 [00:00<?, ?it/s]

  0%|          | 0/2 [00:00<?, ?it/s]

  0%|          | 0/3 [00:00<?, ?it/s]

  0%|          | 0/3 [00:00<?, ?it/s]

  0%|          | 0/2 [00:00<?, ?it/s]

  0%|          | 0/3 [00:00<?, ?it/s]

  0%|          | 0/3 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/2 [00:00<?, ?it/s]

  0%|          | 0/2 [00:00<?, ?it/s]

  0%|          | 0/3 [00:00<?, ?it/s]

  0%|          | 0/3 [00:00<?, ?it/s]

  0%|          | 0/2 [00:00<?, ?it/s]

  0%|          | 0/3 [00:00<?, ?it/s]

  0%|          | 0/3 [00:00<?, ?it/s]

given shift 3, window size 5 and n 6: history length = 20
[INFO] Concatenating the embeddings to the dataframe...
[INFO] - columns beginning with 'e' denote the full embddings.
[INFO] - columns beginning with 'd' denote the dimension reduced embeddings.
[INFO] Adding time feature columns into dataframe in `.df`.
[INFO] Adding 'time_encoding' feature...
[INFO] Adding 'time_diff' feature...
[INFO] Adding 'timeline_index' feature...
[INFO] Padding ids and storing in `.df_padded` and `.array_padded` attributes.


  0%|          | 0/5568 [00:00<?, ?it/s]

[INFO] The path was created for each item in the dataframe, by looking at its history, so to include embeddings in the FFN input, we concatenate the embeddings for each sentence / text.
saving results dataframe to CSV for this hyperparameter search in rumours_output/seqsignet_attention_umap_focal_2_3_5_6_kfold.csv
saving the best model results dataframe to CSV for this hyperparameter search in rumours_output/seqsignet_attention_umap_focal_2_3_5_6_kfold_best_model.csv


In [34]:
seqsignet_attention_umap_20.groupby(
    [
        "dimensions",
        "output_channels",
        "sig_depth",
        "num_heads",
        "num_layers",
        "ffn_hidden_dim",
        "learning_rate",
    ]
).mean()

/tmp/ipykernel_3911517/2726168036.py:1: FutureWarning: The default value of numeric_only in DataFrameGroupBy.mean is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  seqsignet_attention_umap_20.groupby(


accuracy  \
dimensions output_channels sig_depth num_heads num_layers ffn_hidden_dim learning_rate             
15         8               4         6         1          (256, 256)     0.0001         0.671606   
                                                                         0.0005         0.671824   
                                                                         0.0010         0.686238   
                                                          (512, 512)     0.0001         0.678689   
                                                                         0.0005         0.683380   
                                                                         0.0010         0.684654   
           12              3         10        1          (256, 256)     0.0001         0.669525   
                                                                         0.0005         0.663591   
                                                                         0.0010         0.673812   
                                                          (512, 512)     0.0001         0.676701   
                                                                         0.0005         0.667661   
                                                                         0.0010         0.673936   

                                                                                              f1  \
dimensions output_channels sig_depth num_heads num_layers ffn_hidden_dim learning_rate             
15         8               4         6         1          (256, 256)     0.0001         0.648627   
                                                                         0.0005         0.653100   
                                                                         0.0010         0.660819   
                                                          (512, 512)     0.0001         0.652053   
                                                                         0.0005         0.661462   
                                                                         0.0010         0.660449   
           12              3         10        1          (256, 256)     0.0001         0.646153   
                                                                         0.0005         0.640810   
                                                                         0.0010         0.652600   
                                                          (512, 512)     0.0001         0.654024   
                                                                         0.0005         0.651046   
                                                                         0.0010         0.655865   

                                                                                        precision  \
dimensions output_channels sig_depth num_heads num_layers ffn_hidden_dim learning_rate              
15         8               4         6         1          (256, 256)     0.0001          0.646634   
                                                                         0.0005          0.651940   
                                                                         0.0010          0.659125   
                                                          (512, 512)     0.0001          0.650700   
                                                                         0.0005          0.659138   
                                                                         0.0010          0.659044   
           12              3         10        1          (256, 256)     0.0001          0.644121   
                                                                         0.0005          0.639472   
                                                                         0.0010          0.651530   
                                                          (512, 512)     0.0001          0.651832   
                                                                         0

In [35]:
best_seqsignet_attention_umap_20

loss  accuracy        f1                                 f1_scores  \
0  None  0.686300  0.664554   [0.749962858416283, 0.5791447861965492]   
0  None  0.676421  0.653245  [0.7428909952606636, 0.5635997988939164]   
0  None  0.643057  0.621938   [0.7112920247248605, 0.532584818159629]   

   precision                          precision_scores    recall  \
0   0.662002  [0.7782917052112241, 0.5457115928369463]  0.670283   
0   0.650969  [0.7683823529411765, 0.5335554497858163]  0.658133   
0   0.620760  [0.7500794912559618, 0.4914414414414414]  0.628783   

                              recall_scores valid_loss  valid_accuracy  ...  \
0  [0.7236238532110092, 0.6169419286094833]       None        0.847688  ...   
0   [0.7190366972477065, 0.597229621736814]       None        0.834614  ...   
0  [0.6763188073394495, 0.5812466702184337]       None        0.819787  ...   

   learning_rate seed  loss_function gamma  k_fold n_splits  \
0         0.0001    1          focal     2    True        5   
0         0.0001   12          focal     2    True        5   
0         0.0001  123          focal     2    True        5   

   augmentation_type  hidden_dim_aug    comb_method  batch_size  
0             Conv1d            None  concatenation          64  
0             Conv1d            None  concatenation          64  
0             Conv1d            None  concatenation          64  

[3 rows x 47 columns]

In [36]:
best_seqsignet_attention_umap_20[
    [
        "dimensions",
        "output_channels",
        "sig_depth",
        "num_heads",
        "num_layers",
        "ffn_hidden_dim",
        "dropout_rate",
        "learning_rate",
    ]
]

dimensions  output_channels  sig_depth  num_heads  num_layers  \
0          15               12          3         10           1   
0          15               12          3         10           1   
0          15               12          3         10           1   

  ffn_hidden_dim  dropout_rate  learning_rate  
0     (256, 256)           0.1         0.0001  
0     (256, 256)           0.1         0.0001  
0     (256, 256)           0.1         0.0001

In [37]:
best_seqsignet_attention_umap_20["f1"].mean()

0.6465792136086502

In [38]:
best_seqsignet_attention_umap_20["precision"].mean()

0.6445770055787611

In [39]:
best_seqsignet_attention_umap_20["recall"].mean()

0.652399596393816

In [40]:
np.stack(best_seqsignet_attention_umap_20["f1_scores"]).mean(axis=0)

array([0.73471529, 0.55844313])

In [41]:
np.stack(best_seqsignet_attention_umap_20["precision_scores"]).mean(axis=0)

array([0.76558452, 0.52356949])

In [42]:
np.stack(best_seqsignet_attention_umap_20["recall_scores"]).mean(axis=0)

array([0.70632645, 0.59847274])

## Random Projections

In [43]:
(
    seqsignet_attention_grp_20,
    best_seqsignet_attention_grp_20,
    _,
    __,
) = seqsignet_attention_hyperparameter_search(
    shift=shift,
    window_size=window_size,
    n=n,
    dim_reduce_methods=["gaussian_random_projection"],
    results_output=f"{output_dir}/seqsignet_attention_grp_focal_{gamma}_{shift}_{window_size}_{n}_kfold.csv",
    **kwargs,
)

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]


##################################################
dimension: 15 | method: gaussian_random_projection
given shift 3, window size 5 and n 6: history length = 20
[INFO] Concatenating the embeddings to the dataframe...
[INFO] - columns beginning with 'e' denote the full embddings.
[INFO] - columns beginning with 'd' denote the dimension reduced embeddings.
[INFO] Adding time feature columns into dataframe in `.df`.
[INFO] Adding 'time_encoding' feature...
[INFO] Adding 'time_diff' feature...
[INFO] Adding 'timeline_index' feature...
[INFO] Padding ids and storing in `.df_padded` and `.array_padded` attributes.


  0%|          | 0/5568 [00:00<?, ?it/s]

[INFO] The path was created for each item in the dataframe, by looking at its history, so to include embeddings in the FFN input, we concatenate the embeddings for each sentence / text.


  0%|          | 0/2 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/2 [00:00<?, ?it/s]

  0%|          | 0/2 [00:00<?, ?it/s]

  0%|          | 0/3 [00:00<?, ?it/s]

  0%|          | 0/3 [00:00<?, ?it/s]

  0%|          | 0/2 [00:00<?, ?it/s]

  0%|          | 0/3 [00:00<?, ?it/s]

  0%|          | 0/3 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/2 [00:00<?, ?it/s]

  0%|          | 0/2 [00:00<?, ?it/s]

  0%|          | 0/3 [00:00<?, ?it/s]

  0%|          | 0/3 [00:00<?, ?it/s]

  0%|          | 0/2 [00:00<?, ?it/s]

  0%|          | 0/3 [00:00<?, ?it/s]

  0%|          | 0/3 [00:00<?, ?it/s]

given shift 3, window size 5 and n 6: history length = 20
[INFO] Concatenating the embeddings to the dataframe...
[INFO] - columns beginning with 'e' denote the full embddings.
[INFO] - columns beginning with 'd' denote the dimension reduced embeddings.
[INFO] Adding time feature columns into dataframe in `.df`.
[INFO] Adding 'time_encoding' feature...
[INFO] Adding 'time_diff' feature...
[INFO] Adding 'timeline_index' feature...
[INFO] Padding ids and storing in `.df_padded` and `.array_padded` attributes.


  0%|          | 0/5568 [00:00<?, ?it/s]

[INFO] The path was created for each item in the dataframe, by looking at its history, so to include embeddings in the FFN input, we concatenate the embeddings for each sentence / text.
saving results dataframe to CSV for this hyperparameter search in rumours_output/seqsignet_attention_grp_focal_2_3_5_6_kfold.csv
saving the best model results dataframe to CSV for this hyperparameter search in rumours_output/seqsignet_attention_grp_focal_2_3_5_6_kfold_best_model.csv


In [44]:
seqsignet_attention_grp_20.groupby(
    [
        "dimensions",
        "output_channels",
        "sig_depth",
        "num_heads",
        "num_layers",
        "ffn_hidden_dim",
        "dropout_rate",
        "learning_rate",
    ]
).mean()

/tmp/ipykernel_3911517/1800884729.py:1: FutureWarning: The default value of numeric_only in DataFrameGroupBy.mean is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  seqsignet_attention_grp_20.groupby(


accuracy  \
dimensions output_channels sig_depth num_heads num_layers ffn_hidden_dim dropout_rate learning_rate             
15         8               4         6         1          (256, 256)     0.1          0.0001         0.664430   
                                                                                      0.0005         0.675179   
                                                                                      0.0010         0.675179   
                                                                         0.2          0.0001         0.669711   
                                                                                      0.0005         0.668531   
                                                                                      0.0010         0.665673   
                                                          (512, 512)     0.1          0.0001         0.668220   
                                                                                      0.0005         0.688599   
                                                                                      0.0010         0.678907   
                                                                         0.2          0.0001         0.662690   
                                                                                      0.0005         0.675365   
                                                                                      0.0010         0.675489   
           12              3         10        1          (256, 256)     0.1          0.0001         0.675862   
                                                                                      0.0005         0.664554   
                                                                                      0.0010         0.675800   
                                                                         0.2          0.0001         0.669338   
                                                                                      0.0005         0.670829   
                                                                                      0.0010         0.675738   
                                                          (512, 512)     0.1          0.0001         0.679590   
                                                                                      0.0005         0.668468   
                                                                                      0.0010         0.675862   
                                                                         0.2          0.0001         0.675800   
                                                                                      0.0005         0.670954   
                                                                                      0.0010         0.681330   

                                                                                                           f1  \
dimensions output_channels sig_depth num_heads num_layers ffn_hidden_dim dropout_rate learning_rate             
15         8               4         6         1          (256, 256)     0.1          0.0001         0.640026   
                                                                                      0.0005         0.652384   
                                                                                      0.0010         0.652753   
                                                                         0.2          0.0001         0.647349   
                                                                                      0.0005         0.648403   
                                                                                      0.0010         0.647788   
                                                          (512, 512)     0.1          0.0001         0.645820   
                                                                                      0.0005         0.663339   
                                

In [45]:
best_seqsignet_attention_grp_20

loss  accuracy        f1                                 f1_scores  \
0  None  0.673253  0.651513   [0.7385533184190902, 0.564472049689441]   
0  None  0.677540  0.650784  [0.7474452554744525, 0.5541237113402061]   
0  None  0.666542  0.644144   [0.733422738787066, 0.5548643941278926]   

   precision                          precision_scores    recall  \
0   0.649263  [0.7696611750077712, 0.5288640595903166]  0.657542   
0   0.649073  [0.7614515169541939, 0.5366949575636545]  0.653334   
0   0.642058   [0.763574309649395, 0.5205415499533147]  0.649797   

                              recall_scores valid_loss  valid_accuracy  ...  \
0  [0.7098623853211009, 0.6052210974960043]       None        0.841353  ...   
0  [0.7339449541284404, 0.5727224294086308]       None        0.841623  ...   
0   [0.7055619266055045, 0.594033031433138]       None        0.842297  ...   

   learning_rate seed  loss_function gamma  k_fold n_splits  \
0         0.0001    1          focal     2    True        5   
0         0.0001   12          focal     2    True        5   
0         0.0001  123          focal     2    True        5   

   augmentation_type  hidden_dim_aug    comb_method  batch_size  
0             Conv1d            None  concatenation          64  
0             Conv1d            None  concatenation          64  
0             Conv1d            None  concatenation          64  

[3 rows x 47 columns]

In [46]:
best_seqsignet_attention_grp_20.columns

Index(['loss', 'accuracy', 'f1', 'f1_scores', 'precision', 'precision_scores',
       'recall', 'recall_scores', 'valid_loss', 'valid_accuracy', 'valid_f1',
       'valid_f1_scores', 'valid_precision', 'valid_precision_scores',
       'valid_recall', 'valid_recall_scores', 'k', 'shift', 'window_size', 'n',
       'dimensions', 'sig_depth', 'method', 'input_channels',
       'output_channels', 'features', 'standardise_method',
       'include_features_in_path', 'include_features_in_input',
       'embedding_dim', 'num_features', 'log_signature', 'num_heads',
       'num_layers', 'lstm_hidden_dim', 'ffn_hidden_dim', 'dropout_rate',
       'learning_rate', 'seed', 'loss_function', 'gamma', 'k_fold', 'n_splits',
       'augmentation_type', 'hidden_dim_aug', 'comb_method', 'batch_size'],
      dtype='object')

In [47]:
best_seqsignet_attention_grp_20[
    [
        "dimensions",
        "output_channels",
        "sig_depth",
        "num_heads",
        "num_layers",
        "ffn_hidden_dim",
        "dropout_rate",
        "learning_rate",
    ]
]

dimensions  output_channels  sig_depth  num_heads  num_layers  \
0          15               12          3         10           1   
0          15               12          3         10           1   
0          15               12          3         10           1   

  ffn_hidden_dim  dropout_rate  learning_rate  
0     (256, 256)           0.1         0.0001  
0     (256, 256)           0.1         0.0001  
0     (256, 256)           0.1         0.0001

In [48]:
best_seqsignet_attention_grp_20["f1"].mean()

0.6488135779730247

In [49]:
best_seqsignet_attention_grp_20["precision"].mean()

0.6467979281197743

In [50]:
best_seqsignet_attention_grp_20["recall"].mean()

0.6535576373988031

In [51]:
np.stack(best_seqsignet_attention_grp_20["f1_scores"]).mean(axis=0)

array([0.7398071 , 0.55782005])

In [52]:
np.stack(best_seqsignet_attention_grp_20["precision_scores"]).mean(axis=0)

array([0.76489567, 0.52870019])

In [53]:
np.stack(best_seqsignet_attention_grp_20["recall_scores"]).mean(axis=0)

array([0.71645642, 0.59065885])

# history_length=35

In [54]:
shift = 3
window_size = 5
n = 11

## UMAP

In [55]:
(
    seqsignet_attention_umap_35,
    best_seqsignet_attention_umap_35,
    _,
    __,
) = seqsignet_attention_hyperparameter_search(
    shift=shift,
    window_size=window_size,
    n=n,
    dim_reduce_methods=["umap"],
    results_output=f"{output_dir}/seqsignet_attention_umap_focal_{gamma}_{shift}_{window_size}_{n}_kfold.csv",
    **kwargs,
)

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]


##################################################
dimension: 15 | method: umap
given shift 3, window size 5 and n 11: history length = 35
[INFO] Concatenating the embeddings to the dataframe...
[INFO] - columns beginning with 'e' denote the full embddings.
[INFO] - columns beginning with 'd' denote the dimension reduced embeddings.
[INFO] Adding time feature columns into dataframe in `.df`.
[INFO] Adding 'time_encoding' feature...
[INFO] Adding 'time_diff' feature...
[INFO] Adding 'timeline_index' feature...
[INFO] Padding ids and storing in `.df_padded` and `.array_padded` attributes.


  0%|          | 0/5568 [00:00<?, ?it/s]

[INFO] The path was created for each item in the dataframe, by looking at its history, so to include embeddings in the FFN input, we concatenate the embeddings for each sentence / text.


  0%|          | 0/2 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/2 [00:00<?, ?it/s]

  0%|          | 0/2 [00:00<?, ?it/s]

  0%|          | 0/3 [00:00<?, ?it/s]

  0%|          | 0/3 [00:00<?, ?it/s]

  0%|          | 0/2 [00:00<?, ?it/s]

  0%|          | 0/3 [00:00<?, ?it/s]

  0%|          | 0/3 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/2 [00:00<?, ?it/s]

  0%|          | 0/2 [00:00<?, ?it/s]

  0%|          | 0/3 [00:00<?, ?it/s]

  0%|          | 0/3 [00:00<?, ?it/s]

  0%|          | 0/2 [00:00<?, ?it/s]

  0%|          | 0/3 [00:00<?, ?it/s]

  0%|          | 0/3 [00:00<?, ?it/s]

given shift 3, window size 5 and n 11: history length = 35
[INFO] Concatenating the embeddings to the dataframe...
[INFO] - columns beginning with 'e' denote the full embddings.
[INFO] - columns beginning with 'd' denote the dimension reduced embeddings.
[INFO] Adding time feature columns into dataframe in `.df`.
[INFO] Adding 'time_encoding' feature...
[INFO] Adding 'time_diff' feature...
[INFO] Adding 'timeline_index' feature...
[INFO] Padding ids and storing in `.df_padded` and `.array_padded` attributes.


  0%|          | 0/5568 [00:00<?, ?it/s]

[INFO] The path was created for each item in the dataframe, by looking at its history, so to include embeddings in the FFN input, we concatenate the embeddings for each sentence / text.
saving results dataframe to CSV for this hyperparameter search in rumours_output/seqsignet_attention_umap_focal_2_3_5_11_kfold.csv
saving the best model results dataframe to CSV for this hyperparameter search in rumours_output/seqsignet_attention_umap_focal_2_3_5_11_kfold_best_model.csv


In [56]:
seqsignet_attention_umap_35.groupby(
    [
        "dimensions",
        "output_channels",
        "sig_depth",
        "num_heads",
        "num_layers",
        "ffn_hidden_dim",
        "learning_rate",
    ]
).mean()

/tmp/ipykernel_3911517/1515538645.py:1: FutureWarning: The default value of numeric_only in DataFrameGroupBy.mean is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  seqsignet_attention_umap_35.groupby(


accuracy  \
dimensions output_channels sig_depth num_heads num_layers ffn_hidden_dim learning_rate             
15         8               4         6         1          (256, 256)     0.0001         0.687170   
                                                                         0.0005         0.676142   
                                                                         0.0010         0.683162   
                                                          (512, 512)     0.0001         0.680926   
                                                                         0.0005         0.683628   
                                                                         0.0010         0.690276   
           12              3         10        1          (256, 256)     0.0001         0.682199   
                                                                         0.0005         0.663933   
                                                                         0.0010         0.670270   
                                                          (512, 512)     0.0001         0.677788   
                                                                         0.0005         0.669680   
                                                                         0.0010         0.682728   

                                                                                              f1  \
dimensions output_channels sig_depth num_heads num_layers ffn_hidden_dim learning_rate             
15         8               4         6         1          (256, 256)     0.0001         0.658329   
                                                                         0.0005         0.655288   
                                                                         0.0010         0.658666   
                                                          (512, 512)     0.0001         0.655789   
                                                                         0.0005         0.664060   
                                                                         0.0010         0.659841   
           12              3         10        1          (256, 256)     0.0001         0.657717   
                                                                         0.0005         0.644444   
                                                                         0.0010         0.647625   
                                                          (512, 512)     0.0001         0.655378   
                                                                         0.0005         0.644146   
                                                                         0.0010         0.659658   

                                                                                        precision  \
dimensions output_channels sig_depth num_heads num_layers ffn_hidden_dim learning_rate              
15         8               4         6         1          (256, 256)     0.0001          0.657530   
                                                                         0.0005          0.653228   
                                                                         0.0010          0.656697   
                                                          (512, 512)     0.0001          0.653817   
                                                                         0.0005          0.661948   
                                                                         0.0010          0.660173   
           12              3         10        1          (256, 256)     0.0001          0.655651   
                                                                         0.0005          0.642850   
                                                                         0.0010          0.645917   
                                                          (512, 512)     0.0001          0.653157   
                                                                         0

In [57]:
best_seqsignet_attention_umap_35

loss  accuracy        f1                                 f1_scores  \
0  None  0.680895  0.654108  [0.7503645377661126, 0.5578512396694214]   
0  None  0.664306  0.635839  [0.7376547705753823, 0.5340232858990944]   
0  None  0.654800  0.635152  [0.7198184568835099, 0.5504854368932038]   

   precision                          precision_scores    recall  \
0   0.652427  [0.7635014836795252, 0.5413533834586466]  0.656529   
0   0.634446  [0.7497779093870299, 0.5191146881287726]  0.637865   
0   0.633792   [0.762011531069827, 0.5055728934462773]  0.643104   

                              recall_scores valid_loss  valid_accuracy  ...  \
0  [0.7376720183486238, 0.5753862546616942]       None        0.880038  ...   
0  [0.7259174311926605, 0.5498135322322856]       None        0.873164  ...   
0   [0.682052752293578, 0.6041555673947789]       None        0.866694  ...   

   learning_rate seed  loss_function gamma  k_fold n_splits  \
0         0.0005    1          focal     2    True        5   
0         0.0005   12          focal     2    True        5   
0         0.0005  123          focal     2    True        5   

   augmentation_type  hidden_dim_aug    comb_method  batch_size  
0             Conv1d            None  concatenation          64  
0             Conv1d            None  concatenation          64  
0             Conv1d            None  concatenation          64  

[3 rows x 47 columns]

In [58]:
best_seqsignet_attention_umap_35[
    [
        "dimensions",
        "output_channels",
        "sig_depth",
        "num_heads",
        "num_layers",
        "ffn_hidden_dim",
        "dropout_rate",
        "learning_rate",
    ]
]

dimensions  output_channels  sig_depth  num_heads  num_layers  \
0          15               12          3         10           1   
0          15               12          3         10           1   
0          15               12          3         10           1   

  ffn_hidden_dim  dropout_rate  learning_rate  
0     (256, 256)           0.2         0.0005  
0     (256, 256)           0.2         0.0005  
0     (256, 256)           0.2         0.0005

In [59]:
best_seqsignet_attention_umap_35["f1"].mean()

0.6416996212811207

In [60]:
best_seqsignet_attention_umap_35["precision"].mean()

0.6402219815283464

In [61]:
best_seqsignet_attention_umap_35["recall"].mean()

0.6458329260206036

In [62]:
np.stack(best_seqsignet_attention_umap_35["f1_scores"]).mean(axis=0)

array([0.73594592, 0.54745332])

In [63]:
np.stack(best_seqsignet_attention_umap_35["precision_scores"]).mean(axis=0)

array([0.75843031, 0.52201366])

In [64]:
np.stack(best_seqsignet_attention_umap_35["recall_scores"]).mean(axis=0)

array([0.71521407, 0.57645178])

## Random Projections

In [65]:
(
    seqsignet_attention_grp_35,
    best_seqsignet_attention_grp_35,
    _,
    __,
) = seqsignet_attention_hyperparameter_search(
    shift=shift,
    window_size=window_size,
    n=n,
    dim_reduce_methods=["gaussian_random_projection"],
    results_output=f"{output_dir}/seqsignet_attention_grp_focal_{gamma}_{shift}_{window_size}_{n}_kfold.csv",
    **kwargs,
)

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]


##################################################
dimension: 15 | method: gaussian_random_projection
given shift 3, window size 5 and n 11: history length = 35
[INFO] Concatenating the embeddings to the dataframe...
[INFO] - columns beginning with 'e' denote the full embddings.
[INFO] - columns beginning with 'd' denote the dimension reduced embeddings.
[INFO] Adding time feature columns into dataframe in `.df`.
[INFO] Adding 'time_encoding' feature...
[INFO] Adding 'time_diff' feature...
[INFO] Adding 'timeline_index' feature...
[INFO] Padding ids and storing in `.df_padded` and `.array_padded` attributes.


  0%|          | 0/5568 [00:00<?, ?it/s]

[INFO] The path was created for each item in the dataframe, by looking at its history, so to include embeddings in the FFN input, we concatenate the embeddings for each sentence / text.


  0%|          | 0/2 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/2 [00:00<?, ?it/s]

  0%|          | 0/2 [00:00<?, ?it/s]

  0%|          | 0/3 [00:00<?, ?it/s]

  0%|          | 0/3 [00:00<?, ?it/s]

  0%|          | 0/2 [00:00<?, ?it/s]

  0%|          | 0/3 [00:00<?, ?it/s]

  0%|          | 0/3 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/2 [00:00<?, ?it/s]

  0%|          | 0/2 [00:00<?, ?it/s]

  0%|          | 0/3 [00:00<?, ?it/s]

  0%|          | 0/3 [00:00<?, ?it/s]

  0%|          | 0/2 [00:00<?, ?it/s]

  0%|          | 0/3 [00:00<?, ?it/s]

  0%|          | 0/3 [00:00<?, ?it/s]

given shift 3, window size 5 and n 11: history length = 35
[INFO] Concatenating the embeddings to the dataframe...
[INFO] - columns beginning with 'e' denote the full embddings.
[INFO] - columns beginning with 'd' denote the dimension reduced embeddings.
[INFO] Adding time feature columns into dataframe in `.df`.
[INFO] Adding 'time_encoding' feature...
[INFO] Adding 'time_diff' feature...
[INFO] Adding 'timeline_index' feature...
[INFO] Padding ids and storing in `.df_padded` and `.array_padded` attributes.


  0%|          | 0/5568 [00:00<?, ?it/s]

[INFO] The path was created for each item in the dataframe, by looking at its history, so to include embeddings in the FFN input, we concatenate the embeddings for each sentence / text.
saving results dataframe to CSV for this hyperparameter search in rumours_output/seqsignet_attention_grp_focal_2_3_5_11_kfold.csv
saving the best model results dataframe to CSV for this hyperparameter search in rumours_output/seqsignet_attention_grp_focal_2_3_5_11_kfold_best_model.csv


In [66]:
seqsignet_attention_grp_35.groupby(
    [
        "dimensions",
        "output_channels",
        "sig_depth",
        "num_heads",
        "num_layers",
        "ffn_hidden_dim",
        "dropout_rate",
        "learning_rate",
    ]
).mean()

/tmp/ipykernel_3911517/931700321.py:1: FutureWarning: The default value of numeric_only in DataFrameGroupBy.mean is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  seqsignet_attention_grp_35.groupby(


accuracy  \
dimensions output_channels sig_depth num_heads num_layers ffn_hidden_dim dropout_rate learning_rate             
15         8               4         6         1          (256, 256)     0.1          0.0001         0.666294   
                                                                                      0.0005         0.678596   
                                                                                      0.0010         0.677788   
                                                                         0.2          0.0001         0.663125   
                                                                                      0.0005         0.683504   
                                                                                      0.0010         0.688847   
                                                          (512, 512)     0.1          0.0001         0.661758   
                                                                                      0.0005         0.679838   
                                                                                      0.0010         0.687729   
                                                                         0.2          0.0001         0.667909   
                                                                                      0.0005         0.677912   
                                                                                      0.0010         0.690214   
           12              3         10        1          (256, 256)     0.1          0.0001         0.668531   
                                                                                      0.0005         0.669711   
                                                                                      0.0010         0.676421   
                                                                         0.2          0.0001         0.675986   
                                                                                      0.0005         0.676483   
                                                                                      0.0010         0.677477   
                                                          (512, 512)     0.1          0.0001         0.677167   
                                                                                      0.0005         0.685182   
                                                                                      0.0010         0.682199   
                                                                         0.2          0.0001         0.678844   
                                                                                      0.0005         0.674122   
                                                                                      0.0010         0.684436   

                                                                                                           f1  \
dimensions output_channels sig_depth num_heads num_layers ffn_hidden_dim dropout_rate learning_rate             
15         8               4         6         1          (256, 256)     0.1          0.0001         0.640834   
                                                                                      0.0005         0.653167   
                                                                                      0.0010         0.654511   
                                                                         0.2          0.0001         0.636399   
                                                                                      0.0005         0.654659   
                                                                                      0.0010         0.664873   
                                                          (512, 512)     0.1          0.0001         0.634727   
                                                                                      0.0005         0.652414   
                                

In [67]:
best_seqsignet_attention_grp_35

loss  accuracy        f1                                 f1_scores  \
0  None  0.668034  0.636856  [0.7432607755513911, 0.5304508304771948]   
0  None  0.679404  0.646491  [0.7543558983147672, 0.5386266094420601]   
0  None  0.680149  0.653222  [0.7498542274052479, 0.5565891472868217]   

   precision                          precision_scores    recall  \
0   0.636258  [0.7474630327631198, 0.5250521920668059]  0.637534   
0   0.646987  [0.7515651678998293, 0.5424095083738519]  0.646032   
0   0.651572  [0.7627520759193357, 0.5403913697942799]  0.655587   

                              recall_scores valid_loss  valid_accuracy  ...  \
0   [0.739105504587156, 0.5359616409163559]       None        0.868176  ...   
0  [0.7571674311926605, 0.5348961108151306]       None        0.882868  ...   
0  [0.7373853211009175, 0.5737879595098562]       None        0.870333  ...   

   learning_rate seed  loss_function gamma  k_fold n_splits  \
0         0.0001    1          focal     2    True        5   
0         0.0001   12          focal     2    True        5   
0         0.0001  123          focal     2    True        5   

   augmentation_type  hidden_dim_aug    comb_method  batch_size  
0             Conv1d            None  concatenation          64  
0             Conv1d            None  concatenation          64  
0             Conv1d            None  concatenation          64  

[3 rows x 47 columns]

In [68]:
best_seqsignet_attention_grp_35.columns

Index(['loss', 'accuracy', 'f1', 'f1_scores', 'precision', 'precision_scores',
       'recall', 'recall_scores', 'valid_loss', 'valid_accuracy', 'valid_f1',
       'valid_f1_scores', 'valid_precision', 'valid_precision_scores',
       'valid_recall', 'valid_recall_scores', 'k', 'shift', 'window_size', 'n',
       'dimensions', 'sig_depth', 'method', 'input_channels',
       'output_channels', 'features', 'standardise_method',
       'include_features_in_path', 'include_features_in_input',
       'embedding_dim', 'num_features', 'log_signature', 'num_heads',
       'num_layers', 'lstm_hidden_dim', 'ffn_hidden_dim', 'dropout_rate',
       'learning_rate', 'seed', 'loss_function', 'gamma', 'k_fold', 'n_splits',
       'augmentation_type', 'hidden_dim_aug', 'comb_method', 'batch_size'],
      dtype='object')

In [69]:
best_seqsignet_attention_grp_35[
    [
        "dimensions",
        "output_channels",
        "sig_depth",
        "num_heads",
        "num_layers",
        "ffn_hidden_dim",
        "dropout_rate",
        "learning_rate",
    ]
]

dimensions  output_channels  sig_depth  num_heads  num_layers  \
0          15               12          3         10           1   
0          15               12          3         10           1   
0          15               12          3         10           1   

  ffn_hidden_dim  dropout_rate  learning_rate  
0     (256, 256)           0.1         0.0001  
0     (256, 256)           0.1         0.0001  
0     (256, 256)           0.1         0.0001

In [70]:
best_seqsignet_attention_grp_35["f1"].mean()

0.6455229147462471

In [71]:
best_seqsignet_attention_grp_35["precision"].mean()

0.6449388911362037

In [72]:
best_seqsignet_attention_grp_35["recall"].mean()

0.6463839946870128

In [73]:
np.stack(best_seqsignet_attention_grp_35["f1_scores"]).mean(axis=0)

array([0.74915697, 0.54188886])

In [74]:
np.stack(best_seqsignet_attention_grp_35["precision_scores"]).mean(axis=0)

array([0.75392676, 0.53595102])

In [75]:
np.stack(best_seqsignet_attention_grp_35["recall_scores"]).mean(axis=0)

array([0.74455275, 0.54821524])

# history_length=80

In [76]:
shift = 3
window_size = 5
n = 26

## UMAP

In [77]:
(
    seqsignet_attention_umap_80,
    best_seqsignet_attention_umap_80,
    _,
    __,
) = seqsignet_attention_hyperparameter_search(
    shift=shift,
    window_size=window_size,
    n=n,
    dim_reduce_methods=["umap"],
    results_output=f"{output_dir}/seqsignet_attention_umap_focal_{gamma}_{shift}_{window_size}_{n}_kfold.csv",
    **kwargs,
)

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]


##################################################
dimension: 15 | method: umap
given shift 3, window size 5 and n 26: history length = 80
[INFO] Concatenating the embeddings to the dataframe...
[INFO] - columns beginning with 'e' denote the full embddings.
[INFO] - columns beginning with 'd' denote the dimension reduced embeddings.
[INFO] Adding time feature columns into dataframe in `.df`.
[INFO] Adding 'time_encoding' feature...
[INFO] Adding 'time_diff' feature...
[INFO] Adding 'timeline_index' feature...
[INFO] Padding ids and storing in `.df_padded` and `.array_padded` attributes.


  0%|          | 0/5568 [00:00<?, ?it/s]

[INFO] The path was created for each item in the dataframe, by looking at its history, so to include embeddings in the FFN input, we concatenate the embeddings for each sentence / text.


  0%|          | 0/2 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/2 [00:00<?, ?it/s]

  0%|          | 0/2 [00:00<?, ?it/s]

  0%|          | 0/3 [00:00<?, ?it/s]

  0%|          | 0/3 [00:00<?, ?it/s]

  0%|          | 0/2 [00:00<?, ?it/s]

  0%|          | 0/3 [00:00<?, ?it/s]

  0%|          | 0/3 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/2 [00:00<?, ?it/s]

  0%|          | 0/2 [00:00<?, ?it/s]

  0%|          | 0/3 [00:00<?, ?it/s]

  0%|          | 0/3 [00:00<?, ?it/s]

  0%|          | 0/2 [00:00<?, ?it/s]

  0%|          | 0/3 [00:00<?, ?it/s]

  0%|          | 0/3 [00:00<?, ?it/s]

given shift 3, window size 5 and n 26: history length = 80
[INFO] Concatenating the embeddings to the dataframe...
[INFO] - columns beginning with 'e' denote the full embddings.
[INFO] - columns beginning with 'd' denote the dimension reduced embeddings.
[INFO] Adding time feature columns into dataframe in `.df`.
[INFO] Adding 'time_encoding' feature...
[INFO] Adding 'time_diff' feature...
[INFO] Adding 'timeline_index' feature...
[INFO] Padding ids and storing in `.df_padded` and `.array_padded` attributes.


  0%|          | 0/5568 [00:00<?, ?it/s]

[INFO] The path was created for each item in the dataframe, by looking at its history, so to include embeddings in the FFN input, we concatenate the embeddings for each sentence / text.
saving results dataframe to CSV for this hyperparameter search in rumours_output/seqsignet_attention_umap_focal_2_3_5_26_kfold.csv
saving the best model results dataframe to CSV for this hyperparameter search in rumours_output/seqsignet_attention_umap_focal_2_3_5_26_kfold_best_model.csv


In [78]:
seqsignet_attention_umap_80.groupby(
    [
        "dimensions",
        "output_channels",
        "sig_depth",
        "num_heads",
        "num_layers",
        "ffn_hidden_dim",
        "learning_rate",
    ]
).mean()

/tmp/ipykernel_3911517/1912205705.py:1: FutureWarning: The default value of numeric_only in DataFrameGroupBy.mean is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  seqsignet_attention_umap_80.groupby(


accuracy  \
dimensions output_channels sig_depth num_heads num_layers ffn_hidden_dim learning_rate             
15         8               4         6         1          (256, 256)     0.0001         0.694004   
                                                                         0.0005         0.684126   
                                                                         0.0010         0.678751   
                                                          (512, 512)     0.0001         0.695030   
                                                                         0.0005         0.679031   
                                                                         0.0010         0.685213   
           12              3         10        1          (256, 256)     0.0001         0.683411   
                                                                         0.0005         0.675489   
                                                                         0.0010         0.664803   
                                                          (512, 512)     0.0001         0.684436   
                                                                         0.0005         0.685927   
                                                                         0.0010         0.679466   

                                                                                              f1  \
dimensions output_channels sig_depth num_heads num_layers ffn_hidden_dim learning_rate             
15         8               4         6         1          (256, 256)     0.0001         0.662380   
                                                                         0.0005         0.661457   
                                                                         0.0010         0.653436   
                                                          (512, 512)     0.0001         0.666131   
                                                                         0.0005         0.653858   
                                                                         0.0010         0.655907   
           12              3         10        1          (256, 256)     0.0001         0.657754   
                                                                         0.0005         0.648133   
                                                                         0.0010         0.641075   
                                                          (512, 512)     0.0001         0.657218   
                                                                         0.0005         0.656825   
                                                                         0.0010         0.653525   

                                                                                        precision  \
dimensions output_channels sig_depth num_heads num_layers ffn_hidden_dim learning_rate              
15         8               4         6         1          (256, 256)     0.0001          0.663640   
                                                                         0.0005          0.659741   
                                                                         0.0010          0.652556   
                                                          (512, 512)     0.0001          0.665910   
                                                                         0.0005          0.651846   
                                                                         0.0010          0.656319   
           12              3         10        1          (256, 256)     0.0001          0.655875   
                                                                         0.0005          0.646947   
                                                                         0.0010          0.639239   
                                                          (512, 512)     0.0001          0.656066   
                                                                         0

In [79]:
best_seqsignet_attention_umap_80

loss  accuracy        f1                                 f1_scores  \
0  None  0.672507  0.644976  [0.7438402099431403, 0.5461121157323688]   
0  None  0.681827  0.653257  [0.7527878349022447, 0.5537254901960784]   
0  None  0.668593  0.640692  [0.7408163265306124, 0.5405684754521964]   

   precision                          precision_scores    recall  \
0   0.643420  [0.7567487392465144, 0.5300902708124373]  0.647249   
0   0.652122  [0.7606087211003805, 0.5436344969199178]  0.654662   
0   0.639198    [0.75355871886121, 0.5248369292523833]  0.642885   

                              recall_scores valid_loss  valid_accuracy  ...  \
0  [0.7313646788990825, 0.5631326584976025]       None        0.894191  ...   
0  [0.7451261467889908, 0.5641981885988279]       None        0.884081  ...   
0  [0.7284977064220184, 0.5572722429408631]       None        0.875590  ...   

   learning_rate seed  loss_function gamma  k_fold n_splits  \
0         0.0005    1          focal     2    True        5   
0         0.0005   12          focal     2    True        5   
0         0.0005  123          focal     2    True        5   

   augmentation_type  hidden_dim_aug    comb_method  batch_size  
0             Conv1d            None  concatenation          64  
0             Conv1d            None  concatenation          64  
0             Conv1d            None  concatenation          64  

[3 rows x 47 columns]

In [80]:
best_seqsignet_attention_umap_80[
    [
        "dimensions",
        "output_channels",
        "sig_depth",
        "num_heads",
        "num_layers",
        "ffn_hidden_dim",
        "dropout_rate",
        "learning_rate",
    ]
]

dimensions  output_channels  sig_depth  num_heads  num_layers  \
0          15               12          3         10           1   
0          15               12          3         10           1   
0          15               12          3         10           1   

  ffn_hidden_dim  dropout_rate  learning_rate  
0     (256, 256)           0.1         0.0005  
0     (256, 256)           0.1         0.0005  
0     (256, 256)           0.1         0.0005

In [81]:
best_seqsignet_attention_umap_80["f1"].mean()

0.6463084087927735

In [82]:
best_seqsignet_attention_umap_80["precision"].mean()

0.6449129793654739

In [83]:
best_seqsignet_attention_umap_80["recall"].mean()

0.6482652703578975

In [84]:
np.stack(best_seqsignet_attention_umap_80["f1_scores"]).mean(axis=0)

array([0.74581479, 0.54680203])

In [85]:
np.stack(best_seqsignet_attention_umap_80["precision_scores"]).mean(axis=0)

array([0.75697206, 0.5328539 ])

In [86]:
np.stack(best_seqsignet_attention_umap_80["recall_scores"]).mean(axis=0)

array([0.73499618, 0.56153436])

## Random Projections

In [87]:
(
    seqsignet_attention_grp_80,
    best_seqsignet_attention_grp_80,
    _,
    __,
) = seqsignet_attention_hyperparameter_search(
    shift=shift,
    window_size=window_size,
    n=n,
    dim_reduce_methods=["gaussian_random_projection"],
    results_output=f"{output_dir}/seqsignet_attention_grp_focal_{gamma}_{shift}_{window_size}_{n}_kfold.csv",
    **kwargs,
)

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]


##################################################
dimension: 15 | method: gaussian_random_projection
given shift 3, window size 5 and n 26: history length = 80
[INFO] Concatenating the embeddings to the dataframe...
[INFO] - columns beginning with 'e' denote the full embddings.
[INFO] - columns beginning with 'd' denote the dimension reduced embeddings.
[INFO] Adding time feature columns into dataframe in `.df`.
[INFO] Adding 'time_encoding' feature...
[INFO] Adding 'time_diff' feature...
[INFO] Adding 'timeline_index' feature...
[INFO] Padding ids and storing in `.df_padded` and `.array_padded` attributes.


  0%|          | 0/5568 [00:00<?, ?it/s]

[INFO] The path was created for each item in the dataframe, by looking at its history, so to include embeddings in the FFN input, we concatenate the embeddings for each sentence / text.


  0%|          | 0/2 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/2 [00:00<?, ?it/s]

  0%|          | 0/2 [00:00<?, ?it/s]

  0%|          | 0/3 [00:00<?, ?it/s]

  0%|          | 0/3 [00:00<?, ?it/s]

  0%|          | 0/2 [00:00<?, ?it/s]

  0%|          | 0/3 [00:00<?, ?it/s]

  0%|          | 0/3 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/2 [00:00<?, ?it/s]

  0%|          | 0/2 [00:00<?, ?it/s]

  0%|          | 0/3 [00:00<?, ?it/s]

  0%|          | 0/3 [00:00<?, ?it/s]

  0%|          | 0/2 [00:00<?, ?it/s]

  0%|          | 0/3 [00:00<?, ?it/s]

  0%|          | 0/3 [00:00<?, ?it/s]

given shift 3, window size 5 and n 26: history length = 80
[INFO] Concatenating the embeddings to the dataframe...
[INFO] - columns beginning with 'e' denote the full embddings.
[INFO] - columns beginning with 'd' denote the dimension reduced embeddings.
[INFO] Adding time feature columns into dataframe in `.df`.
[INFO] Adding 'time_encoding' feature...
[INFO] Adding 'time_diff' feature...
[INFO] Adding 'timeline_index' feature...
[INFO] Padding ids and storing in `.df_padded` and `.array_padded` attributes.


  0%|          | 0/5568 [00:00<?, ?it/s]

[INFO] The path was created for each item in the dataframe, by looking at its history, so to include embeddings in the FFN input, we concatenate the embeddings for each sentence / text.
saving results dataframe to CSV for this hyperparameter search in rumours_output/seqsignet_attention_grp_focal_2_3_5_26_kfold.csv
saving the best model results dataframe to CSV for this hyperparameter search in rumours_output/seqsignet_attention_grp_focal_2_3_5_26_kfold_best_model.csv


In [88]:
seqsignet_attention_grp_80.groupby(
    [
        "dimensions",
        "output_channels",
        "sig_depth",
        "num_heads",
        "num_layers",
        "ffn_hidden_dim",
        "dropout_rate",
        "learning_rate",
    ]
).mean()

/tmp/ipykernel_3911517/551400281.py:1: FutureWarning: The default value of numeric_only in DataFrameGroupBy.mean is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  seqsignet_attention_grp_80.groupby(


accuracy  \
dimensions output_channels sig_depth num_heads num_layers ffn_hidden_dim dropout_rate learning_rate             
15         8               4         6         1          (256, 256)     0.1          0.0001         0.682386   
                                                                                      0.0005         0.682572   
                                                                                      0.0010         0.675116   
                                                                         0.2          0.0001         0.672445   
                                                                                      0.0005         0.668406   
                                                                                      0.0010         0.680770   
                                                          (512, 512)     0.1          0.0001         0.673998   
                                                                                      0.0005         0.671761   
                                                                                      0.0010         0.683628   
                                                                         0.2          0.0001         0.669649   
                                                                                      0.0005         0.674744   
                                                                                      0.0010         0.688785   
           12              3         10        1          (256, 256)     0.1          0.0001         0.674185   
                                                                                      0.0005         0.666045   
                                                                                      0.0010         0.659832   
                                                                         0.2          0.0001         0.676235   
                                                                                      0.0005         0.659957   
                                                                                      0.0010         0.676048   
                                                          (512, 512)     0.1          0.0001         0.675924   
                                                                                      0.0005         0.665424   
                                                                                      0.0010         0.675116   
                                                                         0.2          0.0001         0.680770   
                                                                                      0.0005         0.661883   
                                                                                      0.0010         0.679155   

                                                                                                           f1  \
dimensions output_channels sig_depth num_heads num_layers ffn_hidden_dim dropout_rate learning_rate             
15         8               4         6         1          (256, 256)     0.1          0.0001         0.652030   
                                                                                      0.0005         0.652878   
                                                                                      0.0010         0.648029   
                                                                         0.2          0.0001         0.643371   
                                                                                      0.0005         0.640851   
                                                                                      0.0010         0.655313   
                                                          (512, 512)     0.1          0.0001         0.647276   
                                                                                      0.0005         0.649190   
                                

In [89]:
best_seqsignet_attention_grp_80

loss  accuracy        f1                                  f1_scores  \
0  None  0.639888  0.600167  [0.7261904761904763, 0.47414262384322264]   
0  None  0.646598  0.610220  [0.7292975442604226, 0.49114331723027377]   
0  None  0.698975  0.668113   [0.7693186687616055, 0.5669080182354519]   

   precision                           precision_scores    recall  \
0   0.601373  [0.7180493273542601, 0.48469671675013914]  0.599278   
0   0.610628    [0.7263936291240045, 0.494862087614927]  0.609852   
0   0.668658   [0.7665812695701679, 0.5707343412526998]  0.667604   

                               recall_scores valid_loss  valid_accuracy  ...  \
0   [0.7345183486238532, 0.4640383590836441]       None        0.888260  ...   
0  [0.7322247706422018, 0.48748002131060203]       None        0.897830  ...   
0   [0.7720756880733946, 0.5631326584976025]       None        0.889473  ...   

   learning_rate seed  loss_function gamma  k_fold n_splits  \
0         0.0001    1          focal     2    True        5   
0         0.0001   12          focal     2    True        5   
0         0.0001  123          focal     2    True        5   

   augmentation_type  hidden_dim_aug    comb_method  batch_size  
0             Conv1d            None  concatenation          64  
0             Conv1d            None  concatenation          64  
0             Conv1d            None  concatenation          64  

[3 rows x 47 columns]

In [90]:
best_seqsignet_attention_grp_80.columns

Index(['loss', 'accuracy', 'f1', 'f1_scores', 'precision', 'precision_scores',
       'recall', 'recall_scores', 'valid_loss', 'valid_accuracy', 'valid_f1',
       'valid_f1_scores', 'valid_precision', 'valid_precision_scores',
       'valid_recall', 'valid_recall_scores', 'k', 'shift', 'window_size', 'n',
       'dimensions', 'sig_depth', 'method', 'input_channels',
       'output_channels', 'features', 'standardise_method',
       'include_features_in_path', 'include_features_in_input',
       'embedding_dim', 'num_features', 'log_signature', 'num_heads',
       'num_layers', 'lstm_hidden_dim', 'ffn_hidden_dim', 'dropout_rate',
       'learning_rate', 'seed', 'loss_function', 'gamma', 'k_fold', 'n_splits',
       'augmentation_type', 'hidden_dim_aug', 'comb_method', 'batch_size'],
      dtype='object')

In [91]:
best_seqsignet_attention_grp_80[
    [
        "dimensions",
        "output_channels",
        "sig_depth",
        "num_heads",
        "num_layers",
        "ffn_hidden_dim",
        "dropout_rate",
        "learning_rate",
    ]
]

dimensions  output_channels  sig_depth  num_heads  num_layers  \
0          15               12          3         10           1   
0          15               12          3         10           1   
0          15               12          3         10           1   

  ffn_hidden_dim  dropout_rate  learning_rate  
0     (256, 256)           0.1         0.0001  
0     (256, 256)           0.1         0.0001  
0     (256, 256)           0.1         0.0001

In [92]:
best_seqsignet_attention_grp_80["f1"].mean()

0.6261667747535754

In [93]:
best_seqsignet_attention_grp_80["precision"].mean()

0.626886228611033

In [94]:
best_seqsignet_attention_grp_80["recall"].mean()

0.6255783077052164

In [95]:
np.stack(best_seqsignet_attention_grp_80["f1_scores"]).mean(axis=0)

array([0.74160223, 0.51073132])

In [96]:
np.stack(best_seqsignet_attention_grp_80["precision_scores"]).mean(axis=0)

array([0.73700808, 0.51676438])

In [97]:
np.stack(best_seqsignet_attention_grp_80["recall_scores"]).mean(axis=0)

array([0.74627294, 0.50488368])