In [1]:
import numpy as np
import pickle
import os

seed = 2023

In [2]:
import torch

# set device
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [3]:
import transformers

# set to only report critical errors to avoid excessing logging
transformers.utils.logging.set_verbosity(50)

In [4]:
from nlpsig_networks.scripts.fine_tune_bert_classification import (
    fine_tune_transformer_average_seed,
)

In [5]:
output_dir = "rumours_output"
if not os.path.isdir(output_dir):
    os.makedirs(output_dir)

## Rumours

In [6]:
%run load_sbert-embeddings.py

In [7]:
df_rumours.head()

id label            datetime  \
0  5.249902e+17     0 2014-10-22 18:26:23   
1  5.249906e+17     0 2014-10-22 18:27:58   
2  5.249908e+17     1 2014-10-22 18:28:46   
3  5.249927e+17     1 2014-10-22 18:36:29   
4  5.250038e+17     1 2014-10-22 19:20:41   

                                                text timeline_id    set  
0  Police have clarified that there were two shoo...           0  train  
1  @CTVNews you guys "confirmed" there were 3 sho...           0  train  
2      @CTVNews get it right. http://t.co/GHYxMuzPG9           0  train  
3  RT @CTVNews Police have clarified that there w...           0  train  
4  @CTVNews @ctvsaskatoon so what happened at Rid...           0  train

## Baseline: Fine-tine BERT for classification

In [11]:
num_epochs = 10
seeds = [1, 12, 123]
loss = "focal"
gamma = 2
validation_metric = "f1"
split_indices = (df_rumours[df_rumours['set']=='train'].index,
                 df_rumours[df_rumours['set']=='dev'].index,
                 df_rumours[df_rumours['set']=='test'].index)

In [12]:
bert_classifier = fine_tune_transformer_average_seed(
    num_epochs=num_epochs,
    pretrained_model_name="bert-base-uncased",
    df=df_rumours,
    feature_name="text",
    label_column="label",
    seeds=seeds,
    loss=loss,
    gamma=gamma,
    split_indices=split_indices,
    k_fold=False,
    validation_metric=validation_metric,
    results_output=f"{output_dir}/bert_classifier.csv",
    device=device,
    verbose=False
)

Map:   0%|          | 0/5568 [00:00<?, ? examples/s]

Map:   0%|          | 0/5568 [00:00<?, ? examples/s]

/bask/projects/v/vjgo8416-rough-paths/envs/nlpsig-networks/lib/python3.8/site-packages/transformers/optimization.py:411: FutureWarning: This implementation of AdamW is deprecated and will be removed in a future version. Use the PyTorch implementation torch.optim.AdamW instead, or set `no_deprecation_warning=True` to disable this warning
  warnings.warn(


  0%|          | 0/1049 [00:00<?, ?it/s]

Map:   0%|          | 0/5568 [00:00<?, ? examples/s]

Map:   0%|          | 0/5568 [00:00<?, ? examples/s]

/bask/projects/v/vjgo8416-rough-paths/envs/nlpsig-networks/lib/python3.8/site-packages/transformers/optimization.py:411: FutureWarning: This implementation of AdamW is deprecated and will be removed in a future version. Use the PyTorch implementation torch.optim.AdamW instead, or set `no_deprecation_warning=True` to disable this warning
  warnings.warn(


  0%|          | 0/1049 [00:00<?, ?it/s]

Map:   0%|          | 0/5568 [00:00<?, ? examples/s]

Map:   0%|          | 0/5568 [00:00<?, ? examples/s]

/bask/projects/v/vjgo8416-rough-paths/envs/nlpsig-networks/lib/python3.8/site-packages/transformers/optimization.py:411: FutureWarning: This implementation of AdamW is deprecated and will be removed in a future version. Use the PyTorch implementation torch.optim.AdamW instead, or set `no_deprecation_warning=True` to disable this warning
  warnings.warn(


  0%|          | 0/1049 [00:00<?, ?it/s]

saving the results dataframe to CSV in rumours_output/bert_classifier.csv


In [13]:
bert_classifier

accuracy        f1                                    f1_scores  precision  \
0  0.556721  0.553860    [[0.589585172109444, 0.5181347150259067]]   0.554776   
0  0.521449  0.520916      [[0.504930966469428, 0.53690036900369]]   0.524413   
0  0.506196  0.499976  [[0.5557461406518011, 0.44420600858369097]]   0.502144   

                             precision_scores    recall  \
0   [[0.571917808219178, 0.5376344086021505]]  0.554189   
0  [[0.5505376344086022, 0.4982876712328767]]  0.524151   
0  [[0.5251215559157212, 0.4791666666666667]]  0.502082   

                   recall_scores  seed   loss  gamma  k_fold  
0    [[0.6083788706739527, 0.5]]     1  focal      2   False  
0  [[0.4663023679417122, 0.582]]    12  focal      2   False  
0  [[0.5901639344262295, 0.414]]   123  focal      2   False

In [14]:
bert_classifier["f1"].mean()

0.52491722864066

In [15]:
bert_classifier["precision"].mean()

0.5271109575075326

In [16]:
bert_classifier["recall"].mean()

0.5268075288403157

In [17]:
np.stack(bert_classifier["f1_scores"]).mean(axis=0)

array([[0.55008743, 0.49974703]])

In [18]:
np.stack(bert_classifier["precision_scores"]).mean(axis=0)

array([[0.54919233, 0.50502958]])

In [19]:
np.stack(bert_classifier["recall_scores"]).mean(axis=0)

array([[0.55494839, 0.49866667]])

## Using Cross-Entropy loss

In [20]:
loss = "cross_entropy"
gamma = None

In [21]:
bert_classifier_ce = fine_tune_transformer_average_seed(
    num_epochs=num_epochs,
    pretrained_model_name="bert-base-uncased",
    df=df_rumours,
    feature_name="text",
    label_column="label",
    seeds=seeds,
    loss=loss,
    gamma=gamma,
    split_indices=split_indices,
    k_fold=False,
    validation_metric=validation_metric,
    results_output=f"{output_dir}/bert_classifier.csv",
    device=device,
    verbose=False
)

Map:   0%|          | 0/5568 [00:00<?, ? examples/s]

Map:   0%|          | 0/5568 [00:00<?, ? examples/s]

/bask/projects/v/vjgo8416-rough-paths/envs/nlpsig-networks/lib/python3.8/site-packages/transformers/optimization.py:411: FutureWarning: This implementation of AdamW is deprecated and will be removed in a future version. Use the PyTorch implementation torch.optim.AdamW instead, or set `no_deprecation_warning=True` to disable this warning
  warnings.warn(


  0%|          | 0/1049 [00:00<?, ?it/s]

Map:   0%|          | 0/5568 [00:00<?, ? examples/s]

Map:   0%|          | 0/5568 [00:00<?, ? examples/s]

/bask/projects/v/vjgo8416-rough-paths/envs/nlpsig-networks/lib/python3.8/site-packages/transformers/optimization.py:411: FutureWarning: This implementation of AdamW is deprecated and will be removed in a future version. Use the PyTorch implementation torch.optim.AdamW instead, or set `no_deprecation_warning=True` to disable this warning
  warnings.warn(


  0%|          | 0/1049 [00:00<?, ?it/s]

Map:   0%|          | 0/5568 [00:00<?, ? examples/s]

Map:   0%|          | 0/5568 [00:00<?, ? examples/s]

/bask/projects/v/vjgo8416-rough-paths/envs/nlpsig-networks/lib/python3.8/site-packages/transformers/optimization.py:411: FutureWarning: This implementation of AdamW is deprecated and will be removed in a future version. Use the PyTorch implementation torch.optim.AdamW instead, or set `no_deprecation_warning=True` to disable this warning
  warnings.warn(


  0%|          | 0/1049 [00:00<?, ?it/s]

saving the results dataframe to CSV in rumours_output/bert_classifier.csv


In [24]:
bert_classifier_ce

accuracy        f1                                    f1_scores  precision  \
0  0.476644  0.474027  [[0.5111308993766697, 0.43692307692307686]]   0.474211   
0  0.498570  0.457999   [[0.6062874251497007, 0.3097112860892388]]   0.482497   
0  0.516683  0.509144   [[0.4483133841131665, 0.5699745547073791]]   0.525801   

                              precision_scores    recall  \
0                 [[0.5, 0.44842105263157894]]  0.474384   
0  [[0.5146124523506989, 0.45038167938931295]]  0.486852   
0   [[0.5567567567567567, 0.4948453608247423]]  0.523614   

                    recall_scores  seed           loss gamma  k_fold  
0   [[0.5227686703096539, 0.426]]     1  cross_entropy  None   False  
0   [[0.7377049180327869, 0.236]]    12  cross_entropy  None   False  
0  [[0.37522768670309653, 0.672]]   123  cross_entropy  None   False

In [25]:
bert_classifier_ce["f1"].mean()

0.4803901043932053

In [26]:
bert_classifier_ce["precision"].mean()

0.49416955032551496

In [27]:
bert_classifier_ce["recall"].mean()

0.4949502125075895

In [28]:
np.stack(bert_classifier_ce["f1_scores"]).mean(axis=0)

array([[0.52191057, 0.43886964]])

In [29]:
np.stack(bert_classifier_ce["precision_scores"]).mean(axis=0)

array([[0.52378974, 0.46454936]])

In [30]:
np.stack(bert_classifier_ce["recall_scores"]).mean(axis=0)

array([[0.54523376, 0.44466667]])