In [1]:
import pickle
import numpy as np
import pandas as pd
import re
import os

seed = 2023

In [2]:
import torch

# set device
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
device

device(type='cuda')

In [3]:
from nlpsig_networks.scripts.ffn_baseline_functions import (
    histories_baseline_hyperparameter_search,
)

In [4]:
output_dir = "rumours_output"
if not os.path.isdir(output_dir):
    os.makedirs(output_dir)

## Rumours

In [5]:
%run load_sbert_embeddings.py

In [6]:
df_rumours.head()

id label            datetime  \
0  5.249902e+17     0 2014-10-22 18:26:23   
1  5.249906e+17     0 2014-10-22 18:27:58   
2  5.249908e+17     1 2014-10-22 18:28:46   
3  5.249927e+17     1 2014-10-22 18:36:29   
4  5.250038e+17     1 2014-10-22 19:20:41   

                                                text timeline_id    set  
0  Police have clarified that there were two shoo...           0  train  
1  @CTVNews you guys "confirmed" there were 3 sho...           0  train  
2      @CTVNews get it right. http://t.co/GHYxMuzPG9           0  train  
3  RT @CTVNews Police have clarified that there w...           0  train  
4  @CTVNews @ctvsaskatoon so what happened at Rid...           0  train

In [7]:
sbert_embeddings.shape

(5568, 384)

# Baseline: Averaging history and use FFN

Here, we average the full history of a path and concatenate it to the current embedding (the total number of features that are passed into the FFN is 2 * sbert_embeddings.shape[0]).

Here, we will run the hyperparameter search to implement the FFN with the same parameters as the standard FFN baseline on the sentence embeddings.

In [8]:
num_epochs = 100
hidden_dim_sizes = [[64, 64], [128, 128], [256, 256], [512, 512]]
dropout_rates = [0.1]
learning_rates = [1e-3, 5e-4, 1e-4]
seeds = [1, 12, 123]
loss = "focal"
gamma = 2
validation_metric = "f1"
patience = 3

In [9]:
kwargs = {
    "num_epochs": num_epochs,
    "df": df_rumours,
    "id_column": "timeline_id",
    "label_column": "label",
    "embeddings": sbert_embeddings,
    "y_data": y_data,
    "output_dim": output_dim,
    "hidden_dim_sizes": hidden_dim_sizes,
    "dropout_rates": dropout_rates,
    "learning_rates": learning_rates,
    "seeds": seeds,
    "loss": loss,
    "gamma": gamma,
    "device": device,
    "split_ids": split_ids,
    "k_fold": True,
    "patience": patience,
    "validation_metric": validation_metric,
    "verbose": False,
}

In [10]:
(
    ffn_mean_history,
    best_ffn_mean_history,
    _,
    __,
) = histories_baseline_hyperparameter_search(
    use_signatures=False,
    results_output=f"{output_dir}/ffn_mean_history_focal_{gamma}_kfold.csv",
    **kwargs,
)

[INFO] Concatenating the embeddings to the dataframe...
[INFO] - columns beginning with 'e' denote the full embddings.
[INFO] Adding time feature columns into dataframe in `.df`.
[INFO] Adding 'time_encoding' feature...
[INFO] Adding 'time_diff' feature...
[INFO] Adding 'timeline_index' feature...
Computing the mean history for each item in the dataframe


  0%|          | 0/5568 [00:00<?, ?it/s]

  0%|          | 0/4 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/3 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/3 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/3 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/3 [00:00<?, ?it/s]

[INFO] Concatenating the embeddings to the dataframe...
[INFO] - columns beginning with 'e' denote the full embddings.
[INFO] Adding time feature columns into dataframe in `.df`.
[INFO] Adding 'time_encoding' feature...
[INFO] Adding 'time_diff' feature...
[INFO] Adding 'timeline_index' feature...
Computing the mean history for each item in the dataframe


  0%|          | 0/5568 [00:00<?, ?it/s]

saving results dataframe to CSV for this hyperparameter search in rumours_output/ffn_mean_history_focal_2_kfold.csv
saving the best model results dataframe to CSV for this hyperparameter search in rumours_output/ffn_mean_history_focal_2_kfold_best_model.csv


In [11]:
ffn_mean_history

loss  accuracy        f1                                 f1_scores  \
0  None  0.649767  0.617148  [0.7288991487519839, 0.5053961568833903]   
0  None  0.641193  0.614894   [0.715531254617999, 0.5142568761039616]   
0  None  0.631128  0.611565   [0.6987364895722332, 0.524393174717616]   
0  None  0.634669  0.611318  [0.7065868263473053, 0.5160493827160494]   
0  None  0.638024  0.616644  [0.7071773220747889, 0.5261102977061981]   
0  None  0.636533  0.611218   [0.7104247104247103, 0.512012012012012]   
0  None  0.644548  0.614319   [0.7222950342216398, 0.506342221071706]   
0  None  0.638956  0.610250  [0.7160240433953965, 0.5044768482987977]   
0  None  0.643616  0.615657  [0.7193188490898414, 0.5119959162838182]   
0  None  0.648276  0.616244  [0.7271149674620391, 0.5053735255570118]   
0  None  0.641193  0.608792  [0.7213779128672745, 0.4962051818895577]   
0  None  0.649394  0.619231              [0.7264, 0.5120622568093386]   
0  None  0.648649  0.617099  [0.7270094134685011, 0.5071895424836602]   
0  None  0.646039  0.615412  [0.7239424334932403, 0.5068813295247988]   
0  None  0.645853  0.615077  [0.7239174658529497, 0.5062370062370062]   
0  None  0.646412  0.617964  [0.7222140869819885, 0.5137144321968726]   
0  None  0.638770  0.612415  [0.7134831460674157, 0.5113464447806355]   
0  None  0.645853  0.616554  [0.7225467289719627, 0.5105615662029881]   
0  None  0.652190  0.622739  [0.7281468531468531, 0.5173305742369374]   
0  None  0.644734  0.615171  [0.7218330414477526, 0.5085095410005157]   
0  None  0.650140  0.621154  [0.7259453934881004, 0.5163617624323628]   
0  None  0.640261  0.610760  [0.7179187372113417, 0.5036008230452674]   
0  None  0.636160  0.609206    [0.711839385887216, 0.506572295247725]   
0  None  0.645294  0.618329  [0.7197761743484025, 0.5168824574765168]   
0  None  0.645666  0.615095  [0.7235713247055402, 0.5066182195691669]   
0  None  0.647717  0.618657  [0.7239263803680982, 0.5133882595262615]   
0  None  0.646412  0.617542  [0.7226202661207778, 0.5124646620406065]   
0  None  0.664678  0.639341  [0.7349344334757625, 0.5437484149125033]   
0  None  0.657782  0.620724  [0.7392786140301051, 0.5021691973969631]   
0  None  0.650885  0.622214  [0.7262896390472015, 0.5181373810136352]   
0  None  0.652936  0.630680   [0.721340915893445, 0.5400197628458497]   
0  None  0.651258  0.621082  [0.7280127925570578, 0.5141521682679823]   
0  None  0.653681  0.622979  [0.7305684454756382, 0.5153886280646844]   
0  None  0.647157  0.619928    [0.721658579620644, 0.518198014762026]   
0  None  0.643989  0.619961   [0.7155198093535896, 0.524402390438247]   
0  None  0.652563  0.620877  [0.7304800462695199, 0.5112742527530153]   

   precision                           precision_scores    recall  \
0   0.616571   [0.7336625036305547, 0.4994797086368366]  0.617826   
0   0.613415   [0.7383348581884721, 0.4884947267497603]  0.618491   
0   0.611279    [0.744888023369036, 0.4776707530647986]  0.619608   
0   0.610125   [0.7393483709273183, 0.4809019788311091]  0.616672   
0   0.615616   [0.7458651399491094, 0.4853669518235029]  0.623313   
0   0.609841   [0.7369069624152803, 0.4827748938178386]  0.615399   
0   0.613196  [0.7339449541284404, 0.49244712990936557]  0.616027   
0   0.608955  [0.7326732673267327, 0.48523622047244097]  0.612711   
0   0.614245   [0.737063778580024, 0.49142577168054874]  0.618386   
0   0.615503  [0.7335862270207179, 0.49742002063983487]  0.617171   
0   0.608048   [0.7284419760304005, 0.4876543209876543]  0.609755   
0   0.618110  [0.7372305875405964, 0.49898887765419614]  0.620861   
0   0.616255  [0.7345624817091015, 0.49794661190965095]  0.618196   
0   0.614362  [0.7342966676496608, 0.49442755825734547]  0.616927   
0   0.614054   [0.7339422510312316, 0.4941653982749873]  0.616538   
0   0.616581   [0.7381023645615086, 0.4950592885375494]  0.620413   
0   0.610984  [0.7365689865689866, 0.48539971278123506]  0.616012   
0   0.615287   [0.7363095238095239, 0.4942643391521197]  0.

In [12]:
best_ffn_mean_history

loss  accuracy        f1                                 f1_scores  \
0  None  0.652936  0.630680   [0.721340915893445, 0.5400197628458497]   
0  None  0.651258  0.621082  [0.7280127925570578, 0.5141521682679823]   
0  None  0.653681  0.622979  [0.7305684454756382, 0.5153886280646844]   

   precision                          precision_scores    recall  \
0   0.628997   [0.754539762053851, 0.5034546292031322]  0.636626   
0   0.619973  [0.7384252432910646, 0.5015197568389058]  0.622664   
0   0.621999  [0.7391431924882629, 0.5048543689320388]  0.624281   

                              recall_scores valid_loss  valid_accuracy  ...  \
0   [0.6909403669724771, 0.582312200319659]       None        0.790538  ...   
0   [0.7178899082568807, 0.527437400106553]       None        0.792829  ...   
0  [0.7221903669724771, 0.5263718700053277]       None        0.788651  ...   

   hidden_dim dropout_rate  learning_rate seed  loss_function gamma k_fold  \
0  (512, 512)          0.1         0.0005    1          focal     2   True   
0  (512, 512)          0.1         0.0005   12          focal     2   True   
0  (512, 512)          0.1         0.0005  123          focal     2   True   

   n_splits  batch_size  input_dim  
0         5          64        768  
0         5          64        768  
0         5          64        768  

[3 rows x 26 columns]

In [13]:
best_ffn_mean_history["f1"].mean()

0.6249137855174428

In [14]:
best_ffn_mean_history["precision"].mean()

0.6236561588012092

In [15]:
best_ffn_mean_history["recall"].mean()

0.6278570187722291

In [16]:
np.stack(best_ffn_mean_history["f1_scores"]).mean(axis=0)

array([0.72664072, 0.52318685])

In [17]:
np.stack(best_ffn_mean_history["precision_scores"]).mean(axis=0)

array([0.74403607, 0.50327625])

In [18]:
np.stack(best_ffn_mean_history["recall_scores"]).mean(axis=0)

array([0.71034021, 0.54537382])