In [1]:
import numpy as np
import pickle
import os

seed = 2023

In [2]:
import torch

# set device
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
device

device(type='cuda')

In [3]:
from nlpsig_networks.scripts.seqsignet_attention_functions import (
    seqsignet_attention_hyperparameter_search,
)

In [4]:
output_dir = "rumours_output"
if not os.path.isdir(output_dir):
    os.makedirs(output_dir)

## Rumours

In [5]:
%run load_sbert-embeddings.py

In [6]:
df_rumours.head()

id label            datetime  \
0  5.249902e+17     0 2014-10-22 18:26:23   
1  5.249906e+17     0 2014-10-22 18:27:58   
2  5.249908e+17     1 2014-10-22 18:28:46   
3  5.249927e+17     1 2014-10-22 18:36:29   
4  5.250038e+17     1 2014-10-22 19:20:41   

                                                text timeline_id    set  
0  Police have clarified that there were two shoo...           0  train  
1  @CTVNews you guys "confirmed" there were 3 sho...           0  train  
2      @CTVNews get it right. http://t.co/GHYxMuzPG9           0  train  
3  RT @CTVNews Police have clarified that there w...           0  train  
4  @CTVNews @ctvsaskatoon so what happened at Rid...           0  train

# SeqSigNet with Attention Network

In [7]:
features = ["time_encoding", "timeline_index"]
standardise_method = ["z_score", None]
num_features = len(features)
include_features_in_path = True

In [8]:
num_epochs = 100
dimensions = [15]  # [50, 15]
# define swmhau parameters: (output_channels, sig_depth, num_heads)
swmhau_parameters = [(12, 3, 10), (8, 4, 6), (8, 4, 12)]
num_layers = [1]
ffn_hidden_dim_sizes = [[128,128],[256,256],[512,512]]
dropout_rates = [0.5, 0.1]
learning_rates = [1e-3, 1e-4, 5e-4]
seeds = [1, 12, 123]
loss = "focal"
gamma = 2
validation_metric = "f1"
patience = 5
split_indices = (
    df_rumours[df_rumours["set"] == "train"].index,
    df_rumours[df_rumours["set"] == "dev"].index,
    df_rumours[df_rumours["set"] == "test"].index,
)

In [9]:
shift = 3
window_size = 5
n = 11

In [10]:
size = shift * n + (window_size - shift)
print(size)

35


## UMAP

In [11]:
(
    seqsignet_attention_umap,
    best_seqsignet_attention_umap,
    _,
    __,
) = seqsignet_attention_hyperparameter_search(
    num_epochs=num_epochs,
    df=df_rumours,
    id_column="timeline_id",
    label_column="label",
    embeddings=sbert_embeddings,
    y_data=y_data,
    output_dim=output_dim,
    shift=shift,
    window_size=window_size,
    n=n,
    dim_reduce_methods=["umap"],
    dimensions=dimensions,
    log_signature=True,
    swmhau_parameters=swmhau_parameters,
    num_layers=num_layers,
    ffn_hidden_dim_sizes=ffn_hidden_dim_sizes,
    dropout_rates=dropout_rates,
    learning_rates=learning_rates,
    seeds=seeds,
    loss=loss,
    gamma=gamma,
    device=device,
    split_indices=split_indices,
    k_fold=False,
    features=features,
    standardise_method=standardise_method,
    include_features_in_path=include_features_in_path,
    patience=patience,
    validation_metric=validation_metric,
    results_output=f"{output_dir}/seqsignet_attention_umap_focal_{gamma}_{size}.csv",
    verbose=False,
)

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]


##################################################
dimension: 15 | method: umap
given shift 3, window size 5 and n 11: history length = 35
[INFO] Concatenating the embeddings to the dataframe...
[INFO] - columns beginning with 'e' denote the full embddings.
[INFO] - columns beginning with 'd' denote the dimension reduced embeddings.
[INFO] Adding time feature columns into dataframe in `.df`.
[INFO] Adding 'time_encoding' feature...
[INFO] Adding 'time_diff' feature...
[INFO] Adding 'timeline_index' feature...
[INFO] Padding ids and storing in `.df_padded` and `.array_padded` attributes.


  0%|          | 0/5568 [00:00<?, ?it/s]

[INFO] The path was created for each item in the dataframe, by looking at its history, so to include embeddings in the FFN input, we concatenate the embeddings for each sentence / text.


  0%|          | 0/3 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/2 [00:00<?, ?it/s]

  0%|          | 0/2 [00:00<?, ?it/s]

  0%|          | 0/3 [00:00<?, ?it/s]

  0%|          | 0/3 [00:00<?, ?it/s]

  0%|          | 0/2 [00:00<?, ?it/s]

  0%|          | 0/3 [00:00<?, ?it/s]

  0%|          | 0/3 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/2 [00:00<?, ?it/s]

  0%|          | 0/2 [00:00<?, ?it/s]

  0%|          | 0/3 [00:00<?, ?it/s]

  0%|          | 0/3 [00:00<?, ?it/s]

  0%|          | 0/2 [00:00<?, ?it/s]

  0%|          | 0/3 [00:00<?, ?it/s]

  0%|          | 0/3 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/2 [00:00<?, ?it/s]

  0%|          | 0/2 [00:00<?, ?it/s]

  0%|          | 0/3 [00:00<?, ?it/s]

  0%|          | 0/3 [00:00<?, ?it/s]

  0%|          | 0/2 [00:00<?, ?it/s]

  0%|          | 0/3 [00:00<?, ?it/s]

  0%|          | 0/3 [00:00<?, ?it/s]

given shift 3, window size 5 and n 11: history length = 35
[INFO] Concatenating the embeddings to the dataframe...
[INFO] - columns beginning with 'e' denote the full embddings.
[INFO] - columns beginning with 'd' denote the dimension reduced embeddings.
[INFO] Adding time feature columns into dataframe in `.df`.
[INFO] Adding 'time_encoding' feature...
[INFO] Adding 'time_diff' feature...
[INFO] Adding 'timeline_index' feature...
[INFO] Padding ids and storing in `.df_padded` and `.array_padded` attributes.


  0%|          | 0/5568 [00:00<?, ?it/s]

[INFO] The path was created for each item in the dataframe, by looking at its history, so to include embeddings in the FFN input, we concatenate the embeddings for each sentence / text.
saving results dataframe to CSV for this hyperparameter search in rumours_output/seqsignet_attention_umap_focal_2_35.csv
saving the best model results dataframe to CSV for this hyperparameter search in rumours_output/seqsignet_attention_umap_focal_2_35_best_model.csv


In [12]:
seqsignet_attention_umap.groupby(
    [
        "dimensions",
        "output_channels",
        "sig_depth",
        "num_heads",
        "num_layers",
        "ffn_hidden_dim",
        "learning_rate",
    ]
).mean()

/tmp/ipykernel_519152/3847072948.py:1: FutureWarning: The default value of numeric_only in DataFrameGroupBy.mean is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  seqsignet_attention_umap.groupby(


loss  \
dimensions output_channels sig_depth num_heads num_layers ffn_hidden_dim learning_rate             
15         8               4         6         1          (256, 256)     0.0001         0.418705   
                                                                         0.0005         0.353103   
                                                                         0.0010         0.336937   
                                                          (512, 512)     0.0001         0.470357   
                                                                         0.0005         0.352802   
                                                                         0.0010         0.343080   
                                     12        1          (256, 256)     0.0001         0.381671   
                                                                         0.0005         0.326523   
                                                                         0.0010         0.337578   
                                                          (512, 512)     0.0001         0.464128   
                                                                         0.0005         0.354064   
                                                                         0.0010         0.336547   
           12              3         10        1          (256, 256)     0.0001         0.620801   
                                                                         0.0005         0.438846   
                                                                         0.0010         0.330509   
                                                          (512, 512)     0.0001         0.680124   
                                                                         0.0005         0.674209   
                                                                         0.0010         0.331050   

                                                                                        accuracy  \
dimensions output_channels sig_depth num_heads num_layers ffn_hidden_dim learning_rate             
15         8               4         6         1          (256, 256)     0.0001         0.602002   
                                                                         0.0005         0.603114   
                                                                         0.0010         0.606927   
                                                          (512, 512)     0.0001         0.599460   
                                                                         0.0005         0.616301   
                                                                         0.0010         0.614395   
                                     12        1          (256, 256)     0.0001         0.594535   
                                                                         0.0005         0.608993   
                                                                         0.0010         0.605497   
                                                          (512, 512)     0.0001         0.593105   
                                                                         0.0005         0.603750   
                                                                         0.0010         0.610264   
           12              3         10        1          (256, 256)     0.0001         0.593581   
                                                                         0.0005         0.567525   
                                                                         0.0010         0.608198   
                                                          (512, 512)     0.0001         0.581506   
                                                                         0.0005         0.590086   
                                                                         0.0010         0.596918   

                                                                                          

In [13]:
best_seqsignet_attention_umap

loss  accuracy        f1                                 f1_scores  \
0  0.354865  0.630124  0.629612  [0.6158415841584158, 0.6433823529411765]   
0  0.297248  0.623451  0.621669  [0.5957011258955988, 0.6476360392506691]   
0  0.420033  0.578646  0.576920    [0.54989816700611, 0.6039426523297491]   

   precision                          precision_scores    recall  \
0   0.634929  [0.6746203904555315, 0.5952380952380952]  0.633242   
0   0.632224  [0.6799065420560748, 0.5845410628019324]  0.628027   
0   0.585317   [0.6235565819861432, 0.547077922077922]  0.582902   

                 recall_scores  valid_loss  valid_accuracy  ...  \
0    [0.5664845173041895, 0.7]    0.450242        0.612100  ...   
0  [0.5300546448087432, 0.726]    0.216798        0.637011  ...   
0  [0.4918032786885246, 0.674]    0.255187        0.683274  ...   

   learning_rate seed  loss_function gamma  k_fold n_splits  \
0         0.0005    1          focal     2   False     None   
0         0.0005   12          focal     2   False     None   
0         0.0005  123          focal     2   False     None   

   augmentation_type  hidden_dim_aug    comb_method  batch_size  
0             Conv1d            None  concatenation          64  
0             Conv1d            None  concatenation          64  
0             Conv1d            None  concatenation          64  

[3 rows x 45 columns]

In [14]:
best_seqsignet_attention_umap[
    [
        "dimensions",
        "output_channels",
        "sig_depth",
        "num_heads",
        "num_layers",
        "ffn_hidden_dim",
        "dropout_rate",
        "learning_rate",
    ]
]

dimensions  output_channels  sig_depth  num_heads  num_layers  \
0          15               12          3         10           1   
0          15               12          3         10           1   
0          15               12          3         10           1   

  ffn_hidden_dim  dropout_rate  learning_rate  
0     (256, 256)           0.5         0.0005  
0     (256, 256)           0.5         0.0005  
0     (256, 256)           0.5         0.0005

In [15]:
best_seqsignet_attention_umap["f1"].mean()

0.6094003202636199

In [16]:
best_seqsignet_attention_umap["precision"].mean()

0.6174900991026165

In [17]:
best_seqsignet_attention_umap["recall"].mean()

0.6147237401335762

In [18]:
np.stack(best_seqsignet_attention_umap["f1_scores"]).mean(axis=0)

array([0.58714696, 0.63165368])

In [19]:
np.stack(best_seqsignet_attention_umap["precision_scores"]).mean(axis=0)

array([0.65936117, 0.57561903])

In [20]:
np.stack(best_seqsignet_attention_umap["recall_scores"]).mean(axis=0)

array([0.52944748, 0.7       ])

## Random Projections

In [21]:
(
    seqsignet_attention_grp,
    best_seqsignet_attention_grp,
    _,
    __,
) = seqsignet_attention_hyperparameter_search(
    num_epochs=num_epochs,
    df=df_rumours,
    id_column="timeline_id",
    label_column="label",
    embeddings=sbert_embeddings,
    y_data=y_data,
    output_dim=output_dim,
    shift=shift,
    window_size=window_size,
    n=n,
    dim_reduce_methods=["gaussian_random_projection"],
    dimensions=dimensions,
    log_signature=True,
    swmhau_parameters=swmhau_parameters,
    num_layers=num_layers,
    ffn_hidden_dim_sizes=ffn_hidden_dim_sizes,
    dropout_rates=dropout_rates,
    learning_rates=learning_rates,
    seeds=seeds,
    loss=loss,
    gamma=gamma,
    device=device,
    split_indices=split_indices,
    k_fold=False,
    features=features,
    standardise_method=standardise_method,
    include_features_in_path=include_features_in_path,
    patience=patience,
    validation_metric=validation_metric,
    results_output=f"{output_dir}/seqsignet_attention_grp_focal_{gamma}_{size}.csv",
    verbose=False,
)

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]


##################################################
dimension: 15 | method: gaussian_random_projection
given shift 3, window size 5 and n 11: history length = 35
[INFO] Concatenating the embeddings to the dataframe...
[INFO] - columns beginning with 'e' denote the full embddings.
[INFO] - columns beginning with 'd' denote the dimension reduced embeddings.
[INFO] Adding time feature columns into dataframe in `.df`.
[INFO] Adding 'time_encoding' feature...
[INFO] Adding 'time_diff' feature...
[INFO] Adding 'timeline_index' feature...
[INFO] Padding ids and storing in `.df_padded` and `.array_padded` attributes.


  0%|          | 0/5568 [00:00<?, ?it/s]

[INFO] The path was created for each item in the dataframe, by looking at its history, so to include embeddings in the FFN input, we concatenate the embeddings for each sentence / text.


  0%|          | 0/3 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/2 [00:00<?, ?it/s]

  0%|          | 0/2 [00:00<?, ?it/s]

  0%|          | 0/3 [00:00<?, ?it/s]

  0%|          | 0/3 [00:00<?, ?it/s]

  0%|          | 0/2 [00:00<?, ?it/s]

  0%|          | 0/3 [00:00<?, ?it/s]

  0%|          | 0/3 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/2 [00:00<?, ?it/s]

  0%|          | 0/2 [00:00<?, ?it/s]

  0%|          | 0/3 [00:00<?, ?it/s]

  0%|          | 0/3 [00:00<?, ?it/s]

  0%|          | 0/2 [00:00<?, ?it/s]

  0%|          | 0/3 [00:00<?, ?it/s]

  0%|          | 0/3 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/2 [00:00<?, ?it/s]

  0%|          | 0/2 [00:00<?, ?it/s]

  0%|          | 0/3 [00:00<?, ?it/s]

  0%|          | 0/3 [00:00<?, ?it/s]

  0%|          | 0/2 [00:00<?, ?it/s]

  0%|          | 0/3 [00:00<?, ?it/s]

  0%|          | 0/3 [00:00<?, ?it/s]

given shift 3, window size 5 and n 11: history length = 35
[INFO] Concatenating the embeddings to the dataframe...
[INFO] - columns beginning with 'e' denote the full embddings.
[INFO] - columns beginning with 'd' denote the dimension reduced embeddings.
[INFO] Adding time feature columns into dataframe in `.df`.
[INFO] Adding 'time_encoding' feature...
[INFO] Adding 'time_diff' feature...
[INFO] Adding 'timeline_index' feature...
[INFO] Padding ids and storing in `.df_padded` and `.array_padded` attributes.


  0%|          | 0/5568 [00:00<?, ?it/s]

[INFO] The path was created for each item in the dataframe, by looking at its history, so to include embeddings in the FFN input, we concatenate the embeddings for each sentence / text.
saving results dataframe to CSV for this hyperparameter search in rumours_output/seqsignet_attention_grp_focal_2_35.csv
saving the best model results dataframe to CSV for this hyperparameter search in rumours_output/seqsignet_attention_grp_focal_2_35_best_model.csv


In [22]:
seqsignet_attention_grp.groupby(
    [
        "dimensions",
        "output_channels",
        "sig_depth",
        "num_heads",
        "num_layers",
        "ffn_hidden_dim",
        "dropout_rate",
        "learning_rate",
    ]
).mean()

/tmp/ipykernel_519152/961439154.py:1: FutureWarning: The default value of numeric_only in DataFrameGroupBy.mean is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  seqsignet_attention_grp.groupby(


loss  \
dimensions output_channels sig_depth num_heads num_layers ffn_hidden_dim dropout_rate learning_rate             
15         8               4         6         1          (256, 256)     0.1          0.0001         0.486526   
                                                                                      0.0005         0.420749   
                                                                                      0.0010         0.343218   
                                                                         0.5          0.0001         0.486561   
                                                                                      0.0005         0.331707   
                                                                                      0.0010         0.318694   
                                                          (512, 512)     0.1          0.0001         0.450419   
                                                                                      0.0005         0.458702   
                                                                                      0.0010         0.357181   
                                                                         0.5          0.0001         0.426305   
                                                                                      0.0005         0.354491   
                                                                                      0.0010         0.472991   
                                     12        1          (256, 256)     0.1          0.0001         0.494773   
                                                                                      0.0005         0.323319   
                                                                                      0.0010         0.338316   
                                                                         0.5          0.0001         0.397339   
                                                                                      0.0005         0.348756   
                                                                                      0.0010         0.340740   
                                                          (512, 512)     0.1          0.0001         0.470996   
                                                                                      0.0005         0.359515   
                                                                                      0.0010         0.334031   
                                                                         0.5          0.0001         0.441502   
                                                                                      0.0005         0.374429   
                                                                                      0.0010         0.352024   
           12              3         10        1          (256, 256)     0.1          0.0001         0.615440   
                                                                                      0.0005         0.545368   
                                                                                      0.0010         0.331637   
                                                                         0.5          0.0001         0.409425   
                                                                                      0.0005         0.467239   
                                                                                      0.0010         0.382688   
                                                          (512, 512)     0.1          0.0001         0.553872   
                                                                                      0.0005         0.387684   
                                                                                      0.0010         0.445581   
                                                                         0.5          0.0001         0.852055   
                                     

In [23]:
best_seqsignet_attention_grp

loss  accuracy        f1                                 f1_scores  \
0  0.404750  0.616778  0.612116   [0.5695931477516061, 0.654639175257732]   
0  0.717734  0.569113  0.568687  [0.5551181102362205, 0.5822550831792975]   
0  0.584507  0.549094  0.547078  [0.5168539325842696, 0.5773011617515639]   

   precision                          precision_scores    recall  \
0   0.632352  [0.6909090909090909, 0.5737951807228916]  0.623259   
0   0.572546  [0.6038543897216274, 0.5412371134020618]  0.571831   
0   0.555091  [0.5883720930232558, 0.5218093699515347]  0.553419   

                  recall_scores  valid_loss  valid_accuracy  ...  \
0  [0.48451730418943534, 0.762]    0.238608        0.608541  ...   
0    [0.5136612021857924, 0.63]    0.438306        0.729537  ...   
0  [0.46083788706739526, 0.646]    0.257459        0.701068  ...   

   learning_rate seed  loss_function gamma  k_fold n_splits  \
0         0.0001    1          focal     2   False     None   
0         0.0001   12          focal     2   False     None   
0         0.0001  123          focal     2   False     None   

   augmentation_type  hidden_dim_aug    comb_method  batch_size  
0             Conv1d            None  concatenation          64  
0             Conv1d            None  concatenation          64  
0             Conv1d            None  concatenation          64  

[3 rows x 45 columns]

In [24]:
best_seqsignet_attention_grp.columns

Index(['loss', 'accuracy', 'f1', 'f1_scores', 'precision', 'precision_scores',
       'recall', 'recall_scores', 'valid_loss', 'valid_accuracy', 'valid_f1',
       'valid_f1_scores', 'valid_precision', 'valid_precision_scores',
       'valid_recall', 'valid_recall_scores', 'k', 'shift', 'window_size', 'n',
       'dimensions', 'sig_depth', 'method', 'input_channels',
       'output_channels', 'features', 'standardise_method',
       'include_features_in_path', 'embedding_dim', 'num_features',
       'log_signature', 'num_heads', 'num_layers', 'ffn_hidden_dim',
       'dropout_rate', 'learning_rate', 'seed', 'loss_function', 'gamma',
       'k_fold', 'n_splits', 'augmentation_type', 'hidden_dim_aug',
       'comb_method', 'batch_size'],
      dtype='object')

In [25]:
best_seqsignet_attention_grp[
    [
        "dimensions",
        "output_channels",
        "sig_depth",
        "num_heads",
        "num_layers",
        "ffn_hidden_dim",
        "dropout_rate",
        "learning_rate",
    ]
]

dimensions  output_channels  sig_depth  num_heads  num_layers  \
0          15                8          4          6           1   
0          15                8          4          6           1   
0          15                8          4          6           1   

  ffn_hidden_dim  dropout_rate  learning_rate  
0     (256, 256)           0.1         0.0001  
0     (256, 256)           0.1         0.0001  
0     (256, 256)           0.1         0.0001

In [26]:
best_seqsignet_attention_grp["f1"].mean()

0.5759601017934483

In [27]:
best_seqsignet_attention_grp["precision"].mean()

0.586662872955077

In [28]:
best_seqsignet_attention_grp["recall"].mean()

0.5828360655737704

In [29]:
np.stack(best_seqsignet_attention_grp["f1_scores"]).mean(axis=0)

array([0.5471884 , 0.60473181])

In [30]:
np.stack(best_seqsignet_attention_grp["precision_scores"]).mean(axis=0)

array([0.62771186, 0.54561389])

In [31]:
np.stack(best_seqsignet_attention_grp["recall_scores"]).mean(axis=0)

array([0.4863388 , 0.67933333])