In [1]:
import numpy as np
import pickle
import os

seed = 2023

In [2]:
import torch

# set device
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
device

device(type='cuda')

In [3]:
from nlpsig_networks.scripts.seqsignet_attention_bilstm_functions import (
    seqsignet_attention_bilstm_hyperparameter_search,
)

In [4]:
output_dir = "rumours_output"
if not os.path.isdir(output_dir):
    os.makedirs(output_dir)

## Rumours

In [5]:
%run load_sbert_embeddings.py

In [6]:
df_rumours.head()

id label            datetime  \
0  5.249902e+17     0 2014-10-22 18:26:23   
1  5.249906e+17     0 2014-10-22 18:27:58   
2  5.249908e+17     1 2014-10-22 18:28:46   
3  5.249927e+17     1 2014-10-22 18:36:29   
4  5.250038e+17     1 2014-10-22 19:20:41   

                                                text timeline_id    set  
0  Police have clarified that there were two shoo...           0  train  
1  @CTVNews you guys "confirmed" there were 3 sho...           0  train  
2      @CTVNews get it right. http://t.co/GHYxMuzPG9           0  train  
3  RT @CTVNews Police have clarified that there w...           0  train  
4  @CTVNews @ctvsaskatoon so what happened at Rid...           0  train

# SeqSigNet with Attention Network

In [7]:
features = ["time_encoding", "timeline_index"]
standardise_method = ["z_score", None]
include_features_in_path = True
include_features_in_input = True

In [8]:
num_epochs = 100
dimensions = [15]
# define swmhau parameters: (output_channels, sig_depth, num_heads)
swmhau_parameters = [(12, 3, 10), (8, 4, 6)]
num_layers = [1]
lstm_hidden_dim_sizes = [384]
ffn_hidden_dim_sizes = [[256, 256], [512, 512]]
dropout_rates = [0.1, 0.2]
learning_rates = [1e-3, 1e-4, 5e-4]
seeds = [1, 12, 123]
loss = "focal"
gamma = 2
validation_metric = "f1"
patience = 5

In [9]:
kwargs = {
    "num_epochs": num_epochs,
    "df": df_rumours,
    "id_column": "timeline_id",
    "label_column": "label",
    "embeddings": sbert_embeddings,
    "y_data": y_data,
    "output_dim": output_dim,
    "dimensions": dimensions,
    "log_signature": True,
    "pooling": "signature",
    "swmhau_parameters": swmhau_parameters,
    "num_layers": num_layers,
    "lstm_hidden_dim_sizes": lstm_hidden_dim_sizes,
    "ffn_hidden_dim_sizes": ffn_hidden_dim_sizes,
    "dropout_rates": dropout_rates,
    "learning_rates": learning_rates,
    "seeds": seeds,
    "loss": loss,
    "gamma": gamma,
    "device": device,
    "features": features,
    "standardise_method": standardise_method,
    "include_features_in_path": include_features_in_path,
    "include_features_in_input": include_features_in_input,
    "split_ids": split_ids,
    "k_fold": True,
    "patience": patience,
    "validation_metric": validation_metric,
    "verbose": False,
}

# history_length=11

In [10]:
shift = 3
window_size = 5
n = 3

## Random Projections

In [11]:
(
    seqsignet_attention_bilstm_grp_11,
    best_seqsignet_attention_bilstm_grp_11,
    _,
    __,
) = seqsignet_attention_bilstm_hyperparameter_search(
    shift=shift,
    window_size=window_size,
    n=n,
    dim_reduce_methods=["gaussian_random_projection"],
    results_output=f"{output_dir}/seqsignet_attention_bilstm_grp_focal_{gamma}_{shift}_{window_size}_{n}_kfold.csv",
    **kwargs,
)

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]


##################################################
dimension: 15 | method: gaussian_random_projection
given shift 3, window size 5 and n 3: history length = 11
[INFO] Concatenating the embeddings to the dataframe...
[INFO] - columns beginning with 'e' denote the full embddings.
[INFO] - columns beginning with 'd' denote the dimension reduced embeddings.
[INFO] Adding time feature columns into dataframe in `.df`.
[INFO] Adding 'time_encoding' feature...
[INFO] Adding 'time_diff' feature...
[INFO] Adding 'timeline_index' feature...
[INFO] Padding ids and storing in `.df_padded` and `.array_padded` attributes.


  0%|          | 0/5568 [00:00<?, ?it/s]

[INFO] The path was created for each item in the dataframe, by looking at its history, so to include embeddings in the FFN input, we concatenate the embeddings for each sentence / text.


  0%|          | 0/2 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/2 [00:00<?, ?it/s]

  0%|          | 0/2 [00:00<?, ?it/s]

  0%|          | 0/3 [00:00<?, ?it/s]

  0%|          | 0/3 [00:00<?, ?it/s]

  0%|          | 0/2 [00:00<?, ?it/s]

  0%|          | 0/3 [00:00<?, ?it/s]

  0%|          | 0/3 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/2 [00:00<?, ?it/s]

  0%|          | 0/2 [00:00<?, ?it/s]

  0%|          | 0/3 [00:00<?, ?it/s]

  0%|          | 0/3 [00:00<?, ?it/s]

  0%|          | 0/2 [00:00<?, ?it/s]

  0%|          | 0/3 [00:00<?, ?it/s]

  0%|          | 0/3 [00:00<?, ?it/s]

given shift 3, window size 5 and n 3: history length = 11
[INFO] Concatenating the embeddings to the dataframe...
[INFO] - columns beginning with 'e' denote the full embddings.
[INFO] - columns beginning with 'd' denote the dimension reduced embeddings.
[INFO] Adding time feature columns into dataframe in `.df`.
[INFO] Adding 'time_encoding' feature...
[INFO] Adding 'time_diff' feature...
[INFO] Adding 'timeline_index' feature...
[INFO] Padding ids and storing in `.df_padded` and `.array_padded` attributes.


  0%|          | 0/5568 [00:00<?, ?it/s]

[INFO] The path was created for each item in the dataframe, by looking at its history, so to include embeddings in the FFN input, we concatenate the embeddings for each sentence / text.
saving results dataframe to CSV for this hyperparameter search in rumours_output/seqsignet_attention_bilstm_grp_focal_2_3_5_3_kfold.csv
saving the best model results dataframe to CSV for this hyperparameter search in rumours_output/seqsignet_attention_bilstm_grp_focal_2_3_5_3_kfold_best_model.csv


In [12]:
seqsignet_attention_bilstm_grp_11.groupby(
    [
        "dimensions",
        "output_channels",
        "sig_depth",
        "num_heads",
        "num_layers",
        "ffn_hidden_dim",
        "dropout_rate",
        "learning_rate",
    ]
).mean()

/tmp/ipykernel_1375213/639134925.py:1: FutureWarning: The default value of numeric_only in DataFrameGroupBy.mean is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  seqsignet_attention_bilstm_grp_11.groupby(


accuracy  \
dimensions output_channels sig_depth num_heads num_layers ffn_hidden_dim dropout_rate learning_rate             
15         8               4         6         1          (256, 256)     0.1          0.0001         0.668903   
                                                                                      0.0005         0.686424   
                                                                                      0.0010         0.679652   
                                                                         0.2          0.0001         0.684871   
                                                                                      0.0005         0.654116   
                                                                                      0.0010         0.678969   
                                                          (512, 512)     0.1          0.0001         0.678347   
                                                                                      0.0005         0.680211   
                                                                                      0.0010         0.673936   
                                                                         0.2          0.0001         0.682075   
                                                                                      0.0005         0.668158   
                                                                                      0.0010         0.681516   
           12              3         10        1          (256, 256)     0.1          0.0001         0.682324   
                                                                                      0.0005         0.693569   
                                                                                      0.0010         0.689158   
                                                                         0.2          0.0001         0.685617   
                                                                                      0.0005         0.681205   
                                                                                      0.0010         0.679031   
                                                          (512, 512)     0.1          0.0001         0.688040   
                                                                                      0.0005         0.689158   
                                                                                      0.0010         0.689966   
                                                                         0.2          0.0001         0.684374   
                                                                                      0.0005         0.676608   
                                                                                      0.0010         0.684871   

                                                                                                           f1  \
dimensions output_channels sig_depth num_heads num_layers ffn_hidden_dim dropout_rate learning_rate             
15         8               4         6         1          (256, 256)     0.1          0.0001         0.654774   
                                                                                      0.0005         0.668101   
                                                                                      0.0010         0.663236   
                                                                         0.2          0.0001         0.670266   
                                                                                      0.0005         0.647928   
                                                                                      0.0010         0.661261   
                                                          (512, 512)     0.1          0.0001         0.663460   
                                                                                      0.0005         0.666013   
                                

In [13]:
best_seqsignet_attention_bilstm_grp_11

loss  accuracy        f1                                 f1_scores  \
0  None  0.688537  0.671317  [0.7465493705445169, 0.5960841189267585]   
0  None  0.696552  0.678867  [0.7542270531400966, 0.6035070628348758]   
0  None  0.679031  0.661799  [0.7381386861313868, 0.5854597977852672]   

   precision                          precision_scores    recall  \
0   0.669084  [0.7925925925925926, 0.5455752212389381]  0.681231   
0   0.676205  [0.7965561224489796, 0.5558546433378196]  0.688133   
0   0.659991  [0.7859455958549223, 0.5340360122968819]  0.671828   

                              recall_scores valid_loss  valid_accuracy  ...  \
0  [0.7055619266055045, 0.6568993074054342]       None        0.772746  ...   
0  [0.7161697247706422, 0.6600958977091103]       None        0.783394  ...   
0  [0.6958142201834863, 0.6478423015450187]       None        0.780294  ...   

   learning_rate seed  loss_function gamma  k_fold n_splits  \
0         0.0001    1          focal     2    True        5   
0         0.0001   12          focal     2    True        5   
0         0.0001  123          focal     2    True        5   

   augmentation_type  hidden_dim_aug    comb_method  batch_size  
0             Conv1d            None  concatenation          64  
0             Conv1d            None  concatenation          64  
0             Conv1d            None  concatenation          64  

[3 rows x 48 columns]

In [14]:
best_seqsignet_attention_bilstm_grp_11[
    [
        "dimensions",
        "output_channels",
        "sig_depth",
        "num_heads",
        "num_layers",
        "ffn_hidden_dim",
        "dropout_rate",
        "learning_rate",
    ]
]

dimensions  output_channels  sig_depth  num_heads  num_layers  \
0          15               12          3         10           1   
0          15               12          3         10           1   
0          15               12          3         10           1   

  ffn_hidden_dim  dropout_rate  learning_rate  
0     (512, 512)           0.1         0.0001  
0     (512, 512)           0.1         0.0001  
0     (512, 512)           0.1         0.0001

In [15]:
best_seqsignet_attention_bilstm_grp_11["f1"].mean()

0.6706610148938169

In [16]:
best_seqsignet_attention_bilstm_grp_11["precision"].mean()

0.668426697961689

In [17]:
best_seqsignet_attention_bilstm_grp_11["recall"].mean()

0.6803972297031994

In [18]:
np.stack(best_seqsignet_attention_bilstm_grp_11["f1_scores"]).mean(axis=0)

array([0.74630504, 0.59501699])

In [19]:
np.stack(best_seqsignet_attention_bilstm_grp_11["precision_scores"]).mean(axis=0)

array([0.7916981 , 0.54515529])

In [20]:
np.stack(best_seqsignet_attention_bilstm_grp_11["recall_scores"]).mean(axis=0)

array([0.70584862, 0.65494584])

# history_length=20

In [21]:
shift = 3
window_size = 5
n = 6

## Random Projections

In [22]:
(
    seqsignet_attention_bilstm_grp_20,
    best_seqsignet_attention_bilstm_grp_20,
    _,
    __,
) = seqsignet_attention_bilstm_hyperparameter_search(
    shift=shift,
    window_size=window_size,
    n=n,
    dim_reduce_methods=["gaussian_random_projection"],
    results_output=f"{output_dir}/seqsignet_attention_bilstm_grp_focal_{gamma}_{shift}_{window_size}_{n}_kfold.csv",
    **kwargs,
)

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]


##################################################
dimension: 15 | method: gaussian_random_projection
given shift 3, window size 5 and n 6: history length = 20
[INFO] Concatenating the embeddings to the dataframe...
[INFO] - columns beginning with 'e' denote the full embddings.
[INFO] - columns beginning with 'd' denote the dimension reduced embeddings.
[INFO] Adding time feature columns into dataframe in `.df`.
[INFO] Adding 'time_encoding' feature...
[INFO] Adding 'time_diff' feature...
[INFO] Adding 'timeline_index' feature...
[INFO] Padding ids and storing in `.df_padded` and `.array_padded` attributes.


  0%|          | 0/5568 [00:00<?, ?it/s]

[INFO] The path was created for each item in the dataframe, by looking at its history, so to include embeddings in the FFN input, we concatenate the embeddings for each sentence / text.


  0%|          | 0/2 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/2 [00:00<?, ?it/s]

  0%|          | 0/2 [00:00<?, ?it/s]

  0%|          | 0/3 [00:00<?, ?it/s]

  0%|          | 0/3 [00:00<?, ?it/s]

  0%|          | 0/2 [00:00<?, ?it/s]

  0%|          | 0/3 [00:00<?, ?it/s]

  0%|          | 0/3 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/2 [00:00<?, ?it/s]

  0%|          | 0/2 [00:00<?, ?it/s]

  0%|          | 0/3 [00:00<?, ?it/s]

  0%|          | 0/3 [00:00<?, ?it/s]

  0%|          | 0/2 [00:00<?, ?it/s]

  0%|          | 0/3 [00:00<?, ?it/s]

  0%|          | 0/3 [00:00<?, ?it/s]

given shift 3, window size 5 and n 6: history length = 20
[INFO] Concatenating the embeddings to the dataframe...
[INFO] - columns beginning with 'e' denote the full embddings.
[INFO] - columns beginning with 'd' denote the dimension reduced embeddings.
[INFO] Adding time feature columns into dataframe in `.df`.
[INFO] Adding 'time_encoding' feature...
[INFO] Adding 'time_diff' feature...
[INFO] Adding 'timeline_index' feature...
[INFO] Padding ids and storing in `.df_padded` and `.array_padded` attributes.


  0%|          | 0/5568 [00:00<?, ?it/s]

[INFO] The path was created for each item in the dataframe, by looking at its history, so to include embeddings in the FFN input, we concatenate the embeddings for each sentence / text.
saving results dataframe to CSV for this hyperparameter search in rumours_output/seqsignet_attention_bilstm_grp_focal_2_3_5_6_kfold.csv
saving the best model results dataframe to CSV for this hyperparameter search in rumours_output/seqsignet_attention_bilstm_grp_focal_2_3_5_6_kfold_best_model.csv


In [23]:
seqsignet_attention_bilstm_grp_20.groupby(
    [
        "dimensions",
        "output_channels",
        "sig_depth",
        "num_heads",
        "num_layers",
        "ffn_hidden_dim",
        "dropout_rate",
        "learning_rate",
    ]
).mean()

/tmp/ipykernel_1375213/967918403.py:1: FutureWarning: The default value of numeric_only in DataFrameGroupBy.mean is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  seqsignet_attention_bilstm_grp_20.groupby(


accuracy  \
dimensions output_channels sig_depth num_heads num_layers ffn_hidden_dim dropout_rate learning_rate             
15         8               4         6         1          (256, 256)     0.1          0.0001         0.672818   
                                                                                      0.0005         0.669214   
                                                                                      0.0010         0.687108   
                                                                         0.2          0.0001         0.672942   
                                                                                      0.0005         0.643243   
                                                                                      0.0010         0.692762   
                                                          (512, 512)     0.1          0.0001         0.673190   
                                                                                      0.0005         0.679714   
                                                                                      0.0010         0.678409   
                                                                         0.2          0.0001         0.678596   
                                                                                      0.0005         0.650450   
                                                                                      0.0010         0.680895   
           12              3         10        1          (256, 256)     0.1          0.0001         0.670581   
                                                                                      0.0005         0.679528   
                                                                                      0.0010         0.690276   
                                                                         0.2          0.0001         0.686424   
                                                                                      0.0005         0.674122   
                                                                                      0.0010         0.677229   
                                                          (512, 512)     0.1          0.0001         0.685057   
                                                                                      0.0005         0.672693   
                                                                                      0.0010         0.690028   
                                                                         0.2          0.0001         0.678844   
                                                                                      0.0005         0.680833   
                                                                                      0.0010         0.670146   

                                                                                                           f1  \
dimensions output_channels sig_depth num_heads num_layers ffn_hidden_dim dropout_rate learning_rate             
15         8               4         6         1          (256, 256)     0.1          0.0001         0.652105   
                                                                                      0.0005         0.658801   
                                                                                      0.0010         0.666062   
                                                                         0.2          0.0001         0.656486   
                                                                                      0.0005         0.637078   
                                                                                      0.0010         0.668263   
                                                          (512, 512)     0.1          0.0001         0.654822   
                                                                                      0.0005         0.664522   
                                

In [24]:
best_seqsignet_attention_bilstm_grp_20

loss  accuracy        f1                                 f1_scores  \
0  None  0.688910  0.670195   [0.7487580912238446, 0.591632003914852]   
0  None  0.691519  0.674110  [0.7494322482967449, 0.5987878787878788]   
0  None  0.678844  0.656511   [0.744096242388237, 0.5689266950212659]   

   precision                          precision_scores    recall  \
0   0.667666  [0.7882725832012678, 0.5470588235294118]  0.678565   
0   0.671705  [0.7940327237728585, 0.5493772241992882]  0.683770   
0   0.654139  [0.7719568567026194, 0.5363207547169812]  0.661965   

                              recall_scores valid_loss  valid_accuracy  ...  \
0  [0.7130160550458715, 0.6441129461907299]       None        0.847014  ...   
0  [0.7095756880733946, 0.6579648375066596]       None        0.855641  ...   
0  [0.7181766055045872, 0.6057538625466169]       None        0.853619  ...   

   learning_rate seed  loss_function gamma  k_fold n_splits  \
0         0.0001    1          focal     2    True        5   
0         0.0001   12          focal     2    True        5   
0         0.0001  123          focal     2    True        5   

   augmentation_type  hidden_dim_aug    comb_method  batch_size  
0             Conv1d            None  concatenation          64  
0             Conv1d            None  concatenation          64  
0             Conv1d            None  concatenation          64  

[3 rows x 48 columns]

In [25]:
best_seqsignet_attention_bilstm_grp_20[
    [
        "dimensions",
        "output_channels",
        "sig_depth",
        "num_heads",
        "num_layers",
        "ffn_hidden_dim",
        "dropout_rate",
        "learning_rate",
    ]
]

dimensions  output_channels  sig_depth  num_heads  num_layers  \
0          15               12          3         10           1   
0          15               12          3         10           1   
0          15               12          3         10           1   

  ffn_hidden_dim  dropout_rate  learning_rate  
0     (256, 256)           0.2         0.0001  
0     (256, 256)           0.2         0.0001  
0     (256, 256)           0.2         0.0001

In [26]:
best_seqsignet_attention_bilstm_grp_20["f1"].mean()

0.6669388599388039

In [27]:
best_seqsignet_attention_bilstm_grp_20["precision"].mean()

0.6645031610204045

In [28]:
best_seqsignet_attention_bilstm_grp_20["recall"].mean()

0.67476666581131

In [29]:
np.stack(best_seqsignet_attention_bilstm_grp_20["f1_scores"]).mean(axis=0)

array([0.74742886, 0.58644886])

In [30]:
np.stack(best_seqsignet_attention_bilstm_grp_20["precision_scores"]).mean(axis=0)

array([0.78475405, 0.54425227])

In [31]:
np.stack(best_seqsignet_attention_bilstm_grp_20["recall_scores"]).mean(axis=0)

array([0.71358945, 0.63594388])

# history_length=35

In [32]:
shift = 3
window_size = 5
n = 11

## Random Projections

In [33]:
(
    seqsignet_attention_bilstm_grp_35,
    best_seqsignet_attention_bilstm_grp_35,
    _,
    __,
) = seqsignet_attention_bilstm_hyperparameter_search(
    shift=shift,
    window_size=window_size,
    n=n,
    dim_reduce_methods=["gaussian_random_projection"],
    results_output=f"{output_dir}/seqsignet_attention_bilstm_grp_focal_{gamma}_{shift}_{window_size}_{n}_kfold.csv",
    **kwargs,
)

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]


##################################################
dimension: 15 | method: gaussian_random_projection
given shift 3, window size 5 and n 11: history length = 35
[INFO] Concatenating the embeddings to the dataframe...
[INFO] - columns beginning with 'e' denote the full embddings.
[INFO] - columns beginning with 'd' denote the dimension reduced embeddings.
[INFO] Adding time feature columns into dataframe in `.df`.
[INFO] Adding 'time_encoding' feature...
[INFO] Adding 'time_diff' feature...
[INFO] Adding 'timeline_index' feature...
[INFO] Padding ids and storing in `.df_padded` and `.array_padded` attributes.


  0%|          | 0/5568 [00:00<?, ?it/s]

[INFO] The path was created for each item in the dataframe, by looking at its history, so to include embeddings in the FFN input, we concatenate the embeddings for each sentence / text.


  0%|          | 0/2 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/2 [00:00<?, ?it/s]

  0%|          | 0/2 [00:00<?, ?it/s]

  0%|          | 0/3 [00:00<?, ?it/s]

  0%|          | 0/3 [00:00<?, ?it/s]

  0%|          | 0/2 [00:00<?, ?it/s]

  0%|          | 0/3 [00:00<?, ?it/s]

  0%|          | 0/3 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/2 [00:00<?, ?it/s]

  0%|          | 0/2 [00:00<?, ?it/s]

  0%|          | 0/3 [00:00<?, ?it/s]

  0%|          | 0/3 [00:00<?, ?it/s]

  0%|          | 0/2 [00:00<?, ?it/s]

  0%|          | 0/3 [00:00<?, ?it/s]

  0%|          | 0/3 [00:00<?, ?it/s]

given shift 3, window size 5 and n 11: history length = 35
[INFO] Concatenating the embeddings to the dataframe...
[INFO] - columns beginning with 'e' denote the full embddings.
[INFO] - columns beginning with 'd' denote the dimension reduced embeddings.
[INFO] Adding time feature columns into dataframe in `.df`.
[INFO] Adding 'time_encoding' feature...
[INFO] Adding 'time_diff' feature...
[INFO] Adding 'timeline_index' feature...
[INFO] Padding ids and storing in `.df_padded` and `.array_padded` attributes.


  0%|          | 0/5568 [00:00<?, ?it/s]

[INFO] The path was created for each item in the dataframe, by looking at its history, so to include embeddings in the FFN input, we concatenate the embeddings for each sentence / text.
saving results dataframe to CSV for this hyperparameter search in rumours_output/seqsignet_attention_bilstm_grp_focal_2_3_5_11_kfold.csv
saving the best model results dataframe to CSV for this hyperparameter search in rumours_output/seqsignet_attention_bilstm_grp_focal_2_3_5_11_kfold_best_model.csv


In [34]:
seqsignet_attention_bilstm_grp_35.groupby(
    [
        "dimensions",
        "output_channels",
        "sig_depth",
        "num_heads",
        "num_layers",
        "ffn_hidden_dim",
        "dropout_rate",
        "learning_rate",
    ]
).mean()

/tmp/ipykernel_1375213/558732954.py:1: FutureWarning: The default value of numeric_only in DataFrameGroupBy.mean is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  seqsignet_attention_bilstm_grp_35.groupby(


accuracy  \
dimensions output_channels sig_depth num_heads num_layers ffn_hidden_dim dropout_rate learning_rate             
15         8               4         6         1          (256, 256)     0.1          0.0001         0.671264   
                                                                                      0.0005         0.671140   
                                                                                      0.0010         0.694066   
                                                                         0.2          0.0001         0.687543   
                                                                                      0.0005         0.653246   
                                                                                      0.0010         0.698602   
                                                          (512, 512)     0.1          0.0001         0.673936   
                                                                                      0.0005         0.672693   
                                                                                      0.0010         0.685927   
                                                                         0.2          0.0001         0.684374   
                                                                                      0.0005         0.670829   
                                                                                      0.0010         0.687729   
           12              3         10        1          (256, 256)     0.1          0.0001         0.676794   
                                                                                      0.0005         0.685617   
                                                                                      0.0010         0.685865   
                                                                         0.2          0.0001         0.683256   
                                                                                      0.0005         0.690214   
                                                                                      0.0010         0.673066   
                                                          (512, 512)     0.1          0.0001         0.678658   
                                                                                      0.0005         0.670270   
                                                                                      0.0010         0.684995   
                                                                         0.2          0.0001         0.682199   
                                                                                      0.0005         0.671637   
                                                                                      0.0010         0.667723   

                                                                                                           f1  \
dimensions output_channels sig_depth num_heads num_layers ffn_hidden_dim dropout_rate learning_rate             
15         8               4         6         1          (256, 256)     0.1          0.0001         0.642625   
                                                                                      0.0005         0.660063   
                                                                                      0.0010         0.667912   
                                                                         0.2          0.0001         0.665384   
                                                                                      0.0005         0.645027   
                                                                                      0.0010         0.673831   
                                                          (512, 512)     0.1          0.0001         0.647214   
                                                                                      0.0005         0.658687   
                                

In [35]:
best_seqsignet_attention_bilstm_grp_35

loss  accuracy        f1                                 f1_scores  \
0  None  0.679404  0.657560   [0.7440476190476191, 0.571072319201995]   
0  None  0.690401  0.672448   [0.7491315511252077, 0.595765393039669]   
0  None  0.679963  0.654968  [0.7478337494492584, 0.5621015047181842]   

   precision                          precision_scores    recall  \
0   0.655159  [0.7735148514851485, 0.5368026254102204]  0.663380   
0   0.669980  [0.7915735716565592, 0.5483870967741935]  0.681557   
0   0.652888  [0.7666365552544414, 0.5391389432485323]  0.658519   

                              recall_scores valid_loss  valid_accuracy  ...  \
0   [0.716743119266055, 0.6100159829515184]       None        0.880173  ...   
0  [0.7110091743119266, 0.6521044219499201]       None        0.875724  ...   
0  [0.7299311926605505, 0.5871070857751731]       None        0.874377  ...   

   learning_rate seed  loss_function gamma  k_fold n_splits  \
0         0.0001    1          focal     2    True        5   
0         0.0001   12          focal     2    True        5   
0         0.0001  123          focal     2    True        5   

   augmentation_type  hidden_dim_aug    comb_method  batch_size  
0             Conv1d            None  concatenation          64  
0             Conv1d            None  concatenation          64  
0             Conv1d            None  concatenation          64  

[3 rows x 48 columns]

In [36]:
best_seqsignet_attention_bilstm_grp_35[
    [
        "dimensions",
        "output_channels",
        "sig_depth",
        "num_heads",
        "num_layers",
        "ffn_hidden_dim",
        "dropout_rate",
        "learning_rate",
    ]
]

dimensions  output_channels  sig_depth  num_heads  num_layers  \
0          15               12          3         10           1   
0          15               12          3         10           1   
0          15               12          3         10           1   

  ffn_hidden_dim  dropout_rate  learning_rate  
0     (256, 256)           0.2         0.0001  
0     (256, 256)           0.2         0.0001  
0     (256, 256)           0.2         0.0001

In [37]:
best_seqsignet_attention_bilstm_grp_35["f1"].mean()

0.6616586894303222

In [38]:
best_seqsignet_attention_bilstm_grp_35["precision"].mean()

0.6593422739715159

In [39]:
best_seqsignet_attention_bilstm_grp_35["recall"].mean()

0.667818496152524

In [40]:
np.stack(best_seqsignet_attention_bilstm_grp_35["f1_scores"]).mean(axis=0)

array([0.74700431, 0.57631307])

In [41]:
np.stack(best_seqsignet_attention_bilstm_grp_35["precision_scores"]).mean(axis=0)

array([0.77724166, 0.54144289])

In [42]:
np.stack(best_seqsignet_attention_bilstm_grp_35["recall_scores"]).mean(axis=0)

array([0.71922783, 0.61640916])

# history_length=80

In [43]:
shift = 3
window_size = 5
n = 26

## Random Projections

In [44]:
(
    seqsignet_attention_bilstm_grp_80,
    best_seqsignet_attention_bilstm_grp_80,
    _,
    __,
) = seqsignet_attention_bilstm_hyperparameter_search(
    shift=shift,
    window_size=window_size,
    n=n,
    dim_reduce_methods=["gaussian_random_projection"],
    results_output=f"{output_dir}/seqsignet_attention_bilstm_grp_focal_{gamma}_{shift}_{window_size}_{n}_kfold.csv",
    **kwargs,
)

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]


##################################################
dimension: 15 | method: gaussian_random_projection
given shift 3, window size 5 and n 26: history length = 80
[INFO] Concatenating the embeddings to the dataframe...
[INFO] - columns beginning with 'e' denote the full embddings.
[INFO] - columns beginning with 'd' denote the dimension reduced embeddings.
[INFO] Adding time feature columns into dataframe in `.df`.
[INFO] Adding 'time_encoding' feature...
[INFO] Adding 'time_diff' feature...
[INFO] Adding 'timeline_index' feature...
[INFO] Padding ids and storing in `.df_padded` and `.array_padded` attributes.


  0%|          | 0/5568 [00:00<?, ?it/s]

[INFO] The path was created for each item in the dataframe, by looking at its history, so to include embeddings in the FFN input, we concatenate the embeddings for each sentence / text.


  0%|          | 0/2 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/2 [00:00<?, ?it/s]

  0%|          | 0/2 [00:00<?, ?it/s]

  0%|          | 0/3 [00:00<?, ?it/s]

  0%|          | 0/3 [00:00<?, ?it/s]

  0%|          | 0/2 [00:00<?, ?it/s]

  0%|          | 0/3 [00:00<?, ?it/s]

  0%|          | 0/3 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/2 [00:00<?, ?it/s]

  0%|          | 0/2 [00:00<?, ?it/s]

  0%|          | 0/3 [00:00<?, ?it/s]

  0%|          | 0/3 [00:00<?, ?it/s]

  0%|          | 0/2 [00:00<?, ?it/s]

  0%|          | 0/3 [00:00<?, ?it/s]

  0%|          | 0/3 [00:00<?, ?it/s]

given shift 3, window size 5 and n 26: history length = 80
[INFO] Concatenating the embeddings to the dataframe...
[INFO] - columns beginning with 'e' denote the full embddings.
[INFO] - columns beginning with 'd' denote the dimension reduced embeddings.
[INFO] Adding time feature columns into dataframe in `.df`.
[INFO] Adding 'time_encoding' feature...
[INFO] Adding 'time_diff' feature...
[INFO] Adding 'timeline_index' feature...
[INFO] Padding ids and storing in `.df_padded` and `.array_padded` attributes.


  0%|          | 0/5568 [00:00<?, ?it/s]

[INFO] The path was created for each item in the dataframe, by looking at its history, so to include embeddings in the FFN input, we concatenate the embeddings for each sentence / text.
saving results dataframe to CSV for this hyperparameter search in rumours_output/seqsignet_attention_bilstm_grp_focal_2_3_5_26_kfold.csv
saving the best model results dataframe to CSV for this hyperparameter search in rumours_output/seqsignet_attention_bilstm_grp_focal_2_3_5_26_kfold_best_model.csv


In [45]:
seqsignet_attention_bilstm_grp_80.groupby(
    [
        "dimensions",
        "output_channels",
        "sig_depth",
        "num_heads",
        "num_layers",
        "ffn_hidden_dim",
        "dropout_rate",
        "learning_rate",
    ]
).mean()

/tmp/ipykernel_1375213/4070696018.py:1: FutureWarning: The default value of numeric_only in DataFrameGroupBy.mean is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  seqsignet_attention_bilstm_grp_80.groupby(


accuracy  \
dimensions output_channels sig_depth num_heads num_layers ffn_hidden_dim dropout_rate learning_rate             
15         8               4         6         1          (256, 256)     0.1          0.0001         0.675986   
                                                                                      0.0005         0.669463   
                                                                                      0.0010         0.681392   
                                                                         0.2          0.0001         0.683691   
                                                                                      0.0005         0.658465   
                                                                                      0.0010         0.682945   
                                                          (512, 512)     0.1          0.0001         0.677540   
                                                                                      0.0005         0.679590   
                                                                                      0.0010         0.679466   
                                                                         0.2          0.0001         0.699907   
                                                                                      0.0005         0.657596   
                                                                                      0.0010         0.680336   
           12              3         10        1          (256, 256)     0.1          0.0001         0.680211   
                                                                                      0.0005         0.693321   
                                                                                      0.0010         0.686984   
                                                                         0.2          0.0001         0.686300   
                                                                                      0.0005         0.699037   
                                                                                      0.0010         0.684374   
                                                          (512, 512)     0.1          0.0001         0.685741   
                                                                                      0.0005         0.679528   
                                                                                      0.0010         0.710531   
                                                                         0.2          0.0001         0.690898   
                                                                                      0.0005         0.702765   
                                                                                      0.0010         0.656229   

                                                                                                           f1  \
dimensions output_channels sig_depth num_heads num_layers ffn_hidden_dim dropout_rate learning_rate             
15         8               4         6         1          (256, 256)     0.1          0.0001         0.649470   
                                                                                      0.0005         0.653929   
                                                                                      0.0010         0.663658   
                                                                         0.2          0.0001         0.653540   
                                                                                      0.0005         0.651061   
                                                                                      0.0010         0.662670   
                                                          (512, 512)     0.1          0.0001         0.644982   
                                                                                      0.0005         0.663248   
                                

In [46]:
best_seqsignet_attention_bilstm_grp_80

loss  accuracy        f1                                 f1_scores  \
0  None  0.661883  0.638186  [0.7307806470762839, 0.5455911823647294]   
0  None  0.705499  0.683212  [0.7672362993517974, 0.5991882293252156]   
0  None  0.712582  0.682111   [0.780529461998292, 0.5836933045356372]   

   precision                          precision_scores    recall  \
0   0.636216  [0.7575384615384615, 0.5148936170212766]  0.643015   
0   0.680502  [0.7890909090909091, 0.5719128329297821]  0.687878   
0   0.683347  [0.7750141322781232, 0.5916803503010399]  0.681021   

                              recall_scores valid_loss  valid_accuracy  ...  \
0   [0.705848623853211, 0.5801811401172083]       None        0.893382  ...   
0  [0.7465596330275229, 0.6291955247735749]       None        0.896482  ...   
0  [0.7861238532110092, 0.5759190197123069]       None        0.895673  ...   

   learning_rate seed  loss_function gamma  k_fold n_splits  \
0         0.0005    1          focal     2    True        5   
0         0.0005   12          focal     2    True        5   
0         0.0005  123          focal     2    True        5   

   augmentation_type  hidden_dim_aug    comb_method  batch_size  
0             Conv1d            None  concatenation          64  
0             Conv1d            None  concatenation          64  
0             Conv1d            None  concatenation          64  

[3 rows x 48 columns]

In [47]:
best_seqsignet_attention_bilstm_grp_80[
    [
        "dimensions",
        "output_channels",
        "sig_depth",
        "num_heads",
        "num_layers",
        "ffn_hidden_dim",
        "dropout_rate",
        "learning_rate",
    ]
]

dimensions  output_channels  sig_depth  num_heads  num_layers  \
0          15               12          3         10           1   
0          15               12          3         10           1   
0          15               12          3         10           1   

  ffn_hidden_dim  dropout_rate  learning_rate  
0     (256, 256)           0.1         0.0005  
0     (256, 256)           0.1         0.0005  
0     (256, 256)           0.1         0.0005

In [48]:
best_seqsignet_attention_bilstm_grp_80["f1"].mean()

0.667836520775326

In [49]:
best_seqsignet_attention_bilstm_grp_80["precision"].mean()

0.666688383859932

In [50]:
best_seqsignet_attention_bilstm_grp_80["recall"].mean()

0.6706379657824723

In [51]:
np.stack(best_seqsignet_attention_bilstm_grp_80["f1_scores"]).mean(axis=0)

array([0.75951547, 0.57615757])

In [52]:
np.stack(best_seqsignet_attention_bilstm_grp_80["precision_scores"]).mean(axis=0)

array([0.77388117, 0.5594956 ])

In [53]:
np.stack(best_seqsignet_attention_bilstm_grp_80["recall_scores"]).mean(axis=0)

array([0.74617737, 0.59509856])