In [1]:
import pickle
import numpy as np
import pandas as pd
import re
import os

seed = 2023

In [2]:
import torch

# set device
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
device

device(type='cuda')

In [3]:
from nlpsig_networks.scripts.ffn_baseline_functions import (
    ffn_hyperparameter_search,
)

In [4]:
output_dir = "rumours_output"
if not os.path.isdir(output_dir):
    os.makedirs(output_dir)

## Rumours

In [5]:
%run load_sbert-embeddings.py

In [6]:
df_rumours.head()

id label            datetime  \
0  5.249902e+17     0 2014-10-22 18:26:23   
1  5.249906e+17     0 2014-10-22 18:27:58   
2  5.249908e+17     1 2014-10-22 18:28:46   
3  5.249927e+17     1 2014-10-22 18:36:29   
4  5.250038e+17     1 2014-10-22 19:20:41   

                                                text timeline_id    set  
0  Police have clarified that there were two shoo...           0  train  
1  @CTVNews you guys "confirmed" there were 3 sho...           0  train  
2      @CTVNews get it right. http://t.co/GHYxMuzPG9           0  train  
3  RT @CTVNews Police have clarified that there w...           0  train  
4  @CTVNews @ctvsaskatoon so what happened at Rid...           0  train

In [7]:
sbert_embeddings.shape

(5568, 384)

## Baseline: FFN

In [8]:
num_epochs = 100
hidden_dim_sizes = [[64,64],[128,128],[256,256]]
dropout_rates = [0.5, 0.1]
learning_rates = [1e-3, 1e-4, 5e-4]
seeds = [1, 12, 123]
loss = "focal"
gamma = 2
validation_metric = "f1"
patience = 5
split_indices = (df_rumours[df_rumours['set']=='train'].index,
                 df_rumours[df_rumours['set']=='dev'].index,
                 df_rumours[df_rumours['set']=='test'].index)

In [9]:
ffn_current, best_ffn_current, _, __ = ffn_hyperparameter_search( 
    num_epochs=num_epochs,
    x_data=sbert_embeddings,
    y_data=y_data,
    hidden_dim_sizes=hidden_dim_sizes,
    output_dim=output_dim,
    dropout_rates=dropout_rates,
    learning_rates=learning_rates,
    seeds=seeds,
    loss=loss,
    gamma=gamma,
    device=device,
    split_ids=None, #torch.tensor(df_rumours['timeline_id'].astype(int)),
    split_indices=split_indices,
    k_fold=False,
    patience=patience,
    validation_metric=validation_metric,
    results_output=f"{output_dir}/ffn_current_focal_{gamma}.csv",
    verbose=False
)

  0%|          | 0/3 [00:00<?, ?it/s]

  0%|          | 0/2 [00:00<?, ?it/s]

  0%|          | 0/3 [00:00<?, ?it/s]

  0%|          | 0/3 [00:00<?, ?it/s]

  0%|          | 0/2 [00:00<?, ?it/s]

  0%|          | 0/3 [00:00<?, ?it/s]

  0%|          | 0/3 [00:00<?, ?it/s]

  0%|          | 0/2 [00:00<?, ?it/s]

  0%|          | 0/3 [00:00<?, ?it/s]

  0%|          | 0/3 [00:00<?, ?it/s]

saving results dataframe to CSV for this hyperparameter search in rumours_output/ffn_current_focal_2.csv
saving the best model results dataframe to CSV for this hyperparameter search in rumours_output/ffn_current_focal_2_best_model.csv


In [10]:
ffn_current

loss  accuracy        f1                                  f1_scores  \
0  0.266496  0.510963  0.496127   [0.5825874694873882, 0.4096662830840046]   
0  0.295249  0.495710  0.486025  [0.5565800502933781, 0.41546961325966847]   
0  0.262980  0.518589  0.501541   [0.5937248592115849, 0.4093567251461988]   
0  0.266704  0.510010  0.486818     [0.5959119496855345, 0.37772397094431]   
0  0.264475  0.510963  0.488889  [0.5951065509076557, 0.38267148014440433]   
0  0.265659  0.509056  0.489364  [0.5896414342629482, 0.38908659549228947]   
0  0.264648  0.517636  0.502152  [0.5899513776337115, 0.41435185185185186]   
0  0.270322  0.509056  0.482413   [0.5998445998445998, 0.3649815043156597]   
0  0.267894  0.518589  0.508540  [0.5788156797331109, 0.43826473859844267]   
0  0.266701  0.511916  0.499534  [0.5782537067545305, 0.42081447963800905]   
0  0.264186  0.522402  0.507913  [0.5923515052888527, 0.42347525891829696]   
0  0.265955  0.516683  0.495695  [0.5985748218527316, 0.39281437125748503]   
0  0.271585  0.510010  0.484581  [0.5990639625585024, 0.37009803921568635]   
0  0.264396  0.522402  0.507580  [0.5930138099106418, 0.42214532871972316]   
0  0.267160  0.513823  0.493726  [0.5945945945945946, 0.39285714285714285]   
0  0.290520  0.495710  0.480412  [0.5695687550854353, 0.39125431530494825]   
0  0.280366  0.498570  0.457999   [0.6062874251497007, 0.3097112860892388]   
0  0.282828  0.506196  0.494882   [0.5704809286898839, 0.4192825112107623]   
0  0.261449  0.533842  0.524889   [0.5901089689857502, 0.4596685082872928]   
0  0.281997  0.521449  0.457965   [0.6434659090909091, 0.2724637681159421]   
0  0.272147  0.507150  0.497950   [0.5659109991603694, 0.4299889746416759]   
0  0.264484  0.523356  0.508730    [0.5934959349593497, 0.423963133640553]   
0  0.270236  0.506196  0.482824  [0.5927672955974843, 0.37288135593220334]   
0  0.269062  0.509056  0.486896   [0.5935280189423835, 0.3802647412755716]   
0  0.270694  0.503336  0.477328  [0.5939204988308652, 0.36073619631901843]   
0  0.291455  0.506196  0.501005  [0.5519031141868512, 0.45010615711252655]   
0  0.272758  0.503336  0.498964   [0.5457715780296426, 0.4521556256572029]   
0  0.253243  0.517636  0.516824  [0.5366300366300366, 0.49701789264413515]   
0  0.265313  0.508103  0.494350   [0.5777414075286417, 0.4109589041095891]   
0  0.264338  0.530982  0.514549  [0.6038647342995169, 0.42523364485981313]   
0  0.263755  0.522402  0.501256   [0.6039525691699605, 0.3985594237695078]   
0  0.269177  0.512869  0.494110  [0.5915267785771383, 0.39669421487603307]   
0  0.262655  0.523356  0.512995    [0.584026622296173, 0.4419642857142857]   
0  0.263677  0.529075  0.515909   [0.5957446808510639, 0.4360730593607306]   
0  0.482334  0.482364  0.451719   [0.5813415574402467, 0.3220973782771535]   
0  0.282623  0.498570  0.459808   [0.6045112781954888, 0.3151041666666667]   
0  0.250881  0.531935  0.531935   [0.5319351763584366, 0.5319351763584366]   
0  0.262237  0.520496  0.503875  [0.5946817082997583, 0.41306884480746786]   
0  0.299979  0.502383  0.496330   [0.5515463917525774, 0.4411134903640257]   
0  0.259906  0.522402  0.504010   [0.5995203836930456, 0.4085005903187721]   
0  0.267809  0.513823  0.497511   [0.5880452342487884, 0.4069767441860465]   
0  0.261770  0.525262  0.512612   [0.5911330049261083, 0.4340909090909091]   
0  0.264176  0.519542  0.501230              [0.5968, 0.40566037735849053]   
0  0.286080  0.508103  0.455159  [0.6250000000000001, 0.28531855955678664]   
0  0.273152  0.518589  0.514174  [0.5604873803307224, 0.46786090621707055]   
0  0.252901  0.519542  0.519521   [0.5227272727272727, 0.5163147792706334]   
0  0.262611  0.524309  0.516889   [0.5767599660729432, 0.4570184983677911]   
0  0.262042  0.531935  0.524171    [0.584953508030431, 0.4633879781420765]   
0  0.263199  0.512869  0.501267   [0.5773366418527709, 0.4251968503937008]   
0  0.279130  0.510010  0.498189   [0.5752066115702479, 0.4211711711711712]   
0  0.267105  0.508103  0.4956

In [11]:
best_ffn_current

loss  accuracy        f1                                  f1_scores  \
0  0.253243  0.517636  0.516824  [0.5366300366300366, 0.49701789264413515]   
0  0.265313  0.508103  0.494350   [0.5777414075286417, 0.4109589041095891]   
0  0.264338  0.530982  0.514549  [0.6038647342995169, 0.42523364485981313]   

   precision                           precision_scores    recall  \
0   0.516833  [0.5395948434622467, 0.49407114624505927]  0.516849   
0   0.501620    [0.524517087667162, 0.4787234042553192]  0.501494   
0   0.526181   [0.5411255411255411, 0.5112359550561798]  0.523530   

                 recall_scores  valid_loss  valid_accuracy  ...  \
0    [0.5336976320582878, 0.5]    0.237407        0.615658  ...   
0   [0.6429872495446266, 0.36]    0.230795        0.637011  ...   
0  [0.6830601092896175, 0.364]    0.243811        0.622776  ...   

                         valid_recall_scores  hidden_dim  dropout_rate  \
0   [0.6368715083798883, 0.5784313725490197]  (128, 128)           0.1   
0  [0.7206703910614525, 0.49019607843137253]  (128, 128)           0.1   
0   [0.7374301675977654, 0.4215686274509804]  (128, 128)           0.1   

  learning_rate  seed loss_function gamma  k_fold  n_splits  batch_size  
0         0.001     1         focal     2   False      None          64  
0         0.001    12         focal     2   False      None          64  
0         0.001   123         focal     2   False      None          64  

[3 rows x 25 columns]

In [12]:
best_ffn_current["f1"].mean()

0.5085744366786221

In [13]:
best_ffn_current["precision"].mean()

0.514877996301918

In [14]:
best_ffn_current["recall"].mean()

0.5139574984820886

In [15]:
np.stack(best_ffn_current["f1_scores"]).mean(axis=0)

array([0.57274539, 0.44440348])

In [16]:
np.stack(best_ffn_current["precision_scores"]).mean(axis=0)

array([0.53507916, 0.49467684])

In [17]:
np.stack(best_ffn_current["recall_scores"]).mean(axis=0)

array([0.619915, 0.408   ])