In [1]:
import numpy as np
X = np.random.rand(10, 5)
y = np.random.rand(10)
groups = np.array([1,1,1,2,2,3,3,4,4,1])

In [2]:
from sklearn.model_selection import (
    GroupKFold,
    GroupShuffleSplit,
    KFold,
    train_test_split,
)

In [3]:
from nlpsig.classification_utils import DataSplits, Folds

In [4]:
groups

array([1, 1, 1, 2, 2, 3, 3, 4, 4, 1])

In [5]:
test = np.array([3, 4, 5, 6, 7, 8])
test[[0,1]]

array([3, 4])

In [6]:
test_datasplits = DataSplits(x_data = X,
                             y_data = y,
                             groups=groups,
                             train_size=0.8,
                             valid_size=0.1,
                             shuffle=False,
                             random_state=50)

[INFO] Splitting data by provided groups


In [9]:
test_datasplits.indices

([0, 1, 2, 7, 8, 9], [3, 4], [5, 6])

In [10]:
[groups[index] for index in test_datasplits.indices]

[array([1, 1, 1, 4, 4, 1]), array([2, 2]), array([3, 3])]

In [14]:
indices = ([1,2,3,4,5], [6, 7, 8, 8,3], [9,0])
test_datasplits = DataSplits(x_data = X,
                             y_data = y,
                             indices=indices,
                             train_size=0.8,
                             valid_size=0.1,
                             shuffle=True,
                             random_state=12)

In [15]:
groups

array([1, 1, 1, 2, 2, 3, 3, 4, 4, 1])

In [16]:
test_datasplits.indices

([1, 2, 3, 4, 5], [6, 7, 8, 8, 3], [9, 0])

In [14]:
indices = (((1,2,3), (4,5,6), (5,6,3)),
           ((1,2,3), (4,5,6), (5,6,3)),
           ((1,2,3), (4,5,6), (5,6,3)),
           ((1,2,3), (4,5,6), (5,6,3)))
    
test_folds = Folds(x_data = X,
                   y_data = y,
                   indices=indices,
                   n_splits=4)

In [10]:
test_folds.fold_indices

(((1, 2, 3), (4, 5, 6), (5, 6, 3)),
 ((1, 2, 3), (4, 5, 6), (5, 6, 3)),
 ((1, 2, 3), (4, 5, 6), (5, 6, 3)),
 ((1, 2, 3), (4, 5, 6), (5, 6, 3)))

In [73]:
train_inds, test_inds = 
X_train, X_test, y_train, y_test = X[train_inds], X[test_inds], y[train_inds], y[test_inds]

In [74]:
train_inds.tolist()

[5, 6]

In [75]:
groups[train_inds]

array([3, 3])

In [76]:
groups[test_inds]

array([1, 1, 1, 2, 2, 4, 4, 1])

In [42]:
test = GroupShuffleSplit(n_splits=1).split(X, y, groups)

In [43]:
t = list(test)

In [44]:
len(t)

1

In [50]:
train_test_split(
                range(len(y)),
                test_size=(0.4),
                shuffle=True,
                random_state=42,
                stratify=groups,
            )

[[8, 1, 4, 0, 9, 5], [7, 3, 2, 6]]