In [13]:
import pickle
import numpy as np
import pandas as pd
import re

seed = 2023

In [14]:
import torch

# set device
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
device = "cuda:1"

In [15]:
from nlpsig_networks.scripts.seqsignet_functions import seqsignet_hyperparameter_search

In [16]:
output_dir = "talklife_moc_output"
if not os.path.isdir(output_dir):
    os.makedirs(output_dir)

Talklife MoC

In [17]:
%run load_talklifemoc.py

In [18]:
%run load_sbert-embeddings.py

In [19]:
sbert_embeddings.shape

torch.Size([18604, 384])

SWNU-BiLSTM

In [20]:
features = ["time_encoding", "timeline_index"]
standardise_method = ["z_score", None]
include_features_in_path = True
include_features_in_input = False

In [21]:
# create indices for kfold
fold_col_names = [c for c in df.columns if "fold" in c]
fold_list = []
for foldc in fold_col_names:
    fold_list.append(
        (
            df[df[foldc] == "train"].index,
            df[df[foldc] == "dev"].index,
            df[df[foldc] == "test"].index,
        )
    )
fold_list = tuple(fold_list)

In [22]:
num_epochs = 100
embedding_dim = 384
dimensions = [15]
dimreduction_method = ["umap"]
swnu_hidden_dim_sizes_and_sig_depths = [([12], 3), ([10], 4)]
lstm_hidden_dim_sizes = [384]
ffn_hidden_dim_sizes = [[256, 256], [512, 512]]
dropout_rates = [0.1, 0.2]
learning_rates = [1e-3, 1e-4, 5e-4]
seeds = [1, 12, 123]
loss = "focal"
gamma = 2
validation_metric = "f1"
patience = 5

In [23]:
shift = 3
window_size = 5
n = 6

In [24]:
size = 20
(
    seqsignet_network_umap_20,
    best_seqsignet_network_umap_20,
    _,
    __,
) = seqsignet_hyperparameter_search(
    num_epochs=num_epochs,
    df=df,
    id_column="timeline_id",
    label_column="label",
    embeddings=sbert_embeddings.numpy(),
    y_data=y_data,
    output_dim=output_dim,
    shift=shift,
    window_size=window_size,
    n=n,
    dim_reduce_methods=dimreduction_method,
    dimensions=dimensions,
    log_signature=True,
    swnu_hidden_dim_sizes_and_sig_depths=swnu_hidden_dim_sizes_and_sig_depths,
    lstm_hidden_dim_sizes=lstm_hidden_dim_sizes,
    ffn_hidden_dim_sizes=ffn_hidden_dim_sizes,
    dropout_rates=dropout_rates,
    learning_rates=learning_rates,
    BiLSTM=True,
    seeds=seeds,
    loss=loss,
    gamma=gamma,
    device=device,
    features=features,
    standardise_method=standardise_method,
    include_features_in_path=include_features_in_path,
    include_features_in_input=include_features_in_input,
    split_ids=None,
    split_indices=fold_list,
    k_fold=True,
    patience=patience,
    validation_metric=validation_metric,
    results_output=f"{output_dir}/seqsignet_umap_focal_{gamma}_{size}_kfold.csv",
    verbose=False,
)

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]


##################################################
dimension: 15 | method: umap
given shift 3, window size 5 and n 6: history length = 20
[INFO] Concatenating the embeddings to the dataframe...
[INFO] - columns beginning with 'e' denote the full embddings.
[INFO] - columns beginning with 'd' denote the dimension reduced embeddings.
[INFO] Adding time feature columns into dataframe in `.df`.
[INFO] Adding 'time_encoding' feature...
[INFO] Adding 'time_diff' feature...
[INFO] Adding 'timeline_index' feature...
[INFO] Padding ids and storing in `.df_padded` and `.array_padded` attributes.


  0%|          | 0/18604 [00:00<?, ?it/s]

[INFO] The path was created for each item in the dataframe, by looking at its history, so to include embeddings in the FFN input, we concatenate the embeddings for each sentence / text.


  0%|          | 0/2 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/2 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/2 [00:00<?, ?it/s]

  0%|          | 0/3 [00:00<?, ?it/s]

  0%|          | 0/3 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/2 [00:00<?, ?it/s]

  0%|          | 0/3 [00:00<?, ?it/s]

  0%|          | 0/3 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/2 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/2 [00:00<?, ?it/s]

  0%|          | 0/3 [00:00<?, ?it/s]

  0%|          | 0/3 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/2 [00:00<?, ?it/s]

  0%|          | 0/3 [00:00<?, ?it/s]

  0%|          | 0/3 [00:00<?, ?it/s]

given shift 3, window size 5 and n 6: history length = 20
[INFO] Concatenating the embeddings to the dataframe...
[INFO] - columns beginning with 'e' denote the full embddings.
[INFO] - columns beginning with 'd' denote the dimension reduced embeddings.
[INFO] Adding time feature columns into dataframe in `.df`.
[INFO] Adding 'time_encoding' feature...
[INFO] Adding 'time_diff' feature...
[INFO] Adding 'timeline_index' feature...
[INFO] Padding ids and storing in `.df_padded` and `.array_padded` attributes.


  0%|          | 0/18604 [00:00<?, ?it/s]

[INFO] The path was created for each item in the dataframe, by looking at its history, so to include embeddings in the FFN input, we concatenate the embeddings for each sentence / text.
saving results dataframe to CSV for this hyperparameter search in talklife_moc_output/seqsignet_umap_focal_2_20_kfold.csv
saving the best model results dataframe to CSV for this hyperparameter search in talklife_moc_output/seqsignet_umap_focal_2_20_kfold_best_model.csv


In [25]:
seqsignet_network_umap_20

loss  accuracy        f1  \
0   None  0.805311  0.546908   
0   None  0.795904  0.549493   
0   None  0.803591  0.546365   
0   None  0.801602  0.542702   
0   None  0.808428  0.555198   
..   ...       ...       ...   
0   None  0.817190  0.547721   
0   None  0.808643  0.548544   
0   None  0.802677  0.541848   
0   None  0.801064  0.548387   
0   None  0.805687  0.542989   

                                            f1_scores  precision  \
0   [0.8863430420711974, 0.45438121047877145, 0.30...   0.533791   
0   [0.8795832104590583, 0.4568398727465536, 0.312...   0.529193   
0   [0.8854193715917944, 0.4562334217506631, 0.297...   0.531913   
0   [0.8837784211039912, 0.4571550074420582, 0.287...   0.530516   
0   [0.8884568021258669, 0.4657226342998427, 0.311...   0.540481   
..                                                ...        ...   
0   [0.8951329973847036, 0.4416934884872493, 0.306...   0.545403   
0   [0.8888386805241754, 0.45961002785515315, 0.29...   0.536265   
0   [0.8848147188390775, 0.45081227436823107, 0.28...   0.528177   
0   [0.8834232243810514, 0.4506914531852188, 0.311...   0.531189   
0   [0.8866565457540618, 0.4525646845211076, 0.289...   0.531758   

                                     precision_scores    recall  \
0   [0.9011581995261911, 0.41708126036484244, 0.28...  0.563340   
0   [0.9059736753290584, 0.39903668025194516, 0.28...  0.579110   
0   [0.9030058262711864, 0.41148325358851673, 0.28...  0.565340   
0   [0.9033180397632822, 0.4000744324525493, 0.288...  0.561500   
0   [0.9045796489375743, 0.4258117550349363, 0.291...  0.573876   
..                                                ...       ...   
0   [0.8966773162939297, 0.44092931290163123, 0.29...  0.550178   
0   [0.9012305275559628, 0.4319371727748691, 0.275...  0.563418   
0   [0.900448312236287, 0.4134933774834437, 0.2705...  0.559156   
0   [0.9018840387422051, 0.4150313152400835, 0.276...  0.571321   
0   [0.8997050147492626, 0.4171548117154812, 0.278...  0.556854   

                                        recall_scores valid_loss  \
0   [0.8720071319409067, 0.4990079365079365, 0.319...       None   
0   [0.8546867040244523, 0.5342261904761905, 0.348...       None   
0   [0.8685048395313296, 0.5119047619047619, 0.315...       None   
0   [0.8650662251655629, 0.533234126984127, 0.2861...       None   
0   [0.8728986245542537, 0.5138888888888888, 0.334...       None   
..                                                ...        ...   
0   [0.8935939887926643, 0.44246031746031744, 0.31...       None   
0   [0.8767829852266938, 0.49107142857142855, 0.32...       None   
0   [0.8697147223637289, 0.4955357142857143, 0.312...       None   
0   [0.8657030056036679, 0.4930555555555556, 0.355...       None   
0   [0.8739811512990321, 0.4945436507936508, 0.302...       None   

    valid_accuracy  ...  BiLSTM loss_function  gamma k_fold  n_splits  \
0         0.800050  ...    True         focal      2   True         5   
0         0.790963  ...    True         focal      2   True         5   
0         0.798091  ...    True         focal      2   True         5   
0         0.796590  ...    True         focal      2   True         5   
0         0.803176  ...    True         focal      2   True         5   
..             ...  ...     ...           ...    ...    ...       ...   
0         0.809762  ...    True         focal      2   True         5   
0         0.804635  ...    True         focal      2   True         5   
0         0.800300  ...    True         focal      2   True         5   
0         0.799967  ...    True         focal      2   True         5   
0         0.802343  ...    True         focal      2   True         5   

   augmentation_type  hidden_dim_aug    comb_method  batch_size  model_id  
0             Conv1d            None  concatenation          64         0  
0             Conv1d            None  concatenation          64         0  
0             Conv1d            None  concatenation          64         0  

In [38]:
best_seqsignet_network_umap_20[
    [
        "f1",
        "f1_scores",
        "precision",
        "recall",
        "valid_f1",
        "valid_f1_scores",
        "valid_precision",
        "valid_recall",
        "features",
        "standardise_method",
        "output_channels",
        "lstm_hidden_dim",
        "dimensions",
        "swnu_hidden_dim",
        "sig_depth",
        "ffn_hidden_dim",
        "dropout_rate",
        "learning_rate",
        "seed",
        "batch_size",
    ]
]

f1                                          f1_scores  precision  \
0  0.551877  [0.8943844700003203, 0.4632024453327063, 0.298...   0.547830   
0  0.550928  [0.8878825127773824, 0.45651214128035317, 0.30...   0.540896   
0  0.551350  [0.8851722903719129, 0.4672077209914455, 0.301...   0.534629   

     recall  valid_f1                                    valid_f1_scores  \
0  0.556841  0.545873  [0.8895001375309445, 0.4688270517787954, 0.279...   
0  0.564836  0.548343  [0.8839387419314012, 0.4716057441253263, 0.289...   
0  0.573782  0.545722  [0.879700968800061, 0.4737448559670782, 0.2837...   

   valid_precision  valid_recall                         features  \
0         0.540209      0.553929  [time_encoding, timeline_index]   
0         0.536358      0.567866  [time_encoding, timeline_index]   
0         0.527708      0.571670  [time_encoding, timeline_index]   

  standardise_method output_channels  lstm_hidden_dim  dimensions  \
0    [z_score, None]            None              384          15   
0    [z_score, None]            None              384          15   
0    [z_score, None]            None              384          15   

  swnu_hidden_dim  sig_depth ffn_hidden_dim  dropout_rate  learning_rate  \
0           (12,)          3     (512, 512)           0.2         0.0001   
0           (12,)          3     (512, 512)           0.2         0.0001   
0           (12,)          3     (512, 512)           0.2         0.0001   

   seed  batch_size  
0     1          64  
0    12          64  
0   123          64

In [26]:
best_seqsignet_network_umap_20["f1"].mean()

0.5513850531101244

In [27]:
best_seqsignet_network_umap_20["precision"].mean()

0.5411183800451284

In [28]:
best_seqsignet_network_umap_20["recall"].mean()

0.5651528257196352

In [29]:
np.stack(best_seqsignet_network_umap_20["f1_scores"]).mean(axis=0)

array([0.88914642, 0.46230744, 0.3027013 ])

In [30]:
np.stack(best_seqsignet_network_umap_20["precision_scores"]).mean(axis=0)

array([0.90241392, 0.42347176, 0.29746945])

In [31]:
np.stack(best_seqsignet_network_umap_20["recall_scores"]).mean(axis=0)

array([0.87633724, 0.50992063, 0.3092006 ])