In [1]:
seed = 2023
from nlpsig_networks.scripts.swnu_network_functions import obtain_SWNUNetwork_input
from nlpsig_networks.utils import obtain_paths_mask, obtain_signatures_mask

In [2]:
import os

os.chdir("Rumours/")

## Rumours

In [3]:
%run load_sbert-embeddings.py

In [4]:
df_rumours.head()

id label            datetime  \
0  5.249902e+17     0 2014-10-22 18:26:23   
1  5.249906e+17     0 2014-10-22 18:27:58   
2  5.249908e+17     1 2014-10-22 18:28:46   
3  5.249927e+17     1 2014-10-22 18:36:29   
4  5.250038e+17     1 2014-10-22 19:20:41   

                                                text timeline_id    set  
0  Police have clarified that there were two shoo...           0  train  
1  @CTVNews you guys "confirmed" there were 3 sho...           0  train  
2      @CTVNews get it right. http://t.co/GHYxMuzPG9           0  train  
3  RT @CTVNews Police have clarified that there w...           0  train  
4  @CTVNews @ctvsaskatoon so what happened at Rid...           0  train

In [5]:
len(df_rumours)

5568

In [7]:
x_data = obtain_SWNUNetwork_input(
    method="umap",
    dimension=3,
    df=df_rumours,
    id_column="timeline_id",
    label_column="label",
    embeddings=sbert_embeddings,
    k=10,
    features=["time_encoding", "timeline_index"],
    standardise_method=None,
    include_features_in_path=False,
)

[INFO] Concatenating the embeddings to the dataframe...
[INFO] - columns beginning with 'e' denote the full embddings.
[INFO] - columns beginning with 'd' denote the dimension reduced embeddings.
[INFO] Adding time feature columns into dataframe in `.df`.
[INFO] Adding 'time_encoding' feature...
[INFO] Adding 'time_diff' feature...
[INFO] Adding 'timeline_index' feature...
[INFO] Padding ids and storing in `.df_padded` and `.array_padded` attributes.


  0%|          | 0/5568 [00:00<?, ?it/s]

[INFO] The path was created for each item in the dataframe, by looking at its history, so to include embeddings in the FFN input, we concatenate the embeddings for each sentence / text.


In [8]:
x_data.keys()

dict_keys(['x_data', 'input_channels', 'embedding_dim', 'num_features'])

In [9]:
x_data["x_data"]

{'path': tensor([[[-7.2296,  2.7356,  8.0972],
          [ 0.0000,  0.0000,  0.0000],
          [ 0.0000,  0.0000,  0.0000],
          ...,
          [ 0.0000,  0.0000,  0.0000],
          [ 0.0000,  0.0000,  0.0000],
          [ 0.0000,  0.0000,  0.0000]],
 
         [[-7.2296,  2.7356,  8.0972],
          [-7.4468,  3.6928,  9.9551],
          [ 0.0000,  0.0000,  0.0000],
          ...,
          [ 0.0000,  0.0000,  0.0000],
          [ 0.0000,  0.0000,  0.0000],
          [ 0.0000,  0.0000,  0.0000]],
 
         [[-7.2296,  2.7356,  8.0972],
          [-7.4468,  3.6928,  9.9551],
          [-9.0931, 12.8440,  9.0442],
          ...,
          [ 0.0000,  0.0000,  0.0000],
          [ 0.0000,  0.0000,  0.0000],
          [ 0.0000,  0.0000,  0.0000]],
 
         ...,
 
         [[-7.1256,  2.5965,  9.4014],
          [-5.3229,  6.2228,  9.8129],
          [-5.5247,  3.6294,  9.8226],
          ...,
          [-8.2079,  5.4001, 10.4869],
          [-7.0656,  5.3290, 10.1910],
          

In [10]:
x_data["x_data"]["path"].shape

torch.Size([5568, 10, 3])

In [11]:
x_data["x_data"]["features"]

tensor([[ 6.4823e-02,  9.3748e-03, -3.3364e-02,  ...,  1.8542e-03,
          2.0148e+03,  1.0000e+00],
        [-2.9260e-02, -5.3905e-02, -3.9863e-02,  ...,  9.3606e-02,
          2.0148e+03,  2.0000e+00],
        [-3.1863e-02,  5.5065e-02, -2.4028e-02,  ...,  9.3310e-02,
          2.0148e+03,  3.0000e+00],
        ...,
        [-2.2057e-03,  8.0860e-02, -9.9185e-02,  ..., -2.3929e-02,
          2.0148e+03,  2.2000e+01],
        [-3.1252e-02,  3.5479e-02,  7.2934e-03,  ..., -1.3536e-02,
          2.0148e+03,  2.3000e+01],
        [ 1.1187e-02,  8.0548e-02, -4.1098e-02,  ...,  8.9290e-02,
          2.0148e+03,  2.4000e+01]])

In [12]:
x_data["input_channels"]

3

In [13]:
x_data["embedding_dim"]

384

In [14]:
x_data["num_features"]

2

In [15]:
path = x_data["x_data"]["path"]

In [16]:
path.shape

torch.Size([5568, 10, 3])

In [17]:
import signatory

In [18]:
signatures = signatory.logsignature(path, 2, stream=True)

In [19]:
signatures.shape

torch.Size([5568, 9, 6])

In [20]:
path[0]

tensor([[-7.2296,  2.7356,  8.0972],
        [ 0.0000,  0.0000,  0.0000],
        [ 0.0000,  0.0000,  0.0000],
        [ 0.0000,  0.0000,  0.0000],
        [ 0.0000,  0.0000,  0.0000],
        [ 0.0000,  0.0000,  0.0000],
        [ 0.0000,  0.0000,  0.0000],
        [ 0.0000,  0.0000,  0.0000],
        [ 0.0000,  0.0000,  0.0000],
        [ 0.0000,  0.0000,  0.0000]], dtype=torch.float64)

In [21]:
signatures[0]

tensor([[ 7.2296, -2.7356, -8.0972,  0.0000,  0.0000,  0.0000],
        [ 7.2296, -2.7356, -8.0972,  0.0000,  0.0000,  0.0000],
        [ 7.2296, -2.7356, -8.0972,  0.0000,  0.0000,  0.0000],
        [ 7.2296, -2.7356, -8.0972,  0.0000,  0.0000,  0.0000],
        [ 7.2296, -2.7356, -8.0972,  0.0000,  0.0000,  0.0000],
        [ 7.2296, -2.7356, -8.0972,  0.0000,  0.0000,  0.0000],
        [ 7.2296, -2.7356, -8.0972,  0.0000,  0.0000,  0.0000],
        [ 7.2296, -2.7356, -8.0972,  0.0000,  0.0000,  0.0000],
        [ 7.2296, -2.7356, -8.0972,  0.0000,  0.0000,  0.0000]],
       dtype=torch.float64)

In [22]:
path[2]

tensor([[-7.2296,  2.7356,  8.0972],
        [-7.4468,  3.6928,  9.9551],
        [-9.0931, 12.8440,  9.0442],
        [ 0.0000,  0.0000,  0.0000],
        [ 0.0000,  0.0000,  0.0000],
        [ 0.0000,  0.0000,  0.0000],
        [ 0.0000,  0.0000,  0.0000],
        [ 0.0000,  0.0000,  0.0000],
        [ 0.0000,  0.0000,  0.0000],
        [ 0.0000,  0.0000,  0.0000]], dtype=torch.float64)

In [23]:
signatures[2]

tensor([[ -0.2172,   0.9573,   1.8579,   0.0000,   0.0000,   0.0000],
        [ -1.8635,  10.1084,   0.9469,  -0.2056,   1.6283,  -8.9369],
        [  7.2296,  -2.7356,  -8.0972, -34.1965,   5.7501, -48.5668],
        [  7.2296,  -2.7356,  -8.0972, -34.1965,   5.7501, -48.5668],
        [  7.2296,  -2.7356,  -8.0972, -34.1965,   5.7501, -48.5668],
        [  7.2296,  -2.7356,  -8.0972, -34.1965,   5.7501, -48.5668],
        [  7.2296,  -2.7356,  -8.0972, -34.1965,   5.7501, -48.5668],
        [  7.2296,  -2.7356,  -8.0972, -34.1965,   5.7501, -48.5668],
        [  7.2296,  -2.7356,  -8.0972, -34.1965,   5.7501, -48.5668]],
       dtype=torch.float64)

In [24]:
stream_dim = signatures.shape[1]
lstm_u = torch.sum(signatures, 2)
lstm_u_shift = torch.roll(lstm_u, shifts=1, dims=1)
lstm_u_shift[:, 0] = -100
seq_lengths = torch.sum(torch.eq(lstm_u, lstm_u_shift) == False, 1)

seq_lengths, perm_idx = seq_lengths.sort(0, descending=True)

In [25]:
stream_dim

9

In [26]:
lstm_u

tensor([[ -3.6032,  -3.6032,  -3.6032,  ...,  -3.6032,  -3.6032,  -3.6032],
        [  2.5980, -13.9378, -13.9378,  ..., -13.9378, -13.9378, -13.9378],
        [  2.5980,   1.6776, -80.6164,  ..., -80.6164, -80.6164, -80.6164],
        ...,
        [  5.8405,   1.6847,  -1.3289,  ...,  10.0744,   8.4509,   3.4485],
        [ -2.7856,  -4.7754, -11.6355,  ...,  -1.3128,   0.1892,   0.9920],
        [ -2.3138,  -0.4232,  -1.0668,  ...,   2.0493,   5.7191,   6.8993]],
       dtype=torch.float64)

In [27]:
lstm_u_shift

tensor([[-100.0000,   -3.6032,   -3.6032,  ...,   -3.6032,   -3.6032,
           -3.6032],
        [-100.0000,    2.5980,  -13.9378,  ...,  -13.9378,  -13.9378,
          -13.9378],
        [-100.0000,    2.5980,    1.6776,  ...,  -80.6164,  -80.6164,
          -80.6164],
        ...,
        [-100.0000,    5.8405,    1.6847,  ...,    7.0180,   10.0744,
            8.4509],
        [-100.0000,   -2.7856,   -4.7754,  ...,   -2.8480,   -1.3128,
            0.1892],
        [-100.0000,   -2.3138,   -0.4232,  ...,    4.1581,    2.0493,
            5.7191]], dtype=torch.float64)

In [28]:
torch.sum(torch.eq(lstm_u, lstm_u_shift) == False, 1)

tensor([1, 2, 3,  ..., 9, 9, 9])

In [29]:
torch.sum(obtain_signatures_mask(signatures) == False, 1)

tensor([1, 2, 3,  ..., 9, 9, 9])

In [30]:
torch.equal(torch.eq(lstm_u, lstm_u_shift), obtain_signatures_mask(signatures))

True

In [31]:
torch.equal(
    torch.sum(torch.eq(lstm_u, lstm_u_shift) == False, 1),
    torch.sum(obtain_signatures_mask(signatures) == False, 1),
)

True

`True` values in the mask are the ones that indicate to MultiheadAttention to ignore in attention calculation.

In [32]:
path_mask = obtain_paths_mask(path)
signatures_mask = obtain_signatures_mask(signatures)

In [33]:
path_mask.shape

torch.Size([5568, 10])

In [34]:
signatures_mask.shape

torch.Size([5568, 9])

In [35]:
path_mask[0]

tensor([False,  True,  True,  True,  True,  True,  True,  True,  True,  True])

In [36]:
signatures_mask[0]

tensor([False,  True,  True,  True,  True,  True,  True,  True,  True])

In [37]:
path_mask_ = torch.sum(path, 2) == 0

In [38]:
signatures_mask_ = path_mask[:, :-1]

In [39]:
path_mask_[0]

tensor([False,  True,  True,  True,  True,  True,  True,  True,  True,  True])

In [40]:
torch.equal(path_mask, path_mask_)

True

In [41]:
torch.equal(signatures_mask, signatures_mask_)

True

In [42]:
path_mask.dtype

torch.bool

In [43]:
path[0]

tensor([[-7.2296,  2.7356,  8.0972],
        [ 0.0000,  0.0000,  0.0000],
        [ 0.0000,  0.0000,  0.0000],
        [ 0.0000,  0.0000,  0.0000],
        [ 0.0000,  0.0000,  0.0000],
        [ 0.0000,  0.0000,  0.0000],
        [ 0.0000,  0.0000,  0.0000],
        [ 0.0000,  0.0000,  0.0000],
        [ 0.0000,  0.0000,  0.0000],
        [ 0.0000,  0.0000,  0.0000]], dtype=torch.float64)

In [44]:
signatures[0]

tensor([[ 7.2296, -2.7356, -8.0972,  0.0000,  0.0000,  0.0000],
        [ 7.2296, -2.7356, -8.0972,  0.0000,  0.0000,  0.0000],
        [ 7.2296, -2.7356, -8.0972,  0.0000,  0.0000,  0.0000],
        [ 7.2296, -2.7356, -8.0972,  0.0000,  0.0000,  0.0000],
        [ 7.2296, -2.7356, -8.0972,  0.0000,  0.0000,  0.0000],
        [ 7.2296, -2.7356, -8.0972,  0.0000,  0.0000,  0.0000],
        [ 7.2296, -2.7356, -8.0972,  0.0000,  0.0000,  0.0000],
        [ 7.2296, -2.7356, -8.0972,  0.0000,  0.0000,  0.0000],
        [ 7.2296, -2.7356, -8.0972,  0.0000,  0.0000,  0.0000]],
       dtype=torch.float64)

In [45]:
path_mask[0]

tensor([False,  True,  True,  True,  True,  True,  True,  True,  True,  True])

In [46]:
signatures_mask[0]

tensor([False,  True,  True,  True,  True,  True,  True,  True,  True])

In [47]:
path[1]

tensor([[-7.2296,  2.7356,  8.0972],
        [-7.4468,  3.6928,  9.9551],
        [ 0.0000,  0.0000,  0.0000],
        [ 0.0000,  0.0000,  0.0000],
        [ 0.0000,  0.0000,  0.0000],
        [ 0.0000,  0.0000,  0.0000],
        [ 0.0000,  0.0000,  0.0000],
        [ 0.0000,  0.0000,  0.0000],
        [ 0.0000,  0.0000,  0.0000],
        [ 0.0000,  0.0000,  0.0000]], dtype=torch.float64)

In [48]:
signatures[1]

tensor([[-0.2172,  0.9573,  1.8579,  0.0000,  0.0000,  0.0000],
        [ 7.2296, -2.7356, -8.0972, -3.1634, -5.8367, -1.3345],
        [ 7.2296, -2.7356, -8.0972, -3.1634, -5.8367, -1.3345],
        [ 7.2296, -2.7356, -8.0972, -3.1634, -5.8367, -1.3345],
        [ 7.2296, -2.7356, -8.0972, -3.1634, -5.8367, -1.3345],
        [ 7.2296, -2.7356, -8.0972, -3.1634, -5.8367, -1.3345],
        [ 7.2296, -2.7356, -8.0972, -3.1634, -5.8367, -1.3345],
        [ 7.2296, -2.7356, -8.0972, -3.1634, -5.8367, -1.3345],
        [ 7.2296, -2.7356, -8.0972, -3.1634, -5.8367, -1.3345]],
       dtype=torch.float64)

In [49]:
path_mask[1]

tensor([False, False,  True,  True,  True,  True,  True,  True,  True,  True])

In [50]:
signatures_mask[1]

tensor([False, False,  True,  True,  True,  True,  True,  True,  True])

## Path mask

In [51]:
import torch.nn as nn

mha = nn.MultiheadAttention(
    embed_dim=path.shape[2],
    num_heads=1,
    batch_first=True,
).double()

In [52]:
attn_output, attn_output_weights = mha(
    path.double(), path.double(), path.double(), key_padding_mask=path_mask
)

In [53]:
i = 0
print(path[i])
print(path_mask[i])
print(attn_output[i])

tensor([[-7.2296,  2.7356,  8.0972],
        [ 0.0000,  0.0000,  0.0000],
        [ 0.0000,  0.0000,  0.0000],
        [ 0.0000,  0.0000,  0.0000],
        [ 0.0000,  0.0000,  0.0000],
        [ 0.0000,  0.0000,  0.0000],
        [ 0.0000,  0.0000,  0.0000],
        [ 0.0000,  0.0000,  0.0000],
        [ 0.0000,  0.0000,  0.0000],
        [ 0.0000,  0.0000,  0.0000]], dtype=torch.float64)
tensor([False,  True,  True,  True,  True,  True,  True,  True,  True,  True])
tensor([[-2.3385, -3.8639,  2.1563],
        [-2.3385, -3.8639,  2.1563],
        [-2.3385, -3.8639,  2.1563],
        [-2.3385, -3.8639,  2.1563],
        [-2.3385, -3.8639,  2.1563],
        [-2.3385, -3.8639,  2.1563],
        [-2.3385, -3.8639,  2.1563],
        [-2.3385, -3.8639,  2.1563],
        [-2.3385, -3.8639,  2.1563],
        [-2.3385, -3.8639,  2.1563]], dtype=torch.float64,
       grad_fn=<SelectBackward>)


In [54]:
i = 1
print(path[i])
print(path_mask[i])
print(attn_output[i])

tensor([[-7.2296,  2.7356,  8.0972],
        [-7.4468,  3.6928,  9.9551],
        [ 0.0000,  0.0000,  0.0000],
        [ 0.0000,  0.0000,  0.0000],
        [ 0.0000,  0.0000,  0.0000],
        [ 0.0000,  0.0000,  0.0000],
        [ 0.0000,  0.0000,  0.0000],
        [ 0.0000,  0.0000,  0.0000],
        [ 0.0000,  0.0000,  0.0000],
        [ 0.0000,  0.0000,  0.0000]], dtype=torch.float64)
tensor([False, False,  True,  True,  True,  True,  True,  True,  True,  True])
tensor([[-2.4279, -4.3203,  2.3048],
        [-2.4240, -4.3003,  2.2983],
        [-2.4226, -4.2931,  2.2959],
        [-2.4226, -4.2931,  2.2959],
        [-2.4226, -4.2931,  2.2959],
        [-2.4226, -4.2931,  2.2959],
        [-2.4226, -4.2931,  2.2959],
        [-2.4226, -4.2931,  2.2959],
        [-2.4226, -4.2931,  2.2959],
        [-2.4226, -4.2931,  2.2959]], dtype=torch.float64,
       grad_fn=<SelectBackward>)


In [55]:
i = 2
print(path[i])
print(path_mask[i])
print(attn_output[i])

tensor([[-7.2296,  2.7356,  8.0972],
        [-7.4468,  3.6928,  9.9551],
        [-9.0931, 12.8440,  9.0442],
        [ 0.0000,  0.0000,  0.0000],
        [ 0.0000,  0.0000,  0.0000],
        [ 0.0000,  0.0000,  0.0000],
        [ 0.0000,  0.0000,  0.0000],
        [ 0.0000,  0.0000,  0.0000],
        [ 0.0000,  0.0000,  0.0000],
        [ 0.0000,  0.0000,  0.0000]], dtype=torch.float64)
tensor([False, False, False,  True,  True,  True,  True,  True,  True,  True])
tensor([[-2.4278, -4.3206,  2.3049],
        [-2.4239, -4.3006,  2.2984],
        [-2.4803, -4.5878,  2.3918],
        [-2.2238, -5.6108,  2.7196],
        [-2.2238, -5.6108,  2.7196],
        [-2.2238, -5.6108,  2.7196],
        [-2.2238, -5.6108,  2.7196],
        [-2.2238, -5.6108,  2.7196],
        [-2.2238, -5.6108,  2.7196],
        [-2.2238, -5.6108,  2.7196]], dtype=torch.float64,
       grad_fn=<SelectBackward>)


In [56]:
i = 4
print(path[i])
print(path_mask[i])
print(attn_output[i])

tensor([[-7.2296,  2.7356,  8.0972],
        [-7.4468,  3.6928,  9.9551],
        [-9.0931, 12.8440,  9.0442],
        [-6.7662,  2.6486,  8.3875],
        [-5.3710,  7.5870, 12.4986],
        [ 0.0000,  0.0000,  0.0000],
        [ 0.0000,  0.0000,  0.0000],
        [ 0.0000,  0.0000,  0.0000],
        [ 0.0000,  0.0000,  0.0000],
        [ 0.0000,  0.0000,  0.0000]], dtype=torch.float64)
tensor([False, False, False, False, False,  True,  True,  True,  True,  True])
tensor([[-2.3568, -4.2305,  2.2408],
        [-2.3613, -4.1863,  2.2317],
        [-2.4182, -4.5371,  2.3472],
        [-2.3556, -4.2074,  2.2346],
        [-2.3724, -4.1854,  2.2383],
        [-2.1726, -5.4662,  2.5835],
        [-2.1726, -5.4662,  2.5835],
        [-2.1726, -5.4662,  2.5835],
        [-2.1726, -5.4662,  2.5835],
        [-2.1726, -5.4662,  2.5835]], dtype=torch.float64,
       grad_fn=<SelectBackward>)


## Signatures mask

In [57]:
import torch.nn as nn

mha = nn.MultiheadAttention(
    embed_dim=signatures.shape[2],
    num_heads=1,
    batch_first=True,
).double()

In [58]:
attn_output, attn_output_weights = mha(
    signatures.double(),
    signatures.double(),
    signatures.double(),
    key_padding_mask=signatures_mask,
)

In [59]:
i = 0
print(path[i])
print(signatures[i])
print(signatures_mask[i])
print(attn_output[i])

tensor([[-7.2296,  2.7356,  8.0972],
        [ 0.0000,  0.0000,  0.0000],
        [ 0.0000,  0.0000,  0.0000],
        [ 0.0000,  0.0000,  0.0000],
        [ 0.0000,  0.0000,  0.0000],
        [ 0.0000,  0.0000,  0.0000],
        [ 0.0000,  0.0000,  0.0000],
        [ 0.0000,  0.0000,  0.0000],
        [ 0.0000,  0.0000,  0.0000],
        [ 0.0000,  0.0000,  0.0000]], dtype=torch.float64)
tensor([[ 7.2296, -2.7356, -8.0972,  0.0000,  0.0000,  0.0000],
        [ 7.2296, -2.7356, -8.0972,  0.0000,  0.0000,  0.0000],
        [ 7.2296, -2.7356, -8.0972,  0.0000,  0.0000,  0.0000],
        [ 7.2296, -2.7356, -8.0972,  0.0000,  0.0000,  0.0000],
        [ 7.2296, -2.7356, -8.0972,  0.0000,  0.0000,  0.0000],
        [ 7.2296, -2.7356, -8.0972,  0.0000,  0.0000,  0.0000],
        [ 7.2296, -2.7356, -8.0972,  0.0000,  0.0000,  0.0000],
        [ 7.2296, -2.7356, -8.0972,  0.0000,  0.0000,  0.0000],
        [ 7.2296, -2.7356, -8.0972,  0.0000,  0.0000,  0.0000]],
       dtype=torch.float64)
ten

In [60]:
i = 1
print(path[i])
print(signatures[i])
print(signatures_mask[i])
print(attn_output[i])

tensor([[-7.2296,  2.7356,  8.0972],
        [-7.4468,  3.6928,  9.9551],
        [ 0.0000,  0.0000,  0.0000],
        [ 0.0000,  0.0000,  0.0000],
        [ 0.0000,  0.0000,  0.0000],
        [ 0.0000,  0.0000,  0.0000],
        [ 0.0000,  0.0000,  0.0000],
        [ 0.0000,  0.0000,  0.0000],
        [ 0.0000,  0.0000,  0.0000],
        [ 0.0000,  0.0000,  0.0000]], dtype=torch.float64)
tensor([[-0.2172,  0.9573,  1.8579,  0.0000,  0.0000,  0.0000],
        [ 7.2296, -2.7356, -8.0972, -3.1634, -5.8367, -1.3345],
        [ 7.2296, -2.7356, -8.0972, -3.1634, -5.8367, -1.3345],
        [ 7.2296, -2.7356, -8.0972, -3.1634, -5.8367, -1.3345],
        [ 7.2296, -2.7356, -8.0972, -3.1634, -5.8367, -1.3345],
        [ 7.2296, -2.7356, -8.0972, -3.1634, -5.8367, -1.3345],
        [ 7.2296, -2.7356, -8.0972, -3.1634, -5.8367, -1.3345],
        [ 7.2296, -2.7356, -8.0972, -3.1634, -5.8367, -1.3345],
        [ 7.2296, -2.7356, -8.0972, -3.1634, -5.8367, -1.3345]],
       dtype=torch.float64)
ten

In [61]:
i = 2
print(path[i])
print(signatures[i])
print(signatures_mask[i])
print(attn_output[i])

tensor([[-7.2296,  2.7356,  8.0972],
        [-7.4468,  3.6928,  9.9551],
        [-9.0931, 12.8440,  9.0442],
        [ 0.0000,  0.0000,  0.0000],
        [ 0.0000,  0.0000,  0.0000],
        [ 0.0000,  0.0000,  0.0000],
        [ 0.0000,  0.0000,  0.0000],
        [ 0.0000,  0.0000,  0.0000],
        [ 0.0000,  0.0000,  0.0000],
        [ 0.0000,  0.0000,  0.0000]], dtype=torch.float64)
tensor([[ -0.2172,   0.9573,   1.8579,   0.0000,   0.0000,   0.0000],
        [ -1.8635,  10.1084,   0.9469,  -0.2056,   1.6283,  -8.9369],
        [  7.2296,  -2.7356,  -8.0972, -34.1965,   5.7501, -48.5668],
        [  7.2296,  -2.7356,  -8.0972, -34.1965,   5.7501, -48.5668],
        [  7.2296,  -2.7356,  -8.0972, -34.1965,   5.7501, -48.5668],
        [  7.2296,  -2.7356,  -8.0972, -34.1965,   5.7501, -48.5668],
        [  7.2296,  -2.7356,  -8.0972, -34.1965,   5.7501, -48.5668],
        [  7.2296,  -2.7356,  -8.0972, -34.1965,   5.7501, -48.5668],
        [  7.2296,  -2.7356,  -8.0972, -34.1965,

In [62]:
i = 4
print(path[i])
print(signatures[i])
print(signatures_mask[i])
print(attn_output[i])

tensor([[-7.2296,  2.7356,  8.0972],
        [-7.4468,  3.6928,  9.9551],
        [-9.0931, 12.8440,  9.0442],
        [-6.7662,  2.6486,  8.3875],
        [-5.3710,  7.5870, 12.4986],
        [ 0.0000,  0.0000,  0.0000],
        [ 0.0000,  0.0000,  0.0000],
        [ 0.0000,  0.0000,  0.0000],
        [ 0.0000,  0.0000,  0.0000],
        [ 0.0000,  0.0000,  0.0000]], dtype=torch.float64)
tensor([[ -0.2172,   0.9573,   1.8579,   0.0000,   0.0000,   0.0000],
        [ -1.8635,  10.1084,   0.9469,  -0.2056,   1.6283,  -8.9369],
        [  0.4634,  -0.0869,   0.2903,  -2.4666,   1.1384,  -7.4285],
        [  1.8586,   4.8514,   4.4014,  -1.2618,   1.8884,  -8.3240],
        [  7.2296,  -2.7356,  -8.0972, -21.3409, -21.5464, -21.9455],
        [  7.2296,  -2.7356,  -8.0972, -21.3409, -21.5464, -21.9455],
        [  7.2296,  -2.7356,  -8.0972, -21.3409, -21.5464, -21.9455],
        [  7.2296,  -2.7356,  -8.0972, -21.3409, -21.5464, -21.9455],
        [  7.2296,  -2.7356,  -8.0972, -21.3409,

In [67]:
(signatures * ~signatures_mask.unsqueeze(-1))[i]

tensor([[ -0.2172,   0.9573,   1.8579,   0.0000,   0.0000,   0.0000],
        [ -1.8635,  10.1084,   0.9469,  -0.2056,   1.6283,  -8.9369],
        [  0.4634,  -0.0869,   0.2903,  -2.4666,   1.1384,  -7.4285],
        [  1.8586,   4.8514,   4.4014,  -1.2618,   1.8884,  -8.3240],
        [  7.2296,  -2.7356,  -8.0972, -21.3409, -21.5464, -21.9455],
        [  0.0000,  -0.0000,  -0.0000,  -0.0000,  -0.0000,  -0.0000],
        [  0.0000,  -0.0000,  -0.0000,  -0.0000,  -0.0000,  -0.0000],
        [  0.0000,  -0.0000,  -0.0000,  -0.0000,  -0.0000,  -0.0000],
        [  0.0000,  -0.0000,  -0.0000,  -0.0000,  -0.0000,  -0.0000]],
       dtype=torch.float64)

In [71]:
torch.sum(signatures * ~signatures_mask.unsqueeze(-1), dim=1)

torch.Size([5568, 6])

In [70]:
torch.sum(~signatures_mask, -1, keepdim=True)

torch.Size([5568, 1])

In [77]:
out = torch.sum(signatures * ~signatures_mask.unsqueeze(-1), dim=1) / torch.sum(
    ~signatures_mask, -1, keepdim=True
)

In [81]:
out[4]

tensor([ 1.4942,  2.6189, -0.1201, -5.0550, -3.3783, -9.3270],
       dtype=torch.float64)