In [1]:
import numpy as np
import pickle
import os

seed = 2023

In [2]:
import torch

# set device
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
device

device(type='cuda')

In [3]:
from nlpsig_networks.scripts.seqsignet_attention_bilstm_functions import (
    seqsignet_attention_bilstm_hyperparameter_search,
)

In [4]:
output_dir = "client_talk_type_output"
if not os.path.isdir(output_dir):
    os.makedirs(output_dir)

## AnnoMI

In [5]:
%run ../load_anno_mi.py

In [6]:
anno_mi.head()

mi_quality  transcript_id                         topic  utterance_id  \
0       high              0  reducing alcohol consumption             0   
1       high              0  reducing alcohol consumption             1   
2       high              0  reducing alcohol consumption             2   
3       high              0  reducing alcohol consumption             3   
4       high              0  reducing alcohol consumption             4   

  interlocutor timestamp                                     utterance_text  \
0    therapist  00:00:13  Thanks for filling it out. We give this form t...   
1       client  00:00:24                                              Sure.   
2    therapist  00:00:25  So, let's see. It looks that you put-- You dri...   
3       client  00:00:34                                            Mm-hmm.   
4    therapist  00:00:34  -and you usually have three to four drinks whe...   

   annotator_id therapist_input_exists therapist_input_subtype  \
0             3                  False                     NaN   
1             3                    NaN                     NaN   
2             3                   True             information   
3             3                    NaN                     NaN   
4             3                   True             information   

  reflection_exists reflection_subtype question_exists question_subtype  \
0             False                NaN            True             open   
1               NaN                NaN             NaN              NaN   
2             False                NaN           False              NaN   
3               NaN                NaN             NaN              NaN   
4             False                NaN           False              NaN   

  main_therapist_behaviour client_talk_type            datetime  speaker  
0                 question              NaN 2023-10-01 00:00:13       -1  
1                      NaN          neutral 2023-10-01 00:00:24        1  
2          therapist_input              NaN 2023-10-01 00:00:25       -1  
3                      NaN          neutral 2023-10-01 00:00:34        1  
4          therapist_input              NaN 2023-10-01 00:00:34       -1

In [7]:
with open("../anno_mi_sbert.pkl", "rb") as f:
    sbert_embeddings = pickle.load(f)

sbert_embeddings.shape

(9699, 384)

In [8]:
features = ["timeline_index", "speaker"]
standardise_method = [None, None]
include_features_in_path = True
include_features_in_input = False

In [9]:
num_epochs = 100
dimensions = [15]
swmhau_parameters = [(12, 3, 10), (8, 4, 6)]
num_layers = [1]
lstm_hidden_dim_sizes = [384]
ffn_hidden_dim_sizes = [[256, 256], [512, 512]]
dropout_rates = [0.1, 0.2]
learning_rates = [1e-3, 1e-4, 5e-4]
seeds = [1, 12, 123]
loss = "focal"
gamma = 2
validation_metric = "f1"
patience = 5

In [ ]:
kwargs = {
    "num_epochs": num_epochs,
    "df": anno_mi,
    "id_column": "transcript_id",
    "label_column": "client_talk_type",
    "embeddings": sbert_embeddings,
    "y_data": y_data_client,
    "output_dim": output_dim_client,
    "dimensions": dimensions,
    "log_signature": True,
    "swmhau_parameters": swmhau_parameters,
    "num_layers": num_layers,
    "lstm_hidden_dim_sizes": lstm_hidden_dim_sizes,
    "ffn_hidden_dim_sizes": ffn_hidden_dim_sizes,
    "dropout_rates": dropout_rates,
    "learning_rates": learning_rates,
    "seeds": seeds,
    "loss": loss,
    "gamma": gamma,
    "device": device,
    "features": features,
    "standardise_method": standardise_method,
    "include_features_in_path": include_features_in_path,
    "include_features_in_input": include_features_in_input,
    "path_indices": client_index,
    "split_ids": client_transcript_id,
    "k_fold": True,
    "patience": patience,
    "validation_metric": validation_metric,
    "verbose": False,
}

# history_length=11

In [10]:
shift = 3
window_size = 5
n = 3

In [11]:
(
    seqsignet_network_umap_kfold_11,
    best_seqsignet_network_umap_kfold_11,
    _,
    __,
) = seqsignet_attention_bilstm_hyperparameter_search(
    shift=shift,
    window_size=window_size,
    n=n,
    dim_reduce_methods=["umap"],
    results_output=f"{output_dir}/seqsignet_attention_bilstm_umap_focal_{gamma}_{shift}_{window_size}_{n}_kfold.csv",
    **kwargs,
)

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]


##################################################
dimension: 15 | method: umap
given shift 3, window size 5 and n 3: history length = 11
[INFO] Concatenating the embeddings to the dataframe...
[INFO] - columns beginning with 'e' denote the full embddings.
[INFO] - columns beginning with 'd' denote the dimension reduced embeddings.
[INFO] Adding time feature columns into dataframe in `.df`.
[INFO] Adding 'time_encoding' feature...
[INFO] Adding 'time_diff' feature...
[INFO] Adding 'timeline_index' feature...
[INFO] Padding ids and storing in `.df_padded` and `.array_padded` attributes.


  0%|          | 0/9699 [00:00<?, ?it/s]

[INFO] The path was created for each item in the dataframe, by looking at its history, so to include embeddings in the FFN input, we concatenate the embeddings for each sentence / text.


  0%|          | 0/2 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/2 [00:00<?, ?it/s]

  0%|          | 0/2 [00:00<?, ?it/s]

  0%|          | 0/3 [00:00<?, ?it/s]

  0%|          | 0/3 [00:00<?, ?it/s]

  0%|          | 0/2 [00:00<?, ?it/s]

  0%|          | 0/3 [00:00<?, ?it/s]

  0%|          | 0/3 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/2 [00:00<?, ?it/s]

  0%|          | 0/2 [00:00<?, ?it/s]

  0%|          | 0/3 [00:00<?, ?it/s]

  0%|          | 0/3 [00:00<?, ?it/s]

  0%|          | 0/2 [00:00<?, ?it/s]

  0%|          | 0/3 [00:00<?, ?it/s]

  0%|          | 0/3 [00:00<?, ?it/s]

given shift 3, window size 5 and n 3: history length = 11
[INFO] Concatenating the embeddings to the dataframe...
[INFO] - columns beginning with 'e' denote the full embddings.
[INFO] - columns beginning with 'd' denote the dimension reduced embeddings.
[INFO] Adding time feature columns into dataframe in `.df`.
[INFO] Adding 'time_encoding' feature...
[INFO] Adding 'time_diff' feature...
[INFO] Adding 'timeline_index' feature...
[INFO] Padding ids and storing in `.df_padded` and `.array_padded` attributes.


  0%|          | 0/9699 [00:00<?, ?it/s]

[INFO] The path was created for each item in the dataframe, by looking at its history, so to include embeddings in the FFN input, we concatenate the embeddings for each sentence / text.
saving results dataframe to CSV for this hyperparameter search in client_talk_type_output/seqsignet_umap_focal_2_3_5_3_kfold.csv
saving the best model results dataframe to CSV for this hyperparameter search in client_talk_type_output/seqsignet_umap_focal_2_3_5_3_kfold_best_model.csv


In [12]:
seqsignet_network_umap_kfold_11

loss  accuracy        f1  \
0   None  0.648659  0.517767   
0   None  0.615517  0.511053   
0   None  0.637356  0.515575   
0   None  0.617241  0.450167   
0   None  0.597126  0.461168   
..   ...       ...       ...   
0   None  0.587548  0.440304   
0   None  0.619923  0.447408   
0   None  0.627395  0.512006   
0   None  0.627203  0.514281   
0   None  0.629885  0.505598   

                                            f1_scores  precision  \
0   [0.7772155558768252, 0.4223545579477783, 0.353...   0.517290   
0   [0.7432182490752158, 0.4442602569415665, 0.345...   0.503654   
0   [0.7616253483937216, 0.43152454780361754, 0.35...   0.510153   
0   [0.7559346126510306, 0.37090909090909085, 0.22...   0.460155   
0   [0.7349540468425733, 0.3761538461538462, 0.272...   0.460052   
..                                                ...        ...   
0   [0.7296175511414172, 0.3670886075949367, 0.224...   0.443223   
0     [0.76, 0.3348017621145375, 0.24742268041237114]   0.458681   
0   [0.7545984746523104, 0.42966101694915254, 0.35...   0.504541   
0   [0.7529091733413934, 0.44661776691116545, 0.34...   0.505567   
0   [0.7609277430865298, 0.4276206322795341, 0.328...   0.499050   

                                     precision_scores    recall  \
0        [0.777103209019948, 0.4747682801235839, 0.3]  0.529533   
0   [0.7957095709570957, 0.4462947543713572, 0.268...  0.541035   
0   [0.7728490622208991, 0.45135135135135135, 0.30...  0.527424   
0   [0.7433603578417668, 0.36342042755344417, 0.27...  0.445582   
0   [0.7539537712895377, 0.3523054755043228, 0.273...  0.463754   
..                                                ...       ...   
0   [0.7484793187347932, 0.3344640434192673, 0.246...  0.441301   
0   [0.7311598075895244, 0.3591682419659735, 0.285...  0.440974   
0   [0.7813564571074636, 0.4416376306620209, 0.290...  0.531128   
0   [0.7885406774295664, 0.44122383252818037, 0.28...  0.533259   
0   [0.783047735618115, 0.4312080536912752, 0.2828...  0.518342   

                                        recall_scores valid_loss  \
0   [0.7773279352226721, 0.3803630363036304, 0.430...       None   
0   [0.6972238288027762, 0.44224422442244227, 0.48...       None   
0   [0.7507229612492771, 0.41336633663366334, 0.41...       None   
0   [0.7689415847310584, 0.3787128712871287, 0.189...       None   
0   [0.7168883747831116, 0.4034653465346535, 0.270...       None   
..                                                ...        ...   
0   [0.711683053788317, 0.4067656765676568, 0.2054...       None   
0   [0.7912087912087912, 0.31353135313531355, 0.21...       None   
0   [0.7296124927703875, 0.4183168316831683, 0.445...       None   
0   [0.7203585887796414, 0.4521452145214521, 0.427...       None   
0   [0.7400231347599768, 0.4240924092409241, 0.390...       None   

    valid_accuracy  ...  seed loss_function  gamma k_fold  n_splits  \
0         0.666346  ...     1         focal      2   True         5   
0         0.652858  ...    12         focal      2   True         5   
0         0.671805  ...   123         focal      2   True         5   
0         0.655588  ...     1         focal      2   True         5   
0         0.627810  ...    12         focal      2   True         5   
..             ...  ...   ...           ...    ...    ...       ...   
0         0.627970  ...    12         focal      2   True         5   
0         0.632948  ...   123         focal      2   True         5   
0         0.657836  ...     1         focal      2   True         5   
0         0.660726  ...    12         focal      2   True         5   
0         0.667951  ...   123         focal      2   True         5   

   augmentation_type  hidden_dim_aug    comb_method  batch_size  model_id  
0             Conv1d            None  concatenation          64         0  
0             Conv1d            None  concatenation          64         0  
0             Conv1d            None  concatenation          64         0  
0             Conv1d   

In [13]:
best_seqsignet_network_umap_kfold_11["f1"].mean()

0.5152682953388444

In [14]:
best_seqsignet_network_umap_kfold_11["precision"].mean()

0.5113237357910293

In [15]:
best_seqsignet_network_umap_kfold_11["recall"].mean()

0.529177068468366

In [16]:
np.stack(best_seqsignet_network_umap_kfold_11["f1_scores"]).mean(axis=0)

array([0.76634954, 0.43163664, 0.3478187 ])

In [17]:
np.stack(best_seqsignet_network_umap_kfold_11["precision_scores"]).mean(axis=0)

array([0.77823326, 0.46188991, 0.29384804])

In [18]:
np.stack(best_seqsignet_network_umap_kfold_11["recall_scores"]).mean(axis=0)

array([0.75486794, 0.40539054, 0.42727273])

## GRP

In [19]:
(
    seqsignet_network_grp_kfold_11,
    best_seqsignet_network_grp_kfold_11,
    _,
    __,
) = seqsignet_attention_bilstm_hyperparameter_search(
    shift=shift,
    window_size=window_size,
    n=n,
    dim_reduce_methods=["gaussian_random_projection"],
    results_output=f"{output_dir}/seqsignet_attention_bilstm_grp_focal_{gamma}_{shift}_{window_size}_{n}_kfold.csv",
    **kwargs,
)

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]


##################################################
dimension: 15 | method: gaussian_random_projection
given shift 3, window size 5 and n 3: history length = 11
[INFO] Concatenating the embeddings to the dataframe...
[INFO] - columns beginning with 'e' denote the full embddings.
[INFO] - columns beginning with 'd' denote the dimension reduced embeddings.
[INFO] Adding time feature columns into dataframe in `.df`.
[INFO] Adding 'time_encoding' feature...
[INFO] Adding 'time_diff' feature...
[INFO] Adding 'timeline_index' feature...
[INFO] Padding ids and storing in `.df_padded` and `.array_padded` attributes.


  0%|          | 0/9699 [00:00<?, ?it/s]

[INFO] The path was created for each item in the dataframe, by looking at its history, so to include embeddings in the FFN input, we concatenate the embeddings for each sentence / text.


  0%|          | 0/2 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/2 [00:00<?, ?it/s]

  0%|          | 0/2 [00:00<?, ?it/s]

  0%|          | 0/3 [00:00<?, ?it/s]

  0%|          | 0/3 [00:00<?, ?it/s]

  0%|          | 0/2 [00:00<?, ?it/s]

  0%|          | 0/3 [00:00<?, ?it/s]

  0%|          | 0/3 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/2 [00:00<?, ?it/s]

  0%|          | 0/2 [00:00<?, ?it/s]

  0%|          | 0/3 [00:00<?, ?it/s]

  0%|          | 0/3 [00:00<?, ?it/s]

  0%|          | 0/2 [00:00<?, ?it/s]

  0%|          | 0/3 [00:00<?, ?it/s]

  0%|          | 0/3 [00:00<?, ?it/s]

given shift 3, window size 5 and n 3: history length = 11
[INFO] Concatenating the embeddings to the dataframe...
[INFO] - columns beginning with 'e' denote the full embddings.
[INFO] - columns beginning with 'd' denote the dimension reduced embeddings.
[INFO] Adding time feature columns into dataframe in `.df`.
[INFO] Adding 'time_encoding' feature...
[INFO] Adding 'time_diff' feature...
[INFO] Adding 'timeline_index' feature...
[INFO] Padding ids and storing in `.df_padded` and `.array_padded` attributes.


  0%|          | 0/9699 [00:00<?, ?it/s]

[INFO] The path was created for each item in the dataframe, by looking at its history, so to include embeddings in the FFN input, we concatenate the embeddings for each sentence / text.
saving results dataframe to CSV for this hyperparameter search in client_talk_type_output/seqsignet_grp_focal_2_3_5_3_kfold.csv
saving the best model results dataframe to CSV for this hyperparameter search in client_talk_type_output/seqsignet_grp_focal_2_3_5_3_kfold_best_model.csv


In [20]:
seqsignet_network_grp_kfold_11

loss  accuracy        f1  \
0   None  0.652299  0.518804   
0   None  0.632759  0.521371   
0   None  0.643487  0.516848   
0   None  0.641571  0.493559   
0   None  0.636398  0.489759   
..   ...       ...       ...   
0   None  0.625096  0.492728   
0   None  0.634100  0.501154   
0   None  0.636782  0.517590   
0   None  0.627778  0.520280   
0   None  0.634483  0.516413   

                                            f1_scores  precision  \
0   [0.7800057290174734, 0.42033898305084744, 0.35...   0.525227   
0   [0.7591836734693879, 0.44646548160396854, 0.35...   0.512386   
0   [0.7703272727272727, 0.4270172257479601, 0.353...   0.515151   
0   [0.7721078573499565, 0.4323681078936929, 0.276...   0.496613   
0   [0.764366156511695, 0.4210116731517509, 0.2838...   0.500582   
..                                                ...        ...   
0   [0.7554900515843773, 0.4189189189189189, 0.303...   0.489408   
0   [0.7625941793470231, 0.43998425816607634, 0.30...   0.497748   
0   [0.7622140221402214, 0.43686309260079753, 0.35...   0.513465   
0   [0.7545440659844203, 0.450891007045172, 0.3554...   0.511788   
0   [0.7618057618057619, 0.4324793747286148, 0.354...   0.510447   

                                     precision_scores    recall  \
0   [0.7727014755959137, 0.5087924970691676, 0.294...  0.532148   
0   [0.7953753563509661, 0.44739022369511183, 0.29...  0.543290   
0   [0.774948785484343, 0.4738430583501006, 0.2966...  0.530246   
0   [0.7741279069767442, 0.4163483575248281, 0.299...  0.492044   
0   [0.7632641291810842, 0.39837997054491897, 0.34...  0.485159   
..                                                ...       ...   
0   [0.7703636910129246, 0.4041411042944785, 0.293...  0.496848   
0   [0.7795228027786167, 0.42061700526711815, 0.29...  0.505566   
0   [0.7784142297256557, 0.4717703349282297, 0.290...  0.535389   
0   [0.7996115247652962, 0.4529558701082431, 0.282...  0.547104   
0   [0.782967032967033, 0.45646196150320806, 0.291...  0.535126   

                                        recall_scores valid_loss  \
0   [0.7874493927125507, 0.3580858085808581, 0.450...       None   
0   [0.7261422787738577, 0.44554455445544555, 0.45...       None   
0   [0.7657605552342395, 0.3886138613861386, 0.436...       None   
0   [0.7700983227299016, 0.44966996699669964, 0.25...       None   
0   [0.7654713707345286, 0.44636963696369636, 0.24...       None   
..                                                ...        ...   
0   [0.7411798727588201, 0.43481848184818483, 0.31...       None   
0   [0.7463851937536148, 0.4612211221122112, 0.309...       None   
0   [0.7466743782533256, 0.4067656765676568, 0.452...       None   
0   [0.7142857142857143, 0.44884488448844884, 0.47...       None   
0   [0.7417582417582418, 0.41089108910891087, 0.45...       None   

    valid_accuracy  ...  seed loss_function  gamma k_fold  n_splits  \
0         0.665222  ...     1         focal      2   True         5   
0         0.655106  ...    12         focal      2   True         5   
0         0.667309  ...   123         focal      2   True         5   
0         0.667630  ...     1         focal      2   True         5   
0         0.664740  ...    12         focal      2   True         5   
..             ...  ...   ...           ...    ...    ...       ...   
0         0.659441  ...    12         focal      2   True         5   
0         0.654785  ...   123         focal      2   True         5   
0         0.652055  ...     1         focal      2   True         5   
0         0.656551  ...    12         focal      2   True         5   
0         0.667470  ...   123         focal      2   True         5   

   augmentation_type  hidden_dim_aug    comb_method  batch_size  model_id  
0             Conv1d            None  concatenation          64         0  
0             Conv1d            None  concatenation          64         0  
0             Conv1d            None  concatenation          64         0  
0             Conv1d   

In [21]:
best_seqsignet_network_grp_kfold_11["f1"].mean()

0.5147234162261934

In [22]:
best_seqsignet_network_grp_kfold_11["precision"].mean()

0.5076724690123672

In [23]:
best_seqsignet_network_grp_kfold_11["recall"].mean()

0.5290366044508827

In [24]:
np.stack(best_seqsignet_network_grp_kfold_11["f1_scores"]).mean(axis=0)

array([0.75824939, 0.44796599, 0.33795487])

In [25]:
np.stack(best_seqsignet_network_grp_kfold_11["precision_scores"]).mean(axis=0)

array([0.78300825, 0.4497759 , 0.29023325])

In [26]:
np.stack(best_seqsignet_network_grp_kfold_11["recall_scores"]).mean(axis=0)

array([0.7350106 , 0.44664466, 0.40545455])

# history_length=20

In [27]:
shift = 3
window_size = 5
n = 6

In [28]:
(
    seqsignet_network_umap_kfold_20,
    best_seqsignet_network_umap_kfold_20,
    _,
    __,
) = seqsignet_attention_bilstm_hyperparameter_search(
    shift=shift,
    window_size=window_size,
    n=n,
    dim_reduce_methods=["umap"],
    results_output=f"{output_dir}/seqsignet_attention_bilstm_umap_focal_{gamma}_{shift}_{window_size}_{n}_kfold.csv",
    **kwargs,
)

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]


##################################################
dimension: 15 | method: umap
given shift 3, window size 5 and n 6: history length = 20
[INFO] Concatenating the embeddings to the dataframe...
[INFO] - columns beginning with 'e' denote the full embddings.
[INFO] - columns beginning with 'd' denote the dimension reduced embeddings.
[INFO] Adding time feature columns into dataframe in `.df`.
[INFO] Adding 'time_encoding' feature...
[INFO] Adding 'time_diff' feature...
[INFO] Adding 'timeline_index' feature...
[INFO] Padding ids and storing in `.df_padded` and `.array_padded` attributes.


  0%|          | 0/9699 [00:00<?, ?it/s]

[INFO] The path was created for each item in the dataframe, by looking at its history, so to include embeddings in the FFN input, we concatenate the embeddings for each sentence / text.


  0%|          | 0/2 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/2 [00:00<?, ?it/s]

  0%|          | 0/2 [00:00<?, ?it/s]

  0%|          | 0/3 [00:00<?, ?it/s]

  0%|          | 0/3 [00:00<?, ?it/s]

  0%|          | 0/2 [00:00<?, ?it/s]

  0%|          | 0/3 [00:00<?, ?it/s]

  0%|          | 0/3 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/2 [00:00<?, ?it/s]

  0%|          | 0/2 [00:00<?, ?it/s]

  0%|          | 0/3 [00:00<?, ?it/s]

  0%|          | 0/3 [00:00<?, ?it/s]

  0%|          | 0/2 [00:00<?, ?it/s]

  0%|          | 0/3 [00:00<?, ?it/s]

  0%|          | 0/3 [00:00<?, ?it/s]

given shift 3, window size 5 and n 6: history length = 20
[INFO] Concatenating the embeddings to the dataframe...
[INFO] - columns beginning with 'e' denote the full embddings.
[INFO] - columns beginning with 'd' denote the dimension reduced embeddings.
[INFO] Adding time feature columns into dataframe in `.df`.
[INFO] Adding 'time_encoding' feature...
[INFO] Adding 'time_diff' feature...
[INFO] Adding 'timeline_index' feature...
[INFO] Padding ids and storing in `.df_padded` and `.array_padded` attributes.


  0%|          | 0/9699 [00:00<?, ?it/s]

[INFO] The path was created for each item in the dataframe, by looking at its history, so to include embeddings in the FFN input, we concatenate the embeddings for each sentence / text.
saving results dataframe to CSV for this hyperparameter search in client_talk_type_output/seqsignet_umap_focal_2_3_5_6_kfold.csv
saving the best model results dataframe to CSV for this hyperparameter search in client_talk_type_output/seqsignet_umap_focal_2_3_5_6_kfold_best_model.csv


In [29]:
seqsignet_network_umap_kfold_20

loss  accuracy        f1  \
0   None  0.652107  0.522199   
0   None  0.629694  0.518186   
0   None  0.636207  0.511797   
0   None  0.619349  0.459311   
0   None  0.594636  0.445205   
..   ...       ...       ...   
0   None  0.576820  0.440587   
0   None  0.607088  0.437618   
0   None  0.631992  0.515900   
0   None  0.615517  0.514863   
0   None  0.636973  0.516142   

                                            f1_scores  precision  \
0   [0.7807347411050045, 0.4256314312441534, 0.360...   0.523550   
0   [0.7580423845098337, 0.4555921052631579, 0.340...   0.510175   
0   [0.7632935631168066, 0.4327979712595097, 0.339...   0.506039   
0   [0.7639348984588794, 0.3730355665839537, 0.240...   0.460229   
0   [0.7374708624708625, 0.35980148883374685, 0.23...   0.443590   
..                                                ...        ...   
0   [0.7235142118863049, 0.3683431952662721, 0.229...   0.438489   
0   [0.7525471039776692, 0.30319148936170215, 0.25...   0.444726   
0   [0.7598738549331732, 0.44557390936044045, 0.34...   0.509159   
0   [0.7412849773331249, 0.4581049334377447, 0.345...   0.505450   
0   [0.7641481481481481, 0.43225270157938483, 0.35...   0.508942   

                                     precision_scores    recall  \
0   [0.7809606481481481, 0.49136069114470843, 0.29...  0.536822   
0   [0.8016768784263141, 0.4540983606557377, 0.274...  0.541700   
0   [0.7778444911438006, 0.4436741767764298, 0.296...  0.522694   
0   [0.7609756097560976, 0.37396351575456055, 0.24...  0.458464   
0   [0.7431004110393423, 0.36069651741293535, 0.22...  0.447249   
..                                                ...       ...   
0   [0.762576097404678, 0.33378016085790885, 0.219...  0.446989   
0   [0.7272727272727273, 0.3275862068965517, 0.279...  0.433334   
0   [0.7903780068728522, 0.4577893820713664, 0.279...  0.535816   
0   [0.8067369853691732, 0.43591654247391953, 0.27...  0.545201   
0   [0.7834143377885784, 0.4355108877721943, 0.307...  0.528586   

                                        recall_scores valid_loss  \
0   [0.780508964719491, 0.37541254125412543, 0.454...       None   
0   [0.7189126662810873, 0.4570957095709571, 0.449...       None   
0   [0.7492770387507229, 0.42244224422442245, 0.39...       None   
0   [0.7669172932330827, 0.3721122112211221, 0.236...       None   
0   [0.731925968768074, 0.3589108910891089, 0.2509...       None   
..                                                ...        ...   
0   [0.6882591093117408, 0.41089108910891087, 0.24...       None   
0   [0.7796414112203586, 0.28217821782178215, 0.23...       None   
0   [0.7316367842683632, 0.43399339933993397, 0.44...       None   
0   [0.6856564488143435, 0.48267326732673266, 0.46...       None   
0   [0.7458068247541931, 0.429042904290429, 0.4109...       None   

    valid_accuracy  ...  seed loss_function  gamma k_fold  n_splits  \
0         0.672286  ...     1         focal      2   True         5   
0         0.648362  ...    12         focal      2   True         5   
0         0.668272  ...   123         focal      2   True         5   
0         0.649005  ...     1         focal      2   True         5   
0         0.638728  ...    12         focal      2   True         5   
..             ...  ...   ...           ...    ...    ...       ...   
0         0.634554  ...    12         focal      2   True         5   
0         0.641940  ...   123         focal      2   True         5   
0         0.659602  ...     1         focal      2   True         5   
0         0.656551  ...    12         focal      2   True         5   
0         0.666346  ...   123         focal      2   True         5   

   augmentation_type  hidden_dim_aug    comb_method  batch_size  model_id  
0             Conv1d            None  concatenation          64         0  
0             Conv1d            None  concatenation          64         0  
0             Conv1d            None  concatenation          64         0  
0             Conv1d   

In [30]:
best_seqsignet_network_umap_kfold_20["f1"].mean()

0.5110348126431621

In [31]:
best_seqsignet_network_umap_kfold_20["precision"].mean()

0.5054653302183464

In [32]:
best_seqsignet_network_umap_kfold_20["recall"].mean()

0.5227404566174759

In [33]:
np.stack(best_seqsignet_network_umap_kfold_20["f1_scores"]).mean(axis=0)

array([0.76300401, 0.43453073, 0.33556969])

In [34]:
np.stack(best_seqsignet_network_umap_kfold_20["precision_scores"]).mean(axis=0)

array([0.78217366, 0.44060033, 0.29362201])

In [35]:
np.stack(best_seqsignet_network_umap_kfold_20["recall_scores"]).mean(axis=0)

array([0.74513206, 0.4309681 , 0.39212121])

## GRP

In [36]:
(
    seqsignet_network_grp_kfold_20,
    best_seqsignet_network_grp_kfold_20,
    _,
    __,
) = seqsignet_attention_bilstm_hyperparameter_search(
    shift=shift,
    window_size=window_size,
    n=n,
    dim_reduce_methods=["gaussian_random_projection"],
    results_output=f"{output_dir}/seqsignet_attention_bilstm_grp_focal_{gamma}_{shift}_{window_size}_{n}_kfold.csv",
    **kwargs,
)

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]


##################################################
dimension: 15 | method: gaussian_random_projection
given shift 3, window size 5 and n 6: history length = 20
[INFO] Concatenating the embeddings to the dataframe...
[INFO] - columns beginning with 'e' denote the full embddings.
[INFO] - columns beginning with 'd' denote the dimension reduced embeddings.
[INFO] Adding time feature columns into dataframe in `.df`.
[INFO] Adding 'time_encoding' feature...
[INFO] Adding 'time_diff' feature...
[INFO] Adding 'timeline_index' feature...
[INFO] Padding ids and storing in `.df_padded` and `.array_padded` attributes.


  0%|          | 0/9699 [00:00<?, ?it/s]

[INFO] The path was created for each item in the dataframe, by looking at its history, so to include embeddings in the FFN input, we concatenate the embeddings for each sentence / text.


  0%|          | 0/2 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/2 [00:00<?, ?it/s]

  0%|          | 0/2 [00:00<?, ?it/s]

  0%|          | 0/3 [00:00<?, ?it/s]

  0%|          | 0/3 [00:00<?, ?it/s]

  0%|          | 0/2 [00:00<?, ?it/s]

  0%|          | 0/3 [00:00<?, ?it/s]

  0%|          | 0/3 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/2 [00:00<?, ?it/s]

  0%|          | 0/2 [00:00<?, ?it/s]

  0%|          | 0/3 [00:00<?, ?it/s]

  0%|          | 0/3 [00:00<?, ?it/s]

  0%|          | 0/2 [00:00<?, ?it/s]

  0%|          | 0/3 [00:00<?, ?it/s]

  0%|          | 0/3 [00:00<?, ?it/s]

given shift 3, window size 5 and n 6: history length = 20
[INFO] Concatenating the embeddings to the dataframe...
[INFO] - columns beginning with 'e' denote the full embddings.
[INFO] - columns beginning with 'd' denote the dimension reduced embeddings.
[INFO] Adding time feature columns into dataframe in `.df`.
[INFO] Adding 'time_encoding' feature...
[INFO] Adding 'time_diff' feature...
[INFO] Adding 'timeline_index' feature...
[INFO] Padding ids and storing in `.df_padded` and `.array_padded` attributes.


  0%|          | 0/9699 [00:00<?, ?it/s]

[INFO] The path was created for each item in the dataframe, by looking at its history, so to include embeddings in the FFN input, we concatenate the embeddings for each sentence / text.
saving results dataframe to CSV for this hyperparameter search in client_talk_type_output/seqsignet_grp_focal_2_3_5_6_kfold.csv
saving the best model results dataframe to CSV for this hyperparameter search in client_talk_type_output/seqsignet_grp_focal_2_3_5_6_kfold_best_model.csv


In [37]:
seqsignet_network_grp_kfold_20

loss  accuracy        f1  \
0   None  0.650575  0.515646   
0   None  0.628352  0.518639   
0   None  0.633525  0.518490   
0   None  0.636015  0.486497   
0   None  0.622989  0.482590   
..   ...       ...       ...   
0   None  0.618966  0.491071   
0   None  0.627778  0.494648   
0   None  0.621648  0.509752   
0   None  0.623563  0.516679   
0   None  0.629885  0.514915   

                                            f1_scores  precision  \
0   [0.7787661406025825, 0.42282507015902715, 0.34...   0.518339   
0   [0.756256635825876, 0.43875838926174493, 0.360...   0.510206   
0   [0.7588673621460507, 0.4384980578334053, 0.358...   0.511932   
0   [0.7682594346391162, 0.40824742268041236, 0.28...   0.489642   
0   [0.7575623432197137, 0.4174795161919625, 0.272...   0.480719   
..                                                ...        ...   
0   [0.7485154394299287, 0.42151394422310756, 0.30...   0.485891   
0   [0.7560035576638008, 0.43534812547819435, 0.29...   0.493170   
0   [0.7491995731056563, 0.4506927465362673, 0.329...   0.501845   
0   [0.7492307692307693, 0.45714285714285713, 0.34...   0.507096   
0   [0.756134051466188, 0.43718166383701185, 0.351...   0.507637   

                                     precision_scores    recall  \
0   [0.7727790432801822, 0.48812095032397407, 0.29...  0.525322   
0   [0.7952153110047847, 0.4462457337883959, 0.289...  0.544152   
0   [0.7829028290282903, 0.4597285067873303, 0.293...  0.538469   
0   [0.7624608373682712, 0.40807914262159933, 0.29...  0.483885   
0   [0.7734257306417596, 0.3960029607698001, 0.272...  0.485494   
..                                                ...       ...   
0   [0.7690665039658329, 0.40755007704160245, 0.28...  0.498198   
0   [0.7755474452554745, 0.405848787446505, 0.2981...  0.498055   
0   [0.7923250564334086, 0.44524959742351045, 0.26...  0.531357   
0   [0.8004602235371466, 0.44036697247706424, 0.28...  0.541016   
0   [0.7833230006199629, 0.45017482517482516, 0.28...  0.534320   

                                        recall_scores valid_loss  \
0   [0.7848467322151532, 0.37293729372937295, 0.41...       None   
0      [0.7209369577790631, 0.4315181518151815, 0.48]       None   
0     [0.7362637362637363, 0.41914191419141916, 0.46]       None   
0   [0.7741469057258531, 0.4084158415841584, 0.269...       None   
0   [0.7423366107576634, 0.4414191419141914, 0.272...       None   
..                                                ...        ...   
0   [0.7290341237709659, 0.43646864686468645, 0.32...       None   
0   [0.7374204742625795, 0.46947194719471946, 0.28...       None   
0   [0.7105263157894737, 0.45627062706270627, 0.42...       None   
0   [0.7041642567958357, 0.4752475247524752, 0.443...       None   
0   [0.7307692307692307, 0.4249174917491749, 0.447...       None   

    valid_accuracy  ...  seed loss_function  gamma k_fold  n_splits  \
0         0.672929  ...     1         focal      2   True         5   
0         0.650771  ...    12         focal      2   True         5   
0         0.662813  ...   123         focal      2   True         5   
0         0.678388  ...     1         focal      2   True         5   
0         0.662010  ...    12         focal      2   True         5   
..             ...  ...   ...           ...    ...    ...       ...   
0         0.663937  ...    12         focal      2   True         5   
0         0.676140  ...   123         focal      2   True         5   
0         0.652858  ...     1         focal      2   True         5   
0         0.651413  ...    12         focal      2   True         5   
0         0.671162  ...   123         focal      2   True         5   

   augmentation_type  hidden_dim_aug    comb_method  batch_size  model_id  
0             Conv1d            None  concatenation          64         0  
0             Conv1d            None  concatenation          64         0  
0             Conv1d            None  concatenation          64         0  
0             Conv1d   

In [38]:
best_seqsignet_network_grp_kfold_20["f1"].mean()

0.5086250178315498

In [39]:
best_seqsignet_network_grp_kfold_20["precision"].mean()

0.5022627929359947

In [40]:
best_seqsignet_network_grp_kfold_20["recall"].mean()

0.5249572086570523

In [41]:
np.stack(best_seqsignet_network_grp_kfold_20["f1_scores"]).mean(axis=0)

array([0.75458885, 0.43588655, 0.33539966])

In [42]:
np.stack(best_seqsignet_network_grp_kfold_20["precision_scores"]).mean(axis=0)

array([0.78293591, 0.43796772, 0.28588475])

In [43]:
np.stack(best_seqsignet_network_grp_kfold_20["recall_scores"]).mean(axis=0)

array([0.72826297, 0.43509351, 0.41151515])

# history_length=35

In [44]:
shift = 3
window_size = 5
n = 11

In [45]:
(
    seqsignet_network_umap_kfold_35,
    best_seqsignet_network_umap_kfold_35,
    _,
    __,
) = seqsignet_attention_bilstm_hyperparameter_search(
    shift=shift,
    window_size=window_size,
    n=n,
    dim_reduce_methods=["umap"],
    results_output=f"{output_dir}/seqsignet_attention_bilstm_umap_focal_{gamma}_{shift}_{window_size}_{n}_kfold.csv",
    **kwargs,
)

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]


##################################################
dimension: 15 | method: umap
given shift 3, window size 5 and n 11: history length = 35
[INFO] Concatenating the embeddings to the dataframe...
[INFO] - columns beginning with 'e' denote the full embddings.
[INFO] - columns beginning with 'd' denote the dimension reduced embeddings.
[INFO] Adding time feature columns into dataframe in `.df`.
[INFO] Adding 'time_encoding' feature...
[INFO] Adding 'time_diff' feature...
[INFO] Adding 'timeline_index' feature...
[INFO] Padding ids and storing in `.df_padded` and `.array_padded` attributes.


  0%|          | 0/9699 [00:00<?, ?it/s]

[INFO] The path was created for each item in the dataframe, by looking at its history, so to include embeddings in the FFN input, we concatenate the embeddings for each sentence / text.


  0%|          | 0/2 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/2 [00:00<?, ?it/s]

  0%|          | 0/2 [00:00<?, ?it/s]

  0%|          | 0/3 [00:00<?, ?it/s]

  0%|          | 0/3 [00:00<?, ?it/s]

  0%|          | 0/2 [00:00<?, ?it/s]

  0%|          | 0/3 [00:00<?, ?it/s]

  0%|          | 0/3 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/2 [00:00<?, ?it/s]

  0%|          | 0/2 [00:00<?, ?it/s]

  0%|          | 0/3 [00:00<?, ?it/s]

  0%|          | 0/3 [00:00<?, ?it/s]

  0%|          | 0/2 [00:00<?, ?it/s]

  0%|          | 0/3 [00:00<?, ?it/s]

  0%|          | 0/3 [00:00<?, ?it/s]

given shift 3, window size 5 and n 11: history length = 35
[INFO] Concatenating the embeddings to the dataframe...
[INFO] - columns beginning with 'e' denote the full embddings.
[INFO] - columns beginning with 'd' denote the dimension reduced embeddings.
[INFO] Adding time feature columns into dataframe in `.df`.
[INFO] Adding 'time_encoding' feature...
[INFO] Adding 'time_diff' feature...
[INFO] Adding 'timeline_index' feature...
[INFO] Padding ids and storing in `.df_padded` and `.array_padded` attributes.


  0%|          | 0/9699 [00:00<?, ?it/s]

[INFO] The path was created for each item in the dataframe, by looking at its history, so to include embeddings in the FFN input, we concatenate the embeddings for each sentence / text.
saving results dataframe to CSV for this hyperparameter search in client_talk_type_output/seqsignet_umap_focal_2_3_5_11_kfold.csv
saving the best model results dataframe to CSV for this hyperparameter search in client_talk_type_output/seqsignet_umap_focal_2_3_5_11_kfold_best_model.csv


In [46]:
seqsignet_network_umap_kfold_35

loss  accuracy        f1  \
0   None  0.626437  0.507571   
0   None  0.627011  0.518118   
0   None  0.634291  0.514651   
0   None  0.595211  0.450426   
0   None  0.578927  0.437230   
..   ...       ...       ...   
0   None  0.570498  0.435795   
0   None  0.610345  0.448161   
0   None  0.633142  0.522410   
0   None  0.615134  0.510413   
0   None  0.631992  0.506878   

                                            f1_scores  precision  \
0   [0.7521470543920445, 0.4487079091620987, 0.321...   0.499894   
0   [0.7534812547819434, 0.45809601301871444, 0.34...   0.509484   
0   [0.7606673556769527, 0.428633784373636, 0.3546...   0.509175   
0   [0.7335691128794576, 0.37205827418752335, 0.24...   0.456286   
0   [0.7241582988777319, 0.3381947181710682, 0.249...   0.435450   
..                                                ...        ...   
0   [0.7167752689801485, 0.35642081617371774, 0.23...   0.433388   
0   [0.7477863467580692, 0.3705195328231978, 0.226...   0.455767   
0   [0.7560829077801141, 0.4459179444674679, 0.365...   0.513258   
0   [0.7429986074578369, 0.445421831267493, 0.3428...   0.501446   
0   [0.7578356002365464, 0.43481748896911354, 0.32...   0.501614   

                                     precision_scores    recall  \
0   [0.7851525636992766, 0.4269746646795827, 0.287...  0.520010   
0   [0.8001299967500812, 0.4518459069020867, 0.276...  0.542468   
0   [0.7770739064856712, 0.45505097312326226, 0.29...  0.531230   
0   [0.7478966346153846, 0.33993174061433445, 0.28...  0.449618   
0   [0.7398913699456849, 0.3237735849056604, 0.242...  0.439801   
..                                                ...       ...   
0   [0.7529449219993632, 0.32625085675119947, 0.22...  0.441917   
0   [0.7387133182844243, 0.3619197482297404, 0.266...  0.444329   
0   [0.7865625, 0.4479600333055787, 0.305250305250...  0.542106   
0   [0.7990016638935108, 0.4321179208688906, 0.273...  0.537968   
0   [0.7752571082879612, 0.42310694769711166, 0.30...  0.513701   

                                        recall_scores valid_loss  \
0   [0.7218045112781954, 0.47277227722772275, 0.36...       None   
0   [0.7119722382880278, 0.4645214521452145, 0.450...       None   
0   [0.7449392712550608, 0.4051155115511551, 0.443...       None   
0   [0.7197802197802198, 0.41089108910891087, 0.21...       None   
0   [0.7090803932909197, 0.35396039603960394, 0.25...       None   
..                                                ...        ...   
0   [0.6839213418160787, 0.3927392739273927, 0.249...       None   
0   [0.757085020242915, 0.3795379537953795, 0.1963...       None   
0   [0.7278773857721226, 0.4438943894389439, 0.454...       None   
0      [0.694331983805668, 0.45957095709570955, 0.46]       None   
0   [0.7411798727588201, 0.4471947194719472, 0.352...       None   

    valid_accuracy  ...  seed loss_function  gamma k_fold  n_splits  \
0         0.656069  ...     1         focal      2   True         5   
0         0.658799  ...    12         focal      2   True         5   
0         0.660886  ...   123         focal      2   True         5   
0         0.647720  ...     1         focal      2   True         5   
0         0.641779  ...    12         focal      2   True         5   
..             ...  ...   ...           ...    ...    ...       ...   
0         0.629897  ...    12         focal      2   True         5   
0         0.645472  ...   123         focal      2   True         5   
0         0.662331  ...     1         focal      2   True         5   
0         0.649486  ...    12         focal      2   True         5   
0         0.673732  ...   123         focal      2   True         5   

   augmentation_type  hidden_dim_aug    comb_method  batch_size  model_id  
0             Conv1d            None  concatenation          64         0  
0             Conv1d            None  concatenation          64         0  
0             Conv1d            None  concatenation          64         0  
0             Conv1d   

In [47]:
best_seqsignet_network_umap_kfold_35["f1"].mean()

0.5051327142948336

In [48]:
best_seqsignet_network_umap_kfold_35["precision"].mean()

0.5001260035714683

In [49]:
best_seqsignet_network_umap_kfold_35["recall"].mean()

0.5201368307256791

In [50]:
np.stack(best_seqsignet_network_umap_kfold_35["f1_scores"]).mean(axis=0)

array([0.76069323, 0.42301289, 0.33169203])

In [51]:
np.stack(best_seqsignet_network_umap_kfold_35["precision_scores"]).mean(axis=0)

array([0.78075721, 0.4408063 , 0.2788145 ])

In [52]:
np.stack(best_seqsignet_network_umap_kfold_35["recall_scores"]).mean(axis=0)

array([0.74185464, 0.4070407 , 0.41151515])

## GRP

In [53]:
(
    seqsignet_network_grp_kfold_35,
    best_seqsignet_network_grp_kfold_35,
    _,
    __,
) = seqsignet_attention_bilstm_hyperparameter_search(
    shift=shift,
    window_size=window_size,
    n=n,
    dim_reduce_methods=["gaussian_random_projection"],
    results_output=f"{output_dir}/seqsignet_attention_bilstm_grp_focal_{gamma}_{shift}_{window_size}_{n}_kfold.csv",
    **kwargs,
)

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]


##################################################
dimension: 15 | method: gaussian_random_projection
given shift 3, window size 5 and n 11: history length = 35
[INFO] Concatenating the embeddings to the dataframe...
[INFO] - columns beginning with 'e' denote the full embddings.
[INFO] - columns beginning with 'd' denote the dimension reduced embeddings.
[INFO] Adding time feature columns into dataframe in `.df`.
[INFO] Adding 'time_encoding' feature...
[INFO] Adding 'time_diff' feature...
[INFO] Adding 'timeline_index' feature...
[INFO] Padding ids and storing in `.df_padded` and `.array_padded` attributes.


  0%|          | 0/9699 [00:00<?, ?it/s]

[INFO] The path was created for each item in the dataframe, by looking at its history, so to include embeddings in the FFN input, we concatenate the embeddings for each sentence / text.


  0%|          | 0/2 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/2 [00:00<?, ?it/s]

  0%|          | 0/2 [00:00<?, ?it/s]

  0%|          | 0/3 [00:00<?, ?it/s]

  0%|          | 0/3 [00:00<?, ?it/s]

  0%|          | 0/2 [00:00<?, ?it/s]

  0%|          | 0/3 [00:00<?, ?it/s]

  0%|          | 0/3 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/2 [00:00<?, ?it/s]

  0%|          | 0/2 [00:00<?, ?it/s]

  0%|          | 0/3 [00:00<?, ?it/s]

  0%|          | 0/3 [00:00<?, ?it/s]

  0%|          | 0/2 [00:00<?, ?it/s]

  0%|          | 0/3 [00:00<?, ?it/s]

  0%|          | 0/3 [00:00<?, ?it/s]

given shift 3, window size 5 and n 11: history length = 35
[INFO] Concatenating the embeddings to the dataframe...
[INFO] - columns beginning with 'e' denote the full embddings.
[INFO] - columns beginning with 'd' denote the dimension reduced embeddings.
[INFO] Adding time feature columns into dataframe in `.df`.
[INFO] Adding 'time_encoding' feature...
[INFO] Adding 'time_diff' feature...
[INFO] Adding 'timeline_index' feature...
[INFO] Padding ids and storing in `.df_padded` and `.array_padded` attributes.


  0%|          | 0/9699 [00:00<?, ?it/s]

[INFO] The path was created for each item in the dataframe, by looking at its history, so to include embeddings in the FFN input, we concatenate the embeddings for each sentence / text.
saving results dataframe to CSV for this hyperparameter search in client_talk_type_output/seqsignet_grp_focal_2_3_5_11_kfold.csv
saving the best model results dataframe to CSV for this hyperparameter search in client_talk_type_output/seqsignet_grp_focal_2_3_5_11_kfold_best_model.csv


In [54]:
seqsignet_network_grp_kfold_35

loss  accuracy        f1  \
0   None  0.638314  0.517802   
0   None  0.628352  0.513674   
0   None  0.630268  0.520610   
0   None  0.619732  0.472331   
0   None  0.621839  0.485408   
..   ...       ...       ...   
0   None  0.623180  0.490960   
0   None  0.611111  0.479441   
0   None  0.611877  0.501858   
0   None  0.624521  0.519868   
0   None  0.629885  0.505956   

                                            f1_scores  precision  \
0   [0.7665443873807777, 0.4102564102564103, 0.376...   0.512991   
0   [0.7548602673147022, 0.4530820573223401, 0.333...   0.504792   
0   [0.753048780487805, 0.46323240267400706, 0.345...   0.510768   
0   [0.75894155277697, 0.38498789346246975, 0.2730...   0.472363   
0   [0.7557386698057681, 0.4020061728395061, 0.298...   0.486536   
..                                                ...        ...   
0   [0.7553967545034985, 0.4224598930481283, 0.295...   0.488489   
0   [0.7473150357995226, 0.39923224568138194, 0.29...   0.476336   
0   [0.7398224670951944, 0.4348171701112878, 0.330...   0.493016   
0   [0.7512721665381651, 0.4519230769230769, 0.356...   0.510013   
0   [0.7578422749926708, 0.41412803532008824, 0.34...   0.501744   

                                     precision_scores    recall  \
0   [0.7780756627941614, 0.45103857566765576, 0.30...  0.537196   
0   [0.7949456174024312, 0.4322097378277154, 0.287...  0.530353   
0   [0.7962604771115409, 0.4425244177310293, 0.293...  0.540086   
0   [0.7631578947368421, 0.3767772511848341, 0.277...  0.472476   
0   [0.7693229478729778, 0.377536231884058, 0.3127...  0.485983   
..                                                ...       ...   
0   [0.7784596501994476, 0.3933143669985775, 0.293...  0.495432   
0   [0.7717190388170055, 0.37329504666188085, 0.28...  0.484483   
0   [0.7857607282184655, 0.419478527607362, 0.2738...  0.522820   
0   [0.8047571853320119, 0.4392523364485981, 0.286...  0.547509   
0   [0.7684304399524375, 0.4453941120607787, 0.291...  0.519987   

                                        recall_scores valid_loss  \
0     [0.7553499132446501, 0.37623762376237624, 0.48]       None   
0   [0.7186234817813765, 0.4760726072607261, 0.396...       None   
0       [0.7142857142857143, 0.485973597359736, 0.42]       None   
0   [0.7547715442452284, 0.3935643564356436, 0.269...       None   
0   [0.7426257952573742, 0.4298679867986799, 0.285...       None   
..                                                ...        ...   
0   [0.7336610757663389, 0.45627062706270627, 0.29...       None   
0        [0.7244071717755928, 0.429042904290429, 0.3]       None   
0   [0.6989589358010411, 0.4513201320132013, 0.418...       None   
0   [0.7044534412955465, 0.46534653465346537, 0.47...       None   
0   [0.7475419317524581, 0.38696369636963696, 0.42...       None   

    valid_accuracy  ...  seed loss_function  gamma k_fold  n_splits  \
0         0.677425  ...     1         focal      2   True         5   
0         0.655106  ...    12         focal      2   True         5   
0         0.664258  ...   123         focal      2   True         5   
0         0.676943  ...     1         focal      2   True         5   
0         0.666667  ...    12         focal      2   True         5   
..             ...  ...   ...           ...    ...    ...       ...   
0         0.666667  ...    12         focal      2   True         5   
0         0.670681  ...   123         focal      2   True         5   
0         0.663616  ...     1         focal      2   True         5   
0         0.655588  ...    12         focal      2   True         5   
0         0.672768  ...   123         focal      2   True         5   

   augmentation_type  hidden_dim_aug    comb_method  batch_size  model_id  
0             Conv1d            None  concatenation          64         0  
0             Conv1d            None  concatenation          64         0  
0             Conv1d            None  concatenation          64         0  
0             Conv1d   

In [55]:
best_seqsignet_network_grp_kfold_35["f1"].mean()

0.5048031299754757

In [56]:
best_seqsignet_network_grp_kfold_35["precision"].mean()

0.4996885597712146

In [57]:
best_seqsignet_network_grp_kfold_35["recall"].mean()

0.5193448527424557

In [58]:
np.stack(best_seqsignet_network_grp_kfold_35["f1_scores"]).mean(axis=0)

array([0.75848112, 0.41722529, 0.33870297])

In [59]:
np.stack(best_seqsignet_network_grp_kfold_35["precision_scores"]).mean(axis=0)

array([0.77729726, 0.43406062, 0.2877078 ])

In [60]:
np.stack(best_seqsignet_network_grp_kfold_35["recall_scores"]).mean(axis=0)

array([0.74117987, 0.40291529, 0.41393939])

# history_length=80

In [61]:
shift = 3
window_size = 5
n = 26

In [62]:
(
    seqsignet_network_umap_kfold_80,
    best_seqsignet_network_umap_kfold_80,
    _,
    __,
) = seqsignet_attention_bilstm_hyperparameter_search(
    shift=shift,
    window_size=window_size,
    n=n,
    dim_reduce_methods=["umap"],
    results_output=f"{output_dir}/seqsignet_attention_bilstm_umap_focal_{gamma}_{shift}_{window_size}_{n}_kfold.csv",
    **kwargs,
)

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]


##################################################
dimension: 15 | method: umap
given shift 3, window size 5 and n 26: history length = 80
[INFO] Concatenating the embeddings to the dataframe...
[INFO] - columns beginning with 'e' denote the full embddings.
[INFO] - columns beginning with 'd' denote the dimension reduced embeddings.
[INFO] Adding time feature columns into dataframe in `.df`.
[INFO] Adding 'time_encoding' feature...
[INFO] Adding 'time_diff' feature...
[INFO] Adding 'timeline_index' feature...
[INFO] Padding ids and storing in `.df_padded` and `.array_padded` attributes.


  0%|          | 0/9699 [00:00<?, ?it/s]

[INFO] The path was created for each item in the dataframe, by looking at its history, so to include embeddings in the FFN input, we concatenate the embeddings for each sentence / text.


  0%|          | 0/2 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/2 [00:00<?, ?it/s]

  0%|          | 0/2 [00:00<?, ?it/s]

  0%|          | 0/3 [00:00<?, ?it/s]

  0%|          | 0/3 [00:00<?, ?it/s]

  0%|          | 0/2 [00:00<?, ?it/s]

  0%|          | 0/3 [00:00<?, ?it/s]

  0%|          | 0/3 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/2 [00:00<?, ?it/s]

  0%|          | 0/2 [00:00<?, ?it/s]

  0%|          | 0/3 [00:00<?, ?it/s]

  0%|          | 0/3 [00:00<?, ?it/s]

  0%|          | 0/2 [00:00<?, ?it/s]

  0%|          | 0/3 [00:00<?, ?it/s]

  0%|          | 0/3 [00:00<?, ?it/s]

given shift 3, window size 5 and n 26: history length = 80
[INFO] Concatenating the embeddings to the dataframe...
[INFO] - columns beginning with 'e' denote the full embddings.
[INFO] - columns beginning with 'd' denote the dimension reduced embeddings.
[INFO] Adding time feature columns into dataframe in `.df`.
[INFO] Adding 'time_encoding' feature...
[INFO] Adding 'time_diff' feature...
[INFO] Adding 'timeline_index' feature...
[INFO] Padding ids and storing in `.df_padded` and `.array_padded` attributes.


  0%|          | 0/9699 [00:00<?, ?it/s]

[INFO] The path was created for each item in the dataframe, by looking at its history, so to include embeddings in the FFN input, we concatenate the embeddings for each sentence / text.
saving results dataframe to CSV for this hyperparameter search in client_talk_type_output/seqsignet_umap_focal_2_3_5_26_kfold.csv
saving the best model results dataframe to CSV for this hyperparameter search in client_talk_type_output/seqsignet_umap_focal_2_3_5_26_kfold_best_model.csv


In [63]:
seqsignet_network_umap_kfold_80

loss  accuracy        f1  \
0   None  0.614751  0.504572   
0   None  0.628161  0.513304   
0   None  0.622414  0.505098   
0   None  0.585824  0.444541   
0   None  0.588697  0.433771   
..   ...       ...       ...   
0   None  0.543678  0.424076   
0   None  0.584291  0.442262   
0   None  0.610536  0.498548   
0   None  0.620115  0.508205   
0   None  0.629885  0.508994   

                                            f1_scores  precision  \
0   [0.7456752655538694, 0.40692989524576956, 0.36...   0.494692   
0   [0.7561453777710753, 0.43944353518821605, 0.34...   0.504775   
0   [0.7480137910358267, 0.4344689378757515, 0.332...   0.497266   
0   [0.7340236686390532, 0.34236453201970446, 0.25...   0.440866   
0   [0.7303206997084547, 0.3580582524271845, 0.212...   0.436574   
..                                                ...        ...   
0   [0.6924676155445386, 0.35852142623487077, 0.22...   0.429045   
0   [0.7277330950253201, 0.36322188449848025, 0.23...   0.441353   
0   [0.7398386360176586, 0.42319999999999997, 0.33...   0.489841   
0   [0.7476522265980006, 0.4328297264189465, 0.344...   0.499435   
0   [0.7544221698113208, 0.4277310924369747, 0.344...   0.502737   

                                     precision_scores    recall  \
0   [0.7844827586206896, 0.39763779527559057, 0.30...  0.525428   
0   [0.7901040025212732, 0.43587662337662336, 0.28...  0.531776   
0   [0.7765328353563647, 0.4224473889321902, 0.292...  0.518055   
0   [0.7513628104179285, 0.34068627450980393, 0.23...  0.450812   
0   [0.736331569664903, 0.33822450476889215, 0.235...  0.433105   
..                                                ...       ...   
0   [0.774597495527728, 0.2970189701897019, 0.2155...  0.435167   
0   [0.7503071253071253, 0.33661971830985915, 0.23...  0.445138   
0   [0.781099324975892, 0.4107142857142857, 0.2777...  0.517911   
0   [0.7849872773536896, 0.4284559417946645, 0.284...  0.528516   
0   [0.7693926638604931, 0.4357876712328767, 0.303...  0.519997   

                                        recall_scores valid_loss  \
0   [0.7105263157894737, 0.4166666666666667, 0.449...       None   
0   [0.7249855407750144, 0.4430693069306931, 0.427...       None   
0   [0.7215153267784846, 0.4471947194719472, 0.385...       None   
0   [0.7174667437825333, 0.34405940594059403, 0.29...       None   
0   [0.7244071717755928, 0.3803630363036304, 0.194...       None   
..                                                ...        ...   
0   [0.6260844418739155, 0.4521452145214521, 0.227...       None   
0   [0.7064777327935222, 0.3943894389438944, 0.234...       None   
0   [0.7027183342972817, 0.43646864686468645, 0.41...       None   
0   [0.7137073452862926, 0.4372937293729373, 0.434...       None   
0      [0.7400231347599768, 0.41996699669966997, 0.4]       None   

    valid_accuracy  ...  seed loss_function  gamma k_fold  n_splits  \
0         0.671805  ...     1         focal      2   True         5   
0         0.670841  ...    12         focal      2   True         5   
0         0.670199  ...   123         focal      2   True         5   
0         0.667470  ...     1         focal      2   True         5   
0         0.654143  ...    12         focal      2   True         5   
..             ...  ...   ...           ...    ...    ...       ...   
0         0.644027  ...    12         focal      2   True         5   
0         0.663777  ...   123         focal      2   True         5   
0         0.668433  ...     1         focal      2   True         5   
0         0.670360  ...    12         focal      2   True         5   
0         0.683365  ...   123         focal      2   True         5   

   augmentation_type  hidden_dim_aug    comb_method  batch_size  model_id  
0             Conv1d            None  concatenation          64         0  
0             Conv1d            None  concatenation          64         0  
0             Conv1d            None  concatenation          64         0  
0             Conv1d   

In [64]:
best_seqsignet_network_umap_kfold_80["f1"].mean()

0.5055488929971662

In [65]:
best_seqsignet_network_umap_kfold_80["precision"].mean()

0.5005151478442117

In [66]:
best_seqsignet_network_umap_kfold_80["recall"].mean()

0.5126134242496931

In [67]:
np.stack(best_seqsignet_network_umap_kfold_80["f1_scores"]).mean(axis=0)

array([0.76133442, 0.41532917, 0.33998309])

In [68]:
np.stack(best_seqsignet_network_umap_kfold_80["precision_scores"]).mean(axis=0)

array([0.77503627, 0.41158203, 0.31492714])

In [69]:
np.stack(best_seqsignet_network_umap_kfold_80["recall_scores"]).mean(axis=0)

array([0.7481203 , 0.41941694, 0.37030303])

## GRP

In [70]:
(
    seqsignet_network_grp_kfold_80,
    best_seqsignet_network_grp_kfold_80,
    _,
    __,
) = seqsignet_attention_bilstm_hyperparameter_search(
    shift=shift,
    window_size=window_size,
    n=n,
    dim_reduce_methods=["gaussian_random_projection"],
    results_output=f"{output_dir}/seqsignet_attention_bilstm_grp_focal_{gamma}_{shift}_{window_size}_{n}_kfold.csv",
    **kwargs,
)

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]


##################################################
dimension: 15 | method: gaussian_random_projection
given shift 3, window size 5 and n 26: history length = 80
[INFO] Concatenating the embeddings to the dataframe...
[INFO] - columns beginning with 'e' denote the full embddings.
[INFO] - columns beginning with 'd' denote the dimension reduced embeddings.
[INFO] Adding time feature columns into dataframe in `.df`.
[INFO] Adding 'time_encoding' feature...
[INFO] Adding 'time_diff' feature...
[INFO] Adding 'timeline_index' feature...
[INFO] Padding ids and storing in `.df_padded` and `.array_padded` attributes.


  0%|          | 0/9699 [00:00<?, ?it/s]

[INFO] The path was created for each item in the dataframe, by looking at its history, so to include embeddings in the FFN input, we concatenate the embeddings for each sentence / text.


  0%|          | 0/2 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/2 [00:00<?, ?it/s]

  0%|          | 0/2 [00:00<?, ?it/s]

  0%|          | 0/3 [00:00<?, ?it/s]

  0%|          | 0/3 [00:00<?, ?it/s]

  0%|          | 0/2 [00:00<?, ?it/s]

  0%|          | 0/3 [00:00<?, ?it/s]

  0%|          | 0/3 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/2 [00:00<?, ?it/s]

  0%|          | 0/2 [00:00<?, ?it/s]

  0%|          | 0/3 [00:00<?, ?it/s]

  0%|          | 0/3 [00:00<?, ?it/s]

  0%|          | 0/2 [00:00<?, ?it/s]

  0%|          | 0/3 [00:00<?, ?it/s]

  0%|          | 0/3 [00:00<?, ?it/s]

given shift 3, window size 5 and n 26: history length = 80
[INFO] Concatenating the embeddings to the dataframe...
[INFO] - columns beginning with 'e' denote the full embddings.
[INFO] - columns beginning with 'd' denote the dimension reduced embeddings.
[INFO] Adding time feature columns into dataframe in `.df`.
[INFO] Adding 'time_encoding' feature...
[INFO] Adding 'time_diff' feature...
[INFO] Adding 'timeline_index' feature...
[INFO] Padding ids and storing in `.df_padded` and `.array_padded` attributes.


  0%|          | 0/9699 [00:00<?, ?it/s]

[INFO] The path was created for each item in the dataframe, by looking at its history, so to include embeddings in the FFN input, we concatenate the embeddings for each sentence / text.
saving results dataframe to CSV for this hyperparameter search in client_talk_type_output/seqsignet_grp_focal_2_3_5_26_kfold.csv
saving the best model results dataframe to CSV for this hyperparameter search in client_talk_type_output/seqsignet_grp_focal_2_3_5_26_kfold_best_model.csv


In [71]:
seqsignet_network_grp_kfold_80

loss  accuracy        f1  \
0   None  0.597893  0.491474   
0   None  0.618008  0.504033   
0   None  0.622605  0.503981   
0   None  0.588889  0.453034   
0   None  0.600958  0.461330   
..   ...       ...       ...   
0   None  0.611877  0.477272   
0   None  0.587165  0.473785   
0   None  0.626437  0.513548   
0   None  0.613985  0.494078   
0   None  0.620881  0.508549   

                                            f1_scores  precision  \
0   [0.7277182235834609, 0.4052718286655684, 0.341...   0.483167   
0   [0.7487054523301858, 0.4375510204081633, 0.325...   0.496422   
0   [0.746742549048974, 0.440221694378464, 0.32497...   0.496725   
0   [0.73224043715847, 0.34405144694533757, 0.2828...   0.449449   
0   [0.7425742574257426, 0.3440501043841336, 0.297...   0.458392   
..                                                ...        ...   
0   [0.7495575221238937, 0.38652050345107586, 0.29...   0.472989   
0   [0.7168601099572389, 0.3901569186875891, 0.314...   0.473661   
0   [0.750488795307565, 0.4412840308817554, 0.3488...   0.504690   
0   [0.7439831528279182, 0.4302229562345169, 0.308...   0.487710   
0   [0.7429091460640073, 0.4494036167756829, 0.333...   0.500076   

                                     precision_scores    recall  \
0   [0.7734375, 0.40460526315789475, 0.27145922746...  0.517681   
0   [0.7908622908622909, 0.43295638126009695, 0.26...  0.524959   
0   [0.7744641192917054, 0.4231354642313546, 0.292...  0.515046   
0   [0.7482644129188047, 0.335423197492163, 0.2646...  0.457887   
0   [0.7478005865102639, 0.34826711749788675, 0.27...  0.465179   
..                                                ...       ...   
0   [0.7649006622516556, 0.38049560351718625, 0.27...  0.483125   
0   [0.7595469255663431, 0.3435929648241206, 0.317...  0.480315   
0   [0.7818865559385773, 0.4347477982385909, 0.297...  0.530451   
0   [0.7752351097178684, 0.4305785123966942, 0.257...  0.509553   
0   [0.7811802232854864, 0.42105263157894735, 0.29...  0.522748   

                                        recall_scores valid_loss  \
0     [0.6871023713128976, 0.40594059405940597, 0.46]       None   
0   [0.7108155002891845, 0.44224422442244227, 0.42...       None   
0   [0.7209369577790631, 0.45874587458745875, 0.36...       None   
0   [0.7168883747831116, 0.35313531353135313, 0.30...       None   
0   [0.7374204742625795, 0.33993399339933994, 0.31...       None   
..                                                ...        ...   
0   [0.7348178137651822, 0.3927392739273927, 0.321...       None   
0   [0.678716020821284, 0.4513201320132013, 0.3109...       None   
0   [0.7215153267784846, 0.44801980198019803, 0.42...       None   
0   [0.7151532677848468, 0.4298679867986799, 0.383...       None   
0   [0.7082128397917872, 0.48184818481848185, 0.37...       None   

    valid_accuracy  ...  seed loss_function  gamma k_fold  n_splits  \
0         0.676301  ...     1         focal      2   True         5   
0         0.671805  ...    12         focal      2   True         5   
0         0.677264  ...   123         focal      2   True         5   
0         0.692197  ...     1         focal      2   True         5   
0         0.684971  ...    12         focal      2   True         5   
..             ...  ...   ...           ...    ...    ...       ...   
0         0.699743  ...    12         focal      2   True         5   
0         0.692357  ...   123         focal      2   True         5   
0         0.681118  ...     1         focal      2   True         5   
0         0.678709  ...    12         focal      2   True         5   
0         0.679030  ...   123         focal      2   True         5   

   augmentation_type  hidden_dim_aug    comb_method  batch_size  model_id  
0             Conv1d            None  concatenation          64         0  
0             Conv1d            None  concatenation          64         0  
0             Conv1d            None  concatenation          64         0  
0             Conv1d   

In [72]:
best_seqsignet_network_grp_kfold_80["f1"].mean()

0.4878311051069672

In [73]:
best_seqsignet_network_grp_kfold_80["precision"].mean()

0.4839229244125589

In [74]:
best_seqsignet_network_grp_kfold_80["recall"].mean()

0.49595292477001696

In [75]:
np.stack(best_seqsignet_network_grp_kfold_80["f1_scores"]).mean(axis=0)

array([0.73329414, 0.40732229, 0.32287689])

In [76]:
np.stack(best_seqsignet_network_grp_kfold_80["precision_scores"]).mean(axis=0)

array([0.7668082 , 0.37424093, 0.31071964])

In [77]:
np.stack(best_seqsignet_network_grp_kfold_80["recall_scores"]).mean(axis=0)

array([0.70320031, 0.44829483, 0.33636364])

# history_length=110

In [78]:
shift = 3
window_size = 5
n = 36

In [79]:
(
    seqsignet_network_umap_kfold_110,
    best_seqsignet_network_umap_kfold_110,
    _,
    __,
) = seqsignet_attention_bilstm_hyperparameter_search(
    shift=shift,
    window_size=window_size,
    n=n,
    dim_reduce_methods=["umap"],
    results_output=f"{output_dir}/seqsignet_attention_bilstm_umap_focal_{gamma}_{shift}_{window_size}_{n}_kfold.csv",
    **kwargs,
)

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]


##################################################
dimension: 15 | method: umap
given shift 3, window size 5 and n 36: history length = 110
[INFO] Concatenating the embeddings to the dataframe...
[INFO] - columns beginning with 'e' denote the full embddings.
[INFO] - columns beginning with 'd' denote the dimension reduced embeddings.
[INFO] Adding time feature columns into dataframe in `.df`.
[INFO] Adding 'time_encoding' feature...
[INFO] Adding 'time_diff' feature...
[INFO] Adding 'timeline_index' feature...
[INFO] Padding ids and storing in `.df_padded` and `.array_padded` attributes.


  0%|          | 0/9699 [00:00<?, ?it/s]

[INFO] The path was created for each item in the dataframe, by looking at its history, so to include embeddings in the FFN input, we concatenate the embeddings for each sentence / text.


  0%|          | 0/2 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/2 [00:00<?, ?it/s]

  0%|          | 0/2 [00:00<?, ?it/s]

  0%|          | 0/3 [00:00<?, ?it/s]

  0%|          | 0/3 [00:00<?, ?it/s]

  0%|          | 0/2 [00:00<?, ?it/s]

  0%|          | 0/3 [00:00<?, ?it/s]

  0%|          | 0/3 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/2 [00:00<?, ?it/s]

  0%|          | 0/2 [00:00<?, ?it/s]

  0%|          | 0/3 [00:00<?, ?it/s]

  0%|          | 0/3 [00:00<?, ?it/s]

  0%|          | 0/2 [00:00<?, ?it/s]

  0%|          | 0/3 [00:00<?, ?it/s]

  0%|          | 0/3 [00:00<?, ?it/s]

given shift 3, window size 5 and n 36: history length = 110
[INFO] Concatenating the embeddings to the dataframe...
[INFO] - columns beginning with 'e' denote the full embddings.
[INFO] - columns beginning with 'd' denote the dimension reduced embeddings.
[INFO] Adding time feature columns into dataframe in `.df`.
[INFO] Adding 'time_encoding' feature...
[INFO] Adding 'time_diff' feature...
[INFO] Adding 'timeline_index' feature...
[INFO] Padding ids and storing in `.df_padded` and `.array_padded` attributes.


  0%|          | 0/9699 [00:00<?, ?it/s]

[INFO] The path was created for each item in the dataframe, by looking at its history, so to include embeddings in the FFN input, we concatenate the embeddings for each sentence / text.
saving results dataframe to CSV for this hyperparameter search in client_talk_type_output/seqsignet_umap_focal_2_3_5_36_kfold.csv
saving the best model results dataframe to CSV for this hyperparameter search in client_talk_type_output/seqsignet_umap_focal_2_3_5_36_kfold_best_model.csv


In [80]:
seqsignet_network_umap_kfold_110

loss  accuracy        f1  \
0   None  0.604215  0.501087   
0   None  0.615134  0.508203   
0   None  0.624330  0.505234   
0   None  0.580651  0.444679   
0   None  0.584483  0.435600   
..   ...       ...       ...   
0   None  0.533525  0.414881   
0   None  0.584100  0.437649   
0   None  0.598659  0.502962   
0   None  0.600192  0.489759   
0   None  0.630843  0.503434   

                                            f1_scores  precision  \
0   [0.7355613737871554, 0.40611724723874254, 0.36...   0.493837   
0   [0.7396377034080441, 0.44902816342721147, 0.33...   0.498900   
0   [0.7500746491489997, 0.4328238133547868, 0.332...   0.497878   
0   [0.7257083518765762, 0.3352781019058732, 0.273...   0.442877   
0   [0.7240579710144928, 0.3381379041682898, 0.244...   0.442453   
..                                                ...        ...   
0   [0.6863456985003946, 0.3322499097146985, 0.226...   0.414400   
0   [0.7245868070791281, 0.34749034749034746, 0.24...   0.441039   
0   [0.72234409276089, 0.4301484583174724, 0.35639...   0.492347   
0   [0.7299757281553398, 0.395882818685669, 0.3434...   0.480756   
0   [0.760673830961371, 0.39069359086918354, 0.358...   0.498959   

                                     precision_scores    recall  \
0   [0.7868204283360791, 0.4185639229422067, 0.276...  0.536199   
0   [0.7882853403141361, 0.43239113827349124, 0.27...  0.530911   
0   [0.7753086419753087, 0.42229199372056514, 0.29...  0.516775   
0   [0.7450502589095339, 0.31714495952906546, 0.26...  0.447652   
0   [0.725740848343986, 0.3202952029520295, 0.2813...  0.432277   
..                                                ...       ...   
0   [0.7556482446993396, 0.29543994861913936, 0.19...  0.427590   
0   [0.7330571174903817, 0.3265602322206096, 0.263...  0.436472   
0   [0.7883036935704515, 0.3992932862190813, 0.289...  0.532126   
0   [0.7677089980855137, 0.380517503805175, 0.2940...  0.507015   
0   [0.7640023337222871, 0.4174484052532833, 0.315...  0.513633   

                                        recall_scores valid_loss  \
0   [0.6905725853094274, 0.3943894389438944, 0.523...       None   
0   [0.6966454598033546, 0.466996699669967, 0.4290...       None   
0      [0.7264314632735686, 0.4438943894389439, 0.38]       None   
0      [0.7073452862926547, 0.3556105610561056, 0.28]       None   
0   [0.7223828802776171, 0.3580858085808581, 0.216...       None   
..                                                ...        ...   
0   [0.6286871023713129, 0.3795379537953795, 0.274...       None   
0   [0.71631000578369, 0.3712871287128713, 0.22181...       None   
0   [0.6665702718334298, 0.4661716171617162, 0.463...       None   
0   [0.6957779063042221, 0.41254125412541254, 0.41...       None   
0   [0.7573742047426258, 0.36716171617161714, 0.41...       None   

    valid_accuracy  ...  seed loss_function  gamma k_fold  n_splits  \
0         0.660405  ...     1         focal      2   True         5   
0         0.661850  ...    12         focal      2   True         5   
0         0.670039  ...   123         focal      2   True         5   
0         0.677585  ...     1         focal      2   True         5   
0         0.671805  ...    12         focal      2   True         5   
..             ...  ...   ...           ...    ...    ...       ...   
0         0.652216  ...    12         focal      2   True         5   
0         0.665382  ...   123         focal      2   True         5   
0         0.665864  ...     1         focal      2   True         5   
0         0.678388  ...    12         focal      2   True         5   
0         0.686416  ...   123         focal      2   True         5   

   augmentation_type  hidden_dim_aug    comb_method  batch_size  model_id  
0             Conv1d            None  concatenation          64         0  
0             Conv1d            None  concatenation          64         0  
0             Conv1d            None  concatenation          64         0  
0             Conv1d   

In [81]:
best_seqsignet_network_umap_kfold_110["f1"].mean()

0.49081927717515156

In [82]:
best_seqsignet_network_umap_kfold_110["precision"].mean()

0.48350598532179806

In [83]:
best_seqsignet_network_umap_kfold_110["recall"].mean()

0.5042405439695695

In [84]:
np.stack(best_seqsignet_network_umap_kfold_110["f1_scores"]).mean(axis=0)

array([0.74390267, 0.40526383, 0.32329133])

In [85]:
np.stack(best_seqsignet_network_umap_kfold_110["precision_scores"]).mean(axis=0)

array([0.77683306, 0.39075906, 0.28292584])

In [86]:
np.stack(best_seqsignet_network_umap_kfold_110["recall_scores"]).mean(axis=0)

array([0.71380374, 0.42134213, 0.37757576])

## GRP

In [87]:
(
    seqsignet_network_grp_kfold_110,
    best_seqsignet_network_grp_kfold_110,
    _,
    __,
) = seqsignet_attention_bilstm_hyperparameter_search(
    shift=shift,
    window_size=window_size,
    n=n,
    dim_reduce_methods=["gaussian_random_projection"],
    results_output=f"{output_dir}/seqsignet_attention_bilstm_grp_focal_{gamma}_{shift}_{window_size}_{n}_kfold.csv",
    **kwargs,
)

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]


##################################################
dimension: 15 | method: gaussian_random_projection
given shift 3, window size 5 and n 36: history length = 110
[INFO] Concatenating the embeddings to the dataframe...
[INFO] - columns beginning with 'e' denote the full embddings.
[INFO] - columns beginning with 'd' denote the dimension reduced embeddings.
[INFO] Adding time feature columns into dataframe in `.df`.
[INFO] Adding 'time_encoding' feature...
[INFO] Adding 'time_diff' feature...
[INFO] Adding 'timeline_index' feature...
[INFO] Padding ids and storing in `.df_padded` and `.array_padded` attributes.


  0%|          | 0/9699 [00:00<?, ?it/s]

[INFO] The path was created for each item in the dataframe, by looking at its history, so to include embeddings in the FFN input, we concatenate the embeddings for each sentence / text.


  0%|          | 0/2 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/2 [00:00<?, ?it/s]

  0%|          | 0/2 [00:00<?, ?it/s]

  0%|          | 0/3 [00:00<?, ?it/s]

  0%|          | 0/3 [00:00<?, ?it/s]

  0%|          | 0/2 [00:00<?, ?it/s]

  0%|          | 0/3 [00:00<?, ?it/s]

  0%|          | 0/3 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/2 [00:00<?, ?it/s]

  0%|          | 0/2 [00:00<?, ?it/s]

  0%|          | 0/3 [00:00<?, ?it/s]

  0%|          | 0/3 [00:00<?, ?it/s]

  0%|          | 0/2 [00:00<?, ?it/s]

  0%|          | 0/3 [00:00<?, ?it/s]

  0%|          | 0/3 [00:00<?, ?it/s]

given shift 3, window size 5 and n 36: history length = 110
[INFO] Concatenating the embeddings to the dataframe...
[INFO] - columns beginning with 'e' denote the full embddings.
[INFO] - columns beginning with 'd' denote the dimension reduced embeddings.
[INFO] Adding time feature columns into dataframe in `.df`.
[INFO] Adding 'time_encoding' feature...
[INFO] Adding 'time_diff' feature...
[INFO] Adding 'timeline_index' feature...
[INFO] Padding ids and storing in `.df_padded` and `.array_padded` attributes.


  0%|          | 0/9699 [00:00<?, ?it/s]

[INFO] The path was created for each item in the dataframe, by looking at its history, so to include embeddings in the FFN input, we concatenate the embeddings for each sentence / text.
saving results dataframe to CSV for this hyperparameter search in client_talk_type_output/seqsignet_grp_focal_2_3_5_36_kfold.csv
saving the best model results dataframe to CSV for this hyperparameter search in client_talk_type_output/seqsignet_grp_focal_2_3_5_36_kfold_best_model.csv


In [88]:
seqsignet_network_grp_kfold_110

loss  accuracy        f1  \
0   None  0.607471  0.488389   
0   None  0.636207  0.519660   
0   None  0.622797  0.504287   
0   None  0.590038  0.459997   
0   None  0.604789  0.463068   
..   ...       ...       ...   
0   None  0.603448  0.477844   
0   None  0.568965  0.459021   
0   None  0.602682  0.495795   
0   None  0.613027  0.502581   
0   None  0.620881  0.512262   

                                            f1_scores  precision  \
0   [0.740829825616356, 0.4006554690700532, 0.3236...   0.480952   
0   [0.7644938419945929, 0.4437113402061856, 0.350...   0.511253   
0   [0.7494774559570021, 0.42637540453074435, 0.33...   0.496723   
0   [0.7294787297783103, 0.37402190923317685, 0.27...   0.455378   
0   [0.7422801112249378, 0.3736780258519389, 0.273...   0.464275   
..                                                ...        ...   
0   [0.7385954381752701, 0.39625585023400933, 0.29...   0.472259   
0   [0.7009375, 0.38762886597938145, 0.28849557522...   0.458532   
0   [0.7282192619813199, 0.4260731319554849, 0.333...   0.486696   
0   [0.7385751654100631, 0.44402985074626866, 0.32...   0.494285   
0   [0.7462277091906722, 0.4390243902439024, 0.351...   0.502355   

                                     precision_scores    recall  \
0   [0.7714464621164684, 0.39788445890968266, 0.27...  0.504127   
0   [0.7953125, 0.44352844187963725, 0.29491945477...  0.537532   
0   [0.7746913580246914, 0.41825396825396827, 0.29...  0.516587   
0   [0.7566811684275948, 0.3556547619047619, 0.253...  0.467397   
0   [0.7514074074074074, 0.35570469798657717, 0.28...  0.462918   
..                                                ...       ...   
0   [0.7676232064878353, 0.3757396449704142, 0.273...  0.486639   
0   [0.7624065261726717, 0.3321554770318021, 0.281...  0.470117   
0   [0.7738366417181907, 0.4110429447852761, 0.275...  0.517248   
0   [0.7892140743176587, 0.4053133514986376, 0.288...  0.519231   
0   [0.7889139542378344, 0.4195488721804511, 0.298...  0.531864   

                                        recall_scores valid_loss  \
0   [0.7125506072874493, 0.4034653465346535, 0.396...       None   
0   [0.7359745517640255, 0.4438943894389439, 0.432...       None   
0   [0.7258530942741469, 0.43481848184818483, 0.38...       None   
0   [0.7041642567958357, 0.3943894389438944, 0.303...       None   
0   [0.7333718912666282, 0.3935643564356436, 0.261...       None   
..                                                ...        ...   
0   [0.711683053788317, 0.41914191419141916, 0.329...       None   
0   [0.6486408328513592, 0.46534653465346537, 0.29...       None   
0   [0.6876807403123193, 0.44224422442244227, 0.42...       None   
0   [0.6940427993059572, 0.4909240924092409, 0.372...       None   
0   [0.7079236552920763, 0.4603960396039604, 0.427...       None   

    valid_accuracy  ...  seed loss_function  gamma k_fold  n_splits  \
0         0.675658  ...     1         focal      2   True         5   
0         0.669075  ...    12         focal      2   True         5   
0         0.673732  ...   123         focal      2   True         5   
0         0.693160  ...     1         focal      2   True         5   
0         0.683365  ...    12         focal      2   True         5   
..             ...  ...   ...           ...    ...    ...       ...   
0         0.691875  ...    12         focal      2   True         5   
0         0.689788  ...   123         focal      2   True         5   
0         0.681920  ...     1         focal      2   True         5   
0         0.677264  ...    12         focal      2   True         5   
0         0.672608  ...   123         focal      2   True         5   

   augmentation_type  hidden_dim_aug    comb_method  batch_size  model_id  
0             Conv1d            None  concatenation          64         0  
0             Conv1d            None  concatenation          64         0  
0             Conv1d            None  concatenation          64         0  
0             Conv1d   

In [89]:
best_seqsignet_network_grp_kfold_110["f1"].mean()

0.4853650377820397

In [90]:
best_seqsignet_network_grp_kfold_110["precision"].mean()

0.482020830253151

In [91]:
best_seqsignet_network_grp_kfold_110["recall"].mean()

0.4912060974749875

In [92]:
np.stack(best_seqsignet_network_grp_kfold_110["f1_scores"]).mean(axis=0)

array([0.74312434, 0.41178784, 0.30118293])

In [93]:
np.stack(best_seqsignet_network_grp_kfold_110["precision_scores"]).mean(axis=0)

array([0.76869562, 0.38353809, 0.29382878])

In [94]:
np.stack(best_seqsignet_network_grp_kfold_110["recall_scores"]).mean(axis=0)

array([0.71920185, 0.44471947, 0.30969697])