In [1]:
import numpy as np
import pickle
import os

seed = 2023

In [2]:
import torch

# set device
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
device

device(type='cuda')

In [3]:
from nlpsig_networks.scripts.seqsignet_functions import seqsignet_hyperparameter_search

In [4]:
output_dir = "client_talk_type_output"
if not os.path.isdir(output_dir):
    os.makedirs(output_dir)

## AnnoMI

In [5]:
%run ../load_anno_mi.py

In [6]:
anno_mi.head()

mi_quality  transcript_id                         topic  utterance_id  \
0       high              0  reducing alcohol consumption             0   
1       high              0  reducing alcohol consumption             1   
2       high              0  reducing alcohol consumption             2   
3       high              0  reducing alcohol consumption             3   
4       high              0  reducing alcohol consumption             4   

  interlocutor timestamp                                     utterance_text  \
0    therapist  00:00:13  Thanks for filling it out. We give this form t...   
1       client  00:00:24                                              Sure.   
2    therapist  00:00:25  So, let's see. It looks that you put-- You dri...   
3       client  00:00:34                                            Mm-hmm.   
4    therapist  00:00:34  -and you usually have three to four drinks whe...   

   annotator_id therapist_input_exists therapist_input_subtype  \
0             3                  False                     NaN   
1             3                    NaN                     NaN   
2             3                   True             information   
3             3                    NaN                     NaN   
4             3                   True             information   

  reflection_exists reflection_subtype question_exists question_subtype  \
0             False                NaN            True             open   
1               NaN                NaN             NaN              NaN   
2             False                NaN           False              NaN   
3               NaN                NaN             NaN              NaN   
4             False                NaN           False              NaN   

  main_therapist_behaviour client_talk_type            datetime  speaker  
0                 question              NaN 2023-09-26 00:00:13       -1  
1                      NaN          neutral 2023-09-26 00:00:24        1  
2          therapist_input              NaN 2023-09-26 00:00:25       -1  
3                      NaN          neutral 2023-09-26 00:00:34        1  
4          therapist_input              NaN 2023-09-26 00:00:34       -1

In [7]:
with open("../anno_mi_sbert.pkl", "rb") as f:
    sbert_embeddings = pickle.load(f)

sbert_embeddings.shape

(9699, 384)

In [8]:
features = ["timeline_index", "speaker"]
standardise_method = [None, None]
include_features_in_path = True
include_features_in_input = False

In [9]:
num_epochs = 100
dimensions = [15]  # [50, 15]
swnu_hidden_dim_sizes_and_sig_depths = [([12], 3), ([10], 4)]
lstm_hidden_dim_sizes = [384]
ffn_hidden_dim_sizes = [[256,256],[512,512]]
dropout_rates = [0.1, 0.2]
learning_rates = [1e-3, 1e-4, 5e-4]
seeds = [1, 12, 123]
loss = "focal"
gamma = 2
validation_metric = "f1"
patience = 5

# history_length=11

In [14]:
shift = 3
window_size = 5
n = 3

In [15]:
(
    seqsignet_network_umap_kfold_11,
    best_seqsignet_network_umap_kfold_11,
    _,
    __,
) = seqsignet_hyperparameter_search(
    num_epochs=num_epochs,
    df=anno_mi,
    id_column="transcript_id",
    label_column="client_talk_type",
    embeddings=sbert_embeddings,
    y_data=y_data_client,
    output_dim=output_dim_client,
    shift=shift,
    window_size=window_size,
    n=n,
    dim_reduce_methods=["umap"],
    dimensions=dimensions,
    log_signature=True,
    swnu_hidden_dim_sizes_and_sig_depths=swnu_hidden_dim_sizes_and_sig_depths,
    lstm_hidden_dim_sizes=lstm_hidden_dim_sizes,
    ffn_hidden_dim_sizes=ffn_hidden_dim_sizes,
    dropout_rates=dropout_rates,
    learning_rates=learning_rates,
    BiLSTM=True,
    seeds=seeds,
    loss=loss,
    gamma=gamma,
    device=device,
    features=features,
    standardise_method=standardise_method,
    include_features_in_path=include_features_in_path,
    include_features_in_input=include_features_in_input,
    path_indices=client_index,
    split_ids=client_transcript_id,
    k_fold=True,
    patience=patience,
    validation_metric=validation_metric,
    results_output=f"{output_dir}/seqsignet_umap_focal_{gamma}_{shift}_{window_size}_{n}_kfold.csv",
    verbose=False,
)

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]


##################################################
dimension: 15 | method: umap
given shift 3, window size 5 and n 3: history length = 11
[INFO] Concatenating the embeddings to the dataframe...
[INFO] - columns beginning with 'e' denote the full embddings.
[INFO] - columns beginning with 'd' denote the dimension reduced embeddings.
[INFO] Adding time feature columns into dataframe in `.df`.
[INFO] Adding 'time_encoding' feature...
[INFO] Adding 'time_diff' feature...
[INFO] Adding 'timeline_index' feature...
[INFO] Padding ids and storing in `.df_padded` and `.array_padded` attributes.


  0%|          | 0/9699 [00:00<?, ?it/s]

[INFO] The path was created for each item in the dataframe, by looking at its history, so to include embeddings in the FFN input, we concatenate the embeddings for each sentence / text.


  0%|          | 0/2 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/2 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/2 [00:00<?, ?it/s]

  0%|          | 0/3 [00:00<?, ?it/s]

  0%|          | 0/3 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/2 [00:00<?, ?it/s]

  0%|          | 0/3 [00:00<?, ?it/s]

  0%|          | 0/3 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/2 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/2 [00:00<?, ?it/s]

  0%|          | 0/3 [00:00<?, ?it/s]

  0%|          | 0/3 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/2 [00:00<?, ?it/s]

  0%|          | 0/3 [00:00<?, ?it/s]

  0%|          | 0/3 [00:00<?, ?it/s]

given shift 3, window size 5 and n 3: history length = 11
[INFO] Concatenating the embeddings to the dataframe...
[INFO] - columns beginning with 'e' denote the full embddings.
[INFO] - columns beginning with 'd' denote the dimension reduced embeddings.
[INFO] Adding time feature columns into dataframe in `.df`.
[INFO] Adding 'time_encoding' feature...
[INFO] Adding 'time_diff' feature...
[INFO] Adding 'timeline_index' feature...
[INFO] Padding ids and storing in `.df_padded` and `.array_padded` attributes.


  0%|          | 0/9699 [00:00<?, ?it/s]

[INFO] The path was created for each item in the dataframe, by looking at its history, so to include embeddings in the FFN input, we concatenate the embeddings for each sentence / text.
saving results dataframe to CSV for this hyperparameter search in client_talk_type_output/seqsignet_umap_focal_2_3_5_3_kfold.csv
saving the best model results dataframe to CSV for this hyperparameter search in client_talk_type_output/seqsignet_umap_focal_2_3_5_3_kfold_best_model.csv


In [16]:
seqsignet_network_umap_kfold_11

loss  accuracy        f1  \
0   None  0.638889  0.508545   
0   None  0.607854  0.508247   
0   None  0.634866  0.512799   
0   None  0.632759  0.525914   
0   None  0.628544  0.511676   
..   ...       ...       ...   
0   None  0.646935  0.525294   
0   None  0.633716  0.514062   
0   None  0.636015  0.517543   
0   None  0.625479  0.518182   
0   None  0.636015  0.516211   

                                            f1_scores  precision  \
0   [0.7702565589215828, 0.40689325035902346, 0.34...   0.512418   
0   [0.7381772627622926, 0.4333199839807769, 0.353...   0.499695   
0   [0.7605220706848511, 0.42493415276558383, 0.35...   0.508132   
0   [0.7523186863311541, 0.46548323471400394, 0.35...   0.515452   
0   [0.7561487702459508, 0.42851516345017715, 0.35...   0.503852   
..                                                ...        ...   
0   [0.769569687178734, 0.4446280991735537, 0.3616...   0.519512   
0   [0.7607434944237919, 0.4357262103505843, 0.345...   0.506783   
0   [0.7628957930726922, 0.44041450777202074, 0.34...   0.511661   
0   [0.7538626281168731, 0.4445371142618849, 0.356...   0.510099   
0   [0.7623529411764706, 0.41953772350632357, 0.36...   0.510151   

                                     precision_scores    recall  \
0   [0.7721592560302237, 0.4846066134549601, 0.280...  0.526341   
0   [0.8049863387978142, 0.421011673151751, 0.2730...  0.542659   
0   [0.771496578399286, 0.4540337711069418, 0.2988...  0.526701   
0   [0.7932029496633536, 0.4459561602418745, 0.307...  0.545596   
0   [0.7853582554517134, 0.40994724943481536, 0.31...  0.523535   
..                                                ...       ...   
0   [0.7818561623396001, 0.445364238410596, 0.3313...  0.533247   
0   [0.7829813284358739, 0.4408783783783784, 0.296...  0.528324   
0   [0.7849495258488834, 0.46195652173913043, 0.28...  0.535492   
0   [0.8002598246183826, 0.4494097807757167, 0.280...  0.546531   
0   [0.7755834829443446, 0.44495837187789083, 0.30...  0.531841   

                                        recall_scores valid_loss  \
0     [0.7683632157316368, 0.35066006600660066, 0.46]       None   
0      [0.6816078658183922, 0.44636963696369636, 0.5]       None   
0   [0.7498554077501446, 0.39933993399339934, 0.43...       None   
0   [0.7154424522845575, 0.4867986798679868, 0.434...       None   
0   [0.7290341237709659, 0.44884488448844884, 0.39...       None   
..                                                ...        ...   
0   [0.7576633892423366, 0.4438943894389439, 0.398...       None   
0   [0.739733950260266, 0.4306930693069307, 0.4145...       None   
0   [0.7420474262579526, 0.4207920792079208, 0.443...       None   
0   [0.7125506072874493, 0.4397689768976898, 0.487...       None   
0   [0.7495662232504338, 0.39686468646864687, 0.44...       None   

    valid_accuracy  ...  BiLSTM loss_function  gamma k_fold  n_splits  \
0         0.666346  ...    True         focal      2   True         5   
0         0.644188  ...    True         focal      2   True         5   
0         0.670520  ...    True         focal      2   True         5   
0         0.667470  ...    True         focal      2   True         5   
0         0.663777  ...    True         focal      2   True         5   
..             ...  ...     ...           ...    ...    ...       ...   
0         0.667791  ...    True         focal      2   True         5   
0         0.672768  ...    True         focal      2   True         5   
0         0.662171  ...    True         focal      2   True         5   
0         0.648523  ...    True         focal      2   True         5   
0         0.663455  ...    True         focal      2   True         5   

   augmentation_type  hidden_dim_aug    comb_method  batch_size  model_id  
0             Conv1d            None  concatenation          64         0  
0             Conv1d            None  concatenation          64         0  
0             Conv1d            None  concatenation          64         0  

In [17]:
best_seqsignet_network_umap_kfold_11["f1"].mean()

0.5207346518508088

In [18]:
best_seqsignet_network_umap_kfold_11["precision"].mean()

0.5127868034452244

In [19]:
best_seqsignet_network_umap_kfold_11["recall"].mean()

0.5373551744995205

In [20]:
np.stack(best_seqsignet_network_umap_kfold_11["f1_scores"]).mean(axis=0)

array([0.75825457, 0.44574979, 0.3581996 ])

In [21]:
np.stack(best_seqsignet_network_umap_kfold_11["precision_scores"]).mean(axis=0)

array([0.78626238, 0.444712  , 0.30738603])

In [22]:
np.stack(best_seqsignet_network_umap_kfold_11["recall_scores"]).mean(axis=0)

array([0.73231155, 0.44884488, 0.43090909])

## GRP

In [23]:
(
    seqsignet_network_grp_kfold_11,
    best_seqsignet_network_grp_kfold_11,
    _,
    __,
) = seqsignet_hyperparameter_search(
    num_epochs=num_epochs,
    df=anno_mi,
    id_column="transcript_id",
    label_column="client_talk_type",
    embeddings=sbert_embeddings,
    y_data=y_data_client,
    output_dim=output_dim_client,
    shift=shift,
    window_size=window_size,
    n=n,
    dim_reduce_methods=["gaussian_random_projection"],
    dimensions=dimensions,
    log_signature=True,
    swnu_hidden_dim_sizes_and_sig_depths=swnu_hidden_dim_sizes_and_sig_depths,
    lstm_hidden_dim_sizes=lstm_hidden_dim_sizes,
    ffn_hidden_dim_sizes=ffn_hidden_dim_sizes,
    dropout_rates=dropout_rates,
    learning_rates=learning_rates,
    BiLSTM=True,
    seeds=seeds,
    loss=loss,
    gamma=gamma,
    device=device,
    features=features,
    standardise_method=standardise_method,
    include_features_in_path=include_features_in_path,
    include_features_in_input=include_features_in_input,
    path_indices=client_index,
    k_fold=True,
    patience=patience,
    split_ids=client_transcript_id,
    validation_metric=validation_metric,
    results_output=f"{output_dir}/seqsignet_grp_focal_{gamma}_{shift}_{window_size}_{n}_kfold.csv",
    verbose=False,
)

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]


##################################################
dimension: 15 | method: gaussian_random_projection
given shift 3, window size 5 and n 3: history length = 11
[INFO] Concatenating the embeddings to the dataframe...
[INFO] - columns beginning with 'e' denote the full embddings.
[INFO] - columns beginning with 'd' denote the dimension reduced embeddings.
[INFO] Adding time feature columns into dataframe in `.df`.
[INFO] Adding 'time_encoding' feature...
[INFO] Adding 'time_diff' feature...
[INFO] Adding 'timeline_index' feature...
[INFO] Padding ids and storing in `.df_padded` and `.array_padded` attributes.


  0%|          | 0/9699 [00:00<?, ?it/s]

[INFO] The path was created for each item in the dataframe, by looking at its history, so to include embeddings in the FFN input, we concatenate the embeddings for each sentence / text.


  0%|          | 0/2 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/2 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/2 [00:00<?, ?it/s]

  0%|          | 0/3 [00:00<?, ?it/s]

  0%|          | 0/3 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/2 [00:00<?, ?it/s]

  0%|          | 0/3 [00:00<?, ?it/s]

  0%|          | 0/3 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/2 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/2 [00:00<?, ?it/s]

  0%|          | 0/3 [00:00<?, ?it/s]

  0%|          | 0/3 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/2 [00:00<?, ?it/s]

  0%|          | 0/3 [00:00<?, ?it/s]

  0%|          | 0/3 [00:00<?, ?it/s]

given shift 3, window size 5 and n 3: history length = 11
[INFO] Concatenating the embeddings to the dataframe...
[INFO] - columns beginning with 'e' denote the full embddings.
[INFO] - columns beginning with 'd' denote the dimension reduced embeddings.
[INFO] Adding time feature columns into dataframe in `.df`.
[INFO] Adding 'time_encoding' feature...
[INFO] Adding 'time_diff' feature...
[INFO] Adding 'timeline_index' feature...
[INFO] Padding ids and storing in `.df_padded` and `.array_padded` attributes.


  0%|          | 0/9699 [00:00<?, ?it/s]

[INFO] The path was created for each item in the dataframe, by looking at its history, so to include embeddings in the FFN input, we concatenate the embeddings for each sentence / text.
saving results dataframe to CSV for this hyperparameter search in client_talk_type_output/seqsignet_grp_focal_2_3_5_3_kfold.csv
saving the best model results dataframe to CSV for this hyperparameter search in client_talk_type_output/seqsignet_grp_focal_2_3_5_3_kfold_best_model.csv


In [24]:
seqsignet_network_grp_kfold_11

loss  accuracy        f1  \
0   None  0.638506  0.511102   
0   None  0.610920  0.508169   
0   None  0.635441  0.518679   
0   None  0.633908  0.515753   
0   None  0.638314  0.516771   
..   ...       ...       ...   
0   None  0.620306  0.508861   
0   None  0.637739  0.515208   
0   None  0.628352  0.503916   
0   None  0.627011  0.519737   
0   None  0.640230  0.521198   

                                            f1_scores  precision  \
0   [0.768158047646717, 0.4081055607917059, 0.3570...   0.512387   
0   [0.737459484488347, 0.42924159499609066, 0.357...   0.497643   
0   [0.7595684941628491, 0.42942686056458507, 0.36...   0.511533   
0   [0.7583135391923991, 0.4389837567680134, 0.349...   0.508384   
0   [0.7636256794476275, 0.4289383561643835, 0.357...   0.510786   
..                                                ...        ...   
0   [0.7464042392127176, 0.43509906995551967, 0.34...   0.499780   
0   [0.7623820754716981, 0.4396155453405766, 0.343...   0.509081   
0   [0.7560046865846515, 0.41318681318681316, 0.34...   0.499666   
0   [0.7545440659844203, 0.44472049689440996, 0.35...   0.510878   
0   [0.7640746729384095, 0.43413566739606124, 0.36...   0.515739   

                                     precision_scores    recall  \
0   [0.7717454757734968, 0.4758241758241758, 0.289...  0.529106   
0   [0.7907977490897053, 0.4078751857355126, 0.294...  0.533399   
0   [0.7766696887277122, 0.44582593250444047, 0.31...  0.534283   
0   [0.7791336180597925, 0.4432296047098402, 0.302...  0.529314   
0   [0.7760525530008958, 0.445729537366548, 0.3105...  0.528925   
..                                                ...       ...   
0   [0.7832856688910073, 0.42664551942902457, 0.28...  0.528002   
0   [0.777510523150932, 0.445385266723116, 0.30434...  0.525457   
0   [0.7658753709198813, 0.44214487300094074, 0.29...  0.516846   
0   [0.7996115247652962, 0.4463840399002494, 0.286...  0.546997   
0   [0.7769805680119581, 0.46225535880708296, 0.30...  0.536641   

                                        recall_scores valid_loss  \
0   [0.7646038172353962, 0.3572607260726073, 0.465...       None   
0   [0.6908617698091383, 0.452970297029703, 0.4563...       None   
0   [0.7432041642567958, 0.4141914191419142, 0.445...       None   
0   [0.7385772122614228, 0.43481848184818483, 0.41...       None   
0   [0.7515905147484094, 0.41336633663366334, 0.42...       None   
..                                                ...        ...   
0   [0.7128397917871602, 0.4438943894389439, 0.427...       None   
0   [0.7478311162521689, 0.43399339933993397, 0.39...       None   
0   [0.7463851937536148, 0.38778877887788776, 0.41...       None   
0   [0.7142857142857143, 0.4430693069306931, 0.483...       None   
0   [0.7515905147484094, 0.40924092409240925, 0.44...       None   

    valid_accuracy  ...  BiLSTM loss_function  gamma k_fold  n_splits  \
0         0.662813  ...    True         focal      2   True         5   
0         0.653500  ...    True         focal      2   True         5   
0         0.665382  ...    True         focal      2   True         5   
0         0.669236  ...    True         focal      2   True         5   
0         0.671805  ...    True         focal      2   True         5   
..             ...  ...     ...           ...    ...    ...       ...   
0         0.662171  ...    True         focal      2   True         5   
0         0.671805  ...    True         focal      2   True         5   
0         0.664900  ...    True         focal      2   True         5   
0         0.655427  ...    True         focal      2   True         5   
0         0.666185  ...    True         focal      2   True         5   

   augmentation_type  hidden_dim_aug    comb_method  batch_size  model_id  
0             Conv1d            None  concatenation          64         0  
0             Conv1d            None  concatenation          64         0  
0             Conv1d            None  concatenation          64         0  

In [25]:
best_seqsignet_network_grp_kfold_11["f1"].mean()

0.5190070840121788

In [26]:
best_seqsignet_network_grp_kfold_11["precision"].mean()

0.5109347779258603

In [27]:
best_seqsignet_network_grp_kfold_11["recall"].mean()

0.5351426692698188

In [28]:
np.stack(best_seqsignet_network_grp_kfold_11["f1_scores"]).mean(axis=0)

array([0.75771302, 0.44357586, 0.35573237])

In [29]:
np.stack(best_seqsignet_network_grp_kfold_11["precision_scores"]).mean(axis=0)

array([0.78620464, 0.43984308, 0.30675661])

In [30]:
np.stack(best_seqsignet_network_grp_kfold_11["recall_scores"]).mean(axis=0)

array([0.7313476 , 0.4480198 , 0.42606061])

# history_length=20

In [10]:
shift = 3
window_size = 5
n = 6

In [32]:
(
    seqsignet_network_umap_kfold_20,
    best_seqsignet_network_umap_kfold_20,
    _,
    __,
) = seqsignet_hyperparameter_search(
    num_epochs=num_epochs,
    df=anno_mi,
    id_column="transcript_id",
    label_column="client_talk_type",
    embeddings=sbert_embeddings,
    y_data=y_data_client,
    output_dim=output_dim_client,
    shift=shift,
    window_size=window_size,
    n=n,
    dim_reduce_methods=["umap"],
    dimensions=dimensions,
    log_signature=True,
    swnu_hidden_dim_sizes_and_sig_depths=swnu_hidden_dim_sizes_and_sig_depths,
    lstm_hidden_dim_sizes=lstm_hidden_dim_sizes,
    ffn_hidden_dim_sizes=ffn_hidden_dim_sizes,
    dropout_rates=dropout_rates,
    learning_rates=learning_rates,
    BiLSTM=True,
    seeds=seeds,
    loss=loss,
    gamma=gamma,
    device=device,
    features=features,
    standardise_method=standardise_method,
    include_features_in_path=include_features_in_path,
    include_features_in_input=include_features_in_input,
    path_indices=client_index,
    split_ids=client_transcript_id,
    k_fold=True,
    patience=patience,
    validation_metric=validation_metric,
    results_output=f"{output_dir}/seqsignet_umap_focal_{gamma}_{shift}_{window_size}_{n}_kfold.csv",
    verbose=False,
)

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]


##################################################
dimension: 15 | method: umap
given shift 3, window size 5 and n 6: history length = 20
[INFO] Concatenating the embeddings to the dataframe...
[INFO] - columns beginning with 'e' denote the full embddings.
[INFO] - columns beginning with 'd' denote the dimension reduced embeddings.
[INFO] Adding time feature columns into dataframe in `.df`.
[INFO] Adding 'time_encoding' feature...
[INFO] Adding 'time_diff' feature...
[INFO] Adding 'timeline_index' feature...
[INFO] Padding ids and storing in `.df_padded` and `.array_padded` attributes.


  0%|          | 0/9699 [00:00<?, ?it/s]

[INFO] The path was created for each item in the dataframe, by looking at its history, so to include embeddings in the FFN input, we concatenate the embeddings for each sentence / text.


  0%|          | 0/2 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/2 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/2 [00:00<?, ?it/s]

  0%|          | 0/3 [00:00<?, ?it/s]

  0%|          | 0/3 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/2 [00:00<?, ?it/s]

  0%|          | 0/3 [00:00<?, ?it/s]

  0%|          | 0/3 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/2 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/2 [00:00<?, ?it/s]

  0%|          | 0/3 [00:00<?, ?it/s]

  0%|          | 0/3 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/2 [00:00<?, ?it/s]

  0%|          | 0/3 [00:00<?, ?it/s]

  0%|          | 0/3 [00:00<?, ?it/s]

given shift 3, window size 5 and n 6: history length = 20
[INFO] Concatenating the embeddings to the dataframe...
[INFO] - columns beginning with 'e' denote the full embddings.
[INFO] - columns beginning with 'd' denote the dimension reduced embeddings.
[INFO] Adding time feature columns into dataframe in `.df`.
[INFO] Adding 'time_encoding' feature...
[INFO] Adding 'time_diff' feature...
[INFO] Adding 'timeline_index' feature...
[INFO] Padding ids and storing in `.df_padded` and `.array_padded` attributes.


  0%|          | 0/9699 [00:00<?, ?it/s]

[INFO] The path was created for each item in the dataframe, by looking at its history, so to include embeddings in the FFN input, we concatenate the embeddings for each sentence / text.
saving results dataframe to CSV for this hyperparameter search in client_talk_type_output/seqsignet_umap_focal_2_3_5_6_kfold.csv
saving the best model results dataframe to CSV for this hyperparameter search in client_talk_type_output/seqsignet_umap_focal_2_3_5_6_kfold_best_model.csv


In [33]:
seqsignet_network_umap_kfold_20

loss  accuracy        f1  \
0   None  0.645594  0.517765   
0   None  0.617433  0.508190   
0   None  0.637931  0.517992   
0   None  0.632950  0.520069   
0   None  0.632184  0.518627   
..   ...       ...       ...   
0   None  0.642146  0.515077   
0   None  0.637548  0.518798   
0   None  0.625670  0.520733   
0   None  0.625096  0.518500   
0   None  0.638506  0.519125   

                                            f1_scores  precision  \
0   [0.7717375630857967, 0.41417910447761197, 0.36...   0.518095   
0   [0.7477380769820579, 0.43321299638989175, 0.34...   0.499059   
0   [0.7646972152644762, 0.42429501084598703, 0.36...   0.511726   
0   [0.7534391534391535, 0.46549707602339185, 0.34...   0.511139   
0   [0.7546205860255446, 0.4435082343929529, 0.357...   0.511943   
..                                                ...        ...   
0   [0.7689614935822638, 0.4226415094339622, 0.353...   0.510691   
0   [0.764128494943486, 0.4386989157631359, 0.3535...   0.511161   
0   [0.7467315293402251, 0.4520884520884521, 0.363...   0.510837   
0   [0.7538626281168731, 0.4389632107023411, 0.362...   0.510098   
0   [0.7631230701367447, 0.4281398359948209, 0.366...   0.512863   

                                     precision_scores    recall  \
0   [0.7696289905090595, 0.47639484978540775, 0.30...  0.531580   
0   [0.7959516813581456, 0.4215456674473068, 0.279...  0.532010   
0   [0.7795133673775909, 0.4473924977127173, 0.308...  0.533724   
0   [0.7893569844789357, 0.44124168514412415, 0.30...  0.534710   
0   [0.7854238348451673, 0.413867047891351, 0.3365...  0.528561   
..                                                ...       ...   
0   [0.7757504414361389, 0.4296675191815857, 0.326...  0.521195   
0   [0.786589099816289, 0.44350758853288363, 0.303...  0.533515   
0   [0.7871794871794872, 0.44878048780487806, 0.29...  0.544925   
0   [0.8002598246183826, 0.4449152542372881, 0.285...  0.547967   
0   [0.7762488782530661, 0.448868778280543, 0.3134...  0.533225   

                                        recall_scores valid_loss  \
0   [0.7738577212261423, 0.36633663366336633, 0.45...       None   
0   [0.7050318102949682, 0.44554455445544555, 0.44...       None   
0   [0.7504337767495662, 0.4034653465346535, 0.447...       None   
0   [0.7206477732793523, 0.49257425742574257, 0.39...       None   
0   [0.7261422787738577, 0.4777227722772277, 0.381...       None   
..                                                ...        ...   
0   [0.7622903412377097, 0.4158415841584158, 0.385...       None   
0   [0.742914979757085, 0.43399339933993397, 0.423...       None   
0   [0.7102371312897628, 0.45544554455445546, 0.46...       None   
0   [0.7125506072874493, 0.43316831683168316, 0.49...       None   
0     [0.7504337767495662, 0.40924092409240925, 0.44]       None   

    valid_accuracy  ...  BiLSTM loss_function  gamma k_fold  n_splits  \
0         0.671162  ...    True         focal      2   True         5   
0         0.658157  ...    True         focal      2   True         5   
0         0.666185  ...    True         focal      2   True         5   
0         0.673089  ...    True         focal      2   True         5   
0         0.671965  ...    True         focal      2   True         5   
..             ...  ...     ...           ...    ...    ...       ...   
0         0.674374  ...    True         focal      2   True         5   
0         0.668593  ...    True         focal      2   True         5   
0         0.655267  ...    True         focal      2   True         5   
0         0.656069  ...    True         focal      2   True         5   
0         0.669557  ...    True         focal      2   True         5   

   augmentation_type  hidden_dim_aug    comb_method  batch_size  model_id  
0             Conv1d            None  concatenation          64         0  
0             Conv1d            None  concatenation          64         0  
0             Conv1d            None  concatenation          64         0  

In [34]:
best_seqsignet_network_umap_kfold_20["f1"].mean()

0.5164772721152695

In [35]:
best_seqsignet_network_umap_kfold_20["precision"].mean()

0.5081440744623626

In [36]:
best_seqsignet_network_umap_kfold_20["recall"].mean()

0.5342635294954211

In [37]:
np.stack(best_seqsignet_network_umap_kfold_20["f1_scores"]).mean(axis=0)

array([0.7576027 , 0.43787008, 0.35395904])

In [38]:
np.stack(best_seqsignet_network_umap_kfold_20["precision_scores"]).mean(axis=0)

array([0.78616118, 0.4405165 , 0.29775454])

In [39]:
np.stack(best_seqsignet_network_umap_kfold_20["recall_scores"]).mean(axis=0)

array([0.73105842, 0.43536854, 0.43636364])

## GRP

In [ ]:
(
    seqsignet_network_grp_kfold_20,
    best_seqsignet_network_grp_kfold_20,
    _,
    __,
) = seqsignet_hyperparameter_search(
    num_epochs=num_epochs,
    df=anno_mi,
    id_column="transcript_id",
    label_column="client_talk_type",
    embeddings=sbert_embeddings,
    y_data=y_data_client,
    output_dim=output_dim_client,
    shift=shift,
    window_size=window_size,
    n=n,
    dim_reduce_methods=["gaussian_random_projection"],
    dimensions=dimensions,
    log_signature=True,
    swnu_hidden_dim_sizes_and_sig_depths=swnu_hidden_dim_sizes_and_sig_depths,
    lstm_hidden_dim_sizes=lstm_hidden_dim_sizes,
    ffn_hidden_dim_sizes=ffn_hidden_dim_sizes,
    dropout_rates=dropout_rates,
    learning_rates=learning_rates,
    BiLSTM=True,
    seeds=seeds,
    loss=loss,
    gamma=gamma,
    device=device,
    features=features,
    standardise_method=standardise_method,
    include_features_in_path=include_features_in_path,
    include_features_in_input=include_features_in_input,
    path_indices=client_index,
    k_fold=True,
    patience=patience,
    split_ids=client_transcript_id,
    validation_metric=validation_metric,
    results_output=f"{output_dir}/seqsignet_grp_focal_{gamma}_{shift}_{window_size}_{n}_kfold.csv",
    verbose=False,
)

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]


##################################################
dimension: 15 | method: gaussian_random_projection
given shift 3, window size 5 and n 6: history length = 20
[INFO] Concatenating the embeddings to the dataframe...
[INFO] - columns beginning with 'e' denote the full embddings.
[INFO] - columns beginning with 'd' denote the dimension reduced embeddings.
[INFO] Adding time feature columns into dataframe in `.df`.
[INFO] Adding 'time_encoding' feature...
[INFO] Adding 'time_diff' feature...
[INFO] Adding 'timeline_index' feature...
[INFO] Padding ids and storing in `.df_padded` and `.array_padded` attributes.


  0%|          | 0/9699 [00:00<?, ?it/s]

[INFO] The path was created for each item in the dataframe, by looking at its history, so to include embeddings in the FFN input, we concatenate the embeddings for each sentence / text.


  0%|          | 0/2 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/2 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/2 [00:00<?, ?it/s]

  0%|          | 0/3 [00:00<?, ?it/s]

  0%|          | 0/3 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/2 [00:00<?, ?it/s]

  0%|          | 0/3 [00:00<?, ?it/s]

  0%|          | 0/3 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/2 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/2 [00:00<?, ?it/s]

  0%|          | 0/3 [00:00<?, ?it/s]

In [ ]:
seqsignet_network_grp_kfold_20

In [ ]:
best_seqsignet_network_grp_kfold_20["f1"].mean()

In [ ]:
best_seqsignet_network_grp_kfold_20["precision"].mean()

In [ ]:
best_seqsignet_network_grp_kfold_20["recall"].mean()

In [ ]:
np.stack(best_seqsignet_network_grp_kfold_20["f1_scores"]).mean(axis=0)

In [ ]:
np.stack(best_seqsignet_network_grp_kfold_20["precision_scores"]).mean(axis=0)

In [ ]:
np.stack(best_seqsignet_network_grp_kfold_20["recall_scores"]).mean(axis=0)

# history_length=35

In [ ]:
shift = 3
window_size = 5
n = 11

In [ ]:
(
    seqsignet_network_umap_kfold_35,
    best_seqsignet_network_umap_kfold_35,
    _,
    __,
) = seqsignet_hyperparameter_search(
    num_epochs=num_epochs,
    df=anno_mi,
    id_column="transcript_id",
    label_column="client_talk_type",
    embeddings=sbert_embeddings,
    y_data=y_data_client,
    output_dim=output_dim_client,
    shift=shift,
    window_size=window_size,
    n=n,
    dim_reduce_methods=["umap"],
    dimensions=dimensions,
    log_signature=True,
    swnu_hidden_dim_sizes_and_sig_depths=swnu_hidden_dim_sizes_and_sig_depths,
    lstm_hidden_dim_sizes=lstm_hidden_dim_sizes,
    ffn_hidden_dim_sizes=ffn_hidden_dim_sizes,
    dropout_rates=dropout_rates,
    learning_rates=learning_rates,
    BiLSTM=True,
    seeds=seeds,
    loss=loss,
    gamma=gamma,
    device=device,
    features=features,
    standardise_method=standardise_method,
    include_features_in_path=include_features_in_path,
    include_features_in_input=include_features_in_input,
    path_indices=client_index,
    split_ids=client_transcript_id,
    k_fold=True,
    patience=patience,
    validation_metric=validation_metric,
    results_output=f"{output_dir}/seqsignet_umap_focal_{gamma}_{shift}_{window_size}_{n}_kfold.csv",
    verbose=False,
)

In [ ]:
seqsignet_network_umap_kfold_35

In [ ]:
best_seqsignet_network_umap_kfold_35["f1"].mean()

In [ ]:
best_seqsignet_network_umap_kfold_35["precision"].mean()

In [ ]:
best_seqsignet_network_umap_kfold_35["recall"].mean()

In [ ]:
np.stack(best_seqsignet_network_umap_kfold_35["f1_scores"]).mean(axis=0)

In [ ]:
np.stack(best_seqsignet_network_umap_kfold_35["precision_scores"]).mean(axis=0)

In [ ]:
np.stack(best_seqsignet_network_umap_kfold_35["recall_scores"]).mean(axis=0)

## GRP

In [ ]:
(
    seqsignet_network_grp_kfold_35,
    best_seqsignet_network_grp_kfold_35,
    _,
    __,
) = seqsignet_hyperparameter_search(
    num_epochs=num_epochs,
    df=anno_mi,
    id_column="transcript_id",
    label_column="client_talk_type",
    embeddings=sbert_embeddings,
    y_data=y_data_client,
    output_dim=output_dim_client,
    shift=shift,
    window_size=window_size,
    n=n,
    dim_reduce_methods=["gaussian_random_projection"],
    dimensions=dimensions,
    log_signature=True,
    swnu_hidden_dim_sizes_and_sig_depths=swnu_hidden_dim_sizes_and_sig_depths,
    lstm_hidden_dim_sizes=lstm_hidden_dim_sizes,
    ffn_hidden_dim_sizes=ffn_hidden_dim_sizes,
    dropout_rates=dropout_rates,
    learning_rates=learning_rates,
    BiLSTM=True,
    seeds=seeds,
    loss=loss,
    gamma=gamma,
    device=device,
    features=features,
    standardise_method=standardise_method,
    include_features_in_path=include_features_in_path,
    include_features_in_input=include_features_in_input,
    path_indices=client_index,
    k_fold=True,
    patience=patience,
    split_ids=client_transcript_id,
    validation_metric=validation_metric,
    results_output=f"{output_dir}/seqsignet_grp_focal_{gamma}_{shift}_{window_size}_{n}_kfold.csv",
    verbose=False,
)

In [ ]:
seqsignet_network_grp_kfold_35

In [ ]:
best_seqsignet_network_grp_kfold_35["f1"].mean()

In [ ]:
best_seqsignet_network_grp_kfold_35["precision"].mean()

In [ ]:
best_seqsignet_network_grp_kfold_35["recall"].mean()

In [ ]:
np.stack(best_seqsignet_network_grp_kfold_35["f1_scores"]).mean(axis=0)

In [ ]:
np.stack(best_seqsignet_network_grp_kfold_35["precision_scores"]).mean(axis=0)

In [ ]:
np.stack(best_seqsignet_network_grp_kfold_35["recall_scores"]).mean(axis=0)