In [4]:
import numpy as np
import pickle
import os

seed = 2023

In [5]:
from nlpsig_networks.scripts.ffn_baseline_functions import (
    histories_baseline_hyperparameter_search,
)

In [6]:
output_dir = "client_talk_type_output"
if not os.path.isdir(output_dir):
    os.makedirs(output_dir)

## AnnoMI

In [7]:
%run ../load_anno_mi.py

In [8]:
anno_mi.head()

mi_quality  transcript_id                         topic  utterance_id  \
0       high              0  reducing alcohol consumption             0   
1       high              0  reducing alcohol consumption             1   
2       high              0  reducing alcohol consumption             2   
3       high              0  reducing alcohol consumption             3   
4       high              0  reducing alcohol consumption             4   

  interlocutor timestamp                                     utterance_text  \
0    therapist  00:00:13  Thanks for filling it out. We give this form t...   
1       client  00:00:24                                              Sure.   
2    therapist  00:00:25  So, let's see. It looks that you put-- You dri...   
3       client  00:00:34                                            Mm-hmm.   
4    therapist  00:00:34  -and you usually have three to four drinks whe...   

   annotator_id therapist_input_exists therapist_input_subtype  \
0             3                  False                     NaN   
1             3                    NaN                     NaN   
2             3                   True             information   
3             3                    NaN                     NaN   
4             3                   True             information   

  reflection_exists reflection_subtype question_exists question_subtype  \
0             False                NaN            True             open   
1               NaN                NaN             NaN              NaN   
2             False                NaN           False              NaN   
3               NaN                NaN             NaN              NaN   
4             False                NaN           False              NaN   

  main_therapist_behaviour client_talk_type            datetime  
0                 question              NaN 2023-08-18 00:00:13  
1                      NaN          neutral 2023-08-18 00:00:24  
2          therapist_input              NaN 2023-08-18 00:00:25  
3                      NaN          neutral 2023-08-18 00:00:34  
4          therapist_input              NaN 2023-08-18 00:00:34

In [9]:
with open("../anno_mi_sbert.pkl", "rb") as f:
    sbert_embeddings = pickle.load(f)

sbert_embeddings.shape

(9699, 384)

# Baseline: Averaging history and use FFN

Here, we average the full history of a path and concatenate it the current embedding (the total number of features that are passed into the FFN is `2 * sbert_embeddings.shape[0]`).

Here, we will run the hyperparameter search to implement the FFN with the same parameters as the standard FFN baseline on the sentence embeddings. Going to try out some variations (1 hidden layer, 2 hidden layers and 3 hidden layers - all of size 100).

In [10]:
num_epochs = 100
hidden_dim_sizes = [[64, 64], [128, 128], [256, 256], [512, 512]]
dropout_rates = [0.5, 0.1]
learning_rates = [1e-3, 1e-4, 5e-4]
seeds = [1, 12, 123]
loss = "focal"
gamma = 2
validation_metric = "f1"
patience = 5

In [11]:
(
    ffn_mean_history,
    best_ffn_mean_history,
    _,
    __,
) = histories_baseline_hyperparameter_search(
    num_epochs=num_epochs,
    df=anno_mi,
    id_column="transcript_id",
    label_column="client_talk_type",
    embeddings=sbert_embeddings,
    y_data=y_data_client,
    output_dim=output_dim_client,
    hidden_dim_sizes=hidden_dim_sizes,
    dropout_rates=dropout_rates,
    learning_rates=learning_rates,
    use_signatures=False,
    seeds=seeds,
    loss=loss,
    gamma=gamma,
    path_indices=client_index,
    split_ids=client_transcript_id,
    k_fold=False,
    patience=patience,
    validation_metric=validation_metric,
    results_output=f"{output_dir}/ffn_mean_history_focal_{gamma}.csv",
    verbose=False,
)

[INFO] Concatenating the embeddings to the dataframe...
[INFO] - columns beginning with 'e' denote the full embddings.
[INFO] Adding time feature columns into dataframe in `.df`.
[INFO] Adding 'time_encoding' feature...
[INFO] Adding 'time_diff' feature...
[INFO] Adding 'timeline_index' feature...
Computing the mean history for each item in the dataframe


  0%|          | 0/9699 [00:00<?, ?it/s]

  0%|          | 0/4 [00:00<?, ?it/s]

  0%|          | 0/2 [00:00<?, ?it/s]

  0%|          | 0/3 [00:00<?, ?it/s]

  0%|          | 0/3 [00:00<?, ?it/s]

  0%|          | 0/2 [00:00<?, ?it/s]

  0%|          | 0/3 [00:00<?, ?it/s]

  0%|          | 0/3 [00:00<?, ?it/s]

  0%|          | 0/2 [00:00<?, ?it/s]

  0%|          | 0/3 [00:00<?, ?it/s]

  0%|          | 0/3 [00:00<?, ?it/s]

  0%|          | 0/2 [00:00<?, ?it/s]

  0%|          | 0/3 [00:00<?, ?it/s]

  0%|          | 0/3 [00:00<?, ?it/s]

[INFO] Concatenating the embeddings to the dataframe...
[INFO] - columns beginning with 'e' denote the full embddings.
[INFO] Adding time feature columns into dataframe in `.df`.
[INFO] Adding 'time_encoding' feature...
[INFO] Adding 'time_diff' feature...
[INFO] Adding 'timeline_index' feature...
Computing the mean history for each item in the dataframe


  0%|          | 0/9699 [00:00<?, ?it/s]

saving results dataframe to CSV for this hyperparameter search in client_talk_type_output/ffn_mean_history_focal_2.csv
saving the best model results dataframe to CSV for this hyperparameter search in client_talk_type_output/ffn_mean_history_focal_2_best_model.csv


In [12]:
ffn_mean_history

loss  accuracy        f1  \
0   0.547621  0.647919  0.537981   
0   0.545115  0.677165  0.557928   
0   0.562399  0.616423  0.506382   
0   0.604800  0.647919  0.484937   
0   0.574287  0.637795  0.520725   
..       ...       ...       ...   
0   0.546397  0.653543  0.533674   
0   0.550391  0.653543  0.551512   
0   0.587151  0.613048  0.510602   
0   0.549914  0.642295  0.536130   
0   0.606111  0.565804  0.504304   

                                            f1_scores  precision  \
0   [0.7615720524017467, 0.48395061728395056, 0.36...   0.522126   
0   [0.7834179357021998, 0.504950495049505, 0.3854...   0.543439   
0   [0.742857142857143, 0.43294117647058816, 0.343...   0.494693   
0   [0.7781512605042017, 0.41350210970464135, 0.26...   0.550732   
0   [0.7615720524017467, 0.43303571428571425, 0.36...   0.512181   
..                                                ...        ...   
0   [0.7718696397941681, 0.46632124352331605, 0.36...   0.519546   
0   [0.7574692442882249, 0.5011286681715575, 0.395...   0.535771   
0   [0.7246111619396158, 0.4660194174757281, 0.341...   0.513374   
0   [0.7515473032714413, 0.5059665871121718, 0.350...   0.520550   
0   [0.6568627450980392, 0.4618181818181818, 0.394...   0.506528   

                                     precision_scores    recall  \
0   [0.8352490421455939, 0.43946188340807174, 0.29...  0.579434   
0   [0.8282647584973166, 0.4594594594594595, 0.342...  0.581365   
0   [0.8370221327967807, 0.3786008230452675, 0.268...  0.549807   
0       [0.8165784832451499, 0.3356164383561644, 0.5]  0.486737   
0   [0.8352490421455939, 0.36466165413533835, 0.33...  0.545856   
..                                                ...       ...   
0   [0.8287292817679558, 0.4411764705882353, 0.288...  0.568304   
0   [0.8368932038834952, 0.42528735632183906, 0.34...  0.588663   
0   [0.8425531914893617, 0.36036036036036034, 0.33...  0.546738   
0   [0.8366141732283464, 0.4472573839662447, 0.277...  0.580264   
0   [0.8438287153652393, 0.3451086956521739, 0.330...  0.574539   

                                        recall_scores  valid_loss  \
0       [0.6998394863563403, 0.5384615384615384, 0.5]    0.767113   
0   [0.7431781701444623, 0.5604395604395604, 0.440...    0.767323   
0   [0.6677367576243981, 0.5054945054945055, 0.476...    0.729765   
0   [0.7431781701444623, 0.5384615384615384, 0.178...    0.736244   
0   [0.6998394863563403, 0.532967032967033, 0.4047...    0.727896   
..                                                ...         ...   
0   [0.7223113964686998, 0.4945054945054945, 0.488...    0.743059   
0   [0.6918138041733547, 0.6098901098901099, 0.464...    0.774854   
0   [0.6356340288924559, 0.6593406593406593, 0.345...    0.760509   
0   [0.6821829855537721, 0.5824175824175825, 0.476...    0.742178   
0   [0.5377207062600321, 0.6978021978021978, 0.488...    0.944215   

    valid_accuracy  ...  dropout_rate learning_rate  seed loss_function  \
0         0.593160  ...           0.5        0.0010     1         focal   
0         0.612028  ...           0.5        0.0010    12         focal   
0         0.586085  ...           0.5        0.0010   123         focal   
0         0.617925  ...           0.5        0.0001     1         focal   
0         0.609670  ...           0.5        0.0001    12         focal   
..             ...  ...           ...           ...   ...           ...   
0         0.600236  ...           0.1        0.0001    12         focal   
0         0.593160  ...           0.1        0.0001   123         focal   
0         0.576651  ...           0.1        0.0005     1         focal   
0         0.587264  ...           0.1        0.0005    12         focal   
0         0.551887  ...           0.1        0.0005   123         focal   

    gamma k_fold n_splits  batch_size  model_id  input_dim  
0       2  False     None          64      0.00        768  
0       2  False     None          64      0.00        768  
0       2  False     None          64   

In [13]:
ffn_mean_history.groupby(["hidden_dim", "dropout_rate", "learning_rate"]).mean()

/tmp/ipykernel_3374083/1445575783.py:1: FutureWarning: The default value of numeric_only in DataFrameGroupBy.mean is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  ffn_mean_history.groupby(["hidden_dim", "dropout_rate", "learning_rate"]).mean()


loss  accuracy        f1  \
hidden_dim dropout_rate learning_rate                                 
(64, 64)   0.1          0.0001         0.556480  0.646044  0.530739   
                        0.0005         0.563046  0.623172  0.515212   
                        0.0010         0.571650  0.605924  0.502906   
           0.5          0.0001         0.577636  0.648669  0.514160   
                        0.0005         0.565111  0.621297  0.514207   
                        0.0010         0.551712  0.647169  0.534097   
(128, 128) 0.1          0.0001         0.550418  0.649419  0.535753   
                        0.0005         0.570038  0.623547  0.514827   
                        0.0010         0.561341  0.620922  0.521268   
           0.5          0.0001         0.553154  0.648669  0.527337   
                        0.0005         0.562083  0.626922  0.512337   
                        0.0010         0.569429  0.620172  0.516305   
(256, 256) 0.1          0.0001         0.550805  0.648669  0.540042   
                        0.0005         0.561179  0.630671  0.526450   
                        0.0010         0.547232  0.650544  0.535575   
           0.5          0.0001         0.548041  0.659168  0.552641   
                        0.0005         0.556264  0.632171  0.519043   
                        0.0010         0.561924  0.609299  0.510291   
(512, 512) 0.1          0.0001         0.548444  0.653543  0.542845   
                        0.0005         0.581059  0.607049  0.517012   
                        0.0010         0.552792  0.639295  0.531676   
           0.5          0.0001         0.549359  0.652043  0.543607   
                        0.0005         0.549849  0.637045  0.531832   
                        0.0010         0.567915  0.622797  0.514652   

                                       precision    recall  valid_loss  \
hidden_dim dropout_rate learning_rate                                    
(64, 64)   0.1          0.0001          0.518011  0.561096    0.737041   
                        0.0005          0.502470  0.557923    0.723509   
                        0.0010          0.495636  0.552592    0.745529   
           0.5          0.0001          0.528703  0.532158    0.735234   
                        0.0005          0.501691  0.557056    0.737231   
                        0.0010          0.520086  0.570202    0.754734   
(128, 128) 0.1          0.0001          0.520397  0.570280    0.747523   
                        0.0005          0.506263  0.553268    0.736515   
                        0.0010          0.512226  0.571218    0.769935   
           0.5          0.0001          0.513722  0.557158    0.729832   
                        0.0005          0.500790  0.549255    0.726636   
                        0.0010          0.508355  0.558833    0.747159   
(256, 256) 0.1          0.0001          0.524547  0.577141    0.767045   
                        0.0005          0.518123  0.568557    0.742212   
                        0.0010          0.522216  0.571831    0.741588   
           0.5          0.0001          0.537359  0.586585    0.767644   
                        0.0005          0.506170  0.557906    0.735877   
                        0.0010          0.503966  0.559967    0.752350   
(512, 512) 0.1          0.0001          0.527362  0.580404    0.750529   
                        0.0005          0.513484  0.567180    0.815634   
                        0.0010          0.521417  0.572683    0.792378   
           0.5          0.0001          0.528667  0.579179    0.766741   
                        0.0005          0.520115  0.576726    0.797849   
                        0.0010          0.510527  0.554384    0.741657   

                                       valid_accuracy  valid_f1  \
hidden_dim dropout_rate learning_rate                             
(64, 64)   0.1          0.0001               0.601022  0.474829   
                        0.0005               0.587264  0.481818   
   

In [14]:
best_ffn_mean_history

loss  accuracy        f1  \
0  0.548044  0.652418  0.546322   
0  0.546784  0.660292  0.549019   
0  0.557586  0.633296  0.524786   

                                           f1_scores  precision  \
0  [0.7609841827768014, 0.49883449883449876, 0.37...   0.529645   
0  [0.7677642980935876, 0.5011820330969268, 0.378...   0.532965   
0  [0.7475642161204605, 0.47272727272727266, 0.35...   0.511031   

                                    precision_scores    recall  \
0  [0.8407766990291262, 0.4331983805668016, 0.314...  0.586376   
0  [0.8342749529190208, 0.43983402489626555, 0.32...  0.581958   
0     [0.83399209486166, 0.40310077519379844, 0.296]  0.563091   

                                       recall_scores  valid_loss  \
0  [0.695024077046549, 0.5879120879120879, 0.4761...    0.769529   
0  [0.7110754414125201, 0.5824175824175825, 0.452...    0.786164   
0  [0.6773675762439807, 0.5714285714285714, 0.440...    0.745442   

   valid_accuracy  ...  hidden_dim dropout_rate  learning_rate seed  \
0        0.593160  ...  (256, 256)          0.1         0.0001    1   
0        0.590802  ...  (256, 256)          0.1         0.0001   12   
0        0.600236  ...  (256, 256)          0.1         0.0001  123   

   loss_function gamma k_fold  n_splits  batch_size  input_dim  
0          focal     2  False      None          64        768  
0          focal     2  False      None          64        768  
0          focal     2  False      None          64        768  

[3 rows x 26 columns]

In [15]:
best_ffn_mean_history["f1"].mean()

0.5400422066070087

In [16]:
best_ffn_mean_history["precision"].mean()

0.524547098019362

In [17]:
best_ffn_mean_history["recall"].mean()

0.5771414395009901

In [18]:
np.stack(best_ffn_mean_history["f1_scores"]).mean(axis=0)

array([0.7587709 , 0.4909146 , 0.37044112])

In [19]:
np.stack(best_ffn_mean_history["precision_scores"]).mean(axis=0)

array([0.83634792, 0.42537773, 0.31191565])

In [20]:
np.stack(best_ffn_mean_history["recall_scores"]).mean(axis=0)

array([0.69448903, 0.58058608, 0.45634921])

## KFold

We can repeat this but use K-Fold evaluation instead - by default, we have $K=5$ folds.

In [21]:
(
    ffn_mean_history_kfold,
    best_ffn_mean_history_kfold,
    _,
    __,
) = histories_baseline_hyperparameter_search(
    num_epochs=num_epochs,
    df=anno_mi,
    id_column="transcript_id",
    label_column="client_talk_type",
    embeddings=sbert_embeddings,
    y_data=y_data_client,
    output_dim=output_dim_client,
    hidden_dim_sizes=hidden_dim_sizes,
    dropout_rates=dropout_rates,
    learning_rates=learning_rates,
    use_signatures=False,
    seeds=seeds,
    loss=loss,
    gamma=gamma,
    path_indices=client_index,
    split_ids=client_transcript_id,
    k_fold=True,
    patience=patience,
    validation_metric=validation_metric,
    results_output=f"{output_dir}/ffn_mean_history_focal_{gamma}_kfold.csv",
    verbose=False,
)

[INFO] Concatenating the embeddings to the dataframe...
[INFO] - columns beginning with 'e' denote the full embddings.
[INFO] Adding time feature columns into dataframe in `.df`.
[INFO] Adding 'time_encoding' feature...
[INFO] Adding 'time_diff' feature...
[INFO] Adding 'timeline_index' feature...
Computing the mean history for each item in the dataframe


  0%|          | 0/9699 [00:00<?, ?it/s]

  0%|          | 0/4 [00:00<?, ?it/s]

  0%|          | 0/2 [00:00<?, ?it/s]

  0%|          | 0/3 [00:00<?, ?it/s]

  0%|          | 0/3 [00:00<?, ?it/s]

  0%|          | 0/2 [00:00<?, ?it/s]

  0%|          | 0/3 [00:00<?, ?it/s]

  0%|          | 0/3 [00:00<?, ?it/s]

  0%|          | 0/2 [00:00<?, ?it/s]

  0%|          | 0/3 [00:00<?, ?it/s]

  0%|          | 0/3 [00:00<?, ?it/s]

  0%|          | 0/2 [00:00<?, ?it/s]

  0%|          | 0/3 [00:00<?, ?it/s]

  0%|          | 0/3 [00:00<?, ?it/s]

[INFO] Concatenating the embeddings to the dataframe...
[INFO] - columns beginning with 'e' denote the full embddings.
[INFO] Adding time feature columns into dataframe in `.df`.
[INFO] Adding 'time_encoding' feature...
[INFO] Adding 'time_diff' feature...
[INFO] Adding 'timeline_index' feature...
Computing the mean history for each item in the dataframe


  0%|          | 0/9699 [00:00<?, ?it/s]

saving results dataframe to CSV for this hyperparameter search in client_talk_type_output/ffn_mean_history_focal_2_kfold.csv
saving the best model results dataframe to CSV for this hyperparameter search in client_talk_type_output/ffn_mean_history_focal_2_kfold_best_model.csv


In [22]:
ffn_mean_history_kfold

loss  accuracy        f1  \
0   None  0.621073  0.511649   
0   None  0.619732  0.509749   
0   None  0.610536  0.509567   
0   None  0.637739  0.518219   
0   None  0.640613  0.519792   
..   ...       ...       ...   
0   None  0.635057  0.514847   
0   None  0.633142  0.521705   
0   None  0.620306  0.512478   
0   None  0.627586  0.514185   
0   None  0.613410  0.510842   

                                            f1_scores  precision  \
0   [0.7466990438609805, 0.44222776392352453, 0.34...   0.503527   
0   [0.7479501973883997, 0.4378748928877464, 0.343...   0.503971   
0   [0.7353579175704988, 0.4476151651039544, 0.345...   0.501341   
0   [0.7610435813815595, 0.446546052631579, 0.3470...   0.511128   
0   [0.7647668393782383, 0.44935389745727383, 0.34...   0.513052   
..                                                ...        ...   
0   [0.7581409117821197, 0.4446280991735537, 0.341...   0.508139   
0   [0.7546658639373871, 0.4541800643086817, 0.356...   0.512353   
0   [0.7439229475615349, 0.4476449980537173, 0.345...   0.502589   
0   [0.7502246181491465, 0.44352844187963725, 0.34...   0.505850   
0   [0.7380660954712361, 0.4272242722427224, 0.367...   0.500743   

                                     precision_scores    recall  \
0   [0.7856914723730437, 0.4455611390284757, 0.279...  0.534961   
0   [0.7874040920716112, 0.4554367201426025, 0.269...  0.536141   
0   [0.7920560747663551, 0.44238517324738114, 0.26...  0.540341   
0   [0.7807177615571776, 0.44508196721311477, 0.30...  0.529513   
0   [0.7834394904458599, 0.45408593091828137, 0.30...  0.531773   
..                                                ...       ...   
0   [0.7765312310491207, 0.445364238410596, 0.3025...  0.525741   
0   [0.7868801004394225, 0.4427899686520376, 0.307...  0.538265   
0   [0.7891663963671748, 0.423728813559322, 0.2948...  0.532063   
0   [0.7779503105590062, 0.443163097199341, 0.2964...  0.530646   
0   [0.783625730994152, 0.42461287693561534, 0.293...  0.538824   

                                        recall_scores valid_loss  \
0   [0.7113938692886062, 0.4389438943894389, 0.454...       None   
0   [0.7122614227877386, 0.42161716171617164, 0.47...       None   
0   [0.6862348178137652, 0.452970297029703, 0.4818...       None   
0   [0.7423366107576634, 0.44801980198019803, 0.39...       None   
0   [0.7469635627530364, 0.44471947194719474, 0.40...       None   
..                                                ...        ...   
0   [0.7406015037593985, 0.4438943894389439, 0.392...       None   
0   [0.7249855407750144, 0.4661716171617162, 0.423...       None   
0   [0.7035858877964141, 0.4744224422442244, 0.418...       None   
0   [0.7244071717755928, 0.4438943894389439, 0.423...       None   
0   [0.6975130133024869, 0.4298679867986799, 0.489...       None   

    valid_accuracy  ...  dropout_rate learning_rate  seed loss_function  \
0         0.676622  ...           0.5        0.0010     1         focal   
0         0.679672  ...           0.5        0.0010    12         focal   
0         0.667470  ...           0.5        0.0010   123         focal   
0         0.687861  ...           0.5        0.0001     1         focal   
0         0.690591  ...           0.5        0.0001    12         focal   
..             ...  ...           ...           ...   ...           ...   
0         0.692999  ...           0.1        0.0001    12         focal   
0         0.686095  ...           0.1        0.0001   123         focal   
0         0.682884  ...           0.1        0.0005     1         focal   
0         0.687861  ...           0.1        0.0005    12         focal   
0         0.681118  ...           0.1        0.0005   123         focal   

    gamma k_fold n_splits  batch_size  model_id  input_dim  
0       2   True        5          64      0.00        768  
0       2   True        5          64      0.00        768  
0       2   True        5          64      0.00        768  
0       2   True        5          

In [23]:
ffn_mean_history_kfold.groupby(["hidden_dim", "dropout_rate", "learning_rate"]).mean()

/tmp/ipykernel_3374083/2776369505.py:1: FutureWarning: The default value of numeric_only in DataFrameGroupBy.mean is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  ffn_mean_history_kfold.groupby(["hidden_dim", "dropout_rate", "learning_rate"]).mean()


accuracy        f1  precision  \
hidden_dim dropout_rate learning_rate                                  
(64, 64)   0.1          0.0001         0.636909  0.519518   0.511822   
                        0.0005         0.628033  0.518918   0.509948   
                        0.0010         0.626181  0.517932   0.508816   
           0.5          0.0001         0.638825  0.520243   0.512853   
                        0.0005         0.630843  0.515559   0.508288   
                        0.0010         0.617114  0.510322   0.502947   
(128, 128) 0.1          0.0001         0.634610  0.518088   0.510114   
                        0.0005         0.626373  0.514391   0.505707   
                        0.0010         0.624202  0.515967   0.507439   
           0.5          0.0001         0.635057  0.520459   0.512132   
                        0.0005         0.624968  0.516604   0.508023   
                        0.0010         0.623436  0.516571   0.507365   
(256, 256) 0.1          0.0001         0.633333  0.517344   0.509393   
                        0.0005         0.619413  0.514758   0.504742   
                        0.0010         0.615262  0.511362   0.501932   
           0.5          0.0001         0.634930  0.521698   0.513018   
                        0.0005         0.627905  0.516861   0.508446   
                        0.0010         0.624649  0.516739   0.507821   
(512, 512) 0.1          0.0001         0.636654  0.520441   0.512735   
                        0.0005         0.620434  0.512502   0.503061   
                        0.0010         0.616347  0.513998   0.504217   
           0.5          0.0001         0.630332  0.516988   0.508327   
                        0.0005         0.627714  0.517807   0.509039   
                        0.0010         0.621967  0.513523   0.504459   

                                         recall  valid_accuracy  valid_f1  \
hidden_dim dropout_rate learning_rate                                       
(64, 64)   0.1          0.0001         0.532172        0.688825  0.591687   
                        0.0005         0.539582        0.681385  0.589699   
                        0.0010         0.540365        0.683687  0.592703   
           0.5          0.0001         0.532788        0.690698  0.591499   
                        0.0005         0.533530        0.687058  0.591491   
                        0.0010         0.537148        0.674588  0.585919   
(128, 128) 0.1          0.0001         0.530949        0.688022  0.590833   
                        0.0005         0.532139        0.681010  0.588465   
                        0.0010         0.540247        0.680368  0.588510   
           0.5          0.0001         0.535379        0.689413  0.593805   
                        0.0005         0.539991        0.681813  0.590393   
                        0.0010         0.539470        0.680582  0.589765   
(256, 256) 0.1          0.0001         0.530532        0.691822  0.596158   
                        0.0005         0.538949        0.681653  0.592161   
                        0.0010         0.537345        0.673946  0.587404   
           0.5          0.0001         0.537725        0.691073  0.597542   
                        0.0005         0.537713        0.687326  0.594284   
                        0.0010         0.539519        0.683044  0.592580   
(512, 512) 0.1          0.0001         0.532784        0.690109  0.594137   
                        0.0005         0.533844        0.683954  0.591718   
                        0.0010         0.541305        0.670627  0.583543   
           0.5          0.0001         0.531668        0.690109  0.597625   
                        0.0005         0.538823        0.688664  0.595826   
                        0.0010         0.535127        0.686470  0.595985   

                                       valid_precision  valid_recall  \
hidden_dim dropout_rate learning_rate                                  
(64, 64)   0.1     

In [24]:
best_ffn_mean_history_kfold

loss  accuracy        f1  \
0  None  0.624904  0.512535   
0  None  0.631801  0.520683   
0  None  0.634291  0.517746   

                                           f1_scores  precision  \
0  [0.7473684210526316, 0.4439951475940154, 0.346...   0.503713   
0  [0.7528666264333133, 0.45522682445759366, 0.35...   0.511354   
0  [0.7558538404175988, 0.4524484014569, 0.344936...   0.509913   

                                    precision_scores    recall  \
0  [0.7785087719298246, 0.43536875495638383, 0.29...  0.528713   
0  [0.7870662460567823, 0.436130007558579, 0.3108...  0.536166   
0  [0.7804126886356637, 0.44400317712470216, 0.30...  0.530126   

                                       recall_scores valid_loss  \
0  [0.7186234817813765, 0.452970297029703, 0.4145...       None   
0  [0.7215153267784846, 0.4760726072607261, 0.410...       None   
0  [0.7327935222672065, 0.4612211221122112, 0.396...       None   

   valid_accuracy  ...  hidden_dim dropout_rate  learning_rate seed  \
0        0.691073  ...  (512, 512)          0.5         0.0001    1   
0        0.687219  ...  (512, 512)          0.5         0.0001   12   
0        0.692036  ...  (512, 512)          0.5         0.0001  123   

   loss_function gamma k_fold  n_splits  batch_size  input_dim  
0          focal     2   True         5          64        768  
0          focal     2   True         5          64        768  
0          focal     2   True         5          64        768  

[3 rows x 26 columns]

In [25]:
best_ffn_mean_history_kfold["f1"].mean()

0.5169880010201018

In [26]:
best_ffn_mean_history_kfold["precision"].mean()

0.5083267122281124

In [27]:
best_ffn_mean_history_kfold["recall"].mean()

0.5316682821164322

In [28]:
np.stack(best_ffn_mean_history_kfold["f1_scores"]).mean(axis=0)

array([0.75202963, 0.45055679, 0.34837758])

In [29]:
np.stack(best_ffn_mean_history_kfold["precision_scores"]).mean(axis=0)

array([0.7819959 , 0.43850065, 0.30448359])

In [30]:
np.stack(best_ffn_mean_history_kfold["recall_scores"]).mean(axis=0)

array([0.72431078, 0.46342134, 0.40727273])