In [1]:
import numpy as np
import pickle
import os

seed = 2023

In [2]:
import torch

# set device
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
device

device(type='cuda')

In [3]:
from nlpsig_networks.scripts.seqsignet_attention_encoder_functions import (
    seqsignet_attention_encoder_hyperparameter_search,
)

In [4]:
output_dir = "client_talk_type_output"
if not os.path.isdir(output_dir):
    os.makedirs(output_dir)

## AnnoMI

In [5]:
%run ../load_anno_mi.py

In [6]:
anno_mi.head()

mi_quality  transcript_id                         topic  utterance_id  \
0       high              0  reducing alcohol consumption             0   
1       high              0  reducing alcohol consumption             1   
2       high              0  reducing alcohol consumption             2   
3       high              0  reducing alcohol consumption             3   
4       high              0  reducing alcohol consumption             4   

  interlocutor timestamp                                     utterance_text  \
0    therapist  00:00:13  Thanks for filling it out. We give this form t...   
1       client  00:00:24                                              Sure.   
2    therapist  00:00:25  So, let's see. It looks that you put-- You dri...   
3       client  00:00:34                                            Mm-hmm.   
4    therapist  00:00:34  -and you usually have three to four drinks whe...   

   annotator_id therapist_input_exists therapist_input_subtype  \
0             3                  False                     NaN   
1             3                    NaN                     NaN   
2             3                   True             information   
3             3                    NaN                     NaN   
4             3                   True             information   

  reflection_exists reflection_subtype question_exists question_subtype  \
0             False                NaN            True             open   
1               NaN                NaN             NaN              NaN   
2             False                NaN           False              NaN   
3               NaN                NaN             NaN              NaN   
4             False                NaN           False              NaN   

  main_therapist_behaviour client_talk_type            datetime  speaker  
0                 question              NaN 2023-11-10 00:00:13       -1  
1                      NaN          neutral 2023-11-10 00:00:24        1  
2          therapist_input              NaN 2023-11-10 00:00:25       -1  
3                      NaN          neutral 2023-11-10 00:00:34        1  
4          therapist_input              NaN 2023-11-10 00:00:34       -1

In [7]:
with open("../anno_mi_sbert.pkl", "rb") as f:
    sbert_embeddings = pickle.load(f)

sbert_embeddings.shape

(9699, 384)

In [8]:
features = ["time_encoding", "timeline_index"]
standardise_method = ["z_score", None]
include_features_in_path = True
include_features_in_input = True

In [49]:
num_epochs = 100
dimensions = [15]
# define swmhau parameters: (output_channels, sig_depth, num_heads)
swmhau_parameters = [(12, 3, 10), (10, 3, 5)]
num_layers = [1]
ffn_hidden_dim_sizes = [[32,32], [128,128], [512,512]]
dropout_rates = [0.1]
learning_rates = [5e-4, 3e-4, 1e-4, 1e-5]
seeds = [1, 12, 123]
loss = "focal"
gamma = 2
validation_metric = "f1"
patience = 3

In [50]:
kwargs = {
    "num_epochs": num_epochs,
    "df": anno_mi,
    "id_column": "transcript_id",
    "label_column": "client_talk_type",
    "embeddings": sbert_embeddings,
    "y_data": y_data_client,
    "output_dim": output_dim_client,
    "dimensions": dimensions,
    "log_signature": True,
    "pooling": "signature",
    "transformer_encoder_layers": 2,
    "swmhau_parameters": swmhau_parameters,
    "num_layers": num_layers,
    "ffn_hidden_dim_sizes": ffn_hidden_dim_sizes,
    "dropout_rates": dropout_rates,
    "learning_rates": learning_rates,
    "seeds": seeds,
    "loss": loss,
    "gamma": gamma,
    "device": device,
    "features": features,
    "standardise_method": standardise_method,
    "include_features_in_path": include_features_in_path,
    "include_features_in_input": include_features_in_input,
    "path_indices": client_index,
    "split_ids": client_transcript_id,
    "k_fold": True,
    "patience": patience,
    "validation_metric": validation_metric,
    "verbose": False,
}

# history_length=11

In [51]:
shift = 3
window_size = 5
n = 3

In [52]:
(
    seqsignet_attention_encoder_umap_kfold_11,
    best_seqsignet_attention_encoder_umap_kfold_11,
    _,
    __,
) = seqsignet_attention_encoder_hyperparameter_search(
    shift=shift,
    window_size=window_size,
    n=n,
    dim_reduce_methods=["umap"],
    results_output=f"{output_dir}/seqsignet_attention_encoder_umap_focal_{gamma}_{shift}_{window_size}_{n}_kfold.csv",
    **kwargs,
)

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]


##################################################
dimension: 15 | method: umap
given shift 3, window size 5 and n 3: history length = 11
[INFO] Concatenating the embeddings to the dataframe...
[INFO] - columns beginning with 'e' denote the full embddings.
[INFO] - columns beginning with 'd' denote the dimension reduced embeddings.
[INFO] Adding time feature columns into dataframe in `.df`.
[INFO] Adding 'time_encoding' feature...
[INFO] Adding 'time_diff' feature...
[INFO] Adding 'timeline_index' feature...
[INFO] Padding ids and storing in `.df_padded` and `.array_padded` attributes.


  0%|          | 0/9699 [00:00<?, ?it/s]

[INFO] The path was created for each item in the dataframe, by looking at its history, so to include embeddings in the FFN input, we concatenate the embeddings for each sentence / text.


  0%|          | 0/2 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/3 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/4 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/4 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/4 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/3 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/4 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/4 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/4 [00:00<?, ?it/s]

given shift 3, window size 5 and n 3: history length = 11
[INFO] Concatenating the embeddings to the dataframe...
[INFO] - columns beginning with 'e' denote the full embddings.
[INFO] - columns beginning with 'd' denote the dimension reduced embeddings.
[INFO] Adding time feature columns into dataframe in `.df`.
[INFO] Adding 'time_encoding' feature...
[INFO] Adding 'time_diff' feature...
[INFO] Adding 'timeline_index' feature...
[INFO] Padding ids and storing in `.df_padded` and `.array_padded` attributes.


  0%|          | 0/9699 [00:00<?, ?it/s]

[INFO] The path was created for each item in the dataframe, by looking at its history, so to include embeddings in the FFN input, we concatenate the embeddings for each sentence / text.
saving results dataframe to CSV for this hyperparameter search in client_talk_type_output/seqsignet_attention_encoder_umap_focal_2_3_5_3_kfold.csv
saving the best model results dataframe to CSV for this hyperparameter search in client_talk_type_output/seqsignet_attention_encoder_umap_focal_2_3_5_3_kfold_best_model.csv


In [53]:
seqsignet_attention_encoder_umap_kfold_11

loss  accuracy        f1  \
0   None  0.639272  0.379968   
0   None  0.646360  0.357379   
0   None  0.664368  0.429112   
0   None  0.660536  0.343206   
0   None  0.663793  0.342117   
..   ...       ...       ...   
0   None  0.656130  0.457628   
0   None  0.639847  0.412263   
0   None  0.650383  0.293526   
0   None  0.656322  0.269600   
0   None  0.652874  0.286827   

                                            f1_scores  precision  \
0   [0.781563126252505, 0.17167381974248927, 0.186...   0.434493   
0   [0.7850030731407499, 0.1751824817518248, 0.111...   0.449790   
0   [0.7986339488995698, 0.24816625916870413, 0.24...   0.499625   
0   [0.7958393807450411, 0.17963314358001262, 0.05...   0.486353   
0   [0.7957196104364556, 0.18656229615133724, 0.04...   0.483829   
..                                                ...        ...   
0   [0.7870282054775856, 0.40312771503040834, 0.18...   0.487666   
0   [0.7738520576948525, 0.3403093721565059, 0.122...   0.467922   
0      [0.7871333964049195, 0.09344490934449096, 0.0]   0.322556   
0     [0.7931274669143256, 0.015673981191222573, 0.0]   0.272926   
0      [0.7895169820190387, 0.07096307023895726, 0.0]   0.318319   

                                     precision_scores    recall  \
0        [0.68935041979673, 0.3341288782816229, 0.28]  0.385922   
0   [0.6827025871285012, 0.3333333333333333, 0.333...  0.369817   
0   [0.7097571942446043, 0.47877358490566035, 0.31...  0.425604   
0   [0.683991683991684, 0.38482384823848237, 0.390...  0.365890   
0     [0.6810043218769294, 0.4454828660436137, 0.325]  0.366178   
..                                                ...       ...   
0   [0.7441381087348622, 0.42568807339449544, 0.29...  0.450243   
0   [0.7133447182239571, 0.3793103448275862, 0.311...  0.410173   
0      [0.6658663465386154, 0.30180180180180183, 0.0]  0.339229   
0                  [0.6625290923196276, 0.15625, 0.0]  0.332035   
0      [0.6650168283508217, 0.28994082840236685, 0.0]  0.337267   

                                        recall_scores valid_loss  \
0     [0.9022556390977443, 0.11551155115511551, 0.14]       None   
0   [0.9233661075766338, 0.1188118811881188, 0.067...       None   
0   [0.9129554655870445, 0.1674917491749175, 0.196...       None   
0   [0.951417004048583, 0.11716171617161716, 0.029...       None   
0   [0.9569115095430885, 0.11798679867986799, 0.02...       None   
..                                                ...        ...   
0   [0.8351648351648352, 0.38283828382838286, 0.13...       None   
0   [0.8455754771544245, 0.3085808580858086, 0.076...       None   
0      [0.9624060150375939, 0.05528052805280528, 0.0]       None   
0      [0.9878542510121457, 0.00825082508250825, 0.0]       None   
0     [0.9713707345286293, 0.040429042904290426, 0.0]       None   

    valid_accuracy  ...  seed loss_function  gamma k_fold  n_splits  \
0         0.646114  ...     1         focal      2   True         5   
0         0.653500  ...    12         focal      2   True         5   
0         0.656872  ...   123         focal      2   True         5   
0         0.648041  ...     1         focal      2   True         5   
0         0.648362  ...    12         focal      2   True         5   
..             ...  ...   ...           ...    ...    ...       ...   
0         0.652216  ...    12         focal      2   True         5   
0         0.651413  ...   123         focal      2   True         5   
0         0.642742  ...     1         focal      2   True         5   
0         0.641940  ...    12         focal      2   True         5   
0         0.644830  ...   123         focal      2   True         5   

   augmentation_type  hidden_dim_aug    comb_method  batch_size  model_id  
0             Conv1d            None  concatenation          64         0  
0             Conv1d            None  concatenation          64         0  
0             Conv1d            None  concatenation          64         0  
0             Conv1d   

In [54]:
best_seqsignet_attention_encoder_umap_kfold_11["f1"].mean()

0.48906065803553905

In [55]:
best_seqsignet_attention_encoder_umap_kfold_11["precision"].mean()

0.4984881070870974

In [56]:
best_seqsignet_attention_encoder_umap_kfold_11["recall"].mean()

0.4833686372300234

In [57]:
np.stack(best_seqsignet_attention_encoder_umap_kfold_11["f1_scores"]).mean(axis=0)

array([0.77671022, 0.38878632, 0.30168544])

In [58]:
np.stack(best_seqsignet_attention_encoder_umap_kfold_11["precision_scores"]).mean(
    axis=0
)

array([0.75120283, 0.42770682, 0.31655467])

In [59]:
np.stack(best_seqsignet_attention_encoder_umap_kfold_11["recall_scores"]).mean(axis=0)

array([0.8040293 , 0.3569857 , 0.28909091])

# history_length=20

In [20]:
shift = 3
window_size = 5
n = 6

In [21]:
(
    seqsignet_attention_encoder_umap_kfold_20,
    best_seqsignet_attention_encoder_umap_kfold_20,
    _,
    __,
) = seqsignet_attention_encoder_hyperparameter_search(
    shift=shift,
    window_size=window_size,
    n=n,
    dim_reduce_methods=["umap"],
    results_output=f"{output_dir}/seqsignet_attention_encoder_umap_focal_{gamma}_{shift}_{window_size}_{n}_kfold.csv",
    **kwargs,
)

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]


##################################################
dimension: 15 | method: umap
given shift 3, window size 5 and n 6: history length = 20
[INFO] Concatenating the embeddings to the dataframe...
[INFO] - columns beginning with 'e' denote the full embddings.
[INFO] - columns beginning with 'd' denote the dimension reduced embeddings.
[INFO] Adding time feature columns into dataframe in `.df`.
[INFO] Adding 'time_encoding' feature...
[INFO] Adding 'time_diff' feature...
[INFO] Adding 'timeline_index' feature...
[INFO] Padding ids and storing in `.df_padded` and `.array_padded` attributes.


  0%|          | 0/9699 [00:00<?, ?it/s]

[INFO] The path was created for each item in the dataframe, by looking at its history, so to include embeddings in the FFN input, we concatenate the embeddings for each sentence / text.


  0%|          | 0/2 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/3 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/3 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/3 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/3 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/3 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/3 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/3 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/3 [00:00<?, ?it/s]

given shift 3, window size 5 and n 6: history length = 20
[INFO] Concatenating the embeddings to the dataframe...
[INFO] - columns beginning with 'e' denote the full embddings.
[INFO] - columns beginning with 'd' denote the dimension reduced embeddings.
[INFO] Adding time feature columns into dataframe in `.df`.
[INFO] Adding 'time_encoding' feature...
[INFO] Adding 'time_diff' feature...
[INFO] Adding 'timeline_index' feature...
[INFO] Padding ids and storing in `.df_padded` and `.array_padded` attributes.


  0%|          | 0/9699 [00:00<?, ?it/s]

[INFO] The path was created for each item in the dataframe, by looking at its history, so to include embeddings in the FFN input, we concatenate the embeddings for each sentence / text.
saving results dataframe to CSV for this hyperparameter search in client_talk_type_output/seqsignet_attention_encoder_umap_focal_2_3_5_6_kfold.csv
saving the best model results dataframe to CSV for this hyperparameter search in client_talk_type_output/seqsignet_attention_encoder_umap_focal_2_3_5_6_kfold_best_model.csv


In [22]:
seqsignet_attention_encoder_umap_kfold_20

loss  accuracy        f1  \
0  None  0.657088  0.447777   
0  None  0.658238  0.451153   
0  None  0.660920  0.357443   
0  None  0.662069  0.467303   
0  None  0.661494  0.361055   
0  None  0.661494  0.310448   
0  None  0.631226  0.389742   
0  None  0.661111  0.318119   
0  None  0.654598  0.323743   
0  None  0.658238  0.469555   
0  None  0.638697  0.401901   
0  None  0.652299  0.474467   
0  None  0.655939  0.483203   
0  None  0.652682  0.422957   
0  None  0.639272  0.474970   
0  None  0.638889  0.339242   
0  None  0.657854  0.328769   
0  None  0.640038  0.322405   
0  None  0.641762  0.477392   
0  None  0.628736  0.468619   
0  None  0.641954  0.474480   
0  None  0.646552  0.469370   
0  None  0.622222  0.472380   
0  None  0.666475  0.464052   
0  None  0.648276  0.437612   
0  None  0.639847  0.393552   
0  None  0.629502  0.370113   
0  None  0.645402  0.489840   
0  None  0.642337  0.474283   
0  None  0.647318  0.478848   
0  None  0.643487  0.464373   
0  None  0.656897  0.379645   
0  None  0.640038  0.413192   
0  None  0.657663  0.299843   
0  None  0.665326  0.308900   
0  None  0.639655  0.318572   
0  None  0.643870  0.508955   
0  None  0.640230  0.488969   
0  None  0.663602  0.532027   
0  None  0.650766  0.520520   
0  None  0.670115  0.461667   
0  None  0.657280  0.511448   
0  None  0.632950  0.391242   
0  None  0.627969  0.403588   
0  None  0.659195  0.345171   
0  None  0.645402  0.484197   
0  None  0.629885  0.481136   
0  None  0.641379  0.477373   
0  None  0.648276  0.464020   
0  None  0.644636  0.481431   
0  None  0.662261  0.456906   
0  None  0.637356  0.439745   
0  None  0.624713  0.438061   
0  None  0.635057  0.402538   

                                           f1_scores  precision  \
0  [0.7888962326503635, 0.34957020057306587, 0.20...   0.495950   
0  [0.792107670194695, 0.312397596941562, 0.24895...   0.492555   
0  [0.7953527774416072, 0.17078052034689792, 0.10...   0.470371   
0  [0.7954790096878362, 0.36873563218390804, 0.23...   0.503355   
0  [0.7941531770959169, 0.17103448275862068, 0.11...   0.487406   
0      [0.7939401112557699, 0.1374045801526718, 0.0]   0.368108   
0  [0.7726513301632182, 0.25222222222222224, 0.14...   0.427351   
0  [0.7935414935296212, 0.14305364511691884, 0.01...   0.495826   
0  [0.7891009482655144, 0.16103896103896104, 0.02...   0.456124   
0  [0.7922043010752688, 0.3573176700930005, 0.259...   0.494660   
0  [0.7721716514954486, 0.31364956437560504, 0.11...   0.462307   
0  [0.7837393922803176, 0.3840217884702678, 0.255...   0.494400   
0  [0.7824748040313549, 0.43013365735115433, 0.23...   0.511500   
0  [0.7842778793418647, 0.339913336543091, 0.1446...   0.484042   
0  [0.7737677292515096, 0.38461538461538464, 0.26...   0.487178   
0  [0.7792908845540425, 0.166256157635468, 0.0721...   0.404373   
0       [0.7892139159744793, 0.197094125078964, 0.0]   0.365500   
0  [0.7823244552058111, 0.1158249158249158, 0.069...   0.384460   
0  [0.7755850014096419, 0.397989107666527, 0.2586...   0.488011   
0  [0.765418192058575, 0.3705673758865248, 0.2698...   0.473568   
0  [0.7738623751387348, 0.3816659321286911, 0.267...   0.488577   
0  [0.7828847481021395, 0.3744414655942806, 0.250...   0.484033   
0  [0.75956678700361, 0.39197659841203514, 0.2655...   0.472064   
0  [0.7941254300079386, 0.3721822541966427, 0.225...   0.513589   
0  [0.778537611783272, 0.3388671875, 0.1954314720...   0.484181   
0  [0.7830620549338759, 0.2105263157894737, 0.187...   0.438865   
0  [0.7652865017305474, 0.27709054923305293, 0.06...   0.447414   
0  [0.7743108996781866, 0.39421813403416556, 0.30...   0.500224   
0  [0.7714563917095563, 0.39759553456419067, 0.25...   0.490751   
0  [0.7779741672331747, 0.34970530451866405, 0.30...   0.496948   
0  [0.7750370669901604, 0.3382563125297761, 0.279...   0.490942   
0  [0.7890227244505152, 0.25667828106852497, 0.09...   0.464767   
0  [0.7799067840497153, 0.258896338318721, 0.2007...   0.464972   
0      [0.791651927

In [23]:
best_seqsignet_attention_encoder_umap_kfold_20["f1"].mean()

0.5099838614640518

In [24]:
best_seqsignet_attention_encoder_umap_kfold_20["precision"].mean()

0.5105735467322742

In [25]:
best_seqsignet_attention_encoder_umap_kfold_20["recall"].mean()

0.5102778484904592

In [26]:
np.stack(best_seqsignet_attention_encoder_umap_kfold_20["f1_scores"]).mean(axis=0)

array([0.77563718, 0.42640384, 0.32791057])

In [27]:
np.stack(best_seqsignet_attention_encoder_umap_kfold_20["precision_scores"]).mean(
    axis=0
)

array([0.76934738, 0.4429996 , 0.31937366])

In [28]:
np.stack(best_seqsignet_attention_encoder_umap_kfold_20["recall_scores"]).mean(axis=0)

array([0.78214768, 0.41171617, 0.3369697 ])

# history_length=35

In [29]:
shift = 3
window_size = 5
n = 11

In [30]:
(
    seqsignet_attention_encoder_umap_kfold_35,
    best_seqsignet_attention_encoder_umap_kfold_35,
    _,
    __,
) = seqsignet_attention_encoder_hyperparameter_search(
    shift=shift,
    window_size=window_size,
    n=n,
    dim_reduce_methods=["umap"],
    results_output=f"{output_dir}/seqsignet_attention_encoder_umap_focal_{gamma}_{shift}_{window_size}_{n}_kfold.csv",
    **kwargs,
)

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]


##################################################
dimension: 15 | method: umap
given shift 3, window size 5 and n 11: history length = 35
[INFO] Concatenating the embeddings to the dataframe...
[INFO] - columns beginning with 'e' denote the full embddings.
[INFO] - columns beginning with 'd' denote the dimension reduced embeddings.
[INFO] Adding time feature columns into dataframe in `.df`.
[INFO] Adding 'time_encoding' feature...
[INFO] Adding 'time_diff' feature...
[INFO] Adding 'timeline_index' feature...
[INFO] Padding ids and storing in `.df_padded` and `.array_padded` attributes.


  0%|          | 0/9699 [00:00<?, ?it/s]

[INFO] The path was created for each item in the dataframe, by looking at its history, so to include embeddings in the FFN input, we concatenate the embeddings for each sentence / text.


  0%|          | 0/2 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/3 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/3 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/3 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/3 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/3 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/3 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/3 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/3 [00:00<?, ?it/s]

given shift 3, window size 5 and n 11: history length = 35
[INFO] Concatenating the embeddings to the dataframe...
[INFO] - columns beginning with 'e' denote the full embddings.
[INFO] - columns beginning with 'd' denote the dimension reduced embeddings.
[INFO] Adding time feature columns into dataframe in `.df`.
[INFO] Adding 'time_encoding' feature...
[INFO] Adding 'time_diff' feature...
[INFO] Adding 'timeline_index' feature...
[INFO] Padding ids and storing in `.df_padded` and `.array_padded` attributes.


  0%|          | 0/9699 [00:00<?, ?it/s]

[INFO] The path was created for each item in the dataframe, by looking at its history, so to include embeddings in the FFN input, we concatenate the embeddings for each sentence / text.
saving results dataframe to CSV for this hyperparameter search in client_talk_type_output/seqsignet_attention_encoder_umap_focal_2_3_5_11_kfold.csv
saving the best model results dataframe to CSV for this hyperparameter search in client_talk_type_output/seqsignet_attention_encoder_umap_focal_2_3_5_11_kfold_best_model.csv


In [31]:
seqsignet_attention_encoder_umap_kfold_35

loss  accuracy        f1  \
0  None  0.650766  0.396536   
0  None  0.661494  0.426731   
0  None  0.640613  0.422239   
0  None  0.653065  0.371318   
0  None  0.656513  0.329344   
0  None  0.661111  0.367753   
0  None  0.647701  0.284934   
0  None  0.666667  0.317205   
0  None  0.616092  0.311654   
0  None  0.651724  0.492981   
0  None  0.648084  0.453726   
0  None  0.646743  0.516407   
0  None  0.641379  0.504371   
0  None  0.638506  0.434878   
0  None  0.654789  0.411214   
0  None  0.635441  0.328724   
0  None  0.644061  0.351190   
0  None  0.643678  0.309641   
0  None  0.636015  0.486719   
0  None  0.643487  0.501994   
0  None  0.646360  0.462807   
0  None  0.637356  0.470486   
0  None  0.647893  0.465101   
0  None  0.637739  0.463597   
0  None  0.651149  0.390511   
0  None  0.642529  0.387922   
0  None  0.632184  0.404734   
0  None  0.648659  0.500209   
0  None  0.649425  0.473194   
0  None  0.637548  0.474737   
0  None  0.647126  0.446198   
0  None  0.661877  0.344025   
0  None  0.646935  0.408790   
0  None  0.635441  0.329170   
0  None  0.639655  0.292327   
0  None  0.638314  0.325489   
0  None  0.661303  0.506940   
0  None  0.655172  0.514437   
0  None  0.633333  0.481615   
0  None  0.645211  0.509690   
0  None  0.653831  0.437895   
0  None  0.657471  0.510620   
0  None  0.627395  0.450977   
0  None  0.633908  0.390809   
0  None  0.626437  0.396859   
0  None  0.621264  0.466176   
0  None  0.645211  0.491571   
0  None  0.645977  0.483081   
0  None  0.611877  0.460193   
0  None  0.646169  0.495192   
0  None  0.654406  0.451563   
0  None  0.647701  0.475326   
0  None  0.646169  0.453417   
0  None  0.661877  0.424600   

                                           f1_scores  precision  \
0  [0.7854527086753378, 0.2581699346405229, 0.145...   0.482444   
0  [0.7933173016073916, 0.2651997683844818, 0.221...   0.497850   
0  [0.7810067462376753, 0.24831460674157302, 0.23...   0.459471   
0  [0.7842704887908857, 0.20927318295739347, 0.12...   0.476071   
0      [0.788654194327097, 0.19937694704049844, 0.0]   0.361314   
0  [0.7941391941391942, 0.20711166562694944, 0.10...   0.483998   
0     [0.7873848334514528, 0.06741573033707866, 0.0]   0.297317   
0     [0.7970191625266146, 0.15459610027855153, 0.0]   0.389958   
0  [0.761250766400981, 0.11365040148239655, 0.060...   0.353102   
0  [0.7863343601232147, 0.38648648648648654, 0.30...   0.500103   
0  [0.7781359118990061, 0.3656509695290859, 0.217...   0.488422   
0  [0.7686435701702877, 0.4621513944223108, 0.318...   0.513594   
0  [0.7663830422451112, 0.46341463414634143, 0.28...   0.512309   
0  [0.7721065888903619, 0.3236434108527132, 0.208...   0.470764   
0  [0.7844342037890426, 0.3197102948784273, 0.129...   0.480879   
0  [0.7762868992437179, 0.14080996884735203, 0.06...   0.403904   
0  [0.7798029556650246, 0.20710059171597633, 0.06...   0.435905   
0  [0.7811865823087024, 0.1022805805114029, 0.045...   0.397397   
0  [0.7696701413679852, 0.39674378748928874, 0.29...   0.488610   
0  [0.7756577045388842, 0.4153909805544063, 0.314...   0.501848   
0  [0.7771679473106476, 0.3860705073086845, 0.225...   0.493145   
0  [0.7773415591699383, 0.36522498907820006, 0.26...   0.478239   
0  [0.7800215401184707, 0.346938775510204, 0.2683...   0.489513   
0  [0.782608695652174, 0.3540925266903915, 0.2540...   0.470540   
0  [0.7848164906988436, 0.257001647446458, 0.1297...   0.486285   
0  [0.780295315682281, 0.25809822361546503, 0.125...   0.466253   
0  [0.7705774758296317, 0.29114557278639325, 0.15...   0.441912   
0  [0.7803764974329721, 0.4154379878577623, 0.304...   0.502210   
0  [0.7748478701825557, 0.38528557599225555, 0.25...   0.496597   
0  [0.7694013303769401, 0.3682539682539682, 0.286...   0.486284   
0  [0.7799334811529934, 0.4089995982322217, 0.149...   0.481563   
0  [0.7951401419463491, 0.1699346405228758, 0.067...   0.505026   
0  [0.7806076276664511, 0.31187122736418504, 0.13...   0.464259   
0  [0.7764763299170

In [32]:
best_seqsignet_attention_encoder_umap_kfold_35["f1"].mean()

0.5009972195625266

In [33]:
best_seqsignet_attention_encoder_umap_kfold_35["precision"].mean()

0.5070925833312471

In [34]:
best_seqsignet_attention_encoder_umap_kfold_35["recall"].mean()

0.49704063138143395

In [35]:
np.stack(best_seqsignet_attention_encoder_umap_kfold_35["f1_scores"]).mean(axis=0)

array([0.77759858, 0.41077495, 0.31461813])

In [36]:
np.stack(best_seqsignet_attention_encoder_umap_kfold_35["precision_scores"]).mean(
    axis=0
)

array([0.75927255, 0.44158948, 0.32041572])

In [37]:
np.stack(best_seqsignet_attention_encoder_umap_kfold_35["recall_scores"]).mean(axis=0)

array([0.79699248, 0.3850385 , 0.30909091])

# history_length=80

In [38]:
shift = 3
window_size = 5
n = 26

In [39]:
(
    seqsignet_attention_encoder_umap_kfold_80,
    best_seqsignet_attention_encoder_umap_kfold_80,
    _,
    __,
) = seqsignet_attention_encoder_hyperparameter_search(
    shift=shift,
    window_size=window_size,
    n=n,
    dim_reduce_methods=["umap"],
    results_output=f"{output_dir}/seqsignet_attention_encoder_umap_focal_{gamma}_{shift}_{window_size}_{n}_kfold.csv",
    **kwargs,
)

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]


##################################################
dimension: 15 | method: umap
given shift 3, window size 5 and n 26: history length = 80
[INFO] Concatenating the embeddings to the dataframe...
[INFO] - columns beginning with 'e' denote the full embddings.
[INFO] - columns beginning with 'd' denote the dimension reduced embeddings.
[INFO] Adding time feature columns into dataframe in `.df`.
[INFO] Adding 'time_encoding' feature...
[INFO] Adding 'time_diff' feature...
[INFO] Adding 'timeline_index' feature...
[INFO] Padding ids and storing in `.df_padded` and `.array_padded` attributes.


  0%|          | 0/9699 [00:00<?, ?it/s]

[INFO] The path was created for each item in the dataframe, by looking at its history, so to include embeddings in the FFN input, we concatenate the embeddings for each sentence / text.


  0%|          | 0/2 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/3 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/3 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/3 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/3 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/3 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/3 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/3 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/3 [00:00<?, ?it/s]

given shift 3, window size 5 and n 26: history length = 80
[INFO] Concatenating the embeddings to the dataframe...
[INFO] - columns beginning with 'e' denote the full embddings.
[INFO] - columns beginning with 'd' denote the dimension reduced embeddings.
[INFO] Adding time feature columns into dataframe in `.df`.
[INFO] Adding 'time_encoding' feature...
[INFO] Adding 'time_diff' feature...
[INFO] Adding 'timeline_index' feature...
[INFO] Padding ids and storing in `.df_padded` and `.array_padded` attributes.


  0%|          | 0/9699 [00:00<?, ?it/s]

[INFO] The path was created for each item in the dataframe, by looking at its history, so to include embeddings in the FFN input, we concatenate the embeddings for each sentence / text.
saving results dataframe to CSV for this hyperparameter search in client_talk_type_output/seqsignet_attention_encoder_umap_focal_2_3_5_26_kfold.csv
saving the best model results dataframe to CSV for this hyperparameter search in client_talk_type_output/seqsignet_attention_encoder_umap_focal_2_3_5_26_kfold_best_model.csv


In [40]:
seqsignet_attention_encoder_umap_kfold_80

loss  accuracy        f1  \
0  None  0.648276  0.427106   
0  None  0.661111  0.320587   
0  None  0.644061  0.354832   
0  None  0.654789  0.284823   
0  None  0.649234  0.303626   
0  None  0.650383  0.349053   
0  None  0.640996  0.293090   
0  None  0.652107  0.296974   
0  None  0.653065  0.290308   
0  None  0.649808  0.515510   
0  None  0.658046  0.491116   
0  None  0.641571  0.486492   
0  None  0.640613  0.517381   
0  None  0.658046  0.441802   
0  None  0.648276  0.401587   
0  None  0.648467  0.377032   
0  None  0.623180  0.332471   
0  None  0.654023  0.320085   
0  None  0.642720  0.491740   
0  None  0.631609  0.472818   
0  None  0.666092  0.441519   
0  None  0.644636  0.464540   
0  None  0.643103  0.486349   
0  None  0.644061  0.467189   
0  None  0.643870  0.431368   
0  None  0.633716  0.434654   
0  None  0.650958  0.336697   
0  None  0.645211  0.502550   
0  None  0.649617  0.451953   
0  None  0.644636  0.491686   
0  None  0.653065  0.480022   
0  None  0.619349  0.379671   
0  None  0.642529  0.391590   
0  None  0.621648  0.335610   
0  None  0.597701  0.327734   
0  None  0.645402  0.282885   
0  None  0.651724  0.519459   
0  None  0.633142  0.459027   
0  None  0.667625  0.505594   
0  None  0.659387  0.499956   
0  None  0.658429  0.419321   
0  None  0.648851  0.517638   
0  None  0.628927  0.474045   
0  None  0.619157  0.421430   
0  None  0.656322  0.285280   
0  None  0.642720  0.499098   
0  None  0.645785  0.492795   
0  None  0.651341  0.461765   
0  None  0.651724  0.476997   
0  None  0.633908  0.442784   
0  None  0.639655  0.484165   
0  None  0.629502  0.440300   
0  None  0.633908  0.447788   
0  None  0.653065  0.473522   

                                           f1_scores  precision  \
0  [0.7837592424438967, 0.2873096446700507, 0.210...   0.487718   
0     [0.7920886452996544, 0.16967267869071478, 0.0]   0.373057   
0  [0.7793162602622227, 0.1848844472204872, 0.100...   0.440751   
0     [0.7911392405063291, 0.06332842415316642, 0.0]   0.319892   
0      [0.7862085421140539, 0.1246684350132626, 0.0]   0.328913   
0  [0.7847457627118644, 0.15699208443271767, 0.10...   0.457797   
0  [0.7811943488068384, 0.06633020908435472, 0.03...   0.350165   
0     [0.7880724174653886, 0.10284920083391244, 0.0]   0.330975   
0     [0.7892630091829528, 0.08166189111747851, 0.0]   0.325130   
0  [0.7740137850124652, 0.45984251968503936, 0.31...   0.514403   
0  [0.7875361919205845, 0.4009280742459396, 0.284...   0.505220   
0  [0.7700564971751411, 0.4102127659574468, 0.279...   0.494232   
0  [0.7645652823423962, 0.4580620451934125, 0.329...   0.512632   
0  [0.7885491216655823, 0.33350703491401773, 0.20...   0.488880   
0  [0.7829218106995884, 0.3024785027819929, 0.119...   0.465025   
0  [0.7873087534487083, 0.2386689615605278, 0.105...   0.435484   
0  [0.764033780427223, 0.1796875, 0.0536912751677...   0.431660   
0      [0.7878423834694859, 0.1724137931034483, 0.0]   0.351738   
0  [0.7768547694070467, 0.41081994928148774, 0.28...   0.493464   
0  [0.7676195867534673, 0.3851528384279477, 0.265...   0.476806   
0  [0.7950894606242654, 0.3625730994152046, 0.166...   0.501603   
0  [0.7746807634216668, 0.38544824599393673, 0.23...   0.491794   
0  [0.7748961169221952, 0.4198807157057654, 0.264...   0.496280   
0  [0.782429649965683, 0.3534971644612476, 0.2656...   0.480211   
0  [0.779656573600734, 0.30452674897119336, 0.209...   0.468152   
0  [0.7707356291035777, 0.31841255191509, 0.21481...   0.471325   
0     [0.7838532110091743, 0.22623906705539354, 0.0]   0.354977   
0  [0.7749386458784467, 0.42279708973322555, 0.30...   0.505792   
0  [0.7787822387662856, 0.355899419729207, 0.2211...   0.487986   
0  [0.7762788083192805, 0.3872113676731794, 0.311...   0.498071   
0  [0.7850828729281767, 0.389203308663474, 0.2657...   0.501126   
0  [0.7699738903394258, 0.23084677419354838, 0.13...   0.407339   
0  [0.7767499999999999, 0.20886460230722526, 0.18...   0.462701   
0  [0.7637130801687

In [41]:
best_seqsignet_attention_encoder_umap_kfold_80["f1"].mean()

0.4946934941144896

In [42]:
best_seqsignet_attention_encoder_umap_kfold_80["precision"].mean()

0.5027473899107543

In [43]:
best_seqsignet_attention_encoder_umap_kfold_80["recall"].mean()

0.49242712819575774

In [44]:
np.stack(best_seqsignet_attention_encoder_umap_kfold_80["f1_scores"]).mean(axis=0)

array([0.78077352, 0.41137528, 0.29193168])

In [45]:
np.stack(best_seqsignet_attention_encoder_umap_kfold_80["precision_scores"]).mean(
    axis=0
)

array([0.76183202, 0.44827906, 0.29813109])

In [46]:
np.stack(best_seqsignet_attention_encoder_umap_kfold_80["recall_scores"]).mean(axis=0)

array([0.80171583, 0.38283828, 0.29272727])

# history_length=110

In [47]:
shift = 3
window_size = 5
n = 36

In [48]:
(
    seqsignet_attention_encoder_umap_kfold_110,
    best_seqsignet_attention_encoder_umap_kfold_110,
    _,
    __,
) = seqsignet_attention_encoder_hyperparameter_search(
    shift=shift,
    window_size=window_size,
    n=n,
    dim_reduce_methods=["umap"],
    results_output=f"{output_dir}/seqsignet_attention_encoder_umap_focal_{gamma}_{shift}_{window_size}_{n}_kfold.csv",
    **kwargs,
)

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]


##################################################
dimension: 15 | method: umap
given shift 3, window size 5 and n 36: history length = 110
[INFO] Concatenating the embeddings to the dataframe...
[INFO] - columns beginning with 'e' denote the full embddings.
[INFO] - columns beginning with 'd' denote the dimension reduced embeddings.
[INFO] Adding time feature columns into dataframe in `.df`.
[INFO] Adding 'time_encoding' feature...
[INFO] Adding 'time_diff' feature...
[INFO] Adding 'timeline_index' feature...
[INFO] Padding ids and storing in `.df_padded` and `.array_padded` attributes.


  0%|          | 0/9699 [00:00<?, ?it/s]

[INFO] The path was created for each item in the dataframe, by looking at its history, so to include embeddings in the FFN input, we concatenate the embeddings for each sentence / text.


  0%|          | 0/2 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/3 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/3 [00:00<?, ?it/s]

KeyboardInterrupt: 

In [ ]:
seqsignet_attention_encoder_umap_kfold_110

In [ ]:
best_seqsignet_attention_encoder_umap_kfold_110["f1"].mean()

In [ ]:
best_seqsignet_attention_encoder_umap_kfold_110["precision"].mean()

In [ ]:
best_seqsignet_attention_encoder_umap_kfold_110["recall"].mean()

In [ ]:
np.stack(best_seqsignet_attention_encoder_umap_kfold_110["f1_scores"]).mean(axis=0)

In [ ]:
np.stack(best_seqsignet_attention_encoder_umap_kfold_110["precision_scores"]).mean(
    axis=0
)

In [ ]:
np.stack(best_seqsignet_attention_encoder_umap_kfold_110["recall_scores"]).mean(axis=0)